### ISSUE TITLE
`alembic` configuration story needs to improve

### ISSUE THREAD

**Issue by abitrolly** [pypi/warehouse#10053]
**What's the problem this feature will solve?**

Fixing linting errors after `alembic` is easy, but a time consuming distractions. While `alembic` doesn't produce linter friendly output by default, it allows to run write hooks. https://alembic.sqlalchemy.org/en/latest/autogenerate.html?highlight=black#applying-post-processing-and-python-code-formatters-to-generated-revisions

**Describe the solution you'd like**

I would like autogenerated migrations to be `black` and `isort` valid.

**Additional context**

I could not find where Pyramid stores configuration for `alembic`, so I can't solve this issue right now.

Long story https://github.com/sqlalchemy/alembic/discussions/925

**Comment by ewjoachim** [comment]
Hey, thanks for opening the issue.

For the record, I'm not entirely comfortable with how adversarial the conversation went on the alembic discussion you linked. Given an upstream tool provider has already implemented everything we need to get it done easily on our side, I don't think it's fair to request that our own usecase would become the new default for everyone. The Python world is large, the practices are equally diverse, and when a project like Alembic has made a choice to provide a hook and not "just" lint by default, it's rarely an oversight. Especially when they explained the reasoning behind this choice, I'm not sure there was a need to continue insisting. I can see how the Alembic people might not have gotten a good experience of this interaction. PyPI is an important project among the community, and we ought to project the best of ourselves to other people when interacting with them in the name of this project. Keep in mind that we're (mostly) all volunteers here with limited time to tackle interesting problems.

With that said, I believe alembic configuration is dynamic, not static (thus why we can't find a .ini file).
I guess this should give us enough to work with:
https://github.com/pypa/warehouse/blob/781e4ae7254f0cc30f868f149e23393842eb0a79/warehouse/db.py#L27-L31

**Comment by ewjoachim** [comment]
I believe this would look something like:
```python
hooks = {
    "black": {"entrypoint": "black", "options": "..."},
    "isort": {"entrypoint": "isort", "options": "..."},
}

alembic_cfg.set_section_option(section="post_write_hooks", name="hooks", value=",".join(hooks))
for key, config in hooks.items():
    config["type"] = "console_scripts"
    for name, value in config.items():
        alembic_cfg.set_section_option(section="post_write_hooks", name=f"{key}.{name}", value=value)

```

**Comment by abitrolly** [comment]
I didn't like the way the report went myself, but I hope we cleared misunderstandings in the process. `black` insane popularity is not because there were no linters, or because the linters were of poor quality. One day I will a better way to explain that default experience matter for occasional contributors, such as those coming from Octoberfest. Then people probably won't close such issues as not important. Adding to that, I opened https://github.com/PyCQA/isort/issues/1812 as a practical way to gather data about what the defaults should be.

> With that said, I believe alembic configuration is dynamic, not static (thus why we can't find a .ini file).

Is it possible to point it to the `warehouse/migrations/alembic.ini`?

**Comment by ewjoachim** [comment]
> Is it possible to point it to the warehouse/migrations/alembic.ini?

I don't understand your suggestion.

I'd say either we need to have all the configuration in an ini file, or none. My suggestion was if we went towards none. I don't know what will need to change for us to go to "all".

**Comment by abitrolly** [comment]
I'd actually prefer all Alembic config to be in `alembic.ini`, because it is the scenario covered in its documentation. From a DevOps standpoint it is not a good practice to hardcode config for invocation of additional shell tools in the code.

**Comment by ewjoachim** [comment]
Well, you'll have to figure out how to link to the database url, which is a project setting, controllable by an environment variable.

**Comment by abitrolly** [comment]
Alembic allows to merge configs, but it doesn't report if it fails to find the config file - https://github.com/sqlalchemy/alembic/issues/931 So far I couldn't make it work.
