### ISSUE TITLE
Non-http(s) URLs used in `project_urls` are rejected as invalid

### ISSUE THREAD

**Issue by WhyNotHugo** [pypi/warehouse#10198]
**Describe the bug**

I recently updated one of my packages to have a few `project_urls`, including website, issue tracker and IRC. For the latter, I used a URL in the format of `irc://example.com/#my-channel`, which Firefox and other tools understand.

**Expected behavior**

Uploading the package should have worked find.

**To Reproduce**

Try uploading a package with:

```python
project_urls={
    "Chat": "irc://example.com/#my-channel",
    # ...
},
```

**My Platform**

I used `twine` to upload the package via GitHub Actions.

I've pinpointed the issue down to this snippet, which tries to validate the URL as http or https, even in cases where it's a different schema.

https://github.com/pypa/warehouse/blob/30a6733a3f4b91594ead39971277491a8b4bee67/warehouse/forklift/legacy.py#L337-L338

**Additional context**

I suspect that the validation is mostly an oversight of not taking this edge-case in mind; I can't imagine there was a strong reason to disallow non-https URLs.

While I think there's definitely value in allowing them, in case there's a strong sentiment against this, it would at least make sense for the error message to be clearer. It was quite tricky for me to figure out exactly what the error was, since right now the validation response just says `Use valid URL.`, without even indicating _which_ URL is wrong or in what way.

**Comment by di** [comment]
I think I'd prefer for us to stick with valid HTTP/HTTPS links, since these go in the sidebar for the project, and other protocols are somewhat exotic.

I'd be in favor of updating the error message here to indicate that this needs to be a valid HTTP/HTTPS URL.

**Comment by WhyNotHugo** [comment]
That sounds reasonable. It would also be good to update the docs to clarify this.

Renaming the field to `project_websites' would be nice, but I don't think it's worth breaking backwards compatibility.

**Comment by di** [comment]
Unfortunately that would require an update to the [Core metadata spec](https://packaging.python.org/en/latest/specifications/core-metadata/#project-url-multiple-use)

Which I'm now noting says:

> A string containing a **browsable** URL for the project and a label for it, separated by a comma.

Which IMO reinforces that this must remain HTTP/HTTPS.

**Comment by WhyNotHugo** [comment]
gemmini: is browsable

**Comment by dstufft** [comment]
I'm going to close this. I think that keeping these as HTTP(S) urls is the path we're going to go for here, and if people feel strongly it's probably best to discuss it on discuss.python.org.
