### ISSUE TITLE
Update 'compute_trending' query to use new public dataset

### ISSUE THREAD

**Issue by di** [pypi/warehouse#10740]
Currently the query in the `compute_trending` task uses the old `the-psf.pypi.downloads*` table. This is likely making our 'trending' calculation incorrect & out of date.

https://github.com/pypa/warehouse/blob/b053ac522ef6689417463cc74482ca2e0bb976d5/warehouse/packaging/tasks.py#L25-L34

This should be updated to use the new `bigquery-public-data.pypi.downloads` table.

**Comment by rajpratyush** [comment]
is this issue open for work?/

**Comment by di** [comment]
Duplicate of #8990.
