### ISSUE TITLE
CI: PRs should be blocked if they don't supply a necessary migration

### ISSUE THREAD

**Issue by woodruffw** [pypi/warehouse#11255]
Per https://github.com/pypa/warehouse/pull/11238#issuecomment-1107343438: PRs that change the DB should also bundle their migrations, so the CI should enforce that.

cc @di

**Comment by di** [comment]
Alembic doesn't seem to provide any functionality to make this straightforward. A couple ways we could do this:

* modifying the `revision` cli command to take a `--test` argument, and then determine if the `alembic.commands.revision` command returns anything
* modify our configuration not to write an empty migration file (via [this](https://stackoverflow.com/questions/70203927/how-to-prevent-alembic-revision-autogenerate-from-making-revision-file-if-it-h)) and then check if anything is written (via `git diff`) when we run a migration. That might be annoying if anyone is using this to generate empty migration files

**Comment by dstufft** [comment]
This could be difficult to do unless we want to give up on the ability to gracefully roll out a change that touches the database (which maybe we do, I'm not sure if anyone but me way early on ever used it in practice).

For instance, let's say you wanted to drop a column gracefully. You can do that by splitting the change up into two PRs:

1. Remove support for the column from the code, but leave it in the database.
    - This is needed because when we deploy, for a portion of time both the old and the new code base will be accessing the same database. So the old deploy that expects the column to be there needs to still have it be there, while the new code will gladly ignore an extraneous column.
2. Roll out a migration that just drops the column, bringing the database back into sync with the code.

There is similar patterns for adding columns, renaming columns, etc. I'm not sure that we ever really used that strategy much though, and I think we often just let the old deploys error out briefly. We could also just implement it as an advisory check, or provide a decent way to explicitly mark a PR as avoiding the check.

**Comment by woodruffw** [comment]
> We could also just implement it as an advisory check, or provide a decent way to explicitly mark a PR as avoiding the check.

My 0.02c is for this pattern: I've used it successfully on other projects (usually gated with a label, e.g. `no-migration-needed` to tell the action to ignore any "missing" migrations).

**Comment by miketheman** [comment]
#16483 should here - but it also might be in slight conflict with the gradual rollouts, so I'm not recommending use use that as a blocking operation, rather generate a red X for discussion.

**Comment by miketheman** [comment]
To accommodate gradual rollouts, we can now have the database consistency check run, and if we deem the PR to need to go through anyhow, we can apply the `skip-db-check` label to the PR.

I think this is now complete, so I'm closing - let me know if there's something I missed!
