### ISSUE TITLE
Newly released package unavailable to pip install 45 minutes after it was released

### ISSUE THREAD

**Issue by gibsondan** [pypi/warehouse#11547]
**Describe the bug**
This is an issue with the same symptoms as https://github.com/pypa/warehouse/issues/11512 from last week.

A new release of the dagster-cloud library came out about 45 minutes ago: https://pypi.org/project/dagster-cloud/#history

It appears on pypi and on the JSON API: https://pypi.org/pypi/dagster-cloud/json

But 'pip install dagster-cloud==0.14.20` fails with:

ERROR: No matching distribution found for dagster-cloud==0.14.20

In the linked issue, the root cause was identified as a Fastly issue, but https://status.fastly.com/ shows no issues.

**Comment by gibsondan** [comment]
I was able to clear the cache for that 0.14.20 package by pushing an 0.14.21rc0 pre-release a few minutes ago (about 3 hours after the package was originally published). Since this has happened two weeks in a row now and never used to happen ago, it seems that some new problem was likely introduced in the last two weeks.

**Comment by aptalca** [comment]
Witnessed something similar for pikepdf and reported here: https://github.com/pypa/pip/issues/11174
sdist appears in pypi files but never made it to simple index

**Comment by di** [comment]
Closing because this is quite old, and we've made some changes here to improve this. if anyone is still encountering this behavior please feel free to open a new issue.
