### ISSUE TITLE
JWT Package Namespace Issue

### ISSUE THREAD

**Issue by s2t2** [pypi/warehouse#11720]
**Describe the bug**
There is a namespace collision between the `jwt` and `pyjwt` packages.

See: 

  + https://github.com/jpadilla/pyjwt/issues/374
  + https://github.com/GehirnInc/python-jwt/issues/9
  + https://github.com/GehirnInc/python-jwt/issues/36
  + https://github.com/pypa/pip/issues/4625

**Expected behavior**
Be able to use both packages without errors. 

**To Reproduce**
Try to use `pyjwt` for encoding a new token.   Like [this](https://github.com/jpadilla/pyjwt/issues/374#issue-362017453)

**My Platform**
Works locally on Mac in Anaconda virtual environment with `pyjwt==2.4.0` and `jwt==1.3.1` in the requirements.txt file, but not on GitHub Actions "Python application" CI when packages are installed from the requirements.txt file.

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
