### ISSUE TITLE
Byte string conversion

### ISSUE THREAD

**Issue by rubenhartenstein** [pypi/warehouse#11722]
Hi there,

I receive the following bytestring:

 b'RFH \x02\x00\x00\x00\xec\x03\x00\x00"\x02\x00\x00\xb8\x04\x00\x00MQSTR   \x00\x00\x00\x00\xb8\x04\x00\x00 \x00\x00\x00<mcd><Msd>jms_text</Msd></mcd>  d\x00\x00\x00<jms><Dst> ...'

I want to receive it converted from MQ as a string but I receive the above bytestring.
I used the following coding:
    def initialize_mq(self):
        self.logger.debug("initialize_mq entered!")

        # Message Descriptor
        self.md = pymqi.MD()

        # Get Message Options
        self.gmo = pymqi.GMO()
        self.gmo.Options = pymqi.CMQC.MQGMO_WAIT | pymqi.CMQC.MQGMO_FAIL_IF_QUIESCING | pymqi.CMQC.MQGMO_CONVERT
        self.gmo.WaitInterval = 5000  # 5 seconds

        self.qmgr = pymqi.connect(self.queue_manager, self.channel, self.conn_info)
        self.queue = pymqi.Queue(self.qmgr, self.queue_name)

        self.logger.debug("initialize_mq left!")

In another method I call:
        self.message_text = self.queue.get(None, self.md, self.gmo)

But the conversion seems not to work. 
What am I doing wrong?

This is how it looks like in MQ Admin:
![image](https://user-images.githubusercontent.com/41000830/176412120-4a1fe871-1f3f-4179-aeec-661cf0e8d27b.png)

Best regards
Ruben Hartenstein

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
