### ISSUE TITLE
Confirmation pops up when page is refreshed

### ISSUE THREAD

**Issue by s-mm** [pypi/warehouse#11778]
After a organization account request has been submitted, if the page is refreshed, a pop up appears asking if it should resend the information.

To recreate the issue-
1. Click on 'Ypur organizations
2. Enter details to create new organization
3. Click on Create
4. Refresh the page
![project2](https://user-images.githubusercontent.com/37237726/177825505-9612810b-2e79-469c-8fbd-13cdecbfb86b.png)

**Comment by s-mm** [comment]
Priority 3/3
Response from these views should be redirect and not the form again

**Comment by divbzero** [comment]
This also occurs with other forms in PyPI. When addressing this bug, we should search through `POST` requests in the code and make sure we are following the [POST-redirect-GET](https://en.wikipedia.org/wiki/Post/Redirect/Get) pattern everywhere.
