### ISSUE TITLE
Unable to register account on PyPI as all Usernames are invalid

### ISSUE THREAD

**Issue by OllyK** [pypi/warehouse#11780]
**Describe the bug**

Over the last couple of days I've tired several times to create an account on PyPI, however I always get the message "The username is invalid. Usernames must be composed of letters, numbers, dots, hyphens and underscores. And must also start and finish with a letter or number. Choose a different username."  I have tried several different Usernames, all which fit the requirements. I have an account on TestPyPI and that Username is also flagged as invalid, for example. 

**Expected behavior**

I expect to be able to create an account on PyPI when I provide a valid Username
**To Reproduce**

Try to create an account on PyPI at https://pypi.org/account/register/
**My Platform**

Have tried from Chrome 103.0.5060.66 on WIndows 10 Enterprise 21H1 and also using Firefox 91.9.0esr running on RHEL 7.9

**Additional context**

**Comment by di** [comment]
Can you tell us what username you're trying to use? Maybe a screenshot of the registration page with all the fields filled out and the error message?

**Comment by OllyK** [comment]
Hi @di Apologies, this was just a PEBCAK issue - I was using an invalid character, perhaps I need a holiday. Have registered now. Have a good weekend!
