### ISSUE TITLE
Critical project mail: localhost link

### ISSUE THREAD

**Issue by srittau** [pypi/warehouse#11792]
**Describe the bug**

I'm not sure whether this is a problem with warehouse or the pypi.org configuration, but I just got a mail titled "[PyPI] A project you maintain has been designated as critical", which contains the following URLs: `http://localhost/manage/projects/` and `http://localhost/security-key-giveaway/`. Apart from the first URL not being linked as opposed to the the second URL, strangely enough my localhost does not have the specified paths. :)

**Expected behavior**
Link to pypi.org instead of localhost.

**Comment by di** [comment]
Thanks for the report! We're soft-launching the feature to our dependencies first and hit a small bug, which should be fixed by https://github.com/pypi/warehouse/issues/11792. You should get a follow-up email with the right links shortly, and I'll pin this for now.
