### ISSUE TITLE
Email prompting to enable MFA has http links

### ISSUE THREAD

**Issue by loicteixeira** [pypi/warehouse#11802]
**Describe the bug**

I received the following email from noreply@pypi.org, promoting me to enable 2FA since one of the project I contribute to had been flagged as critical.

The various links are http.

<details>
<summary>Email Content</summary>
Congratulations! A project you ('lta') maintain has been designated as a critical project on PyPI. You can see which project(s) has been designated at http://pypi.org/manage/projects/. .

As part of this effort, in the coming months maintainers of projects designated as critical, like yourself, will be required to enable two-factor authentication on their account in order to add new releases or otherwise modify a critical project.

You can enable two-factor authenticaion on your account today by visiting http://pypi.org/account/two-factor/.

PS: To make it easier for maintainers like you to enable two-factor authentication, we're also distributing security keys to eligible maintainers. See http://pypi.org/security-key-giveaway/ for more details.
</details>

**Expected behavior**

The various links are http**s**

**Comment by loicteixeira** [comment]
Ah, someone opened #11801 while I was writing this one.

**Comment by di** [comment]
Looks like this is still happening even when the job is run via cron and not via CLI.
