### ISSUE TITLE
Prefer "critical project" to "2fa required" badge on /manage/projects/

### ISSUE THREAD

**Issue by alex** [pypi/warehouse#11806]
On https://pypi.org/manage/projects/ if you have a project which enabled 2fa requirement manually and then became a critical project, it has the 2fa required badge (and not the critical one). I believe the order of this priority should be reversed, and it should show the critical badge.

a) Criticality is functionally a superset of the behavior, it means 2fa is both required now _and_ that it cannot be disabled
b) Criticality gives you some information about the download volume of the project

**Comment by di** [comment]
Agreed, that's a bug.

**Comment by SamirPS** [comment]
Hello where is this priority in the source code ?

**Comment by alex** [comment]
https://github.com/pypi/warehouse/blob/39daea188d2e1e6494c50753cd48cb5a8da3e8c4/warehouse/templates/manage/projects.html I think it shere.

**Comment by SamirPS** [comment]
Thanks, i check it and try to solve this issue

**Comment by SamirPS** [comment]
I create a pull request yesterday for this issue but i have this : Code scanning results / CodeQL Completed in 1m — 2 analyses not found 

it's normal ?

**Comment by SamirPS** [comment]
I have updated the PR, waiting for reviews.
