### ISSUE TITLE
Provide a way to lock in requiring 2FA for a project

### ISSUE THREAD

**Issue by brettcannon** [pypi/warehouse#11825]
**What's the problem this feature will solve?**
Users will know from a certain point forward that baseline security for a project will be met via requiring 2FA forever.

**Describe the solution you'd like**
Along with the enable/disable button, provide a way to make the enablement of 2FA permanent. Then I would like the project to display the fact that 2FA is on, now and forever.

**Additional context**
While it's great to require project maintainers to have 2FA at a project level, I want a way to make a promise to my users that I'm not only using 2FA but that I'm not going to back out of doing that. This would provide some level of security guarantees that an account takeover which could allow for a malicious upload would require a certain amount of effort. Thus future updates can be considered a bit safer than if I didn't have 2FA (permanently) on.

**Comment by dstufft** [comment]
agreed
