### ISSUE TITLE
Vanishing whl package

### ISSUE THREAD

**Issue by zjl767864079zjl** [pypi/warehouse#11861]
Hi, I found the whl packages that existed before,  now can not find any,only left tar.gz packages.
For example, https://pypi.org/project/GDAL/#files, https://pypi.org/project/Fiona/.
But, probably last year, I did download their whl packages and I can still find them, GDAL-3.3.1-cp38-cp38-win_amd64.whl Fiona-1.8.20-cp38-cp38-win_amd64.whl.
Now I want to upgrade python to 3.9.x,but I can't install successfully.

Can I find more whl packages from somewhere else?

**Comment by di** [comment]
We have no record of these projects ever uploading those distributions. You will need to either install from source or build new wheels.
