### ISSUE TITLE
pip not using proxy correctly in venv on Windows

### ISSUE THREAD

**Issue by klaypigeon** [pypi/warehouse#11860]
**Describe the bug**

Not sure if this a bug or is somehow expected behavior... But it is annoying AF.
When in a venv pip throws the following error:
(venv) C:\Users\tmacris>pip install --proxy http://proxyvip.int.cdphp.com:8080 pandas
ERROR: Could not install packages due to an OSError: Proxy URL had no scheme, should start with http:// or https://

When not in a venv, this command executes without issue.

Some web help suggested manually setting the env, but mine was already set:
(venv) C:\Users\tmacris>set https_proxy
HTTPS_PROXY=proxyvip.int.cdphp.com:8080

(venv) C:\Users\tmacris>set http_proxy
HTTP_PROXY=proxyvip.int.cdphp.com:8080

If I try it without the proxy argument I get identical results. (works outside of venv but not in venv)

**Expected behavior**

package gets installed.

**To Reproduce**

Unsure. I didn't do anything special.
python -m venv venv
venv/Scripts/activate
pip install --proxy https://your-proxy:port pandas

**My Platform**

python.org 3.10
pip 21.1.2
Windows 10
(venv) C:\Users\tmacris>where python
C:\Users\tmacris\OneDrive\OneDrive - CDPHP\PycharmProjects\tnmscripts\venv\Scripts\python.exe
C:\Program Files\Python310\python.exe

**Additional context**

[pipVerbose.txt](https://github.com/pypi/warehouse/files/9124092/pipVerbose.txt)

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
