### ISSUE TITLE
Unclear wording for creating API tokens

### ISSUE THREAD

**Issue by sfermigier** [pypi/warehouse#11874]
The text "Add an API token" is misleading. A better wording would be "Create an API token" as the token is created by the platform, not uploaded by the user.

Also: the help message "What is this token for?" under "Token name" is not useful. What are we supposed to call our tokens ? I called mine "API Token". Maybe I should have called it "First token" ?

Even better: generate the name automatically unless the user knows what they want (e.g. "API token for Maria", etc.).

**Comment by di** [comment]
Thanks! I added the "Good First Issue" label to this issue.

**Comment by aakash1185** [comment]
Hi, beginner here, I would like to contribute to this. Any help is appreciated.

**Comment by saip007** [comment]
Hi there, Is the issue still up for grabs? Can I work on the issue

**Comment by di** [comment]
Yes.

**Comment by arshm06** [comment]
I have submitted my pull request for this!
