### ISSUE TITLE
Malicious packages on PyPI

### ISSUE THREAD

**Issue by ashishbijlani** [pypi/warehouse#11898]
Hi,

We found the following malicious packages on PyPI using Packj tool https://github.com/ossillate-inc/packj

- https://pypi.org/project/malpip-tgh/
- https://pypi.org/project/oixgwsmcnwyequxsgj/
- https://pypi.org/project/pip-vulnerable-package/
- https://pypi.org/project/phdaysdefc/
- https://pypi.org/project/whatalovelyday/

**Comment by di** [comment]
Hi, please follow our security policy here: https://pypi.org/security/
