### ISSUE TITLE
daq.Gauge color gradient does not accept ranges < 0

### ISSUE THREAD

**Issue by irfaun** [pypi/warehouse#11913]
When min value is less then 0, color gradient fails for ranges < 0. The gauge dial numbers does reflect the negative value correctly but the gradient colors don't follow.
Example:
 daq.Gauge(
      min=-10,
      max=40,
      color={"gradient":True,
          "ranges":{"blue": [-10, 10],
              "cyan": [10, 20],
              "orange": [20, 30],
              "red": [30, 40]
              }
          },
      value=27,
      size=150,
      label={
              'label': 'Out Door Temp C',
              'style': {
                  'color': 'white',
                  'fontSize': 12
              }
          },
      labelPosition="bottom",
      showCurrentValue=True,
      units="..",
      id='daq-gauge2',
      className='dark-theme-control'),

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
