### ISSUE TITLE
daq components graduates has no color control

### ISSUE THREAD

**Issue by irfaun** [pypi/warehouse#11914]
**What's the problem this feature will solve?**
The graduate numbers on the thermometer gauge are not visible when a dark background-color is used

**Describe the solution you'd like**
Make the color of the graduate values defineable

**Additional context**

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
