### ISSUE TITLE
Version of released package missing from `releases` in JSON API

### ISSUE THREAD

**Issue by emcd** [pypi/warehouse#11936]
**Describe the bug**

https://pypi.org/project/importlib-resources/ shows `importlib-resources-5.9.0` as latest.
However, `curl --silent --location --header 'Accept: application/json' https://pypi.org/pypi/importlib-resources/json | jq '.releases' | grep '5\.9\.0'` does not find it.

This discrepancy is causing errors with package dependency upgrades when there is attempt to associate `importlib-resources-5.9.0` with a particular file to download.

![image](https://user-images.githubusercontent.com/221418/180614190-975c5db0-d5c9-4f81-8742-b9e472086ad5.png)

```
$ curl --silent --location --header 'Accept: application/json' https://pypi.org/pypi/importlib-resources/json | jq '.releases' | grep '5\.8\.1' || echo $?
  "5.8.1": [
      "filename": "importlib_resources-5.8.1-py3-none-any.whl",
      "url": "https://files.pythonhosted.org/packages/be/1f/f5a73ba2612c0b9efb4babd07163feed72390c42655e2eb2399b3eb9ab89/importlib_resources-5.8.1-py3-none-any.whl",
$ curl --silent --location --header 'Accept: application/json' https://pypi.org/pypi/importlib-resources/json | jq '.releases' | grep '5\.9\.0' || echo $?
1
```

**Expected behavior**

`releases` list from JSON API should reflect what is considered the latest release in the Warehouse UI as long as `releases` is still being used at all.

**To Reproduce**

See description.

**My Platform**

Not particularly relevant, but I can see same problem with both `curl` and Python's `urllib`.

**Additional context**

I understand that the `releases` portion of the response has been [marked as deprecated in the JSON API](https://warehouse.pypa.io/api-reference/json.html#project), but my understanding is that it has not yet been obsoleted. Unsure if this is related to [recent changes](https://github.com/pypi/warehouse/commit/d8683b3ffbd9cdc3a9a2110f30f66ca7ea0a8098) in the Warehouse code base or not - cursory inspection show there is some schema change related to releases but I have not dove deep enough to understand its relevance and possible effects.

**Comment by emcd** [comment]
Issue has disappeared during the time since I filed this ticket. Closing.

**Comment by emcd** [comment]
Reopening as this is still occurring (with some high profile Python packages at that).

![image](https://user-images.githubusercontent.com/221418/180896308-c1dbe977-7928-4a9d-9a1e-6961351f3959.png)

```
$ curl --silent --location --header 'Accept: application/json' https://pypi.org/pypi/virtualenv/json | jq '.releases' | grep '20\.15\.1' || echo $?
  "20.15.1": [
      "filename": "virtualenv-20.15.1-py2.py3-none-any.whl",
      "url": "https://files.pythonhosted.org/packages/6f/43/df7c7b1b7a5ac4e41fac24c3682c1cc32f2c1d683d308bba2500338d1e3e/virtualenv-20.15.1-py2.py3-none-any.whl",
      "filename": "virtualenv-20.15.1.tar.gz",
      "url": "https://files.pythonhosted.org/packages/a4/2f/05b77cb73501c01963de2cef343839f0803b64aab4d5476771ae303b97a6/virtualenv-20.15.1.tar.gz",
$ curl --silent --location --header 'Accept: application/json' https://pypi.org/pypi/virtualenv/json | jq '.releases' | grep '20\.16' || echo $?
1
```

**Comment by emcd** [comment]
@di: Also happened with Sphinx 5.1.0 yesterday although that one is now caught up. If you want to investigate current breakage, then virtualenv 20.16.0 is a good candidate.

**Comment by miketheman** [comment]
I improved the `jq` command a bit to get the last one based on upload_time:

```shellsession
$ curl --silent --location --header 'Accept: application/json' https://pypi.org/pypi/virtualenv/json | jq '.releases|to_entries| sort_by(.value[].upload_time)|.[].key' | tail -1
"20.16.0"
```

This is the current version. This may have been impacted by the linked (resolved) issue - is this still a problem?

**Comment by emcd** [comment]
> ```
> curl --silent --location --header 'Accept: application/json' https://pypi.org/pypi/virtualenv/json | jq '.releases|to_entries| sort_by(.value[].upload_time)|.[].key' | tail -1
> ```

That's not the result I'm getting:
```
$ curl --silent --location --header 'Accept: application/json' https://pypi.org/pypi/virtualenv/json | jq '.releases|to_entries| sort_by(.value[].upload_time)|.[].key' | tail -1
"20.15.1"
```

Also, the linked issue was allegedly resolved many hours before I posted my update to say that there was still a problem.
If this is somehow CDN-related, you may be hitting an edge node that is more up-to-date than the one I am hitting.

Replacing `--silent` with `--verbose`, I see the following lines of interest:
```
* Connected to pypi.org (151.101.0.223) port 443 (#0)
< etag: "ANW0jPypeXeBgfyaBuyx3g"
< x-pypi-last-serial: 14279337
< date: Tue, 26 Jul 2022 04:33:17 GMT
< x-served-by: cache-iad-kiad7000176-IAD, cache-bfi-krnt7300034-BFI
< x-cache: HIT, HIT
< x-cache-hits: 7691, 1
```

**Comment by miketheman** [comment]
@emcd That does indeed appear to be the case.

You can pass a custom header to the request to get more debug information from the Fastly CDN service - this may point out which TTL and path are used.

For example, from my location, I see this:
```shellsession
$ curl -I --silent --header 'Accept: application/json' --header 'Fastly-Debug: 1' https://pypi.org/pypi/virtualenv/json| grep fastly-debug
fastly-debug-path: (D cache-bos4648-BOS 1658970394) (F cache-bos4646-BOS 1658969969) (D cache-iad-kiad7000176-IAD 1658969969) (F cache-iad-kjyo7100051-IAD 1658958863)
fastly-debug-ttl: (H cache-bos4648-BOS - - 424) (H cache-iad-kiad7000176-IAD 75293.859 86400.000 11106)
fastly-debug-digest: 8573210ed01d067b56b65df9dd5217a26d4ebb7799a7cbde1cf74b30c58968c6
```

ref: https://developer.fastly.com/reference/http/http-headers/Fastly-Debug/ and https://developer.fastly.com/reference/http/http-headers/Fastly-Debug-TTL/

In my example, I can see that the `cache-iad-kiad7000176-IAD` host will continue to serve this object for another 75293.859 seconds (remainingTTL). This is of course unless there's another upload which is supposed to trigger the [cache invalidation behavior](https://github.com/pypi/warehouse/blob/39daea188d2e1e6494c50753cd48cb5a8da3e8c4/warehouse/cache/origin/__init__.py#L45-L55) - which the linked ticket of "CDN purging broken.." addressed.

Sine the default cache period is one day, it's possible that this misbehavior persisted for a bit after resolution - but I think enough time has passed that this ought to work now - can you confirm?

**Comment by emcd** [comment]
@miketheman: Oh, in case it wasn't clear, it's been working for some time now. Eventually the caches do update, sometimes after 18 hours or more, similar to what is being observed by others still posting to the [closed ticket](https://github.com/pypi/warehouse/issues/11949):
* https://github.com/pypi/warehouse/issues/11949#issuecomment-1195220508
* https://github.com/pypi/warehouse/issues/11949#issuecomment-1196346854
* https://github.com/pypi/warehouse/issues/11949#issuecomment-1197474921
* https://github.com/pypi/warehouse/issues/11949#issuecomment-1198403593

This is the reason I'm leaving my ticket open and have not closed it. It is possible that the PyPA folks are not noticing the activity in the closed ticket. I didn't want to pester @di, @dstufft, or @ewdurbin too much, but given the number of folks affected (which is surely a much larger number than who are being vocal), this issue needs additional scrutiny. I think PyPA has someone who is on the PSF payroll (i.e., not a volunteer) - would maybe be nice to see her look at this.

**Comment by dstufft** [comment]
It would be useful to know for someone who is getting a stale response, can they add the `Fastly-Debug: 1` header, and see if there is a ``Surrogate-Key`` header, and if so, what the value is of that header?

**Comment by emcd** [comment]
@miketheman @dstufft : Here's one that my daily Github Actions task turned up a little while ago and which I just confirmed locally (i.e. from a different machine than the one that caught it, so possibly hitting a different cache node):
```
$ curl --head --verbose --location --header 'Accept: application/json' --header 'Fastly-Debug: 1' https://pypi.org/pypi/jsonschema/json | egrep '(surrogate|fastly-debug|pypi|etag)'
etag: "MSWJBwrgR1jE+dkxcgGFlw"
surrogate-control: max-age=86400, stale-while-revalidate=300, stale-if-error=86400
surrogate-key:
x-pypi-last-serial: 14406929
fastly-debug-path: (D cache-bfi-krnt7300063-BFI 1659063631) (F cache-bfi-krnt7300080-BFI 1658588462) (D cache-iad-kjyo7100124-IAD 1658588462) (F cache-iad-kjyo7100124-IAD 1658550841)
fastly-debug-ttl: (H cache-bfi-krnt7300063-BFI - - 424) (H cache-iad-kjyo7100124-IAD 48778.980 86400.000 37621)
fastly-debug-digest: c2b71dfdc359c26a52aa1c6f362af62292fdbc19166c67968435e503b1e77686

```

Edge node is: `* Connected to pypi.org (151.101.192.223) port 443 `

Note that this is for `jsonschema` which was reported broken by @dalthviz 10 hours ago.

**Comment by dstufft** [comment]
Hmm, that URL must not have gotten picked up in our purging. I'm not sure why it's still being served. 

Possibly the cache re-validation didn't see a new object after the purge because the ETag might only consider the request body, not the request headers and the surrogate-key is how Fastly determines what items to purge when a release is updated, but if ETag is only computing over the request body, then Fastly won't update the cache until the request body has changed AND the previous response fell out of the cache.

**Comment by dstufft** [comment]
I don't have time to dig into it further right now, but if I hit the backends on that URL directly, I see:

```
$  curl https://BACKENDS/pypi/jsonschema/json -H 'Fastly-Debug: 1' -H 'Host: pypi.org' -I
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since
Access-Control-Allow-Methods: GET
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: X-PyPI-Last-Serial
Access-Control-Max-Age: 86400
Cache-Control: max-age=900, public
Content-Length: 90019
Content-Security-Policy: base-uri 'self'; block-all-mixed-content; connect-src 'self' https://api.github.com/repos/ fastly-insights.com *.fastly-insights.com *.ethicalads.io https://api.pwnedpasswords.com https://2p66nmmycsj3.statuspage.io; default-src 'none'; font-src 'self' fonts.gstatic.com; form-action 'self'; frame-ancestors 'none'; frame-src 'none'; img-src 'self' https://warehouse-camo.ingress.cmh1.psfhosted.org/ www.google-analytics.com *.fastly-insights.com *.ethicalads.io; script-src 'self' www.googletagmanager.com www.google-analytics.com *.fastly-insights.com *.ethicalads.io 'sha256-U3hKDidudIaxBDEzwGJApJgPEf2mWk6cfMWghrAa6i0='; style-src 'self' fonts.googleapis.com *.ethicalads.io 'sha256-2YHqZokjiizkHi1Zt+6ar0XJ0OeEy/egBnlm+MDMtrM=' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='; worker-src *.fastly-insights.com
Content-Type: application/json
Date: Fri, 29 Jul 2022 03:09:36 GMT
ETag: "FE3vSUKbuzMEssOduk8xGw"
Referrer-Policy: origin-when-cross-origin
Server: nginx/1.13.9
Surrogate-Control: max-age=86400, stale-while-revalidate=300, stale-if-error=86400
Surrogate-Key: project/jsonschema
Vary: Accept-Encoding
Vary: Accept-Encoding
X-PyPI-Last-Serial: 14573646
Connection: keep-alive
```

**Comment by dstufft** [comment]
I've manually purged jsonschema from the cache, it should be fixed now.

**Comment by guillp** [comment]
FYI, I still have that issue with a new package version I published about 24h ago. New version at https://pypi.org/project/binapy/ is `0.6.0`, but version `0.5.0` still appears as newest on https://pypi.org/pypi/binapy/json .

Debug headers, if that helps:

```
$ curl https://pypi.org/pypi/binapy/json -H 'Fastly-Debug: 1' -I
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 14403
Access-Control-Allow-Headers: Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since
Access-Control-Allow-Methods: GET
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: X-PyPI-Last-Serial
Access-Control-Max-Age: 86400
Cache-Control: max-age=900, public
Content-Security-Policy: base-uri 'self'; block-all-mixed-content; connect-src 'self' https://api.github.com/repos/ fastly-insights.com *.fastly-insights.com *.ethicalads.io https://api.pwnedpasswords.com https://2p66nmmycsj3.statuspage.io; default-src 'none'; font-src 'self' fonts.gstatic.com; form-action 'self'; frame-ancestors 'none'; frame-src 'none'; img-src 'self' https://warehouse-camo.ingress.cmh1.psfhosted.org/ www.google-analytics.com *.fastly-insights.com *.ethicalads.io; script-src 'self' www.googletagmanager.com www.google-analytics.com *.fastly-insights.com *.ethicalads.io 'sha256-U3hKDidudIaxBDEzwGJApJgPEf2mWk6cfMWghrAa6i0='; style-src 'self' fonts.googleapis.com *.ethicalads.io 'sha256-2YHqZokjiizkHi1Zt+6ar0XJ0OeEy/egBnlm+MDMtrM=' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='; worker-src *.fastly-insights.com
Content-Type: application/json
ETag: "os2bkUepvhtJwCinjlF9lQ"
Referrer-Policy: origin-when-cross-origin
Server: nginx/1.13.9
X-PyPI-Last-Serial: 14574179
Accept-Ranges: bytes
Date: Fri, 29 Jul 2022 07:25:10 GMT
X-Served-By: cache-iad-kjyo7100146-IAD, cache-cdg20777-CDG
X-Cache: HIT, HIT
X-Cache-Hits: 28, 1
X-Timer: S1659079511.972997,VS0,VE1
Vary: Accept-Encoding, Accept-Encoding
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Permitted-Cross-Domain-Policies: none
```

**Comment by ewdurbin** [comment]
Unfortunately we don't have the ability to purge all JSON by a Surrogate-Key.

I propose that we add the following Surrogate-Keys:

- Route `legacy.api.json.project`: `all-json` and  `json-project` in addition to the `project/` key
- Route `legacy.api.json.release `: `all-json` and `json-release` in addition to the `project/` key

Once we're serving those, we can knuckle down and issue a Purge All on the service. Then in the future if we break JSON API similarly we can do a more targeted mass purge.

**Comment by dalthviz** [comment]
> I've manually purged jsonschema from the cache, it should be fixed now.

Thank you so much @dstufft ! I can confirm that now the latest release for `jsonschema` (4.8.0) is being retrieved 🎉 

Also, big thank you to all the people trying to figure out solutions for this issue and related ones :)

**Comment by dstufft** [comment]
I'm going to close this out. We've instituted a global purge that should have shaken out all of the cached objects and we've mostly recovered from that.

If people continue to run into problem with this, either open a new ticket or we can re-open this one, but for now I'm going to close.
