### ISSUE TITLE
https://pypi.org/simple/ is no longer updating

### ISSUE THREAD

**Issue by bdraco** [pypi/warehouse#11935]
**Describe the bug**

After the CDN issues yesterday, new packages are no longer appearing at https://pypi.org/simple/ 

`wget https://pypi.org/simple/ -O - |grep bleak-connector-retry`
https://pypi.org/project/bleak-retry-connector/

`wget https://pypi.org/simple/ -O - |grep moat-ble`
https://pypi.org/project/moat-ble/

**Expected behavior**

The following produce results:
`wget https://pypi.org/simple/ -O - |grep moat-ble`
`wget https://pypi.org/simple/ -O - |grep bleak-connector-retry`

**To Reproduce**

See expected behavior

**My Platform**

**Additional context**

**Comment by di** [comment]
See #7384, #8385, etc: it takes ~24 hours for projects to appear on /simple. This shouldn't affect installability as installers go directly to the project's simple page, e.g.: https://pypi.org/simple/sampleproject/

**Comment by bdraco** [comment]
Thanks.  I think the real issue I'm having is encapsulated in https://github.com/pypi/warehouse/issues/11949 and I don't know enough about the system to understand what's was going on.

**Comment by bdraco** [comment]
Thanks.  I think the real issue I'm having is encapsulated in https://github.com/pypi/warehouse/issues/11949 and I don't know enough about the system to understand what's was going on.
