### ISSUE TITLE
https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz not updating

### ISSUE THREAD

**Issue by mullenkamp** [pypi/warehouse#11940]
**Describe the bug**
Links to packages via the simplified links https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz did not update for my package. This link specifically is: https://pypi.io/packages/source/h/hilltop-py/hilltop-py-2.0.7.tar.gz

**Expected behavior**
The file should be accessible via https://pypi.io/packages/source/h/hilltop-py/hilltop-py-2.0.7.tar.gz.

**To Reproduce**
https://pypi.io/packages/source/h/hilltop-py/hilltop-py-2.0.7.tar.gz

**Additional context**
Likely related issues #11937, #11939, #11935.

**Comment by di** [comment]
This is likely due to https://github.com/pypi/warehouse/issues/11949.

**Comment by di** [comment]
This should now be resolved.

**Comment by mahesh11T** [comment]
[https://conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs.html]
was following this tutorial got this error.

Error: HTTP 404 NOT FOUND for url <https://pypi.io/packages/source/c/click/click-7.0.tar.gz>
Elapsed: 00:00.442006

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
WARNING:conda_build.source:Error: HTTP 404 NOT FOUND for url <https://pypi.io/packages/source/c/click/click-7.0.tar.gz>
Elapsed: 00:00.442006

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
Could not download https://pypi.io/packages/source/c/click/click-7.0.tar.gz
