### ISSUE TITLE
Author from pyproject.toml is displayed incorect

### ISSUE THREAD

**Issue by JakobDev** [pypi/warehouse#11990]
**Describe the bug**
I had made a new project with a pyprorejt.toml. MY pyproject.toml contains author information this form:
```toml
authors = [
  { name="Example Author", email="author@example.com" },
]
```
This is the right form [according to the official packaging guide](https://packaging.python.org/en/latest/tutorials/packaging-projects/#configuring-metadata). But the author is  displayed wrong on PyPI.

**Expected behavior**
![grafik](https://user-images.githubusercontent.com/15185051/181994557-48b349bd-38f8-4384-9eef-64b0db51a7e4.png)

**To Reproduce**
Visit my [new project](https://pypi.org/project/desktop-entry-lib/). You will see this:
![grafik](https://user-images.githubusercontent.com/15185051/181994587-eb2f92ea-d6de-44c8-9e9d-11808546243e.png)
It is also in the mailto link, which leads to a invalid mailto.

**My Platform**
Any platform

**Additional context**
I first thought that was a bug in the build module, so I [reported it there](https://github.com/pypa/build/issues/501). But according to the PEPs the behaviour of the build module is right and the Bug is on the side of PyPI.

**Comment by woodruffw** [comment]
This is a funny case: [RFC 2328](https://www.rfc-editor.org/rfc/rfc2368) allows `mailto:` to contain "mailbox"-style addesses (like `Foo Bar <foo.bar@example.com>`), while [RFC 6068](https://datatracker.ietf.org/doc/html/rfc6068) (which supersedes 2328) only allows the address-specification form. 

PyPI should arguably follow the latest RFC, but it seems like support for the older one is still common (for example, macOS's `Mail.app` has no problems with the `mailto:Foo Bar <foo.bar@example.com>` format.

So, arguably, the `mailto:` URL itself is not invalid. We _could_ probably render the author without their email in angle brackets, but there might be additional data quality issues (e.g. authors with emails only, no names) that make that annoying.

**Comment by miketheman** [comment]
I think today warehouse is echoing the input from the metadata only, nothing more. It's stored as an unstructured text column.

I'm exploring a custom jinja filter that would format it correctly on display.

**Comment by miketheman** [comment]
I visited https://pypi.org/project/desktop-entry-lib/ today, and after all the caching expired it looks like it's working for your package, @JakobDev

**Comment by JakobDev** [comment]
Nice! Thanks!
