### ISSUE TITLE
Request trove classifier for Windows 11

### ISSUE THREAD

**Issue by GitHub30** [pypi/warehouse#12029]
Trove classifiers exist for all Microsoft Windows versions up to Windows 10. Since then, versions 11 have been released. I propose the addition of the following a classifier:

```
Operating System :: Microsoft :: Windows :: Windows 11
```

**Comment by miketheman** [comment]
Please move this issue to the trove-classifiers repo.

@GitHub30 feel free to open a pull request to add in https://github.com/pypa/trove-classifiers/blob/main/src/trove_classifiers/__init__.py

**Comment by di** [comment]
Please file an issue or make a PR here: https://github.com/pypa/trove-classifiers/

**Comment by di** [comment]
Please file an issue or make a PR here: https://github.com/pypa/trove-classifiers/
