### ISSUE TITLE
Please make the important message red

### ISSUE THREAD

**Issue by SkySailing** [pypi/warehouse#12026]
some times some important message is gray color,which will make ignored. 
like this [weblink](https://pypi.org/project/grpc-tools/#files) ,the head line `Please install the official package with: pip install grpcio-tools.`should be marked as red.

**Comment by miketheman** [comment]
The message displayed is the contents of a given package's `description` field, so it wouldn't be appropriate to re-color that message globally.

It's preferable to inform the package maintainers to provide a `long_description` that can be rendered in the body of the web page that can inform users what to do.
I tracked down the source of this message to here if you wanted to help that project improve their messaging: https://github.com/grpc/grpc/blob/18d82d4a6a00cebfc874eb0b9c935a3ae4733c3a/tools/distrib/python/grpc_prefixed/templates/setup.py.template#L38
