### ISSUE TITLE
Email generated after changing user role shows enum

### ISSUE THREAD

**Issue by s-mm** [pypi/warehouse#12039]
Once a user has joined an org, the role of the user can be changed. When the role is changed, the email generated lists the new role as the enum value.

to recreate the steps-

- Click on 'Your organization'
- Select an org
- Scroll down to view the members in the org
- Change the role of any member and click on 'Save'

The following emails are generated

![test2](https://user-images.githubusercontent.com/37237726/183418403-8fdf722b-2629-48ff-bdff-f6fbf994a510.png)

![test3](https://user-images.githubusercontent.com/37237726/183418413-b7b15d59-d0f5-4926-a830-d467bf8f748a.png)

**Comment by ewdurbin** [comment]
The template variable values in https://github.com/pypi/warehouse/blob/637435d22451494c83a5c404c409211b25df7c13/warehouse/manage/views.py#L2022-L2037 need to be updated to `role.role_name.value`.

Resolving this should also include checking for this in other places where `role.role_name` or similar is called.

**Comment by miketheman** [comment]
Related https://github.com/pypi/warehouse/issues/6636

**Comment by divbzero** [comment]
Fixed by #12231.
