### ISSUE TITLE
External collaborator cannot leave the project

### ISSUE THREAD

**Issue by s-mm** [pypi/warehouse#12049]
An external collaborator who is also an Owner cannot leave the project

To recreate the issue-
1. Click on 'Your Projects'
2. Select a Project where the user is an external collaborator and Owner of the Project

The external collaborator cannot leave the project
![test9](https://user-images.githubusercontent.com/37237726/183531936-801e4b56-6ca3-4d69-9e2b-9bf8452ad80f.png)

**Comment by divbzero** [comment]
This is closely related to #4729.
