### ISSUE TITLE
Organization URL should accept just TLDs

### ISSUE THREAD

**Issue by s-mm** [pypi/warehouse#12051]
When creating a new org account, the  ️Organization URL should accept TLDs. It should auto expand to https:// and reject ftp://.

To recreate the issue-

- Log in
- Click on 'Your Organizations'
- Enter the URL and other details to create a new organization

The Organization URL accepts **ftp://.**

**Comment by ewdurbin** [comment]
We should reject non http/https URLs for sure. That's a high-ish priority.

Accepting tlds is low priority.

**Comment by miketheman** [comment]
We can reject the inputs from the form with a custom Validator pretty easily - https://github.com/pypi/warehouse/pull/12691

Adding a constraint to the DB is a little harder, as we're using `sqlalchemy_utils` [URLType](https://sqlalchemy-utils.readthedocs.io/en/latest/data_types.html#module-sqlalchemy_utils.types.url) today, which doesn't have any real configuration to it, nor do we install [`furl`](https://github.com/gruns/furl) to take advantage of the data structure, so I'm not sure if we gain much from using URLType in the DB, it's a `text` column with no other constraints. We can add a CheckConstraint against that condition - but would need to verify that no existing data in the prod DB before we add that migration with something like:

```sql
select link_url from organizations where link_url not like 'http%';
```

**Comment by miketheman** [comment]
And the automatic expansion changes the game somewhat - in that case, we'd back out the validator from the form, massage the input prior to inserting to the DB, and relying on the DB constraint to validate inputs.

**Comment by ewdurbin** [comment]
```
warehouse_test=> select count(*) from organizations;
 count 
-------
     0
(1 row)```

```
warehouse=> select count(*) from organizations;
 count 
-------
     0
(1 row)
```

So we're good with a CheckConstraint.
