### ISSUE TITLE
Support edit token scope

### ISSUE THREAD

**Issue by jossef** [pypi/warehouse#12063]
Please add an option to edit the scope of an existing API token. I'd like to narrow down the scope of a token to a newly created package without creating a new token.

🙏
> ![image](https://user-images.githubusercontent.com/1287098/184081872-8dd22d9a-866d-463c-9170-9239bb432eb9.png)

**Comment by di** [comment]
All API tokens support adding caveats to narrow scope, so you could potentially do this yourself with https://pypi.org/project/pypitoken/, but we have no plans introduce this feature to PyPI, as we would prefer you to create a new token that is singly scoped to the project in question instead.
