### ISSUE TITLE
How to create a whl which includes another bar.gz, and Then, when installing whl, also install bar.gz

### ISSUE THREAD

**Issue by yudonghai** [pypi/warehouse#12096]
I want to create a foo.whl - when you pip install foo, it also install bar, that is packaged in to foo.whl as bar.gz 

I don't want tocreate another whl with bar.gz.

How can I achieve it? thanks very much

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.

**Comment by yudonghai** [comment]
@di I want to push a whl package, and it includes a gz file, for example, a.whl and b.gz is packaged in to a.whl. when install the a.whl, Can b.gz be installed automatically too?

**Comment by di** [comment]
It seems like you might be describing https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#package-data

You can ask in https://github.com/pypa/setuptools instead if you're using Setuptools, otherwise https://github.com/pypa/packaging-problems

**Comment by yudonghai** [comment]
thanks @di

I know this package-data https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#package-data,

I can put another gz to this, but I want to installed it automatically when installing the a.whl. for example, two whl files(a.whl and b.whl),  b.whl in the package_data of a, but when installing a.whl, the b.whl is only put the installation path, how to trigger it's installation automatically?
