### ISSUE TITLE
JupyterLab incorrect error.

### ISSUE THREAD

**Issue by Saatdhaan** [pypi/warehouse#12107]
Whilst learning Python I was given the following code as an exercise. You will see at the bottom there is an error:
"TypeError: "tuple" object is not callable. "
I spent some time trying to get rid of the error but couldn't.
The person delivering the code demonstrated it worked on replit.com i.e. gave a random name from the input list.
I tried it on PyCharm and Spyder and they both worked flawlessly as per the replit example.
It seems there is a bug in JupyterLab and this is just for your infomation should you want to address it.

import random
names_string = input("Give me everybody's name separated by a comma. ")
names = names_string.split(", ")
len(names)
print(names)
num_items = len(names)
random_choice = random.randint(0, num_items - 1)
print(random_choice)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_7480\1290467816.py in <module>
      5 print(names)
      6 num_items = len(names)
----> 7 random_choice = random.randint(0, num_items - 1)
      8 print(random_choice)

TypeError: 'tuple' object is not callable

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
