### ISSUE TITLE
Expose which projects are fully protected by 2FA (both visually and programmatically)

### ISSUE THREAD

**Issue by brettcannon** [pypi/warehouse#12128]
**What's the problem this feature will solve?**
Let people know which projects they rely on are the most vulnerable to phishing attacks.

**Describe the solution you'd like**
Two parts. One is visually show on pypi.org when a project is protected by 2FA thanks to all people with release access having 2FA turned on. Two is exposing via some API the data as to whether this holds true (either at the time of a specific release or for the whole project via #11825 ).

**Additional context**
I currently don't see a way to know if a project is following good security practices by using 2FA. For me, it might act as a tiebreaker if I'm trying to pick between two similar projects.

**Comment by miketheman** [comment]
> I currently don't see a way to know if a project is following good security practices by using 2FA.

All other parts of the request aside, my hope is that we can accelerate to the finish line of "everyone has 2FA" and not need the visibility. 😁

**Comment by di** [comment]
Somewhat related, https://github.com/pypi/warehouse/pull/11793 has some discussion about exposing the criticality of a given project.

**Comment by di** [comment]
This is maybe blocked on https://github.com/pypi/warehouse/issues/11825. We should also discuss what level of detail we would provide with regards to exposing 2FA status (e.g., do we say what form of 2FA is in use?).

**Comment by di** [comment]
This can probably be closed given https://blog.pypi.org/posts/2023-05-25-securing-pypi-with-2fa/.

**Comment by dstufft** [comment]
agreed
