### ISSUE TITLE
2FA giveaway lists critical + 2FA required projects, should only list critical

### ISSUE THREAD

**Issue by hugovk** [pypi/warehouse#12138]
**Describe the bug**

The 2FA key giveaway eligibility says:

"Congrats, you may be eligible to receive a promo code! The following projects you maintain are considered critical projects:"

But not all of these 15 are critical:

<img width="903" alt="image" src="https://user-images.githubusercontent.com/1324225/186908565-479f41ab-6b23-4506-8469-f164fd49b96e.png">

**Expected behavior**

Only list the critical projects. 

At https://pypi.org/manage/projects/ only these 4 are listed as critical: prettytable, humanize, ujson, Pillow.

**To Reproduce**

1. Visit https://pypi.org/security-key-giveaway/
2. Click "Log in to determine if you are eligible" and log in

**My Platform**

n/a

**Additional context**

I have 18 projects at https://pypi.org/manage/projects/

* 4 are critical
* 11 I've also set as 2FA required
* looks like these 4+11 are being listed as critical on the promo page, but it should just be the 4

**Comment by di** [comment]
Thanks, looks like this line is incorrect: https://github.com/pypi/warehouse/blob/f2d6fc455a135b3b3ba72539d5c9f4c4f0d48223/warehouse/views.py#L487

It's taking into account all projects that require 2FA, not just the critical ones. We'll probably want to additionally filter this comprehension on `project.pypi_mandates_2fa`: https://github.com/pypi/warehouse/blob/604b675e9c554ce7da6d4af8f4019a79282ed864/warehouse/packaging/models.py#L157
