### ISSUE TITLE
Bad version name in jw.util package

### ISSUE THREAD

**Issue by donchkat** [pypi/warehouse#12144]
## Bad source in Weblate

**Link to the source string:** https://pypi.org/project/jw.util/-class.-jw.util.version.Version-/ 

**Description of the problem:** There is a strange version that seems wrong in the versions list of jw.util package in PyPI repository.
[Link to the release history of the package](https://pypi.org/project/jw.util/-class.-jw.util.version.Version-/#history) - you can see that this versions is in the bottom of the list. 
Please let me know if this version name is normal. 
Thanks!

**Comment by di** [comment]
Thanks for the report. This is no longer a valid version, but was possible at the time the release was created (2014) and thus is just a historical artifact.
