### ISSUE TITLE
Document how we cache our APIs

### ISSUE THREAD

**Issue by dstufft** [pypi/warehouse#12155]
In https://github.com/pypi/warehouse/issues/12095#issuecomment-1231801345 @pfmoore mentioned:

> Having said that, I do think it might be useful to document the caching behaviour. Things like that have as you say important but non-obvious implications on how people can use the APIs. And people tend to only find out about them through heresay. 

I think that documenting our overall caching strategy for the API endpoints would be a positive thing, and would likely aid people in writing against our APIs plus let them understand why sometimes surprising behavior happens.

**Comment by di** [comment]
This is documented here: https://warehouse.pypa.io/api-reference/index.html#caching
