### ISSUE TITLE
Escaped HTML visible in package description on pypi.org

### ISSUE THREAD

**Issue by sergei-maertens** [pypi/warehouse#12162]
**Describe the bug**

After publishing the package, there is some escaped HTML visible:

```
<nav class="contents" id="contents">
(table of contens, rendered properly)
</nav>
```

Seeing this with these projects: 

* https://pypi.org/project/zgw-consumers/
* https://pypi.org/project/django-simple-certmanager/

I suspect that something is going wrong with the `contents::`` rst directive, but I can't guarantee this.

**Expected behavior**

No HTML should be visible, instead pypi.org should properly convert the rst into HTML.

**To Reproduce**

* https://pypi.org/project/zgw-consumers/, with readme file: https://github.com/maykinmedia/zgw-consumers/blob/main/README.rst
* https://pypi.org/project/django-simple-certmanager/, with readme file: https://github.com/maykinmedia/django-simple-certmanager/blob/main/README.rst

**My Platform**

* Brave 1.42.88 (Chromium 104.0.5112.81)
* Packages published using the official Github action
* Package built on Github CI with the latest setuptools/wheel that's available (`pip install pip setuptools wheel --upgrade`)

**Additional context**

I cannot reproduce this using any of the `rst2htmlX.py` scripts in my virtualenv.

**Comment by di** [comment]
This is likely an issue with https://github.com/pypa/readme_renderer, not PyPI. I'd recommend opening this issue there instead.

**Comment by sergei-maertens** [comment]
I created pypa/readme_renderer#258 there, thanks for the pointer!

**Comment by sergei-maertens** [comment]
Thanks for the pointer, I couldn't figure where the code for that
description renderer lives!
