### ISSUE TITLE
Disabling password resets for specific email (e.g. public email)

### ISSUE THREAD

**Issue by jack1142** [pypi/warehouse#12186]
**What's the problem this feature will solve?**
Since I can only set my public PyPI email to one of the verified emails and verified emails can be used for password resets, by adding a custom domain email as my public email I'm telling everyone "watch this domain's expiry dates very carefully so that if you're lucky, you can reset my password and publish malware in my name".

**Describe the solution you'd like**
I'd like to have a way to disable password resets for some of the emails verified on my PyPI account. By default, a newly added email should be available for account recovery and the user should explicitly disable account recovery for it if they want to.

**Additional context**
The section "Email security is your top priority" in [Security for package maintainers post by Seth Michael Larson](https://sethmlarson.dev/blog/security-for-package-maintainers#email-security-is-your-top-priority)

**Comment by di** [comment]
Thanks for the issue. At this time, we're not planning to add features which would significantly increase PyPI's support burden [(which is already high)](https://github.com/pypa/pypi-support/issues/796), as this likely would for users who have turned off password resets but legitimately need to regain access to their account.

Instead, our preference is for users to use 2FA on PyPI, ideally using security keys, which does not have the effect of disabling attempts at password resets, but does prevent account compromise in the event of domain resurrection/takeover.

I'm going to close this in favor of a broader 'meta' issue/discussion about how we can offer features like this, and what they should be: https://github.com/pypi/warehouse/issues/12255

**Comment by jack1142** [comment]
Thanks for taking the time to respond to my issue. In case it helps with future decisions in #12255 or some other issue, I'd like to elaborate a bit more on this feature request.

> as this likely would for users who have turned off password resets but legitimately need to regain access to their account.

Somehow I missed this in the description but my intention was that at least one email would have to remain available for recovery, that's pretty crucial to my request and I somehow did not mention it, sorry about that...

My reason for this is just that I want to be able to have a public email on PyPI without having that email available for password recovery. Perhaps there's a better way to solve this but this was just my idea based on how GitLab (and GitHub, sort of) does it.

> Instead, our preference is for users to use 2FA on PyPI, ideally using security keys, which does not have the effect of disabling attempts at password resets, but does prevent account compromise in the event of domain resurrection/takeover.

Hmm yeah, that's fair, after password recovery one would still need 2FA to login so I would still be safe. It still sits wrong with me to introduce a potential attack vector, even if it requires 2FA but I have to agree that this definitely increases the security a lot and makes it rather unlikely to be a problem.
