### ISSUE TITLE
It's not extracting anything under '/Annots'

### ISSUE THREAD

**Issue by gchang1020** [pypi/warehouse#12187]
**Describe the bug**
get a pdf: input1 = PyPDF2.PdfFileReader(open(src, "rb"))
get a pdf page: page = input1.getPage(i)
iterate on for annot by page['/Annots']
then what?

subtype = annot.getObject()['/Subtype']
there is nothing under subtype '/Text' nor '/Contents'!

**Expected behavior**
highlighted text (annotation) got be somewhere under /Annots
there needs to be a way to extract them

**To Reproduce**

import io
import sys
import PyPDF2

sys.stdout = io.TextIOWrapper(sys.stdout.buffer,encoding='utf8')

try:
    src = sys.argv[1]
except:
    src = r'd:/Gordon & Ynitso 2022.pdf'

# put the role into the rst file
print('.. role:: slide-title')
print('')

input1 = PyPDF2.PdfFileReader(open(src, "rb"))
nPages = input1.getNumPages()

for i in range(nPages) :
    # get the data from this PDF page (first line of text, plus annotations)
    page = input1.getPage(i)
    # print(page)
    
    text = page.extractText() #.decode('utf-8')
    # text = str(page.extractText(), decode='utf-8')
    # print(text)
    # exit()
    
    print(':slide-title:`' + text.splitlines()[0] + '`')
    print('===')

    annos = page.annotations
    try:
        if "/Annots" in page:
            for annot in annos: #page['/Annots']:
                # print('annot')
                # print(annot.getObject())

                # Other subtypes, such as /Link, cause errors
                subtype = annot.getObject()['/Subtype']
                print('subtype: ')
                print(subtype)
                
                if subtype == "/Text":
                    print(annot.getObject()['/Contents'])
                    print('...')
                # exit() # 1st annot
        else:
            print("None")
    except:
        # there are no annotations on this page
        pass
    exit() # 1st page
    
print('')

**My Platform**

OS: Win10
System Type: x64-based PC
Processor: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz, 1800 Mhz, 4 Core(s), 8 Logical Processor(s)

**Additional context**

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
