### ISSUE TITLE
Cannot extract highlighted text by using pypdf2

### ISSUE THREAD

**Issue by gchang1020** [pypi/warehouse#12188]
**Describe the bug**
After get page = input1.getPage(), then "for annot in page['/Annots'],  the highlighted (annoation) cannot be extracted

**Expected behavior**

Expected behavior is to get the text

**To Reproduce**

import io
import sys
import PyPDF2

sys.stdout = io.TextIOWrapper(sys.stdout.buffer,encoding='utf8')

try:
    src = sys.argv[1]
except:
    src = r'your-pdf-file-name.pdf'

# put the role into the rst file
print('.. role:: slide-title')
print('')

input1 = PyPDF2.PdfFileReader(open(src, "rb"))
nPages = input1.getNumPages()

for i in range(nPages) :
    # get the data from this PDF page (first line of text, plus annotations)
    page = input1.getPage(i)
    # print(page)
    
    text = page.extractText() #.decode('utf-8')
    # text = str(page.extractText(), decode='utf-8')
    # print(text)
    
    print(':slide-title:`' + text.splitlines()[0] + '`')
    print('===')

    annos = page.annotations
    try:
        if "/Annots" in page:
            for annot in annos: #page['/Annots']:
                # print('annot')
                # print(annot.getObject())

                # Other subtypes, such as /Link, cause errors
                subtype = annot.getObject()['/Subtype']
                # print('subtype: ')
                # print(subtype)
                                
                if subtype == "/Text":
                    print(annot.getObject()['/Contents'])
                    print('...')
                # exit() # 1st annot
        else:
            print("None")
    except:
        # there are no annotations on this page
        pass
    exit() # 1st page
    
print('')

**My Platform**

Win10
x64-based PC

**Additional context**

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
