### ISSUE TITLE
Commit Hash in JSON API

### ISSUE THREAD

**Issue by shariq027** [pypi/warehouse#12196]
**What's the problem this feature will solve?**
I am trying to get the commit Id from the API **GET /pypi/sampleproject/1.2.0/json HTTP/1.1**

**Describe the solution you'd like**
It would be great if we are able to get Get commit hashes.

Please help me understand if we already getting it in some or the other way.

**Comment by di** [comment]
Do you mean the commit hash of the source repository? This is not something PyPI is aware of or able to provide.

**Comment by shariq027** [comment]
But I see that npm is Providing all the commit for a specific version.
Could you please help me understand what is the sha, md5 key/hash provided in the response of  **/pypi/sampleproject/1.2.0/json** ?

**Comment by di** [comment]
These are the hash digests of the files in question:

```
$ curl -s https://pypi.org/pypi/sampleproject/1.2.0/json | jq -r .urls[0].digests.md5
bab8eb22e6710eddae3c6c7ac3453bd9

$ wget -q -O - $(curl -s https://pypi.org/pypi/sampleproject/1.2.0/json | jq -r .urls[0].url) | tee file | md5sum
bab8eb22e6710eddae3c6c7ac3453bd9

$ curl -s https://pypi.org/pypi/sampleproject/1.2.0/json | jq -r .urls[0].digests.sha256
7a7a8b91086deccc54cac8d631e33f6a0e232ce5775c6be3dc44f86c2154019d

$ wget -q -O - $(curl -s https://pypi.org/pypi/sampleproject/1.2.0/json | jq -r .urls[0].url) | tee file | sha256sum
7a7a8b91086deccc54cac8d631e33f6a0e232ce5775c6be3dc44f86c2154019d
```

They are unrelated to the source control repository.

**Comment by shariq027** [comment]
ok, Thanks for the info
