### ISSUE TITLE
Top level section header ignored in text/reST package description, not in text/markdown

### ISSUE THREAD

**Issue by dnicolodi** [pypi/warehouse#12204]
When using text/reST for the package description in the METADATA package dist-info file, the top level section header is omitted in the rendered page, however it is included when the description is in text/markdown format.

This can be easily verified running `python -m readme_renderer README.rst` vs `python -m readme_renderer README.rst`.

Is this intentional? Looking at the `docutils` configuration used in `readme_renderer` it looks so. However, why are markdown and reST threated differently?

**Comment by miketheman** [comment]
This issue is better reported over at https://github.com/pypa/readme_renderer
The basic answer is that the RST behavior is intentional, and the markdown behavior needs some work to make it on par with the RST behavior.

**Comment by di** [comment]
Closing in favor of https://github.com/pypa/readme_renderer/issues/260.
