### ISSUE TITLE
Unable to install the latest version of this package

### ISSUE THREAD

**Issue by rafalkrupinski** [pypi/warehouse#12224]
**Describe the bug**

The latest version in the release history doesn't show as the version in the search results, is an empty entry in the json, and is not installable.
https://pypi.org/project/mimeparse/#history

**Expected behavior**

The latest version should be available

**To Reproduce**

- [search results](https://pypi.org/search/?q=mimeparse) show mimeparse 0.1.3
- [project page](https://pypi.org/project/mimeparse/) shows 0.1.4
- [json](https://pypi.org/pypi/mimeparse/json) shows releases/0.1.4 element is empty
- `pip install mimeparse` will only install 0.1.3

**My Platform**

- pip 22.2.2 from /Users/matte/Library/Caches/pypoetry/virtualenvs/gsmtasks_project_api-RodA6A9H-py3.10/lib/python3.10/site-packages/pip (python 3.10)
- Python 3.10.6
**Additional context**

**Comment by miketheman** [comment]
I can confirm that the version of 0.1.4 does not display any files on pypi.org

Considering that the source project also does not display a version for 0.1.4 https://code.google.com/archive/p/mimeparse/downloads where has the project gone and who's trying to to upload a Project release with no files?

**Comment by rafalkrupinski** [comment]
So is it's not a problem with PyPI? Shell I contact the author then?

**Comment by miketheman** [comment]
Related https://github.com/pypi/warehouse/issues/4520 explains why this could have happened, as the last release was a while ago.

Yes, it seems like the author may have had an issue uploading 0.1.4 and the warehouse allowed it back then.
If there’s newer code, by all means, contact the author.

**Comment by di** [comment]
Yes, this is a historical edge case. There are no distribution files for this release.
