### ISSUE TITLE
Document best practices for securely managing projects

### ISSUE THREAD

**Issue by pfmoore** [pypi/warehouse#12244]
**What's the problem this feature will solve?**
Many projects on PyPI are relied on by significant numbers of consumers. And supply chain integrity and the risks involved are very high profile these days - with little or no consideration being given to the fact that many developers are hobbyists, and have no real experience in securing high-value software. In particular, the average developer may not have sufficient knowledge or understanding of security practices and terminology in order to maintain their accounts securely.

**Describe the solution you'd like**
Documentation of good security practices for password management, use of 2FA and other tools such as biometrics, OS-level identity management, etc. This should be written for the end user, explicitly avoiding technical terms such as "webauthn" or "TOTP" in favour of descriptions that developers can relate to their working environment. In particular, care should be taken *not* to assume that users understand web application development, and may well be "scared off" certain technologies by reports in the media of hacking.

Documentation should cover:

* Best practices for password management, including recommendations of good tools to use.
* How to set up and manage 2FA, including what options are available and recommended approaches.
* OS and hardware supplied solutions such as biometrics.
* How to set things up so that working on multiple devices, both PC and mobile, is straightforward.
* Good practices for things like storing API keys, how to set up signing of releases, etc.

The documentation should be *specific*, recommending actual tools and devices, and should not assume that the reader is necessarily interested in doing their own research.

**Additional context**
Users working on Python projects as a hobby are unlikely to want to set up a complex software management environment, so advice on how to set up a minimal system, using as much as possible OS-supplied or commonly available components, would be important.

Ideally, the document should *not* be restricted to just securing PyPI credentials, but should cover the whole software development supply chain, including github, CI and automated builds, etc. It is important to have one definitive document that covers everything, and offers consistent[^1] and unified recommendations. If that means that this should not be hosted as part of the PyPI documentation, but somewhere else (as a blog post, or "best practices" document somewhere) and linked from the PyPI docs, then I'm fine with that.

See the thread starting at https://discuss.python.org/t/pypi-security-work-multifactor-auth-progress-help-needed/1042/51 for further context.

[^1]: A PyPI document recommending a tool that doesn't work with (say) github, is no use, as it simply leaves me having to manage multiple tools/devices with no good information on how to unify them.

**Comment by di** [comment]
Seems like this would be more appropriate to be part of https://github.com/pypa/packaging.python.org/ instead? PyPI's documentation is really only currently scoped to using/developing PyPI, not the other parts of the 'whole software development supply chain' you mention there.

**Comment by pfmoore** [comment]
I don't have a problem with that. @dstufft suggested raising it here, but I'm happy for it to be moved if the PUG seems more appropriate.

**Comment by ewdurbin** [comment]
I tend to agree that this isn't specific to PyPI, or even Python packaging itself. These best practices and standards would ideally be document broadly by an organization like the [OpenSSF](https://openssf.org).

As a project PyPI works to implement features that support industry best practices. One part of this issue, the terminology we use specifically, could be addressed via a specific issue that matches such guidelines.

**Comment by di** [comment]
I can't actually transfer this to https://github.com/pypa/packaging.python.org/ because we're in a different org now, so I'll close this here, but would definitely encourage you to copy/paste this into that tracker instead.

**Comment by pfmoore** [comment]
I've opened https://github.com/pypa/packaging.python.org/issues/1148
