### ISSUE TITLE
Security history IP Addresses include 127.0.0.1 

### ISSUE THREAD

**Issue by domdfcoding** [pypi/warehouse#12306]
**Describe the bug**
In the security history under https://pypi.org/manage/account/, the IP addresses which generated the event are listed. This includes mine (starting "2a02"), and what must be the PyPI server, as shows "Redacted". 

However, the event for them email telling me a project of mine has been marked as critical has the IP address 127.0.0.1 (i.e. localhost). 
It's not a problem, just surprising to see, and it might confuse somebody.

**Expected behavior**
For consistency the 127.0.0.1 IP address shows instead as "Redacted", or marked in some other way that it was the PyPI server itself.

**To Reproduce**
https://pypi.org/manage/account/, and scroll down to "Security History", but it might not be in your log so here's a screenshot:

![image](https://user-images.githubusercontent.com/8050853/193627028-55144c29-a849-4320-a716-833122f9e6ef.png)

**My Platform**
N/A

**Additional context**

**Comment by di** [comment]
Thanks for the report. I created #12309 to fix this going forward, but we'll need to manually edit these events going backwards for notifications that have already been sent.
