### ISSUE TITLE
sqlalchemy_inspect - module 'time' has no attribute 'clock' where I don't use time library

### ISSUE THREAD

**Issue by brunonascimento89** [pypi/warehouse#12301]
**Describe the bug**

I am not using time library and I got an error (module 'time' has no attribute 'clock') on my package sqlalchemy_inspect - repo https://github.com/brunonascimento89/sqlalchemy-inspect

**Expected behavior**

Download the database schema

**To Reproduce**

1. pip install -i https://test.pypi.org/simple/ sqlalchemy-inspect
2. write the following code
```python
from sqlalchemy_inspect import database
from decouple import config

conn = database.SQL(
    host=config('DB_HOST'),
    port=config('DB_PORT'),
    database=config('DB_NAME'),
    user=config('DB_USER'),
    password=config('DB_PASS'),
)
conn.extract_model(filename='test_model.py', engine='mysql+pymysql', engine_args=True)
```
where .env have
```python
DB_NAME=db_name
DB_USER=db_user
DB_PASS=db_pass
DB_HOST=db_host
DB_PORT=db_port
```

**Additional context**

Error:
```vscode
Exception has occurred: AttributeError
module 'time' has no attribute 'clock'
  File "project\directory\test_my_package\test.py", line 1, in <module>
    from sqlalchemy_inspect import database
```

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.

**Comment by brunonascimento89** [comment]
Hello @di. I got this reference on https://test.pypi.org/help/#feedback where they wrote "If you're experiencing an issue with PyPI itself, we welcome constructive feedback and bug reports via our [issue tracker](https://github.com/pypi/warehouse/issues)."
I cannot find another reference in pypi. Might you help me please? Thank you in advance
