### ISSUE TITLE
The new release 0.1.75 skips some business days

### ISSUE THREAD

**Issue by proxyhor** [pypi/warehouse#12324]
Before the last release, my code worked fine without errors, but after October 4, the working code simply stopped working. Error: list out of range.

It turns out that the new release does not take some business days. 

I did an experiment. The experimental period is from 2020-04-01 to 2020-04-30.

In 0.1.74 I took into account April 30, which is Thursday.

And in 0.1.75 the number of business days is 21, this version doesn't count the last day of the month (April 30).

Check the availability of April 30 on yahoo. There this date is present.

Judging from experience, in the new version of yfinance missing days are not few. I have attached the screenshots.

yf_0.1.75 - https://ibb.co/WDWHPKM
yf_0.1.74 - https://ibb.co/PCwSXFv
historical data in yahoo - https://ibb.co/D81b1Mx
calendar (2020-04) - https://ibb.co/jrvg8Gh

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.

**Comment by proxyhor** [comment]
Ohh thanks
