### ISSUE TITLE
IfxPy

### ISSUE THREAD

**Issue by analindezabrito** [pypi/warehouse#12354]
**Describe the bug**
<I have a python 3.10.8 and there ins´t a library IfxPy for this python version.
Can provide a version for this python version please.
Thanks>

**Expected behavior**

**To Reproduce**

**My Platform**

**Additional context**

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
