### ISSUE TITLE
mariadb connector is using old buggy version

### ISSUE THREAD

**Issue by atkellyx** [pypi/warehouse#12365]
Apologies in advance, I'm a newb.

The PyPi repo is hosting an old and buggy python connector:

`pi@camPi:~ $ pip3 install mariadb
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting mariadb
  Downloading mariadb-1.1.4.zip (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.4/97.4 kB 727.2 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-0of4ctfp/mariadb_8d26959a6287418381b219357b8a7517/setup.py", line 27, in <module>
          cfg = get_config(options)
        File "/tmp/pip-install-0of4ctfp/mariadb_8d26959a6287418381b219357b8a7517/mariadb_posix.py", line 64, in get_config
          print('MariaDB Connector/Python requires MariaDB Connector/C '
      TypeError: not enough arguments for format string
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

I reported this to mariadb who advised this bug was fixed in 1.1.5 so the repo needs to be updated.  Unfortunately they didn't provide me a link to 1.1.5 and their download page still shows 1.1.4.

I have asked them to update their download page.

Cheers

Anthony

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
