### ISSUE TITLE
Add DNSSEC to pypi.org

### ISSUE THREAD

**Issue by ChampiYann** [pypi/warehouse#12378]
**What's the problem this feature will solve?**

Adding DNSSEC to pypi.org improves security for organisations that use python dependencies. With DNSSEC, systems pulling dependencies from pypi.org are insured that the package being pulled originated from the pypi repository. This reduces the risk of a supply chain attack.

**Describe the solution you'd like**

DNSSEC is implemented and is verified by the result of [this scan](https://en.internet.nl/site/pypi.org/).

**Additional context**

**Comment by ewdurbin** [comment]
This is done. https://github.com/pypi/infra/pull/108

FWIW we have not pursued DNSSEC in the past due to dubious claims of efficacy and complexity of setup.

Given that our registrar and DNS provider now support it fairly seamlessly this will at least reduce the chatter around it.
