### ISSUE TITLE
Issues Installing pypi packages on VPN

### ISSUE THREAD

**Issue by rishabh-bhatnagar-soroco** [pypi/warehouse#12411]
**Describe the bug**
After connecting to vpn, I am not able to install packages via pip on wsl

**Expected behavior**
Packages available with pypi must be resolved

**To Reproduce**
1. Connect to vpn
2. Open a wsl instance
3. Try installing any lib (I had used pyinstrument for testing)

**My Platform**
1. Windows os
2. wsl: Ubuntu 20.04 Focal LTS

**Comment by di** [comment]
Please file a network access issue here instead: https://github.com/pypa/pypi-support/issues/new/choose, but note that this is very likely an issue with your local VPN or network and not something we can assist with or an issue with PyPI itself.
