### ISSUE TITLE
Changing the organization display name shows error code 404

### ISSUE THREAD

**Issue by s-mm** [pypi/warehouse#12417]
When the display name of the organization is updated, an error is observed.

To recreate the error-

- Click on Your organizations
- Click on Manage for a specific organization
- Click on Settings
- Enter the new display name
- Click on 'Update organization'

This leads to manage/organization/org_name/settings/ with error code 404. Also, the display name is not updated.

**Comment by ewdurbin** [comment]
I'm unable to reproduce this.

**Comment by di** [comment]
@s-mm Was this one of the ones we came across together? I'm trying to recall which 404 this was.

**Comment by s-mm** [comment]
@di No, this wasn't the one we encountered. We saw this error- https://github.com/pypi/warehouse/issues/12418

**Comment by divbzero** [comment]
I was able to reproduce the error. It seems to occur for Company organizations only.
