### ISSUE TITLE
Missing email in organization account operations

### ISSUE THREAD

**Issue by s-mm** [pypi/warehouse#12420]
For the following operations, no email is generated-

Revoking collaborator invitation-

- Click on Your organizations
- Click on Manage for a specific organization
- Click on Projects
- Click on Manage for a specific project
- Click on Collaborators
- Click on Revoke invite and then confirm the operation

Deleting a project-

- Click on Your organizations
- Click on Manage for a specific organization
- Click on Projects
- Click on Manage for a specific project
- Click on Settings
- Enter the project name
- Click on Delete project

When deleting the project, the email to the owners should mention who deleted it. This information is not required when revoking external collaborator invitation.

**Comment by miketheman** [comment]
For revoking, we generate an email with "An invitation for you to join the "sample1" organization has been canceled."
Refs: `warehouse.email.send_canceled_as_invited_organization_member_email()` - no further action needed.

Org Project deletion needs a minor change, will add a PR.
