### ISSUE TITLE
Project maintainer should not lose maintainer status

### ISSUE THREAD

**Issue by s-mm** [pypi/warehouse#12423]
When a project is added to an organization, the individual owner/maintainer loses their project role status. This status should exist even after the transfer.

To recreate the issue-

- Click on Your organizations
- Click on Manage for a specific organization
- Click on Projects
- Scroll down to the bottom of the page and select a project from the drop down list. The projects associated with the user will appear in the list. 
- Click on Transfer existing project

The organization becomes the sole owner of the project.

![Image](https://user-images.githubusercontent.com/37237726/197813867-526f9d36-a48d-4b22-bccd-869fbaa65a8f.png)

**Comment by ewdurbin** [comment]
I'd like to hear more of your thoughts here @di, since I've been told this feedback comes from you.

Since we require a User to be both owner of a project and owner of an organization to perform a transfer, they retain their role implicitly, but we don't leave the dangling Role associated.

**Comment by di** [comment]
It's information loss, basically. There's no option to maintain the current list of collaborators, so transferring a project to an organization would require who were the original collaborators and re-adding them to the organization.

This is going to be very tedious for a large organization with lots of projects and lots of unique collaborators on those projects, who likely want to maintain the existing collaborator structure.

**Comment by di** [comment]
> Since we require a User to be both owner of a project and owner of an organization

Why do we require them to be organization owners? IMO this should be like regular collaborator role invites, where anyone can invite an organization to accept a project transfer, but only organization owners can accept the transfer.

I'm imagining it's going to be a common use case where it doesn't make sense for any project collaborators to be organization owners.

**Comment by ewdurbin** [comment]
It's a bit too much for our timeline to implement invitations. Added notes in 0e34a0e25 and filed #13394 as a feature request.

**Comment by di** [comment]
Is invitation strictly necessary? My main concern is losing the lost of roles for all the collaborators that didn't initiate the transfer. Can their roles get turned into non-owner roles on the organization instead of getting dropped?

**Comment by ewdurbin** [comment]
No one except the transferring owner has their permissions changed
