### ISSUE TITLE
Manage option should lead to organization, team, project settings

### ISSUE THREAD

**Issue by s-mm** [pypi/warehouse#12429]
When the 'Manage' button is clicked, it should land on the Settings page for an organization, team or project. 

To recreate this issue-
Click on Your organizations
Click on Manage for a specific organization

or

Click on Your organizations
Click on Manage for a specific organization
Click on Teams
Click on Manage for a specific team

or 

Click on Your organizations
Click on Manage for a specific organization
Click on Projects
Click on Manage for a specific project

**Comment by ewdurbin** [comment]
Seems valid. The current behavior matches "Manage" for existing non-organization Project views. Should those change as well @di?

**Comment by di** [comment]
When testing this with orgs, it just was feeling weird that "Manage" was going to the list of projects and not the other sub-pages (list of teams or org settings). I think it probably would be more intuitive to have this default to the settings subpage, and require an extra click to get to the other two.

I think this is a weird thing about our existing views too, but changing that is probably out of scope.
