### ISSUE TITLE
Localhost error in organization email

### ISSUE THREAD

**Issue by s-mm** [pypi/warehouse#12424]
In any email generated after an organization operation, the links in the email lead to localhost. The links should be able to detect the host and direct the page accordingly.

This is not an issue specific to organization features.

**Comment by miketheman** [comment]
For clarification, this was surfaced when using tools like ngrok to share a locally-running application with others. The resulting URL in the email showing up in maildev isn't then clickable by the viewer, making them have to replace the URL manually.

**Comment by di** [comment]
I suspect this is actually similar to https://github.com/pypi/warehouse/issues/11792 and not due to how PyPI was being run at the time, but could be wrong!

**Comment by miketheman** [comment]
It's entirely possible - I'll review the notes I had from that effort - I still have [an open PR](https://github.com/pypi/warehouse/pull/11797) on that topic, but that was largely looking to determine the value from the registry - which I don't think would work in the ngrok/localhost case

**Comment by miketheman** [comment]
I don't know what changed, but I tested this today and was able to confirm that when running `make serve` and `ngrok` in another session, the email generated in maildev contained a URL to ngrok, and I was able to click it no problem.

Closing as can't repro.
