### ISSUE TITLE
Add organization user details to organization operation email

### ISSUE THREAD

**Issue by s-mm** [pypi/warehouse#12421]
For any organization account operation, the email should mention who performed that operation. For example, if a user role is changed, the email does not list the user who performed that operation.

Assign a user role

- Click on Your organizations
- Click on Manage for a specific organization
- Click on People
- Assign a new role to a user who is a member of the organization. The new role can be owner, manager, billing manager or member. 
- Click on Save

This change needs to be performed for all org operations. The only exception would be revoking a external collaborator invitation as we would not want to expose user details to an external user.

**Comment by s-mm** [comment]
Priority - high

**Comment by miketheman** [comment]
I have found the right email template for the "role-changed-as-organization-member" action - instead of listing out emails, would it be better to list out the org actions?

**Comment by s-mm** [comment]
Not sure if listing out org actions is the right thing to do. An email is generated after every org action (not limited to role change). Few emails have the user info missing. Would listing out org actions help identify which emails have the user info missing?
