### ISSUE TITLE
Change in organization details is not reflected in the Stripe invoice

### ISSUE THREAD

**Issue by s-mm** [pypi/warehouse#12426]
When an organization account name is updated, the change is not reflected in the Stripe invoice/receipt. The same issue occurs when billing address is updated.

1. Should we display the organization account name or organization display name?
2. The invoice/receipt should say PyPI instead of Warehouse
3. Any change to organization account/display name and billing address should show up in the invoice/receipt. 

![Image](https://user-images.githubusercontent.com/37237726/197813602-575481ed-8d64-4062-ad18-d1a9b8937a6b.png)

**Comment by ewdurbin** [comment]
Seems we should definitely be sending an update to stripe when org names change. We can address the prefix "Warehouse Organization" at that time.

We can probably update the product names to reflect "PyPI Organization Account" and similar at that time.

I anticipate we'll also need to do some updates to capture a human name for billing before launch. We'll address this as part of that phase.

**Comment by ewdurbin** [comment]
> 1. Should we display the organization account name or organization display name?

I'm gonna go with "both"

> 2. The invoice/receipt should say PyPI instead of Warehouse

"Warehouse" comes from the `site.name` setting, so it will automatically be "PyPI" for pypi.org. 

https://github.com/pypi/warehouse/blob/ff5db0f76133185a1735522f42eba3f99331ff8f/warehouse/manage/views/organizations.py#L489

> 3. Any change to organization account/display name and billing address should show up in the invoice/receipt.

I'll get an update method for the customer name put together, that shouldn't be a problem.

We don't touch billing address, that is all in the portal.

**Comment by ewdurbin** [comment]
addressed in 089034d72 as part of #13395
