### ISSUE TITLE
Information displayed when deleting an organization is not sufficient

### ISSUE THREAD

**Issue by s-mm** [pypi/warehouse#12428]
When deleting an organization, there is a link to transfer ownership and then delete the project. The link should be changed to transfer ownership, remove a project or delete the project. 

To recreate this issue-

- Click on Your organizations
- Click on Manage for a specific organization
- Click on Settings
- Scroll to the bottom of the page and click on Delete organization

Transferring a project to an individual user is not sufficient. It should be removed from the organization or deleted.

**Comment by s-mm** [comment]
Priority - high

**Comment by ewdurbin** [comment]
ca2000c9a6fbb7d732536582cdfbe7178ecf018d: <img width="813" alt="transanddelete" src="https://user-images.githubusercontent.com/1200832/230731807-c01a879f-0a76-4d2b-963f-a2d0aa720a6a.png">
