### ISSUE TITLE
AdminFlag.READ_ONLY no longer works

### ISSUE THREAD

**Issue by ewdurbin** [pypi/warehouse#12422]
**Describe the bug**

Enabling the `read-only` admin flag leads to multiple errors.

**Expected behavior**

Enabling the `read-only` admin flag should at least allow the basic web ui, simple api, and JSON api to function without error.

**To Reproduce**

- Login as an admin user (`ewdurbin`:`password` in dev)
- Navigate to http://localhost/admin/flags
- Enable `read-only` flag and save
- Attempt any request with http://localhost/

**Additional context**

I'd like to use the `read-only` flag to minimize the overall impact of upgrading our Postgres database from 12 -> 14. Read only mode would allow us to keep all services online and readable while dumping from 12 and loading into 14 which would minimize the impact/downtime.

**Comment by ewdurbin** [comment]
Thanks for the fix @di, I'm curious if we should file a new issue to restore admin bypass? I'm kind of OK leaving read-only as an e-stop style flag though.

**Comment by di** [comment]
I'm OK leaving it as is, as it keeps things simple and I think it also gives us some additional security guarantees.
