### ISSUE TITLE
Organization name should be clickable

### ISSUE THREAD

**Issue by s-mm** [pypi/warehouse#12430]
1. In any email generated after an organization operation, the organization name in the email should be clickable
2. When a team or project is viewed, the organization name above the team or project should be clickable. 

![project1](https://user-images.githubusercontent.com/37237726/197818834-43b9a40f-bc73-4621-b222-f13aa4de65c4.png)
![team](https://user-images.githubusercontent.com/37237726/197818850-f711e180-92ae-4918-8b49-cd7fb86c1a21.png)

The first image shows an organization and project and the second image shows an organization and team. In both instances, the organization name is not clickable.

**Comment by ewdurbin** [comment]
For the manage views, would clicking that lead to the internal manage page for the organization or to the public profile?

For emails, it seems that public profile would be our only option. We can't do that until we have such a page.

**Comment by divbzero** [comment]
Currently, clicking on project name leads to the public profile of the project. To be consistent, we would probably want clicking on organization name (in both manage views and emails) to also lead to the public profile of the organization.
