### ISSUE TITLE
Titan security key issue with PyPI

### ISSUE THREAD

**Issue by wjakob** [pypi/warehouse#12434]
**Describe the bug**

I ordered a Titan security key using the (very generous) PyPI giveaway and just wanted to set this up online. I was able to reach the point where the browser talks to the device:

<img width="856" alt="Screen Shot 2022-10-26 at 00 30 23" src="https://user-images.githubusercontent.com/1203629/197894329-25eba3a6-7651-4bf7-8174-cf3ea625a8af.png">

However, after pushing the little button on the key, an error message shows up:

<img width="854" alt="Screen Shot 2022-10-26 at 00 27 49" src="https://user-images.githubusercontent.com/1203629/197894214-2196a6cb-d070-4b72-91a1-9839bab9a3b3.png">

**Expected behavior**

The key should be registered successfully.

**To Reproduce**

Attempt to register an USB-C titan security key using PyPI on macOS/Safari.

**My Platform**

macOS Monterey 12.6
Safari Version 16.0
Titan security key (USB-C version)

**Additional context**

The security key generally seems to work on my machine, using this specific browser. For example, I was able to associate it with my Google account.

My PyPI account name is `wjakob`.

**Comment by wjakob** [comment]
Curiously, registering the key using Chrome works, and I can subsequently log in via Safari, using that same key. It's just the setting up step that does not work using Safari.

**Comment by di** [comment]
This is maybe an issue that needs reported upstream with https://github.com/duo-labs/py_webauthn, which we're using for our WebAuthN backend.

(cc @woodruffw if you have any ideas)

**Comment by woodruffw** [comment]
No ideas off the top of my head, but I'll take a closer look.

**Comment by woodruffw** [comment]
Here's where the error comes from during device registration:

```python
    # Generate a hash of the expected RP ID for comparison
    expected_rp_id_hash = hashlib.sha256()
    expected_rp_id_hash.update(expected_rp_id.encode("utf-8"))
    expected_rp_id_hash_bytes = expected_rp_id_hash.digest()


    if auth_data.rp_id_hash != expected_rp_id_hash_bytes:
        raise InvalidRegistrationResponse("Unexpected RP ID hash")
```

...and the code during authentication looks very similar:

```python
    # Generate a hash of the expected RP ID for comparison
    expected_rp_id_hash = hashlib.sha256()
    expected_rp_id_hash.update(expected_rp_id.encode("utf-8"))
    expected_rp_id_hash_bytes = expected_rp_id_hash.digest()


    if auth_data.rp_id_hash != expected_rp_id_hash_bytes:
        raise InvalidAuthenticationResponse("Unexpected RP ID hash")
```

**Comment by woodruffw** [comment]
(I also have one of these keys, I think, so I can try reproducing this locally tomorrow.)

**Comment by di** [comment]
@woodruffw, did you have any opportunity to reproduce this?

**Comment by woodruffw** [comment]
Not yet 😅 -- I should have the time tomorrow.

**Comment by wjakob** [comment]
Mine says K40T.

**Comment by woodruffw** [comment]
Hmm, I probably have the first generation one then. 

Does yours look like this?

<img width="433" alt="Screenshot 2022-11-01 at 11 44 04 AM" src="https://user-images.githubusercontent.com/3059210/199275646-7f595ede-1fc8-4602-bdc8-6344dc899e5d.png">

**Comment by ewdurbin** [comment]
I'm unable to reproduce this using a K40T on MacOS 13.0.1 (22A400) running on M1 and Safari 16.1 (18614.2.9.1.12). Successfully enrolled and authenticated with the key.

**Comment by wjakob** [comment]
I will close this given that nobody is able to reproduce the issue. For me, it was in any case only the enrollment part that was problematic, and I could do that with another browser.
