### ISSUE TITLE
Deleting an organization should add a warning

### ISSUE THREAD

**Issue by s-mm** [pypi/warehouse#12432]
When deleting an organization, a warning should let the owner know to download invoices/receipts from Stripe. It should also indicate what will happen to the subscription plan - whether the plan will be cancelled automatically or if the user has to cancel the plan before deleting the organization.

**Comment by ewdurbin** [comment]
Seems we have two chances to communicate this, one in the "danger box"



![Image](https://user-images.githubusercontent.com/1200832/199565593-1cf42267-5528-43cd-8c71-34841fe4f2a3.png)

and one in the confirm modal



![Image](https://user-images.githubusercontent.com/1200832/199565610-eb622cd8-c530-40ed-b4d9-a6f49a442e37.png)


I'm not sure how hard it is to add text to the modal, but if its possible I think this would be good to do for _both_.

**Comment by s-mm** [comment]
Priority - high

**Comment by ewdurbin** [comment]
resolved in #13395
