### ISSUE TITLE
Various pages are localized into Chinese if you navigate via the release history.

### ISSUE THREAD

**Issue by glyph** [pypi/warehouse#12445]
**Describe the bug**

![image](https://user-images.githubusercontent.com/716529/198199254-4e559ffc-0da8-4c50-ade1-331ab345df09.png)
![image](https://user-images.githubusercontent.com/716529/198199281-dd29e410-7bed-4a4c-a120-45bfe8324015.png)
![image](https://user-images.githubusercontent.com/716529/198199547-942de640-c2d9-449b-bd1b-3a1ee9c9cf94.png)

**Expected behavior**

I expect these pages to be in English.

**To Reproduce**

1. Navigate to a project, i.e. https://pypi.org/project/requests/
2. Click "release history"
3. Click on a few different releases until the page turns chinese.  Not all versions seem to do this.  I have had some success with https://pypi.org/project/requests/2.28.0/ and https://pypi.org/project/Twisted/22.10.0rc1/ and I cannot get it to happen with any version of https://pypi.org/project/textual/.
4. Now the page will stay in chinese until you navigate from somewhere else, e.g. go to the search page and search for Twisted or Requests and click through from there.

**My Platform**

On macOS, tested on recent versions of Chrome and Safari, tested both logged in and logged out

**Additional context**

**Comment by uranusjr** [comment]
Also you seem to be able to switch to any language _except English_. The bug is probably in the localisation code that redirects you to the “first” localised language (Chinest Simplified) when it should show the unlocalised content (English) instead.

**Comment by ewdurbin** [comment]
This is almost certainly a regression due to #6864.

**Comment by ewdurbin** [comment]
Curious if for those able to reproduce: If you select a language explicitly in the switcher, does the correct translation come up?

**Comment by jenca-adam** [comment]
Does this happen only on recently updated packages?

**Comment by ewdurbin** [comment]
As far as I've been able to find, the issue is only happening when the `en` identifier is selected either by default or via cookie, and the translation being served is `zh_Hans`. This may indicate that something in our handling of `Accept-Language` headers is going haywire and setting the caching header `PyPI-Locale` to `en` when an `Accept-Language` header is negotiated to `zh-Hans`.

**Comment by wouterel** [comment]
By the way the link I posted to the plain package page without version number has the language problem, but going to the latest version by explicitly specifying it in the URL works just fine: https://pypi.org/project/perconet/0.2.0/

**Comment by ewdurbin** [comment]
Current theory is that the way we handle Accept-Language in VCL:

https://github.com/pypi/infra/blob/main/terraform/warehouse/vcl/main.vcl#L151

Differs in how our backends negotiate Accept-Language:

https://github.com/pypi/warehouse/blob/090575fd719fbce7e048656de27a9fb6d3bf3c34/warehouse/i18n/__init__.py#L92-L97

It seems to me that there may be a case where a common Accept-Language value is determined by our VCL to be `en`, then our backends decide it should be `zh-Hans`. Thus the requests is cached with `PyPI-Locale: en` but the response is in another language.

I need to investigate the differences in how (`accept.language_filter_basic` (VCL))[https://developer.fastly.com/reference/vcl/functions/content-negotiation/accept-language-filter-basic/], (`accept.language_lookup` (VCL))[https://developer.fastly.com/reference/vcl/functions/content-negotiation/accept-language-lookup/], and (`request.accept_language.best_match`)[https://docs.pylonsproject.org/projects/webob/en/stable/api/request.html#webob.request.BaseRequest.accept_language] handle a given string.

One seemingly decent option is just to collapse them in VCL by setting the Accept-Language on the request to whatever `accept.language_lookup` (VCL) chooses.

**Comment by ewdurbin** [comment]
OK, fix in https://github.com/pypi/infra/pull/110 is live and a purge has been completed for `all-html`.

I think this should resolve the issue, please comment if more instances are detected.

**Comment by glyph** [comment]
Thanks for the rapid response. I can confirm that I'm seeing PyPI's UI entirely in english now, as expected.
