### ISSUE TITLE
[FIDO 2][doc] Mention the cheap Yubikeys promotion available through CloudFlare

### ISSUE THREAD

**Issue by webknjaz** [pypi/warehouse#12454]
The following places suggest people to buy hardware tokens:
- https://github.com/pypi/warehouse/blob/e9e5c8d422dc157e3c817b8637cbef0d75def862/warehouse/templates/pages/security-key-giveaway.html#L110-L117
- https://github.com/pypi/warehouse/blob/bfb17e4158d2223e67f694d1618c6dd3b2191976/warehouse/templates/pages/help.html#L398-L400

They link to normal key purchase pages.

I suggest linking to https://blog.cloudflare.com/making-phishing-defense-seamless-cloudflare-yubico/#how-to-get-started — CloudFlare users can get promotional codes for getting FIDO 2 ready Yubikeys for $10-11 (up to 10 pcs). The deal is valid through the end of the year.
I think this could help the critical infrastructure project maintainers cover their hardware key needs with reduced financial load.

P.S. I'm not affiliated with CloudFlare, just thought it could be useful to someone. I've ordered these promotional keys myself, but haven't received them yet.

**Comment by di** [comment]
Happy to merge a PR that fixes this.

**Comment by Secrus** [comment]
The promotion has ended, the issue can be closed.
