### ISSUE TITLE
unsble to install ipkernel in with python 3.11 

### ISSUE THREAD

**Issue by Defcon404** [pypi/warehouse#12456]
**Describe the bug**
I tried installing ipkernel for use with vs code but I get an error. I guess the current version of ipkernel
doesnot support python 3.11. Please fix this.

**Expected behavior**
Want ipkernel to support the latest version of python 3.11

**To Reproduce**
tried ti install ipkernel to be used for Jupiter in vscode but unable to install inkernel because it does not support 
the latest version of python 3.11.0

**My Platform**
    Lenovo legion with updated drivers,net-frameworks, ide's, and packages. OS version Windows 11 22h2.

**Additional context**

**Comment by Defcon404** [comment]
Please provide ipkernel support for python 3.11.0.
Thank you

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
