### ISSUE TITLE
Recent upgrade of docutils seems to have broken formatting of RestructuredText descriptions

### ISSUE THREAD

**Issue by schlatterbeck** [pypi/warehouse#12459]
**Describe the bug**
Included graphics now have an un-rendered `<figure class="align-center">` start tag and end tag `</figure>`
For an example see https://pypi.org/project/plot-antenna/1.0/
This worked previously for the same ReST.

When including citation references, the citation at the end now has a newline after the citation mark and no hanging indent is used. An example is also under the link above.

Note for my Nikola Blog (also ReST based) I had to include the following CSS for correctly formatting citations:
```
aside.footnote p {
    display: inline;
}

aside.footnote {
    padding-left: 2em;
    text-indent: -2em;
}
```

**Expected behavior**
Github displays the same ReST fine: https://github.com/schlatterbeck/plot-antenna

**To Reproduce**
See https://pypi.org/project/plot-antenna/1.0/
source of is the README for https://github.com/schlatterbeck/plot-antenna

**My Platform**
Firefox browser on Debian Bullseye

**Comment by miketheman** [comment]
This might be an issue with readme_temderer instead, as that project needs to expose the 'figure' class.

**Comment by schlatterbeck** [comment]
You mean readme-renderer?
What I reported are actually two bugs, one with the figure embedding and one with the citations. The latter seems to affect different programs internally using docutils (including my nikola blog). So maybe readme-renderer uses docutils internally?

As for the first bug: I really don't know how the figure-embedding is done.
Ralf

**Comment by di** [comment]
Yes, `readme_renderer` uses `docutils` internally for rST rendering.

I'm going to close this in favor of re-opening it at https://github.com/pypa/readme_renderer to determine if this is something that needs fixed in `readme_renderer` or in `docutils` instead -- there's nothing for PyPI to do here.

**Comment by schlatterbeck** [comment]
I've opened https://github.com/pypa/readme_renderer/issues/264
