### ISSUE TITLE
Carrier data not loading

### ISSUE THREAD

**Issue by masterseo2000** [pypi/warehouse#12457]
Hello all,
I have installed phonenumber (not phonenumberlite) while looking up  a particular phone number I’m getting almost everything but the carrier and that is precisely the carrier that I’m looking for.   (FYI I am not the programmer) I was wondering if The Programmer is missing a step like downloading the data set for a particular country or carrier.
Also since we’re talking about carrier data how accurate is that data given the huge number of porting requests (people that change the number from one Carrier to the other on a daily basis)
Thanks for your help! If I can make this work for us that would be wonderful ❤️

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.

**Comment by masterseo2000** [comment]
This is a code issue… the resulting response does not match the readme file (speaking about the carrier info) please only close the ticket once you have answered or guided to a solution…

**Comment by di** [comment]
This is the issue tracker for the website pypi.org. We aren't able to help with individual projects that are hosted on PyPI, those are uploaded by other individuals, and we have no knowledge of them.
