### ISSUE TITLE
reStructuredText markup broken for Robot Framework code blocks

### ISSUE THREAD

**Issue by mentalisttraceur** [pypi/warehouse#12484]
**Describe the bug**
Project description written in reStructuredText; `.. code:: robotframework` blocks rendered with strikethrough on all the keyword arguments.

![image](https://user-images.githubusercontent.com/6531708/200101948-c0ec74d1-f25a-47a5-89c7-f4c1f097e0b7.png)

Example image from [`robotframework-dependencylibrary`](https://pypi.org/project/robotframework-dependencylibrary/).

**Expected behavior**
No strikethrough in code blocks.

**To Reproduce**
Make a package with a reStructuredText description containing `.. code:: robotframework` blocks with at least one test calling at least one keyword with at least one argument, I presume.

**Comment by mentalisttraceur** [comment]
Note that it previously rendered correctly for years.

I've had that package with a lot of the same project description reStructuredText since December 2017, last looked at it around October 2021, and I think I would've noticed strikethrough in my code blocks.

**Comment by mentalisttraceur** [comment]
The change to the generated HTML happened sometime between [January 28 2022](http://web.archive.org/web/20220128014519/https://pypi.org/project/robotframework-dependencylibrary/) and [October 31 2022](http://web.archive.org/web/20221031123817/https://pypi.org/project/robotframework-dependencylibrary/).

**Comment by mentalisttraceur** [comment]
Looks like the HTML change was specifically `<span class='s'>...</span>` being replaced with `<s>...</s>`.

**Comment by miketheman** [comment]
Thanks for the detailed report! I believe this is due to how the conversion from HTML4 to HTML5 elements worked along with the Pygments library setting for using short codes where 's' is used for a string, and it can also mean strike through.

Fixing this means a change to readme_renderer and the CSS here in warehouse to adapt.
