### ISSUE TITLE
Can't access pypi server or update package from Sudan

### ISSUE THREAD

**Issue by moe-a-m** [pypi/warehouse#12486]
##

**Describe the bug**

I wanted to install flask to deploy an app but I could not get packages as it says
```
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/0f/43/15f4f9ab225b0b25352412e8daa3d0e3d135fcf5e127070c74c3632c8b4c/Flask-2.2.2-py3-none-any.whl (Caused by ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))
```
After trying to update pip as it might be the source of the issue, I found it blocking access to the [pythonhosted packges](https://files.pythonhosted.org). the response I get this response:

![2022-11-06 03 32 55 files pythonhosted org a2c62f6aa36b](https://user-images.githubusercontent.com/1516025/200150637-7b6a2b71-24a2-4c11-a726-d9df99dcf8a3.png)

I was able to solve this issue by using VPN to change the IP to another country. But it was working until last week. 

I am familiar with this issue similar situation as I get the response years ago from other vendors as Sudan was sanctioned by the US. However, the US have left it a long time ago. Can you please update the CDN host to unfilter the Sudan IPs and enable access again?

**Expected behaviour**

```
Installing collected packages: Werkzeug, itsdangerous, click, Flask
Successfully installed Flask-2.2.2 Werkzeug-2.2.2 click-8.1.3 itsdangerous-2.1.2
```
**To Reproduce**

1. Change the IP to [Sudan range](https://lite.ip2location.com/sudan-ip-address-ranges?lang=en_US)
2.  ``` pip install flask```

**My Platform**

My OS: Windows 10 
Python version: 3.10.5
**Additional context**

#

**Comment by di** [comment]
Hi @moe-a-m, sorry you're having trouble. Could you file a [network access issue](https://github.com/pypa/pypi-support/issues/new?assignees=&labels=network&template=access-issues.yml) instead, which will give us a bit more information about what's going wrong here? Thanks!

**Comment by moe-a-m** [comment]
Thank you @di, I have opened another [ticket](https://github.com/pypa/pypi-support/issues/2364). Hopefully, it will be resolved soon.
