### ISSUE TITLE
Can't accept PyPi Project invite

### ISSUE THREAD

**Issue by erikwrede** [pypi/warehouse#12487]
I can't accept an invite to a project I got on PyPi. The project invite link fails with "no token provided" and if I try to accept the invite from the "my projects page" using the accept button, I get an internal server error page: 

![image](https://user-images.githubusercontent.com/9725143/200161650-f7bfd649-268d-488c-b907-d55c91a777e7.png)

Happens on all major web browsers

PyPi username: erikwrede

**Comment by di** [comment]
@erikwrede, is there any chance you're using PyPI in a language/locale other than English?

**Comment by erikwrede** [comment]
Yup, German

**Comment by erikwrede** [comment]
I can confirm that changing my browser language settings to english fixed the issue. I did not specifcally setup any language in the PyPi settings though.

**Comment by di** [comment]
We recently added support for autodetecting the locale based on browser settings (https://github.com/pypi/warehouse/issues/6864) so that's why.

**Comment by di** [comment]
(Sorry, the following comment didn't get posted:)

Thanks. This is due to a broken translation string in our German translation. In the short term, this should work if you switch your locale to English (or any other language but German I think). Long term fix for this is to fall back to English for broken translations strings.

**Comment by erikwrede** [comment]
Thanks for the help! Feel free to close this if this issue is already tracked in another context! 🙂

**Comment by di** [comment]
Closing this in favor of https://github.com/pypi/warehouse/issues/12552, but thanks for the report!
