### ISSUE TITLE
[UI?][i18n] Enable horizontal scroll for code blocks on PyPI

### ISSUE THREAD

**Issue by webknjaz** [pypi/warehouse#12529]
**Describe the bug**

I noticed that the monotype text in a `.pypirc` example overflows the right border.
I suppose it's because the translation string is longer than the original English one.
The problem of text not fitting in the UI is common 

**Expected behavior**

I think that a horizontal scroll bar appearing in such code blocks would handle this case very well. The translators aren't immediately exposed to where and how the translation strings will be rendered. So it is unlikely for this to be fixed during the translation-time, only post-merge/build/deploy.

**To Reproduce**

It's on https://pypi.org/manage/account/token/.

**My Platform**

N/A

**Additional context**

![i18n-code-block-needs-scroll](https://user-images.githubusercontent.com/578543/200952314-45c688a9-4a58-4b6f-a722-e3b062065b78.png)

**Comment by miketheman** [comment]
The problem manifests in English as well:

<img width="838" alt="Screen Shot 2022-11-11 at 9 09 41 AM" src="https://user-images.githubusercontent.com/529516/201357262-32874fcf-1f63-4483-ba95-34ffbdefae0e.png">

The content is located in this template:

https://github.com/pypi/warehouse/blob/1387d3a1212cb56feb114611cf44739f63707eb2/warehouse/templates/manage/account/token.html#L98-L111

The width of the overall content column is set in SCSS:

https://github.com/pypi/warehouse/blob/1387d3a1212cb56feb114611cf44739f63707eb2/warehouse/static/sass/layout-helpers/_containers.scss#L28-L29
https://github.com/pypi/warehouse/blob/1387d3a1212cb56feb114611cf44739f63707eb2/warehouse/static/sass/settings/_grid.scss#L17

I don't think it's likely to change the global width setting to accommodate this. Rather, it's more likely to explore adding the horizontal scroll to the specific code block SCSS https://github.com/pypi/warehouse/blob/1387d3a1212cb56feb114611cf44739f63707eb2/warehouse/static/sass/blocks/_code-block.scss
