### ISSUE TITLE
pyqt6-tools installation failure

### ISSUE THREAD

**Issue by NiuJun-1015** [pypi/warehouse#12535]
**Describe the bug**
After installed PyQt6/PyQt6-Qt6 6.4.0, I am installing PyQt6-tools to use Qt Designer tool, but is failed: 
![image](https://user-images.githubusercontent.com/105597116/201503186-3d17c542-e87b-4932-b691-ef386034be82.png)

**Expected behavior**
I wish the tools installation successfully

**To Reproduce**
Python3.11, manually install in win powershell terminal
![OS config](https://user-images.githubusercontent.com/105597116/201503383-327bfce4-0ed0-4a3a-a4ef-ab2434e80a00.png)
![PS capture](https://user-images.githubusercontent.com/105597116/201503385-28437150-41bb-4a7a-b826-e33da63cf368.png)

**My Platform**
<Window 11,  
![image](https://user-images.githubusercontent.com/105597116/201503286-15cf087e-8097-42ac-95c8-21209ba7ac59.png)

    Any details about your specific platform:
    * If the problem is in the browser, what browser, version, and OS?
    * If the problem is with a command-line tool, what version of that tool?
    * If the problem is with connecting to PyPI, include some details about
      your network, including SSL/TLS implementation in use, internet service
      provider, and if there are any firewalls or proxies in use.
-->

**Additional context**

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
