### ISSUE TITLE
Fallback on default translation when interpolation fails.

### ISSUE THREAD

**Issue by di** [pypi/warehouse#12552]
As noted in issues such as https://github.com/pypi/warehouse/issues/12487, sometimes our translation strings change in ways that break the existing string interpolation (or sometimes translations have typos) which cause some views to fail entirely.

Ideally, we should fall back on the original translation if using a given translation fails in any way, allowing requests for views with faulty translations to succeed with minimal breakage.

**Comment by ewdurbin** [comment]
ref: https://github.com/pallets/jinja/issues/421#issuecomment-127705489

**Comment by ewdurbin** [comment]
Here's a working implementation... though I'm really uneasy on if it is a good idea or not: https://github.com/pypi/warehouse/commit/7aad60be39a5483361c0321973e07962a7233167
