### ISSUE TITLE
Untrapped spam account can squat multiple names with identical nonsense code (possible supply chain attack)

### ISSUE THREAD

**Issue by wbeckler** [pypi/warehouse#12553]
**Describe the bug**
There is a spam account with 23 repos all with identical code under multiple squatted names: https://pypi.org/user/david-aws/

**Expected behavior**
If someone is spamming names, they should at least be unable to spam the same code to lots of names.

**To Reproduce**
Visit https://pypi.org/user/david-aws/

**My Platform**
This is an issue of a missing spam detection in the Pypi platform 

**Additional context**
There are various clever ways in which a well named repo can become a supply chain attack, and I don't want to install or run the tests on this weird looking codebase to find out for sure.

**Comment by wistuba** [comment]
25 by now. Would be great if the account can be removed and the project names be made available again.

**Comment by gianlucadetommaso** [comment]
Same problem here. Would be great if the names could be made available again.

**Comment by di** [comment]
Once removed, the names are able to be made available on a case-by-case basis as described here: https://pypi.org/help/#project-name-claim

**Comment by wistuba** [comment]
Thanks for the fast response, really appreciated!
