### ISSUE TITLE
Support pyproject metadata in JSON API

### ISSUE THREAD

**Issue by ofek** [pypi/warehouse#12585]
**What's the problem this feature will solve?**

- https://github.com/encode/httpx/discussions/2454
- https://github.com/squidfunk/mkdocs-material/pull/4392#issuecomment-1261352190

**Describe the solution you'd like**

- PEP 639 license string / License-Expression
- PEP 621 urls populate homepage/download or just remove them

**Comment by cadojo** [comment]
Do any PyPA APIs (i.e. `simple`) support pyproject metadata yet? I love this feature idea, and I hope it is implemented.

**Comment by di** [comment]
> PEP 639 license string / License-Expression

This [PEP](https://peps.python.org/pep-0639/) has not been finished yet. It will need to be accepted before PyPI can implement it.

> PEP 621 urls populate homepage/download or just remove them

These are currently available in the JSON response as `.['project_urls']['Homepage']`, etc. Is this request about adding them to the `.['home_page']` field? This was previously discussed in https://github.com/pypi/warehouse/issues/11220 and the consensus was that PEP 621 does not provide a way to fill this field, and build tools should not attempt to backfill it from other fields.

> Do any PyPA APIs (i.e. simple) support pyproject metadata yet? I know there is core metadata available, but it does not include things like dependencies. I love this feature idea, and I hope it is implemented.

The JSON API currently includes dependencies via the `requires_dist`/[`Requires-Dist`](https://packaging.python.org/en/latest/specifications/core-metadata/#requires-dist-multiple-use) field.

**Comment by dstufft** [comment]
I'm going to close this, PEP 639 is still a draft and PEP 621 doesn't provide a way to backfill the non project-url URLs, and PyPI already supports project-urls. 

Also as a rule, PyPI doesn't look at `pyproject.toml`, but at the various core metadata specs.
