### ISSUE TITLE
[UX] PyPI shouldn't make `setup.py`-based suggestions anymore

### ISSUE THREAD

**Issue by webknjaz** [pypi/warehouse#12598]
**What's the problem this feature will solve?**

I noticed that PyPI suggests editing `setup.py` on the project settings pages.

**Describe the solution you'd like**

I'm not sure, but it should probably point at PEP's and mention `pyproject.toml`? Or maybe change the wording?

**Additional context**

This also caused confusion @ https://github.com/pypi/warehouse/discussions/12190 but that was never turned into an actionable task.

Affected templates:
* https://github.com/pypi/warehouse/blob/ef9747c737019cd3f55d81d3a316fbaf7865643b/warehouse/templates/manage/project/settings.html#L105
* https://github.com/pypi/warehouse/blob/d58e6b241ce6fd2d65da469c32189b51a5572ff8/warehouse/templates/pages/help.html#L578

**Comment by woodruffw** [comment]
Once #16258 is merged there will be no other (non-cached translated) references to `setup.py` left:

```bash
rg setup.py warehouse/ -g '!locale/'
```
