### ISSUE TITLE
404 when using predictable (conveyor) URL

### ISSUE THREAD

**Issue by dopplershift** [pypi/warehouse#12620]
**Describe the bug**

Trying to download an sdist for traitlets 5.6.0 using the predictable url https://files.pythonhosted.org/packages/source/t/traitlets/traitlets-5.6.0.tar.gz produces a 404:

```sh
❯ curl -I https://files.pythonhosted.org/packages/source/t/traitlets/traitlets-5.6.0.tar.gz
HTTP/2 404 
content-type: application/octet-stream
server: nginx/1.13.9
accept-ranges: bytes
date: Tue, 29 Nov 2022 17:26:07 GMT
age: 0
x-served-by: cache-iad-kiad7000160-IAD, cache-den8256-DEN
x-cache: MISS, MISS
x-cache-hits: 0, 0
x-timer: S1669742767.083365,VS0,VE122
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-frame-options: deny
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-permitted-cross-domain-policies: none
x-robots-header: noindex
content-length: 0
```

This was seen on a conda-forge worker and I've reproduced locally. This works fine for the previous version (5.5.0). It also works fine if I use the (unpredictable) URL that's listed on pypi: https://files.pythonhosted.org/packages/ed/98/43976cc847e7f2a79770af0a92cbb3cbf0e568ba0b3daa88699b4c746ae9/traitlets-5.6.0.tar.gz

This package was uploaded about 5 hours ago. Other, more recently updated packages also seem fine.

**Comment by ewdurbin** [comment]
Confirmed, this is a symptom of #11949, closing as duplicate.

**Comment by ewdurbin** [comment]
wrong issue ref, sorry: #12214
