### ISSUE TITLE
PEP 541: Request to transfer ownership of pia

### ISSUE THREAD

**Issue by ssbarnea** [pypi/warehouse#12661]
I would like to request transfer of ownership for project `pia` to `ssbarnea` pypa user, as the project never released any code and has only one placeholder upload 7 years ago.

I already contacted the owner by creating a ticket on https://github.com/soasme/pia/issues/7 and I alse mentioned him, @soasme.

Thanks,
Sorin Sbarnea

**Comment by soasme** [comment]
@ssbarnea approved from the current owner. I'm happy the project name can be reactivated for good.

**Comment by ssbarnea** [comment]
Thanks!

**Comment by di** [comment]
This should be an issue at https://github.com/pypa/pypi-support, not here.

**Comment by ssbarnea** [comment]
@di hi! Organization members can easily use the transfer button to move tickets. I'm not yet, but I hope I will become, likely when we decide to move pip-tools under pypa.

The reality is that the real place to raise tickets is very well hidden:
- Lets look at https://pypi.org/ and try to find the link to support/contact/report.
- After you find https://pypi.org/help/#feedback and you read the paragraphs, surprise you are sent towards https://github.com/pypi/warehouse/issues and not  https://github.com/pypa/pypi-support

If the right information would be make available, we would not mistake. As I did not remember well which one was the right tracker, I even searched for existing tickets as I knew that I had the same kind of activity in the past. Surprise, I found several! I guess nobody bothered to move them.

@soasme Don't forget to login to https://pypi.org/ and add me as owner to the project, I cannot do anything until you invite me.

**Comment by di** [comment]
> @di hi! Organization members can easily use the transfer button to move tickets. I'm not yet, but I hope I will become, likely when we decide to move pip-tools under pypa.

This repository is not in the `pypa` org, so I can't transfer this issue previous issues there.

https://pypi.org/help/#feedback says:

> If you're experiencing an issue with PyPI itself, we welcome constructive feedback and bug reports via our [issue tracker](https://github.com/pypi/warehouse/issues). Please note that this tracker is only for issues with the software that runs PyPI.

I think that's fairly clear that this issue tracker is not for the projects hosted on PyPI, but I'd welcome anything that would make this more clear.

Instead, https://pypi.org/help/#project-name-claim links to https://peps.python.org/pep-0541/#how-to-request-a-name-transfer which links to https://github.com/pypa/pypi-support/issues/new?labels=PEP+541&template=pep541-request.yml&title=PEP+541+Request%3A+PROJECT_NAME

Please open an issue there instead -- that will allow our team volunteer moderators to triage and respond to this request appropriately.
