### ISSUE TITLE
GitHub statistics (for 1 package) are using the wrong base URI / lead to 404s

### ISSUE THREAD

**Issue by Julian** [pypi/warehouse#12725]
**Describe the bug**
The sidebar of https://pypi.org/project/jsonschema-specifications/ has links for GitHub statistics, but they lead to 404s.

The Stars link is currently trying to send someone to https://pypi.org/project/jsonschema-specifications/undefined/stargazers, and the Forks and Open Issues links are similarly somehow thinking that those links should redirect to somewhere under https://pypi.org/project/jsonschema-specifications/undefined.

All numbers are similarly not rendering (so the actual counts don't appear either).

**Expected behavior**
Similar counts and links as those which appear on other pages.

**To Reproduce**
https://pypi.org/project/jsonschema-specifications/ is the page I noticed this on.

Looking at another package I recently created (https://pypi.org/project/referencing/) shows that one seems fine, as do random other packages I've just browsed to check.

Not sure if the above is transient behavior that I've just never noticed, but filing since I don't see any existing issues mentioning it (unless I missed em).

**My Platform**

Firefox 109.0b2 (64-bit) on macOS Ventura 13.1

**Additional context**

Clearly this isn't hugely impactful, at least to me, filing mostly to track and in case it's wider spread and I just can't tell. Thank you all for everything!

<img width="386" alt="Screenshot 2022-12-27 at 19 51 11" src="https://user-images.githubusercontent.com/329822/209740980-ebb1e261-e733-4839-999b-ab05670af196.png">

**Comment by di** [comment]
Looks like we're interpreting the URL `https://github.com/sponsors/Julian` as the repository URL, and that's causing the requests to the GitHub API to fail.

Two things I think we should do here:

a) fail more gracefully when the GitHub API gives us a 404
b) specifically exclude `/sponsors` (and maybe other things?) from this somewhat naive function: https://github.com/pypi/warehouse/blob/b06c866306d639c895e74d79b200dcefd9d435f4/warehouse/packaging/models.py#L587-L594

**Comment by jayaddison** [comment]
This seems to affect more than GitHub-sponsor-path-URLs - the [`arcana-core`](https://pypi.org/project/arcana-core/) package similarly displays empty statistical information:

![image](https://user-images.githubusercontent.com/55152140/210579958-b58e7f73-0e9f-4cac-9575-3a1e8da7bc69.png)

...and similarly links to `https://pypi.org/project/arcana-core/undefined/issues` instead of `https://github.com/ArcanaFramework/arcana/issues`.

The `arcana-core` [URL list as configured in `pyproject.toml` looks fine](https://github.com/ArcanaFramework/arcana-core/blob/238aa5abc46d613b0c5f12fcade354ee0db9feba/pyproject.toml#L63-L66) (the single GitHub URL in there is `https://github.com/ArcanaFramework/arcana.git`, which seems like it should return a result from `github_repo_info_url`, based on some manual testing in a Python interpreter session).

**Comment by di** [comment]
I agree, that's the "fail more gracefully when the GitHub API gives us a 404" part of this.

However, it looks like a 3rd thing is that we could additionally be stripping `.git` suffixes from these URLs if present -- it doesn't seem like GitHub will let you create a repository called "foo.git", so this shouldn't be ambiguous.

> https://github.com/Mottie/github-reserved-names/blob/master/reserved-names.json

This appears to be a pretty decent list and up-to-date-ish (last updated 1 month ago?) but it might be challenging for us to consume this as an npm module.

**Comment by jayaddison** [comment]
Ok, yep, thanks both - that makes sense :+1: 

Unless I hear otherwise, I'll open a separate issue for the `.git` suffix removal within `github_repo_info_url` (initially that seems straightforward and isolated from the reserved-namespaces question and API-response-handling changes).

**Comment by di** [comment]
Sounds good to me. @Julian, I think this one could also be split in two if you're up for it.

**Comment by Julian** [comment]
Yeah I can send a PR.

> This appears to be a pretty decent list and up-to-date-ish (last updated 1 month ago?)

Sorry, I was looking at the release page I think which showed 2020. You're right definitely.

> might be challenging for us to consume this as an npm module

I copied it over trivially [here](https://pypi.org/project/github-reserved-names/). Do you want to use that? (Obviously if not it seemed nice to give us access to anyhow even if we just do simpler things here, so no wasted work).

**Comment by Julian** [comment]
> Looks like https://github.com/Julian/github-reserved-names might be private though?

Hah, I hadn't pushed precisely because I was trying to figure out a good way to do...

> suggesting a workflow for updating this automatically, I maintain something similar here

exactly this :D so yes, definitely suggestion welcome, I'll have a look at what you have there.
