### ISSUE TITLE
Request to be removed as maintainer

### ISSUE THREAD

**Issue by jaraco** [pypi/warehouse#12743]
Since self-disenrollment isn't currently implemented, I'm requesting to have my account administratively removed from the following packages:

- khartoum
- celery-schedulers
- upsidedown
- thumpy

That's all, thanks.

**Comment by miketheman** [comment]
This should be an issue at [pypa/pypi-support](https://github.com/pypa/pypi-support), not here.

**Comment by jaraco** [comment]
My mistake. Thanks.
