### ISSUE TITLE
panda-stubs source files not getting updated with known URL

### ISSUE THREAD

**Issue by Dr-Irv** [pypi/warehouse#12776]
I'm the maintainer of pandas-stubs, and we're having an issue with the source URL's not existing for new releases:

**Describe the bug**
The following URL works:  https://files.pythonhosted.org/packages/source/p/pandas-stubs/pandas-stubs-1.5.2.221124.tar.gz
These 2 URL's don't work:
-  https://files.pythonhosted.org/packages/source/p/pandas-stubs/pandas-stubs-1.5.2.221213.tar.gz
-  https://files.pythonhosted.org/packages/source/p/pandas-stubs/pandas-stubs-1.5.2.230105.tar.gz

If you look at:  https://pypi.org/project/pandas-stubs/#history
you will see there are releases 1.5.2.221213 and 1.5.2.230105

- https://pypi.org/project/pandas-stubs/1.5.2.221213/#files
- https://pypi.org/project/pandas-stubs/1.5.2.230105/#files

For our conda-feedstock recipes to work, we need the standard URL's.  Why did the last 2 releases not get put in the usual place?

**Expected behavior**
for each release,  https://files.pythonhosted.org/packages/source/p/pandas-stubs/pandas-stubs-VERSION.tar.gz should exist

**To Reproduce**
See above

**My Platform**
N/A

**Additional context**

See https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=637557&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d at line 151 where it couldn't find the source.

**Comment by ewdurbin** [comment]
It looks like the filename format changed after the 22124 release. Note the underscore versus dash in the sdist filename.

The URL translation service does not handle/transform filenames themselves.

So in this case, https://files.pythonhosted.org/packages/source/p/pandas-stubs/pandas_stubs-1.5.2.221213.tar.gz and https://files.pythonhosted.org/packages/source/p/pandas-stubs/pandas_stubs-1.5.2.230105.tar.gz would work.

**Comment by ewdurbin** [comment]
In this instance, the URL transform service is acting as expected.

For more reliable file discovery when the filename formatting changes the [JSON document for a given release](https://warehouse.pypa.io/api-reference/json.html#release) is available.

**Comment by Dr-Irv** [comment]
@ewdurbin Thanks much for finding that.  We use `poetry build` and apparently it changed the convention for how it named source files starting with poetry 1.2.1
