### ISSUE TITLE
Two dependencies in notdatadog.py are deprecated

### ISSUE THREAD

**Issue by ristomcgehee** [pypi/warehouse#12779]
**Describe the bug**
The `asyncore` and `smtpd` modules in [notdatadog.py](https://github.com/pypi/warehouse/blob/04ee9be504caa89345617b2795ff53fc22631297/dev/notdatadog.py) are deprecated and will be removed in Python 3.12.

**Expected behavior**
When running Warehouse locally, the notdatadog container does not create a bunch of deprecation logs.

**To Reproduce**

Run Warehouse locally using docker-compose. View the logs from the `notdatadog` container. You'll see something like this:
```
/opt/warehouse/dev/notdatadog.py:13: DeprecationWarning: The asyncore module is deprecated and will be removed in Python 3.12. The recommended replacement is asyncio
  import asyncore
/opt/warehouse/dev/notdatadog.py:16: DeprecationWarning: The smtpd module is deprecated and unmaintained and will be removed in Python 3.12.  Please see aiosmtpd (https://aiosmtpd.readthedocs.io/) for the recommended replacement.
  import smtpd
```

**My Platform**

I'm running Warehouse in Ubuntu 20.04 using docker-compose version 2.14.2.

**Additional context**

Assuming we want to keep maintaining the `notdatadog` service, I can do the upgrades for this. I would replace `asyncore` with `asyncio`. The only thing `smtpd` is used for is to parse the single command line argument, so I'd probably just use `sys.argv` instead. Even `argparse` seems a bit overkill for this use.

**Comment by miketheman** [comment]
Thanks @ristomcgehee ! I can confirm these are observed. I'd be happy to review a patch!
