### ISSUE TITLE
Project detail statistics: support multiple statistics providers

### ISSUE THREAD

**Issue by jayaddison** [pypi/warehouse#12789]
**What's the problem this feature will solve?**
The project detail page displays release-related statistics which can be useful for consumers who would like to gauge project popularity and community size.

Currently, GitHub is the sole supported statistics provider, but there are a number of other source code forges that host FOSS projects and provide statistical information about them.

![image](https://user-images.githubusercontent.com/55152140/211384658-375d13dd-b2c6-4212-9991-74bc55d80520.png)

**Describe the solution you'd like**
Extend the [stats URL detection logic](https://github.com/pypi/warehouse/blob/8b29ea360aa80d521575949772282ec5e7e75fdf/warehouse/packaging/models.py#L589) to support multiple source control forges.

**Additional context**
Different forges are likely to use different naming terminology for their statistics; PyPi could choose to decide upon a standard naming format, and may omit statistical fields from display if they are not relevant or available from a provider.

Each additional provider would likely require an associated [`connect-src` entry](https://github.com/pypi/warehouse/blob/8b29ea360aa80d521575949772282ec5e7e75fdf/warehouse/csp.py#L86) for the frontend application's content security policy.

This repository's test data file (`dev/example.sql.xz`) could provide a way to help figure out potential providers to support.

Relates to #4384.

**Comment by jayaddison** [comment]
Also worth considering: it's not a great idea to make too many assumptions about the bandwidth and resource capacity of statistics providers.

Although most of the major providers are likely well-resourced, PyPI itself may receive significant inbound traffic, and since subsequent outbound requests are made from the frontend application -- by geographically disparate users -- it could be challenging for providers to filter that traffic.

**Comment by di** [comment]
Fixed in #15931.

**Comment by jayaddison** [comment]
Nice!  Thank you, @nE0sIghT!
