### ISSUE TITLE
New account registration seems to be broken. "Invalid username" error, but it's only Latin letters 

### ISSUE THREAD

**Issue by snowyurik** [pypi/warehouse#12844]
**Describe the bug**
I'm trying to register on pypi.org, https://pypi.org/account/register/
I've tried a few usernames including "snowyurik", but they all failed with error:
"The username is invalid. Usernames must be composed of letters, numbers, dots, hyphens and underscores. And must also start and finish with a letter or number. Choose a different username."
I can interpret this error message only like "there is forbidden symbol in the username", but it's just Latin letters. 

**Expected behavior**
Successful registration, or maybe "username is taken" message if it's taken.

**To Reproduce**
go to https://pypi.org/account/register/
type name/email/password
hit "Create account"

**My Platform**
Linux, Brave browser [Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)](https://brave.com/latest/)
Adblocker disabled

**Additional context**

**Comment by di** [comment]
Can you share a screenshot of the error?

**Comment by snowyurik** [comment]
![Screenshot_20230117_123925](https://user-images.githubusercontent.com/2470204/212818771-0fb24513-bc33-48b8-af2b-4a0e1cdcc247.png)

**Comment by snowyurik** [comment]
Same behavior in Firefox 107.0 (64-bit)

**Comment by di** [comment]
You have your email address in the "username" field.
