### ISSUE TITLE
Not receiving verification emails from Test PyPI

### ISSUE THREAD

**Issue by samahka** [pypi/warehouse#12910]
I'm attempting to register on Test PyPi , but I'm not receiving the verification e-mails. I've tried different e-mail addresses, but still no luck.

**Comment by di** [comment]
Can you provide any of the emails you've tried?

**Comment by EssamWisam** [comment]
I have the same problem with the following details:

username: essamwisam

primary email: essamwisam@outlook.com
secondary email: essam.wsam@gmail.com

Note that when I signed up on PyPI I received the verification email immediately, this is a problem with test PyPI.

**Comment by di** [comment]
Thanks. I can confirm that I see no email activity for those addresses. We'll look into it.

**Comment by di** [comment]
Looks like our job queue is backed up due to a different task repeatedly failing, causing emails to be delayed. We disabled it and increased the # of workers, this should resolve shortly.

**Comment by EssamWisam** [comment]
Received it indeed, thanks a lot.

**Comment by di** [comment]
This should be resolved now.
