### ISSUE TITLE
Unpin constraint on `packaging`

### ISSUE THREAD

**Issue by di** [pypi/warehouse#12920]
This was constrained in https://github.com/pypi/warehouse/pull/12664/ due to https://github.com/googleapis/python-bigquery/issues/1435 which is now resolved:

https://github.com/pypi/warehouse/blob/186180c600da5a99a7bdc0da548f852351d91e84/requirements/deploy.in#L4

We attempted to unconstrain it in https://github.com/pypi/warehouse/pull/12871, however due to https://github.com/pypa/packaging/pull/407, we can't migrate to the latest version until https://github.com/pypa/packaging/pull/669 is resolved.

**Comment by di** [comment]
This now needs a release of `packaging` which includes https://github.com/pypa/packaging/pull/669, a release of https://github.com/di/packaging_legacy, and an update here to use that dependency.

**Comment by donatocayurin** [comment]
Thank you ❤️🙏
