### ISSUE TITLE
Create a ROI of same properties?

### ISSUE THREAD

**Issue by AlgorithmesAndCo** [pypi/warehouse#12935]
Hello,

I'm not sure this is the best place, but it's a place at least...

We're using SILX with our software, and displaying a picture on which you can select rectangular ROIs.
One of our customers wants to create several ROIs of the same size, but I couldn't find an easy way to do it.

I've had several ideas, the best would be copy/paste (ctrl+c / ctrl+v) as everybody knows how to do it, but I couldn't find an example showing that kind of functionality.

I also tought about adding a couple of buttons "copy rectangle size" and "paste rectangle size" in the ROI area, but the code looks like it is SILX and it doesn't look like something open to adding new buttons. So I'm stuck at the moment on that functionality.

Can you help me find the best way to do that? (btw I speak french and english)

Thanks in advance, 

Ludo

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
