### ISSUE TITLE
TestPyPi download fails to resolve dependencies -- works with PyPi & local wheel

### ISSUE THREAD

**Issue by ethanmsl** [pypi/warehouse#12955]
[This repo fails to download the latest version test.pypi bldr-test](https://test.pypi.org/project/bldr-test/).
It will download an earlier version (with different dependencies) (e.g. 0.3.3)but complains that `typer[all]` can't be resolved if forced to download a later version (e.g. 0.4.2)
<img width="776" alt="Error on --force" src="https://user-images.githubusercontent.com/33399972/217450549-4de41e5f-b06c-4fc3-bcab-eea04fe84a93.png">

However,
## **1**) Installation with a local wheel works.
<img width="785" alt="local wheel works" src="https://user-images.githubusercontent.com/33399972/217450818-76d9c71b-4207-4ecf-b455-607a3839c256.png">

## **2**) Installation from TestPyPi works **_if_** I download the Typer[all] dependencies first.
<img width="772" alt="works if dependencies already exist" src="https://user-images.githubusercontent.com/33399972/217450838-1717eb54-cc59-4431-935d-9ec4ef991807.png">

## **3**) Installation of Typer[all] dependencies works.
<img width="775" alt="typer all  install works" src="https://user-images.githubusercontent.com/33399972/217450861-953f767f-eff3-49ad-aecd-7441a271dc33.png">

## **4**) Placing the same package on regular PyPi and downloading from there (using defaults) works.
<img width="773" alt="works fine with PyPi" src="https://user-images.githubusercontent.com/33399972/217450879-4388d44a-6e64-42d2-8eef-327c89c92bd5.png">

## **5**) Downloading from PyPi, but using the index-url flag (`pip3 install -i https://pypi.org/simple/ bldr-test`) _also_ works.
<img width="780" alt="index-url flag and PyPi works" src="https://user-images.githubusercontent.com/33399972/217451362-f6f75d76-4fe4-4c77-82d2-f9d6f432446c.png">

I'm not certain how TestPyPi would interface with this problem.  Whether it interacts with dependency resolution directly somehow (that would surprise me) or it impacts the wheel somehow.  (or there's another issue relating to the history of uploads that's the culprit).
But at this juncture this seems plausibly TestPyPi related...

TestPyPi package: https://test.pypi.org/project/bldr-test/
PyPi package: https://pypi.org/project/bldr-test/      

pip3 version: **22.3.1**
python3 version: **3.10.9**
python3 location: **/opt/homebrew/bin/python3**
<img width="586" alt="pip3 and python3 versions" src="https://user-images.githubusercontent.com/33399972/217451573-c7ef8265-ad95-4dc8-b379-7b8631d30b5e.png">
<img width="214" alt="which python3" src="https://user-images.githubusercontent.com/33399972/217452492-ae6ffc41-e37a-48b2-a5c3-fdece65dae93.png">

computer: **M1 mac**
os: **ventura 13.2**

**Comment by di** [comment]
You're mixing TestPyPI and PyPI: they're entirely separate indexes. TestPyPI only contains a 0.0.1 version of `typer`: https://test.pypi.org/project/typer/#history, so trying to install `bldr-test` from there when it has a `>=0.7.0` requirement on `typer` will fail.

You either only install from one index, or install some sub-dependencies from PyPI first, and then the package you want from TestPyPI.

**Comment by ethanmsl** [comment]
Oh.
So you're saying that if I download from an Index then _all dependencies must _also_ come from that index.
I hadn't checked, but I assumed that all dependencies would default to PyPi unless specified somehow.

Thanks for explaining.
I'll look into whether there's a way to specify dependency source separate from the index I'm directly downloading something from.
