### ISSUE TITLE
Find JavaScript Developer(s)

### ISSUE THREAD

**Issue by nlhkabu** [pypi/warehouse#1297]
# JavaScript volunteers who want to shape the next PyPI

[Warehouse](https://pypi.io/) is an open-source project that will replace the current [Python Packaging Index](https://pypi.python.org/pypi) - it is due for release in 2016.

Please note: We do not currently have any funding for this work, although we are working on setting up funding streams for the project, so there may be some budget available for large features in the future.

All we can offer is the feel-good satisfaction of helping every Python developer, as well as being able to say "I helped build that".

In order to get our JS into shape, we're searching for help with the following tasks:
- Improving the current (fairly small) JS codebase, fixing bugs and porting it to ES6 - so that it is ready for launch
- Defining/choosing a JS style guide, documenting it and enforcing it via linting
- Adding frontend tests
- Improving the frontend build process (as/if required)
- Adding new JS where neccessary

In the long term, we are hoping to add data visualisation to the platform, so there will be an opportunity to get stuck into some fancy JS graphing too!

Ideally we'd love someone to step up and take the lead on this project, but if you've got some free time, and a little bit of determination, we'd appreciate the help.

If the idea of one or two things above sounds fun, (or maybe even perhaps all of them!) please contact Donald (donald@python.org) - we'd love to work with you!

**Comment by brainwane** [comment]
@nlhkabu Thanks for writing this up originally. Are the TODOs you mention still mostly needed?

@waseem18, @yeraydiazdiaz, @aalmazan, @jw, @Volcyy, and probably others I've missed: thanks for your recent work on Warehouse's frontend! Here's a heads-up in case you hadn't seen this request for help earlier.

**Comment by nlhkabu** [comment]
Not sure @brainwane :) ping @di for feedback.

**Comment by di** [comment]
I think we've addressed most of this, and we've got a great crop of new contributors writing JS, so this could probably be closed!

Some things that are still outstanding:
* Frontend tests (e.g. #2154 should probably become "Add frontend tests", especially for Stimulus controllers)
* I should probably add some information to our docs about our use of Stimulus on the frontend, graceful JS degradation, etc.

**Comment by miketheman** [comment]
We’ve got ten better at JS. I wouldn’t call myself a JavaScript Developer, but I do okay.
