### ISSUE TITLE
Split 'Open issues/PRs' to display the values separately 

### ISSUE THREAD

**Issue by HallvardMM** [pypi/warehouse#12971]
**What's the problem this feature will solve?**
Change the GitHub statistics from:
 `Open issues/PRs: number`

Display it like this:
```
Open issues: number 
Open PRs: number
```

 Example:
![image](https://user-images.githubusercontent.com/49036938/217904590-1aadbb2c-dfe8-4402-888a-a0de4c953732.png)

It would help give a clearer understanding to users of how many issues and PRs are open for a package.
One example of why I argue today's display is somewhat problematic:
The [Django](https://pypi.org/project/Django/) package looks like it has 149 issues/PRs 

![image](https://user-images.githubusercontent.com/49036938/217906574-600e9172-da68-439e-b7ed-340e0785a9ce.png)

The [Pandas](https://pypi.org/project/pandas/) package looks like it has 3681 issues/PRs 

![image](https://user-images.githubusercontent.com/49036938/217906499-3dde7a9d-c613-4d91-8611-4c0363f13b75.png)

The difference makes Django seem way better maintained, however, the difference is linked to Django not displaying issues on GitHub. The total number of open PRs is about the same for the two projects.

**Additional context**
Would it be possible to use this solution?
https://github.com/isaacs/github/issues/536#issuecomment-532884919 

Use `https://api.github.com/repos/OWNER/REPO` to get open PRs and open Issues count from `"open_issues": number,` and
`https://api.github.com/search/issues?q=repo:OWNER/REPO+type:issue+state:open&per_page=1`
to get the open issues count from `"total_count": number,` and then subtract `open_issues`-`total_count` to get open PRs?

This is linked to #3697 and #3673

**Comment by miketheman** [comment]
The current code for fetching and displaying the issues can be found here:

https://github.com/pypi/warehouse/blob/8d8cc16f0e0770156fb4c3648da64f2a7d5bc21f/warehouse/static/js/warehouse/controllers/github_repo_stats_controller.js
https://github.com/pypi/warehouse/blob/8d8cc16f0e0770156fb4c3648da64f2a7d5bc21f/warehouse/static/js/warehouse/controllers/github_repo_info_controller.js
https://github.com/pypi/warehouse/blob/8d8cc16f0e0770156fb4c3648da64f2a7d5bc21f/warehouse/templates/includes/packaging/project-data.html

We derive the API URL here:
https://github.com/pypi/warehouse/blob/186180c600da5a99a7bdc0da548f852351d91e84/warehouse/packaging/models.py#L586-L597

Would you like to take a stab at the changes necessary to make that happen? It would likely double the amount of client-side API calls the browser makes to GitHub API.

**Comment by HallvardMM** [comment]
Yes I can take a look at it 😄
