### ISSUE TITLE
Forex-Python | Currency Rates Source Not Ready

### ISSUE THREAD

**Issue by Himanshukumar30** [pypi/warehouse#12982]
## Bad source in Forex-Python  

I have tried installing the latest version V 1.8 as well as V 1.6 of Forex-python API. However, the API source is not responding. 

The error is as follows:
RatesNotAvailableError
forex_python.converter.RatesNotAvailableError: Currency Rates Source Not Ready

I'll appreciate if someone could let me know when it will be up?

**Comment by ewdurbin** [comment]
Hello @Himanshukumar30. This is the issue tracker for pypi.org itself, not the projects hosted there.

You should identify the issue tracker for the project you've installed and request support from them directly.
