### ISSUE TITLE
project on pypi has multiple "latest" versions

### ISSUE THREAD

**Issue by kratsg** [pypi/warehouse#13002]
**Describe the bug**

https://pypi.org/project/itksn/ indicates that `0.0.3` is the latest version.

**Expected behavior**

https://pypi.org/project/itksn/ indicates that `0.1.0` is the latest version.

**To Reproduce**

Just visit the page. Additionally:

- https://pypi.org/project/itksn/0.1.0/ indicates `0.1.0` is the latest version
- https://pypi.org/project/itksn/0.0.3/ indicates `0.0.3` is the latest version
- https://pypi.org/project/itksn/0.0.2/ indicates `0.0.3` is the latest version

**My Platform**

Seems to be across browsers -- but -- I am on MacOS 13.0.1 (22A400) using Google Chrome Version 109.0.5414.87 (Official Build) (x86_64).

**Additional context**

I deployed this via GitHub actions with no issue: https://github.com/kratsg/itksn/actions/runs/4187028318/jobs/7256337792

**Comment by kratsg** [comment]
![Screenshot 2023-02-15 at 10 51 36 AM](https://user-images.githubusercontent.com/761483/219125306-431333b5-44a0-48b9-90b4-944b93fbb782.png)

![Screenshot 2023-02-15 at 10 54 40 AM](https://user-images.githubusercontent.com/761483/219125427-d5e293db-fdc4-41fd-be3f-34403e6123d4.png)

![Screenshot 2023-02-15 at 10 54 49 AM](https://user-images.githubusercontent.com/761483/219125441-27254ccf-5d95-4514-8cbc-1ae30d133359.png)

![Screenshot 2023-02-15 at 10 54 57 AM](https://user-images.githubusercontent.com/761483/219125458-c6810b38-f126-4ea8-88cf-3bba8bfe136c.png)

**Comment by di** [comment]
Looks like our cache purging was perhaps a little slow. I see all releases now indicating that `0.1.0` is the latest version.

**Comment by kratsg** [comment]
> Looks like our cache purging was perhaps a little slow

Hopefully that's the case. Do you want me to close the issue once I see that it's changed?

**Comment by di** [comment]
Yep, https://github.com/pypi/warehouse/pull/13003 will resolve the actual issue causing a backup in our worker queues. Thanks for the report, it gave us an early warning!
