### ISSUE TITLE
Use mypy's SQLite cache option?

### ISSUE THREAD

**Issue by woodruffw** [pypi/warehouse#13019]
Typechecking Warehouse with `make lint` can be pretty slow; `mypy`'s `sqlite-cache = true` setting would probably slow it up a bit.

I can do this, just creating an issue first for visibility/in case there's a known reason not to do this 🙂

**Comment by miketheman** [comment]
I believe mypy by default will create a binary cache in .mypy_cache - is that not created or used?

**Comment by woodruffw** [comment]
> I believe mypy by default will create a binary cache in .mypy_cache - is that not created or used?

It's created and used, but that's actually not a binary cache: unless they've changed it recently, it's a JSON cache. 

I've experienced decent speedups on other repos just by switching it to the SQLite backend 🙂

**Comment by miketheman** [comment]
> it's a JSON cache.

Whoops, I misspoke - you're absolutely right.

The SQLite cache is self-proclaimed "hokey" https://github.com/python/mypy/blob/b562cc235dcd2e71d2fed1aad72a4a8400bc307d/mypy/metastore.py#L6-L8

The timing issues stem from us not preserving the `.mypy_cache` directory in a volume between runs of `make lint` - so regardless of the caching technique, we recreate the cache each run.

When adding the cache directory as a volume, we get the benefit of the timing speedup, regardless of the caching technique - from ~3 minutes total to ~1.5 minutes

I'll put up a PR with the changes, as well as some other cache directories we can benefit from in local development.
