### ISSUE TITLE
Versions disappeared from a package on PyPi

### ISSUE THREAD

**Issue by donchkat** [pypi/warehouse#13047]
**Describe the bug**
Looks like some versions of PaddlePaddle were removed from PyPi, but they still exist in the original repository. 

**Expected behavior**
The versions are: 1.8.2, 1.8.3, 1.8.4
They still exist in the original repository so I can't find why they would disappear.
This influences different security tools that relay on the PyPi documentation of all available versions for a package. 

**To Reproduce**
Check the [original repo tags page](https://github.com/PaddlePaddle/Paddle/tags?after=v2.0.1)
and the [PaddlePaddle page on PyPi](https://pypi.org/project/paddlepaddle/)

**My Platform**
I use chrome to enter PyPi web page.

**Additional context**
Here are some screenshots from a database I maintain that provides remediation information for packages and their vulnerabilities. For this purpose I use the PyPi API to get the list of all available versions per package. As you can see some random versions were removed. 
<img width="931" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/74149435/220326186-36cb8812-b791-4b24-a67b-215b6960e059.png">
<img width="941" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/74149435/220326200-9248668d-3121-4997-b1aa-301843b52ea5.png">
<img width="933" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/74149435/220326224-04a596e4-e2d0-49fb-b6ff-d143914b70d4.png">

Thank you.

**Comment by miketheman** [comment]
These versions were removed from PyPI by the project owner.

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
