### ISSUE TITLE
Can't search for exact package name (yolov5)

### ISSUE THREAD

**Issue by ruckc** [pypi/warehouse#13055]
**Describe the bug**
If I search for "yolov5" I get back 231 packages, and yolov5 isn't the first project.

**Expected behavior**
If I search for an exact package name, that package should be the first response.

**To Reproduce**
[Search for "yolov5"](https://pypi.org/search/?q=yolov5)

**My Platform**
Chrome, v110, Windows 11 & Ubuntu 22.04

**Comment by di** [comment]
Duplicate of https://github.com/pypi/warehouse/issues/8321 or https://github.com/pypi/warehouse/issues/2877.
