### ISSUE TITLE
Webauthn allows me to register my phone as security key but not login with it

### ISSUE THREAD

**Issue by mickeydarrenlau** [pypi/warehouse#13062]
**Describe the bug**
Webauthn allows me to register my phone as security key but not login with it

**Expected behavior**
After closing the native is security key prompt, A chrome prompt like this should pop up and allows me to select my phone to use as a security key
![ss](https://user-images.githubusercontent.com/62752664/220800866-232ebbed-8b27-4805-a4d9-210b3349b3c6.png)

**To Reproduce**
Add a android phone as a security key by visiting your profile and clicking add security key and follow the expected behavior
Then logout and try to login with the same expected behaviour

**My Platform**
Windows 10 and chrome version Version 110.0.5481.177 (Official Build) (64-bit)

**Additional context**
None

**Comment by di** [comment]
I think I can reproduce this: the only option that it presents is for a security key, regardless of whether a security key is enabled or not, correct?

**Comment by di** [comment]
I think #13076 should fix this.

**Comment by mickeydarrenlau** [comment]
Is it out

**Comment by di** [comment]
Not yet, that PR needs merged first.
