### ISSUE TITLE
Is PEP 541 proper approach to dealing with sniped project name?

### ISSUE THREAD

**Issue by gadams999** [pypi/warehouse#13077]
**Describe the bug**
Attempted to push package to https://pypi.org/ and received the error:

```
The user 'aws-icpsh' isn't allowed to upload to project 'awsiot-credentialhelper'
```

When I checked the URL https://pypi.org/project/awsiot-credentialhelper/ I saw that it was a spam package with no content or source URL. I opened an issue for PEP 541, but am not sure if that's the right approach.

After that, the package looks to be removed (404 now) so thought it might have been cleared. But still getting the same Forbidden 403 error. I understand the error is on our side as we made the repo public prior to pushing the first release. Just curious if opening the PEP 541 is the correct way to go and gain access, or if there is any recourse.

[Issue](https://github.com/pypi/support/issues/2629) we're tracking right now.

First time running into this, so apologies if I'm asking in the wrong setting.

**Comment by di** [comment]
Hey @gadams999, no worries. PEP 541 is the right approach here, the project name is still owned by the original owner, it just has no releases so doesn't show up on PyPI.
