### ISSUE TITLE
pip list - SSL: UNKNOWN_PROTOCOL

### ISSUE THREAD

**Issue by MagnaFrisia90** [pypi/warehouse#13115]
Hello,
I am running behind a http_proxy(squid) & want to run "pip list"(same for pip3 list) on my CentOS7 machine.
The following error is printed:

>     Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:877)'),)) - skipping

This squid receives the request - log entry:

    1.2.3.4 - - [01/Mar/2023:14:44:30 +0100] "NONE error:invalid-request HTTP/1.1" 400 342 NONE:HIER_NONE

I have already talked to the Proxy-Admin about this. No further information can be provided.
So basically pip seems to be sending a wrong/malformed HTTP(s) request.

Does anybody run his pip behind a httpproxy ? Or experienced the same issue?
Any ideas how to solve this ?

pip version 21.3.1

Thanks in advance !
Kind regards

**Comment by di** [comment]
This appears to be an issue with your usage of `pip`, not with PyPI, please open this issue here instead: https://github.com/pypa/pip/issues.
