### ISSUE TITLE
Buffer Over Flow

### ISSUE THREAD

**Issue by evanwheelrr** [pypi/warehouse#13128]
My code is as follows. I am attempting to read a pointer location using offsets and than write to them. issue is when process.get_pointer()
is called. you get the collowing error

ctypes.windll.kernel32.ReadProcessMemory(self.handle, lp_base_address, lp_buffer,
ctypes.ArgumentError: argument 2: OverflowError: int too long to convert

`from ReadWriteMemory import ReadWriteMemory

rwm = ReadWriteMemory()
# Define the pointer address
#7FF7E9c400000
#00497DE0

points_pointer_address = 0x19BC7D60160+0x00497DE0

process = rwm.get_process_by_name("PieceByPiece.exe")

process.open()

points_pointer = process.get_pointer(points_pointer_address, offsets=[0xB8, 0x2F8, 0x18, 0x70, 0x20, 0x10, 0x60])
process.write(points_pointer, 500)

#while True:
    #value = process.read(points_pointer)
    #print(value)`

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.

**Comment by evanwheelrr** [comment]
where do i post it than?
