### ISSUE TITLE
Is it correct to use a user installer that downloads packages from pypi ?

### ISSUE THREAD

**Issue by iperov** [pypi/warehouse#13150]
(sorry for feature request category. Did not find correct category for this question)

I found that the invoke.ai project prompts users to download an installer that downloads packages from pypi during installation.

I suppose this puts a lot of stress on the pypi servers, since the packages are not downloaded by the developer, but by the application on the end user's computer.

This is essentially free app hosting.

Do you approve of this approach?

**Comment by di** [comment]
Are you talking about this project? https://pypi.org/project/InvokeAI/

**Comment by iperov** [comment]
yes
it has 12mb installer
https://github.com/invoke-ai/InvokeAI/releases/tag/v2.3.1.post2#installation-2.3.1
that installs huge app

**Comment by di** [comment]
I'm not seeing any concerns with this project, it has a lot of dependencies but appears to behave like many other Python projects, unless I'm missing something.

**Comment by iperov** [comment]
I'm not talking about the project, but in general, do you approve of such a load on the servers so that I can also use the installation directly from pypi in my application ?
Just imagine hundreds of users a day downloading 10gb from pypi ? Is that normal?

**Comment by di** [comment]
I don't see this resulting in a significantly higher load. It's likely a drop in the bucket compared to PyPI's total traffic. Thanks for raising the question though!

**Comment by iperov** [comment]
ok thanks
