### ISSUE TITLE
Can't find Project!

### ISSUE THREAD

**Issue by Sayad-Uddin-Tahsin** [pypi/warehouse#13160]
Hey,
I had uploaded my [project](https://pypi.org/project/sra-pylib) into PyPI. But It's not showing in [`pypi.org/simple`](https://pypi.org/simple) that's causing, IDE can't find project such as PyCharm and can't install it from `Settings -> Python Interpreter`!

Thanks! I really would like to see my project there!
Thanks again!

**Comment by di** [comment]
See #11935, https://github.com/pypi/warehouse/issues/7384, https://github.com/pypi/warehouse/issues/8385, etc: it takes ~24 hours for projects to appear on /simple. This shouldn't affect installability as installers can go directly to the project's simple page, e.g.: https://pypi.org/simple/sra-pylib/

**Comment by Sayad-Uddin-Tahsin** [comment]
It's mentionable that I've published almost 2 days ago. And the simple link, I can see there but PyCharm don't search there. And It's not affecting my installability but not showing in PyCharm Built in Package Searcher

**Comment by Sayad-Uddin-Tahsin** [comment]
> See #11935, #7384, #8385, etc: it takes ~24 hours for projects to appear on /simple. This shouldn't affect installability as installers can go directly to the project's simple page, e.g.: https://pypi.org/simple/sra-pylib/

It's mentionable that I've published almost 2 days ago. And the simple link, I can see there but PyCharm don't search there. And It's not affecting my installability but not showing in PyCharm Built in Package Searcher
