### ISSUE TITLE
Can't find my project!

### ISSUE THREAD

**Issue by Sayad-Uddin-Tahsin** [pypi/warehouse#13162]
I didn't meant to open it, but the other issue were closed!

From #13160:
> See #11935, #7384, #8385, etc: it takes ~24 hours for projects to appear on /simple. This shouldn't affect installability as installers can go directly to the project's simple page, e.g.: https://pypi.org/simple/sra-pylib/

@di , It's mentionable that I've published 2 days ago. And the simple link, I can see there but PyCharm don't search there. And It's not affecting my installability but not showing in PyCharm Built in Package Searcher

**Comment by ewdurbin** [comment]
I'm not seeing an issue here

```
$ curl --silent https://pypi.org/simple/ | grep -i sra-pylib
    <a href="/simple/sra-pylib/">sra-pylib</a>
    ```

**Comment by di** [comment]
I think you need to take this up with PyCharm:

```
$ curl -s https://pypi.org/simple/ | grep sra-pylib
    <a href="/simple/sra-pylib/">sra-pylib</a>
```

**Comment by Sayad-Uddin-Tahsin** [comment]
But will my other users do so?

**Comment by Sayad-Uddin-Tahsin** [comment]
> I think you need to take this up with PyCharm:
> 
> ```
> $ curl -s https://pypi.org/simple/ | grep sra-pylib
>     <a href="/simple/sra-pylib/">sra-pylib</a>
> ```

Without having in /simple it don't recommend Update also!

**Comment by miketheman** [comment]
@Sayad-Uddin-Tahsin as recommended, this seems to be a PyCharm issue, not a PyPI one.

**Comment by Sayad-Uddin-Tahsin** [comment]
> @Sayad-Uddin-Tahsin as recommended, this seems to be a PyCharm issue, not a PyPI one.

It's not because they retrieve the information from `pypi.org/simple` but my project still don't appearing there. How can I say that it's a PyCharm issue?

**Comment by miketheman** [comment]
> they retrieve the information from `pypi.org/simple` but my project still doesn't appear there.

@Sayad-Uddin-Tahsin this has already been shown as working by both di and ewdurbin above. The package `sra-pylib` appears in the `/simple` endpoint.

Thus if **PyCharm** is not suggesting an update, that appears to be an issue with **PyCharm**.

**Comment by Sayad-Uddin-Tahsin** [comment]
> > they retrieve the information from `pypi.org/simple` but my project still doesn't appear there.
> 
> @Sayad-Uddin-Tahsin this has already been shown as working by both di and ewdurbin above. The package `sra-pylib` appears in the `/simple` endpoint.
> 
> Thus if **PyCharm** is not suggesting an update, that appears to be an issue with **PyCharm**.

Sorry to say, if it my fault but it seems not appearing because I'm trying to find `sra-pylib` in `pypi.org/simple`!

**Comment by miketheman** [comment]
@Sayad-Uddin-Tahsin Earlier in this thread, @di shows how to to use `curl` to inspect the response from `/simple` and proves the library is there.

I've also loaded the page in a browser. It takes a while to load - it's 24MB in size! After it finished loading the entire page, I captured a screenshot showing the library:

<img width="598" alt="Screenshot 2023-04-13 at 15 22 08" src="https://user-images.githubusercontent.com/529516/231756731-ba27a272-5ffe-4b05-b623-b604ca5c1dbe.png">

If you're running into an issue that this is not available by either of these two methods, please provide more details and examples using `curl` of what the response is.
