### ISSUE TITLE
pytrends.exceptions.ResponseError: The request failed: Google returned a response with code 429.

### ISSUE THREAD

**Issue by techblogger5** [pypi/warehouse#13188]
I tried lot, but unable to resolve this time, I tried proxy, other PC, other international PC, but not able to encounter "Google returned a response with code 429."

**Comment by miketheman** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
