### ISSUE TITLE
503: Service Unavailable

### ISSUE THREAD

**Issue by sicotteh** [pypi/warehouse#13307]
**Describe the bug**

On CentOS-7

when trying to upload package,
 
I get the following error
HTTPError: 503 Service Unavailable from https://test.pypi.org/legacy/
Service Unavailable

even though that URL responds when using a browser.
(p.s. using __token__ as username .. with appropriate token)]]

**Expected behavior**

I expect sucessfull test deployment of package
**To Reproduce**

cd into my package source code (CAVA)
then

python3 -m twine upload --repository testpypi dist/*

**Additional context**

**Comment by di** [comment]
Thanks, we are investigating: https://status.python.org/incidents/vc41bg4603qn

**Comment by miketheman** [comment]
Incident should be resolved.
