### ISSUE TITLE
Unfortunate Introduction

### ISSUE THREAD

**Issue by allan-bonadio** [pypi/warehouse#13346]
This is for the website pypi.org .  

**Describe the bug**
Your introduction, on Bing.com, doesn't say much that common people could understand.  Or in some cases, even a programmer.

**Expected behavior**
Your introduction should clearly explain the overall gist of what Pypi and NNG are, in words that common people can understand.  Something like, "NNG is a software interface for computer networking".  Something that grandma would understand.  

**To Reproduce**
- Go to bing.com
- search for "NNG python"      (nng just takes you to Neilsen Norman Group.)
- Result is taken from your website, but it' confusing.  
- - First paragraph starts with "On Windows, MacOS, and Linux, the usual should suffice.", like you're starting in the middle of a paragraph.  Looks like it somehow decided to pick up some of your install doc instead of a general description
- - The Goals start with "Provide a Pythonic, works-out-of-the box library on Windows and Unix-platforms."  An empty file would achieve this goal; and it would work everwhere.  This goal forgot the most important part: what it is, what it does.  Try something like "...works-out-of-the box *network* library ..."

**My Platform**

This was noticed 3/31/2023, and the search was done on bing.com

**Additional context**

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
