### ISSUE TITLE
reCAPTCHA blocked in China

### ISSUE THREAD

**Issue by SimFG** [pypi/warehouse#13350]
**Describe the bug**

![image](https://user-images.githubusercontent.com/21985684/229109299-93d24df6-680c-43fb-938a-c98588c4db64.png)
can't register a account, refer to: #3174
**Expected behavior**

**To Reproduce**

**My Platform**

**Additional context**

**Comment by miketheman** [comment]
I've shipped a change to the [Content Security Policy](https://content-security-policy.com/) we set as headers for the recaptcha - this directive helps by telling browsers what the authors of a website have decided which scripts to securely allow, and prevent unintended other scripts loading.

If you wouldn't mind deactivating the plugins that disable the CSP behavior and confirming that the recaptcha loads on registration page [pypi.org/account/register](https://pypi.org/account/register/) so we can close this out?

**Comment by SimFG** [comment]
ok, thanks your reply
