### ISSUE TITLE
'flux-capacitor' is too similar to an existing project, but there exists none such project

### ISSUE THREAD

**Issue by The-Ludwig** [pypi/warehouse#13373]
**Describe the bug**
When trying to initially upload and register a project named `flux-capacitor` (via `twine upload --verbose dist/flux_capacitor-0.1.0.dev0-py3-none-any.whl` generated from [this repo](https://github.com/The-Ludwig/flux-capacitor)), I get the error 
```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/                                                                                       
         The name 'flux-capacitor' is too similar to an existing project. See https://pypi.org/help/#project-name for more information.
```
Upon searching on PyPi, there does not seem to be such a project. The closest names are `flux-cli` and `flux-cloud`.
The same thing on test-PyPi works: https://test.pypi.org/project/flux-capacitor/

**Expected behavior**

Uploading `flux-capacitor` to pypi works since there are no similarly named projects.

**To Reproduce**

Clone https://github.com/The-Ludwig/flux-capacitor, run `python -m build` and upload with `twine upload --verbose dist/flux_capacitor-0.1.0.dev0-py3-none-any.whl`.

**My Platform**

```
> python --version
Python 3.10.4
```
```
> python -m build --version
build 0.10.0
```

```
> twine --version
twine version 4.0.2 (importlib-metadata: 4.13.0, keyring: 23.9.3, pkginfo: 1.8.3, requests: 2.27.1, requests-toolbelt: 0.10.1, urllib3: 1.26.8)
```

**Additional context**

**Comment by maxnoe** [comment]
Mmh, we searched for that.

Why does this not show up here:
https://pypi.org/search/?q=fluxcapacitor
