### ISSUE TITLE
Object Storage Migration - Issues with files.pythonhosted.org please discussed here.

### ISSUE THREAD

**Issue by ewdurbin** [pypi/warehouse#13403]
See https://status.python.org/incidents/y52td1f7pyy1

**Comment by mohon8156** [comment]
Md Mohon 1993/1996

**Comment by ewdurbin** [comment]
> Iranian Developers cannot install any packages using pip!!!! any idea to fix it??? it's been over two month and it is getting worst.

Hi can you file a network access request at https://github.com/pypi/support/issues?q=is%3Aopen+is%3Aissue+label%3Anetwork? This is the first we've heard of this, though I'm not certain what can be done. Once you get the issue filed we can try to determine what's going on.

**Comment by ArchbishopMoipolai** [comment]
I am struggling to install gdal and geopandas on pydroid3, can anyone help in this regard

**Comment by ewdurbin** [comment]
hi @ArchbishopMoipolai do you have anything that indicates this is related to the object storage migration?

**Comment by ArchbishopMoipolai** [comment]
No, I don't think that's the case. It keeps on asking for gdal_confg...

**Comment by ewdurbin** [comment]
You should contact the maintainers of the projects you're asking about. This issue is for reports of impact due to the migration we are performing.

**Comment by mw-root** [comment]
I'm getting a 404 from https://pypi.org/project/codecov/ from the Toronto Ontario area.

Most other packages seem to work fine.

**Comment by di** [comment]
It's unrelated to the migration: the codecov project maintainers removed the project. See https://community.codecov.com/t/codecov-yanked-from-pypi-all-versions/4259 for more details.

**Comment by di** [comment]
@kamicase24 This is likely unrelated, please open a new issue with more details (including your username, the project name, the command your using and the resulting error message).
