### ISSUE TITLE
Unable to install codecov

### ISSUE THREAD

**Issue by haorong4** [pypi/warehouse#13418]
**Describe the bug**
codecov is missing in the Pypi projects. 
```
(myenv) work/path % pip install codecov     
ERROR: Could not find a version that satisfies the requirement codecov (from versions: none)
ERROR: No matching distribution found for codecov
```
This page is also down <https://pypi.org/project/codecov/>. Is the codecov package no longer support from pypi?

**Expected behavior**
I successfully installed the package a few days ago. 

**To Reproduce**
pip install codecov

**My Platform**
using a Macbook zsh terminal

**Additional context**

**Comment by di** [comment]
The project was deleted by it's maintainers. Please see https://community.codecov.com/t/codecov-yanked-from-pypi-all-versions/4259
