### ISSUE TITLE
Document how trusted publishing feature protects against resurrection attacks

### ISSUE THREAD

**Issue by di** [pypi/warehouse#13469]
This was raised by a user: we sort of hint about protecting against resurrection attacks in https://docs.pypi.org/trusted-publishers/security-model/, but we could go into more detail there about how we do this, and what is/isn't possible as a result.

**Comment by webknjaz** [comment]
Thanks to @ssbarnea for pointing out that this is undocumented/unclear!

**Comment by di** [comment]
Fixed in #13720.
