### ISSUE TITLE
after upgrading to kubuntu 23.04 maestral stop working

### ISSUE THREAD

**Issue by asenler** [pypi/warehouse#13477]
$ maestral
Traceback (most recent call last):
  File "/home/user/.local/bin/maestral", line 5, in <module>
    from maestral.cli import main
ModuleNotFoundError: No module named 'maestral'

**Comment by miketheman** [comment]
Hi, this issue tracker is for issues with the codebase behind [pypi.org](https://pypi.org/) itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
