### ISSUE TITLE
[UX+bug] UI for non-activated organizations in clickable where it shouldn't be: disabled `[Activate Billing]` can lead to HTTP 500

### ISSUE THREAD

**Issue by webknjaz** [pypi/warehouse#13487]
**Describe the bug**

This is similar to https://github.com/pypi/warehouse/issues/10773. A disabled button is clickable for a non-reviewed/non-approved org and it allows navigating to a "forbidden" page that possibly tracebacks internally.

**Expected behavior**

1. The button shouldn't be clickable.
2. The activation page shouldn't render HTTP 500 but rather HTTP 401/403.

**To Reproduce**

1. Create an organization at https://pypi.org/manage/organizations/
2. Click on a "disabled" `[Activate Billing]` button.
3. Get surprised it's clickable.
4. Click on the `[Activate Subscription]` button.
5. See an HTTP 500 page implying that PyPI is down.

**My Platform**
Chrome on Android, probably unrelated.

**Additional context**

![Screenshot_2023-04-23-14-03-34-54_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/578543/233863544-135ada22-ab7e-4a5a-85bf-a22cdab6201a.jpg)
![Screenshot_2023-04-23-14-04-44-17_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/578543/233863546-61f1e993-e303-40b7-85b5-31ceb88c1e1b.jpg)

**Comment by miketheman** [comment]
Thanks! We changed the visibility to disable, but didn't actually disable the button.

**Comment by webknjaz** [comment]
Yeah, but I suppose there's two bugs, the second one being the ability to navigate to the nested URLs behind that button.

**Comment by miketheman** [comment]
Agreed - but I think disabling the button AND href will be enough for now until we re-instate billing.
