### ISSUE TITLE
Trusted publishing: preserve OIDC claims for events

### ISSUE THREAD

**Issue by woodruffw** [pypi/warehouse#13515]
As part of making trusted publisher events "richer" and more useful to users, we should figure out how to embed their associated OIDC claims.

This is currently impossible, due to how we perform the token exchange and request identity setup:

1. During token exchange, we take the OIDC token and exchange it for a PyPI API token; this API token is a macaroon that can contain arbitrary data, but we don't currently embed any of the OIDC claims in it;
2. During authentication with an OIDC-minted API token, we use `OIDCProvider` as our `request.identity` type, which are "stateless" with respect to the *specific* API token that produced them;
3. Consequently, there's no `request` state that links the current `request.identity` to either the underlying macaroon *or* OIDC token that produced it.

To fix this, we have to create links at (1) and (2): the minted API token should contain caveats (or other metadata?) for the OIDC token's claims, and `request.identity` should become a type that contains the claims extracted from the macaroon.

CC @di

**Comment by woodruffw** [comment]
@tnytown will be looking at this as well.

**Comment by woodruffw** [comment]
To summarize Slack chat, this should probably be done as two separate PRs:

1. Add the OIDC claims (or some reasonable subset of them?) to a new or existing Macaroon caveat (maybe the current `OIDCProvider` caveat?)
2. Find a way to link the request's macaroon's caveat with OIDC events

**Comment by woodruffw** [comment]
> * Find a way to link the request's macaroon's caveat with OIDC events

We have a few options here:

* We could replace the current `request.identity` (`OIDCProvider`) with a wrapped type that includes both the `OIDCProvider` and the relevant claims.
* We could add another sidecar attribute to `request` or similar, e.g. `request._identity_oidc_claims`.

CC @di and @dstufft for opinions here -- I think modifying `request.identity` is probably the cleanest approach here, but I'm possibly missing something better as well 🙂

**Comment by woodruffw** [comment]
Great work here @tnytown!

**Comment by dstufft** [comment]
✨
