### ISSUE TITLE
Trusted publishing: "OIDC added" email does not specify full trust details

### ISSUE THREAD

**Issue by webknjaz** [pypi/warehouse#13577]
### Story

I asked my co-maintainer to configure trusted publishing on a project where I don't have owner privileges. I gave them detailed instructions.
When they added trusted publishing, I got this email:
https://github.com/pypi/warehouse/blob/0795e55d/warehouse/templates/email/trusted-publisher-added/body.html#L31

Specifically, this is what I saw:
> Publisher name: GitHub
> Publisher specification: ci-cd.yml

As you can see, the specification field only contains the workflow name. It does not say which *repository* is trusted, nor does it specify the *environment* name (which was the main piece of information I was looking out for).

### Expectations

I'd like to be able to see all the details of the trust configuration, including the optional fields.

### Motivation

This is useful for logging purposes, correctness verification, implementation matching. Especially since this information is not available on the web interface to the accounts with the maintainer-level access.

**Comment by di** [comment]
Thanks for the issue, I agree this could use more detail. The templates are here if anyone would like to work on this: https://github.com/pypi/warehouse/tree/main/warehouse/templates/email/trusted-publisher-added

**Comment by Martolivna** [comment]
I'll take it.

**Comment by woodruffw** [comment]
@Martolivna FYI, feel free to tag me and/or @tnytown for review on any changes here! We're partially funded to work on tasks like these.

**Comment by Martolivna** [comment]
Hello @woodruffw, thank you for your assistance. I have encountered some difficulties while resolving this issue, so once I have any updates or a potential solution, I will let you know. I apologize if it takes up too much time.

**Comment by woodruffw** [comment]
No problem at all! We're also happy to help with questions, if you have any.

**Comment by woodruffw** [comment]
> Hi, @woodruffw. Could you please review this attempt?

Reviewed, thanks for the ping!

**Comment by di** [comment]
Reopening this, these emails should include the name of the repository owner as well (right now it's just the repository name).

**Comment by woodruffw** [comment]
Whoops, I missed that, thanks.

CC @jleightcap: This would be a good one to round out -- it should just be a few additional lines for the `repository_owner` in addition to the current `repository_name`.
