### ISSUE TITLE
Trusted publishing: consolidate the GitHub publisher form a little

### ISSUE THREAD

**Issue by woodruffw** [pypi/warehouse#13660]
The registration forms for GitHub publishers currently look like this:

![image](https://github.com/pypi/warehouse/assets/3059210/8c2c7259-826e-40fd-b645-3802dde90ea9)

The split between "Owner" and "Repository name" is arguably pointless: the `user/repo` slug format is well known and commonly used by developers, and having it broken across multiple form inputs means that the user needs to tab or otherwise select between them.

So, my proposal: remove the separate form inputs here, and consolidate them into a single "Repository" input that expects inputs in `user/repo` slug format.

This would mean updating the screenshots once more, but IMO it's worth it for the slightly improved UX 🙂 

CC @di for thoughts

**Comment by di** [comment]
I think I'm a -0 on this. We haven't gotten any feedback AFAIK that this has been confusing/challenging, and I think the separate form fields actually allow us to make it _more_ clear what we want in each (especially because the form mixes things from PyPI with things from GitHub).

**Comment by woodruffw** [comment]
Makes sense. I could have sworn I remembered a request for this, but I can't find it now (and I agree with your point about clarity).

#13681 is open for this, but it's in a stable state so @jleightcap and I will icebox it until/if this comes up again.

**Comment by di** [comment]
Going to close this for now, unless we get feedback that this would be an improvement over the existing form, I don't think we should change this.
