### ISSUE TITLE
Chore: Forms: replace `DataRequired` with `InputRequired`

### ISSUE THREAD

**Issue by woodruffw** [pypi/warehouse#13695]
A bunch of the Warehouse forms use `DataRequired` when they should probably be using `InputRequired`, since the latter is stricter and doesn't do default (probably unintended) input coercions.

Ref: https://wtforms.readthedocs.io/en/2.3.x/validators/#wtforms.validators.DataRequired

Assigning to myself for triage.

**Comment by woodruffw** [comment]
Triaging: @jleightcap will be working on this.

**Comment by di** [comment]
Does https://github.com/pypi/warehouse/pull/13696 need to be taken over?

**Comment by di** [comment]
This was reverted in #13760 due to #13759.

**Comment by woodruffw** [comment]
#13828.
