### ISSUE TITLE
Stop sending emails (and maybe warnings) on PGP signature uploads

### ISSUE THREAD

**Issue by dstufft** [pypi/warehouse#13733]
In https://github.com/pypi/warehouse/pull/13707 we removed the support for uploading signatures to PyPI, but we added warnings both in email and in twine if someone attempts to upload a signature to let them know that support is gone.

We should remove that at some point in the future. Probably in roughly a year (so May 2024? or so).

**Comment by di** [comment]
It's May 2024, I made https://github.com/pypi/warehouse/pull/15896 to resolve this.
