### ISSUE TITLE
Trusted publishing: support a "dry-run" mode

### ISSUE THREAD

**Issue by woodruffw** [pypi/warehouse#13735]
Filing from https://github.com/urllib3/urllib3/pull/3042: the `urllib3` maintainers recently switched to trusted publishing, and ran into a small snarl because of a configuration mismatch. 

That snarl was easy to resolve, but could have been caught earlier by a "dry-run" mode for the token exchange. Some thoughts on how we could do that:

1. A separate endpoint for dry-runs that validates the OIDC token and matches it to a publisher, but without returning a temporary PyPI token. This should be no less of an oracle than the current minting endpoint is, and means that people can test their configurations without exposing even a short-lived PyPI token.
2. Explicitly encouraging people to use the existing `mint-token` endpoint for dry-runs, with the expectation that the temporary token is discarded.
3. Some fusion of the above, e.g. a `dry-run: bool` parameter on the `mint-token` endpoint.

Regardless of what we do here, this also needs to be exposed in some useful way -- either in the web UI or via `gh-action-pypi-publish`.

CC @sethmlarson

**Comment by di** [comment]
How would we expect people to run said dry run?

**Comment by woodruffw** [comment]
> How would we expect people to run said dry run?

Yeah, I'm not sure 🙂 -- I think the easiest thing would be to also expose it via the `gh-action-pypi-publish` action with a manual workflow trigger, although that's a lot of complexity that needs to be added/removed from a publishing workflow just for a self-test.

**Comment by woodruffw** [comment]
I can't think of a good way to do this and I think the need for this is largely offset by the debugging info that's been added to both PyPI's responses and the official workflow recently, so closing.
