### ISSUE TITLE
Unable to add token

### ISSUE THREAD

**Issue by mikemhenry** [pypi/warehouse#13759]
**Describe the bug**
Unable to make new API token.

**Expected behavior**
I expected to be able to make an API token. 

**To Reproduce**
Go to https://pypi.org/manage/account/token/ and make a token with any name or scope. 
Then hit "add token".
When I do that, I get "Specify a token name" and "Specify the token scope" regardless what name or scope I pick. 

**My Platform**

Firefox, windows 11. I disabled all my extensions and have the same issue.

**Additional context**

**Comment by IAlibay** [comment]
Also experiencing this on Chrome.

We also are finding that removing tokens isn't working either.

**Comment by ewdurbin** [comment]
Confirmed. Likely related to #13696. @di can you take a look?

**Comment by mikemhenry** [comment]
Thanks! It works now 🎉
