### ISSUE TITLE
Require 2FA for creating a new project

### ISSUE THREAD

**Issue by dstufft** [pypi/warehouse#13765]
We can start requiring 2FA to be enabled when creating a new project, to help ratchet more users into 2FA earlier.

**Comment by sethmlarson** [comment]
@dstufft  I'm seeing many "Require 2FA to do X", is it sensible to also require the same for new users in general? That way expectations are set right away rather than "You can create an account but immediately after trying to do anything you need 2FA".

**Comment by dstufft** [comment]
https://github.com/pypi/warehouse/issues/13762

**Comment by sethmlarson** [comment]
Ah I see, thanks for pointing that one out!

**Comment by di** [comment]
Closing now that [2FA is required for all users](https://blog.pypi.org/posts/2024-01-01-2fa-enforced/).
