### ISSUE TITLE
Remove support for passwords in upload API

### ISSUE THREAD

**Issue by dstufft** [pypi/warehouse#13770]
With the [push to 2FA](https://blog.pypi.org/posts/2023-05-25-securing-pypi-with-2fa/) we should eventually just remove the ability to authenticate with username/password in uploads all together and just require an API token.

Ideally this comes after https://github.com/pypi/warehouse/issues/13769.

This differs from https://github.com/pypi/warehouse/issues/7265 in that https://github.com/pypi/warehouse/issues/7265 only applies to people who have 2FA on their account, this applies to *everyone*.

**Comment by ewdurbin** [comment]
duplicate of #7265

**Comment by ewdurbin** [comment]
ope sorry :)

**Comment by miketheman** [comment]
A message will now be returned to users attempting to upload with basic auth.

We should eventually remove most of the associated code in the policy and simplify the logic to return the message regardless of whether the account works or not. Leaving this open as a reminder for that.
