### ISSUE TITLE
Prevent removing the last 2FA method associated with an account

### ISSUE THREAD

**Issue by dstufft** [pypi/warehouse#13771]
2FA will be required on PyPI, and for some projects is already required. We should prevent an account from regressing in their 2FA-ness and prevent the last 2FA method from being removed before another method is added.

**Comment by ristomcgehee** [comment]
Hi, I'd be happy to work on this one. Here are the implementation details I'd likely follow. Feel free to voice suggested changes:
* On the Account Settings page, if there is only one 2FA method, the Remove button will be disabled and greyed out.
* If you mouse over the disabled Remove button, the cursor will turn into the "not" symbol and a tool tip will say "Not allowed to remove last 2FA method" (similar behavior to the Your Projects page with the Manage and View buttons).
* The backend will also check that at least two 2FA methods are present before removing a method.
