### ISSUE TITLE
Call out deprecated fields of APIs

### ISSUE THREAD

**Issue by ucodery** [pypi/warehouse#13788]
**What's the problem this feature will solve?**
Users of warehouse's API will better understand how to handle the returned data.

**Describe the solution you'd like**
The API reference on warehouse.pypa.io clearly calls out deprecated fields.

**Additional context**
With the change to `has_sig` this field is essentially deprecated, but the documentation doesn't show this. The only way to know that this field can safely be ignored by clients is to check the source.

Similarly, `downloads` can safely be ignored by clients, but there is no mention of this in the docs.

`releases` _is_ called out in the docs as deprecated, and that clients should begin to not rely on it even though it is still serving actionable data.

My open questions:
* these requested changes are geared toward the JSON API. Should the XML API receive similar call-outs? The fields also exist there and also do not return actionable data, but the entire API guide is cautioned as deprecated.
* are there any other fields that should be marked as deprecated that are not as obvious?

**Comment by ucodery** [comment]
update: already found another looking through the JSON source: `bugtrack_url`

**Comment by dstufft** [comment]
Good catch, we should definitely do this.
