### ISSUE TITLE
The list of available packages on `https://pypi.org/simple` is incomplete

### ISSUE THREAD

**Issue by rakovskij-stanislav** [pypi/warehouse#13795]
**Describe the bug**
Some packages that exist on the main page and presented on `https://pypi.org/simple/<package_name>` are not visible on `https://pypi.org/simple` link.
Example:  `antchain-ak-727a48eea1b24a469ff11ca2938fb727`

Project page [exists](https://pypi.org/project/antchain-ak-727a48eea1b24a469ff11ca2938fb727/):
<img width="842" alt="image" src="https://github.com/pypi/warehouse/assets/25303578/585c2779-fc9e-495b-b321-e5043c0c0017">

The file listing on `https://pypi.org/simple/<package_name>` also [exists](https://pypi.org/simple/antchain-ak-727a48eea1b24a469ff11ca2938fb727/):
<img width="609" alt="image" src="https://github.com/pypi/warehouse/assets/25303578/886fb7ca-a7b3-4a4c-9b0d-634e468292fd">

But there are no evidence of this package on `https://pypi.org/simple`:
<img width="905" alt="image" src="https://github.com/pypi/warehouse/assets/25303578/bb64bf07-d7ef-4bd4-8dc7-5b4bc7a80911">
The `simple` endpoint don't have 'antchain-ak-727a...' package.

**Expected behavior**
The presense of `antchain-ak-727a48eea1b24a469ff11ca2938fb727` on `simple` endpoint.

**Comment by di** [comment]
See #13160, https://github.com/pypi/warehouse/issues/11935, https://github.com/pypi/warehouse/issues/7384, https://github.com/pypi/warehouse/issues/8385, etc: it takes ~24 hours for projects to appear on /simple. This shouldn't affect installability as installers can go directly to the project's simple page, e.g. https://pypi.org/simple/antchain-ak-727a48eea1b24a469ff11ca2938fb727/.
