### ISSUE TITLE
Add full content on blog RSS feed

### ISSUE THREAD

**Issue by osantana** [pypi/warehouse#13812]
**What's the problem this feature will solve?**

This feature will enable newsreaders that subscribe to the feed to read the content directly on their newsreader software. It is also possible to aggregate these posts on other aggregation services (e.g. Planets)

**Describe the solution you'd like**

I don't know how to implement the solution, but looks like it is a matter of removing these lines of `mkdocs-blog.yml` configuration will be enough to put the whole content of the posts inside the RSS feed:

* https://github.com/pypi/warehouse/blob/main/docs/mkdocs-blog.yml#L41-L42

**Comment by ewdurbin** [comment]
I don't think the blog plugin and rss plugin we're using play nicely together with how things render.

When making the change, I found that the RSS previewers I could find generated some pretty ugly results for the post bodies.

See PR linked above.

**Comment by ewdurbin** [comment]
I think we'd welcome a PR that renders the blogs with a sane rendering though. I'm going to close that PR for now as it was just a curiosity of mine.

**Comment by osantana** [comment]
I will try to work on a PR to make the RSS render produce a nice result and submit it. Thanks in advance for the quick reply.
