### ISSUE TITLE
How to report problems with foreign packages

### ISSUE THREAD

**Issue by buhtz** [pypi/warehouse#13824]
I can not find on your website where and how to report problems with foreign packages.

For example there are security problems, hijacked packages, or just out-dated packages without enough information's to contact the maintainers etc

Can I do this in this Issue section here?

**Comment by di** [comment]
If there are security issues, please follow our security policy here: https://pypi.org/security/

**Comment by buhtz** [comment]
My list included more than security problems.

e.g. https://pypi.org/project/youplay/

It is outdated (2014), no maintainer contact possible, to known source repository

There is another "youplay" on Microsoft GitHub which is not the same project I think.
