### ISSUE TITLE
Organization stuck in awaiting approval stage

### ISSUE THREAD

**Issue by bryandyck** [pypi/warehouse#13846]
**Describe the bug**
I submitted a new organization 3 weeks ago that seems to be stuck in the queue. The organization name is "vitruvi".

**Expected behavior**
I would have though the organization would have been approved, I would have received an email requestion more clarification or information if required, or that the website would have an updated state or progress indication. Or alternatively, having an ability to delete that organization that is stuck in awaiting approval so I could submit another request.

**Comment by ewdurbin** [comment]
We are slowly ramping up organization approvals. As of #13821, we allow up to 3 submissions.
