### ISSUE TITLE
Add confirmation checkboxes to Release deletion

### ISSUE THREAD

**Issue by miketheman** [pypi/warehouse#13876]
**What's the problem this feature will solve?**
When removing a project, the user is presented with a number of checkboxes to confirm their choice with short descriptions of the consequences.

When removing a release, the only confirmation the user must provide is the version number.
![Screenshot 2023-06-06 12 03 09](https://github.com/pypi/warehouse/assets/529516/c3f8f778-0e43-4aea-a590-0d1f48114e02)

**Describe the solution you'd like**
Prompt the user to confirm a few more things, so that there's a little more friction to the release removal and prevent support requests.

**Comment by mm** [comment]
I've gotten started working on this! Looks like a fun first issue to work on 😄

**Comment by mm** [comment]
Before I get a PR up and the translation party started, I added these checkboxes based on the contents of the warning message (in this case the version is `7.0.3`) Do we like the wording here / would other checks be valuable?

<img width="802" alt="Screenshot 2023-06-11 at 11 48 17 PM" src="https://github.com/pypi/warehouse/assets/639901/a158188f-efbb-44bf-9373-429ca1fdc80e">

**Comment by di** [comment]
Looks good to me! Only one small nit: we should be consistent with language between this and the other series of checkboxes, e.g. "undo" vs. "reverse".

**Comment by ewdurbin** [comment]
Closed via #13930
