### ISSUE TITLE
Project description does not display on PyPI, although present in metadata

### ISSUE THREAD

**Issue by helloDestroyerOfWorlds** [pypi/warehouse#13916]
Agreed.

**Describe the bug**
 Title says it all.

**Expected behavior**
 I get a description on my pypi page

**To Reproduce**

1.  Use twine to upload package using PyCharm's terminal and "py -m twine upload dist/*"
2.  I suppose there may be more to it than this, but this is all I have to do and it's repeatable for me.

**My Platform**

Windows 10 using PyCharm IDE terminal

**Additional context**
  See my other open issue here:
[pypi says my project has no description but it does.txt](https://github.com/pypi/warehouse/files/11720086/pypi.says.my.project.has.no.description.but.it.does.txt)

**Comment by henryiii** [comment]
See https://github.com/pypa/packaging-problems/issues/675.

**Comment by TrojranHrorse** [comment]
Literally you guys are just linking me to all the issues I MYSELF have opened today.

**Comment by miketheman** [comment]
Hi there!

As this is clearly an issue with the way you're constructing your package and metadata for upload, I'll close out this issue on the warehouse, since there's no issue with the warehouse itself. I can see you're getting assistance over on the packaging-problems repo.

Best of luck!
