### ISSUE TITLE
Add confirmation gauntlet to release file deletion

### ISSUE THREAD

**Issue by ewdurbin** [pypi/warehouse#13935]
When deleting a single file from a release, we should include similar acknowledgments to what we do for releases and projects.

While reviewing #13930 I recognized that we have one more irreversible user initiated deletion that should have a similar set of acknowledgements:

- [ ] I understand that my users will no longer be able to install this file for this release of this project.
- [ ] I understand that I will <a href="https://pypi.org/help/#file-name-reuse">not be able to re-upload a using the same file name</a> {{ file.filename }}.
- [ ] I understand that I will not be able to undo this.
- [ ] I understand that the PyPI administrators will not be able to undo this.

_Originally posted by @ewdurbin in https://github.com/pypi/warehouse/issues/13930#issuecomment-1588301970_

**Comment by ewdurbin** [comment]
cc @mm if you're interested in implementing.

**Comment by mm** [comment]
back for more! we love a fun checkbox adventure 🎉  I have this more or less working, though may need some styling fixes:

https://github.com/pypi/warehouse/assets/639901/ccc898ff-65ad-4989-8c78-4ebd7acab4db

To accomplish that `If the checkboxes are checked, AND the input string matches, let us proceed` logic, I took the approach of modifying the ConfirmController that modal uses to accept listening on checkboxes (if they're marked as `checkbox` targets) and the input string as before:

https://github.com/mm/warehouse/blob/3168a1bcb666148f3171eb39ba98f747ad2a5547/warehouse/static/js/warehouse/controllers/confirm_controller.js#L43

It might be re-usable for other modals in the future and I can open a PR with the changes once I get the test coverage up, but was curious on initial thoughts on extending it that way 🙂

**Comment by ewdurbin** [comment]
I think that makes good sense! Thanks for digging in.
