### ISSUE TITLE
PyPI is now requiring wheels to be too much compressed

### ISSUE THREAD

**Issue by moriyoshi** [pypi/warehouse#13962]
**Describe the bug**

The change ([#13877](https://github.com/pypi/warehouse/pull/13877)) done in last week made my valid wheels that contain some native shared objects totally unuploadable. IMO requiring compression ratio < 0.1 is pretty rigorous.

**Expected behavior**

The threshold is too heuristic. Mitigation for zipbombs should be done in another way.

**To Reproduce**

Build any wheel of the following project and upload it to pypi:

https://github.com/opencollector/jntajis-python

**My Platform**

I am using cibuildwheel to build wheels.

**Additional context**

N/A

**Comment by miohtama** [comment]
I encountered this issue with [web3-ethereum-defi](https://github.com/tradingstrategy-ai/web3-ethereum-defi) and can no longer not upload new versions of the package produced with Poetry.

[Poetry discussion here](https://github.com/orgs/python-poetry/discussions/8115).

**Comment by di** [comment]
Should be fixed by #13967.
