### ISSUE TITLE
PIP INSTALL: ProtocolError | Connection broken/aborted | ConnectionResetError 10054

### ISSUE THREAD

**Issue by UskoKruM** [pypi/warehouse#13987]
**Describe the bug**
I am unable to download or install any python packages using pip (even inside a virtual environment), getting the following error message:

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forced to be aborted by the remote host', None, 10054, None))': /simple/virtualenv/

ERROR: Could not find a version that satisfies the requirement virtualenv (from versions: none)
ERROR: No matching distribution found for virtualenv

**Expected behavior**
Until a couple of days ago I was able to download and install packages using pip, as normal, even within virtual environments created with 'virtualenv'.

**To Reproduce**
- pip install virtualenv
or, inside a virtual environment:
- pip install Django (or another package, is the same error)

**My Platform**

- OS: Windows 10
- Command Line: CMD ( [Versión 10.0.19045.3086] )
- Python version: 3.10.0
- My computer is for personal use, I am not within a company network or through a Proxy server.

**Additional context**
- I have tried uninstalling and reinstalling different versions of python, always getting the same problem.
- I have pinged pypi.org ( ping pypi.org ) and I get a satisfactory response.
- My computer is for personal use, I am not within a company network or through a Proxy server.

![image](https://github.com/pypi/warehouse/assets/11650755/02ee8520-ee42-4cf8-8bcd-33f48b216c4c)

**Comment by miketheman** [comment]
Please open a Network Issue https://github.com/pypi/support/issues/new?labels=network&template=access-issues.yml
and provide relevant debugging information per the prompts.
