### ISSUE TITLE
Replace deprecated usage of `pkg_resources`

### ISSUE THREAD

**Issue by miketheman** [pypi/warehouse#13991]
`setuptools` has deprecated their `pkg_resources` sub-package in favor of stdlib packages. See https://setuptools.pypa.io/en/latest/pkg_resources.html

We appear to use it on only a few places:

```shellsession
$ git grep pkg_resources
tests/unit/forklift/test_legacy.py:import pkg_resources
tests/unit/forklift/test_legacy.py:                project.name, pkg_resources.safe_name(project.name).lower()
warehouse/forklift/legacy.py:import pkg_resources
warehouse/forklift/legacy.py:    prefix = pkg_resources.safe_name(project.name).lower()
warehouse/forklift/legacy.py:    if not pkg_resources.safe_name(filename).lower().startswith(prefix):
warehouse/utils/readme.py:import pkg_resources
warehouse/utils/readme.py:    return pkg_resources.get_distribution("readme-renderer").version
```

I'm not certain where to best find a replacement for [`safe_name()`](https://setuptools.pypa.io/en/latest/pkg_resources.html#parsing-utilities:~:text=on%20other%20lines.-,safe_name(name),-Return%20a%20%E2%80%9Csafe) yet. We might have existing comparable functionality in warehouse already.
**Feel free to omit this from the refactor if it's too complex**.

A similar refactor took place in `readme-renderer`, see https://github.com/pypa/readme_renderer/pull/281 for details.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypi/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/).

If you are working on this issue and have questions, feel free to ask them here, in the [`#pypa-dev` chat channel on Libera](https://web.libera.chat/#pypa-dev), the [PyPA Discord](https://discord.gg/pypa) or on the [Discourse](https://discuss.python.org/c/packaging/14).

**Screenshot Required**: *If your pull request makes a visual change*, include a screenshot of your update. This helps our team give you feedback faster.

**Comment by di** [comment]
I think that changing the behavior where we use `safe_name` basically amounts to fixing https://github.com/pypi/warehouse/issues/10030, which is a considerably bigger lift than just switching to a stdlib equivalent, so that might not be "good first issue" material.

The change where we use `get_distribution` should be straightforward, though!
