### ISSUE TITLE
Help Suggestion

### ISSUE THREAD

**Issue by jlleng** [pypi/warehouse#14096]
This may be helpful to others attempting to compile a program using espeakng with mbrola voices in auto-py-to-exe.
I spent many hours researching this. Mbrola voices work fine in IDE Thonny but not in an exe created using auto-py-to-exe.
Finally stumbled onto the solution.  Add path i.e. Home/.local/lib/python3.10/site-packages/espeakng to the additional files/
add folder section.

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.

**Comment by jlleng** [comment]
OK, thanks

    On Monday, July 10, 2023 at 08:30:37 AM EDT, Dustin Ingram ***@***.***> wrote:  
 
 


Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
