### ISSUE TITLE
Migrate to the mkdocs-material blog plugin

### ISSUE THREAD

**Issue by di** [pypi/warehouse#14112]
This is now generally available: https://squidfunk.github.io/mkdocs-material/insiders/#12000-piri-piri

More details here: https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/

**Comment by miketheman** [comment]
To potentially replace, but preserve similar behavior.
https://github.com/pypi/warehouse/blob/4f30c931d4eb8caa0898e2f82dc0253d9c6ca04a/requirements/docs-blog.in#L3
https://github.com/pypi/warehouse/blob/4f30c931d4eb8caa0898e2f82dc0253d9c6ca04a/docs/mkdocs-blog.yml#L31-L41
