### ISSUE TITLE
Cannot register on test.pypi.org

### ISSUE THREAD

**Issue by cbusse1** [pypi/warehouse#14189]
When trying to create an account on https://test.pypi.org/account/register/ (Chrome Browser, Windows 11) I get the following error message:

"The username is invalid. Usernames must be composed of letters, numbers, dots, hyphens and underscores. And must also start and finish with a letter or number. Choose a different username."

I tried different and long usernames. I have doubts that they already exist.
Also, it would be nice if the username is checked immediately after entering is marked as ok or not ok.

**Comment by di** [comment]
Hi, what username are you trying to use? Can you provide a screenshot?

**Comment by cbusse1** [comment]
The issue can be closed. I was not careful enough and thought the first field was for "username".
When entering the email address, chrome also filled out the actual username field with the email (I assumed it was for repeating email). Sorry about that, I have registered normally now.

**Comment by centroid457** [comment]
same for me!
your UX is not friendly!
typically we have to write double times email but here we have on next form (after email) unexpected username, fiasco!
