### ISSUE TITLE
ChromeDriverManager(version="114.0.5735.16") is not working in latest webdriver-manager 3.9.1.

### ISSUE THREAD

**Issue by souryadhal** [pypi/warehouse#14215]
**Describe the bug**

**Expected behavior**

**To Reproduce**

**My Platform**

**Additional context**

ChromeDriverManager(version="114.0.5735.16") is not working in latest webdriver-manager 3.9.1. but the same is working in  webdriver-manager 3.8.6.
Please resolve the issue.

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
