### ISSUE TITLE
Unable to use my own custom dark css theme for pypi.org due to some sort of overlapping framework(?)

### ISSUE THREAD

**Issue by coolslutguy420** [pypi/warehouse#14231]
**Describe the bug**
Unable to use my own custom dark css theme for pypi.org due to some sort of overlapping framework(?). In more detail: There may be some "wasted" or more appropriate to call it so "leftover" css framework injection bloat interfering with this. Injection as in particular or multiple css frameworks have been imported into pypi.org's website base of such. 
As a result, I cannot get my custom css theme to work for the website while browsing it. I understand there could also be an option to just add a dark mode switch whilst browsing but I think it would serve more of a solution or do greater help (lack of a better way to describe this at the moment) to altogether see what's going on with the css as a whole for pypi.org. 

PS~ I am using userstyles to custom theme websites to my personal liking and preference; if one or more reading this is unfamiliar with stylus (not to be confused with stylish) the firefox extension.

**Expected behavior**
I thought I could just find my way around into the css properties/classes, managing to get said dark css theme working with the website, so I could browse in a specific variant of dark mode that I felt best with using.

**To Reproduce**
Make an attempt to change the css on the pypi.org website, it _may_ be different for development than it is when making a userstyle. _From personal experience of doing this for any other website, it shouldn't be near impossible though, with any other website typically._ I style websites all the time to my personal preference. _This is just from my experience._

**My Platform**
 Using Firefox latest stable version on Linux XFCE

**Comment by di** [comment]
Hi @coolslutguy420, sorry you're having trouble. We really only have the bandwidth to support the default theme, and probably can't help with debugging this or anything related to custom user styles. That said, if you're able to identify the problem, happy to review a PR which would resolve it.

**Comment by coolslutguy420** [comment]
Not to be rude, but aside from "bandwidth" issues, that sounds like a problem with someone on the working side of technical staff rather than something I can further explain said problem of.
