### ISSUE TITLE
SSL timeout

### ISSUE THREAD

**Issue by rubenhartenstein** [pypi/warehouse#14268]
Hi there,

I attached all necessary information. Please have a look to it.

Best regards
Ruben
[SSL_timeout.docx](https://github.com/pypi/warehouse/files/12249768/SSL_timeout.docx)

**Comment by rubenhartenstein** [comment]
Here is the definition of systemd:
[Unit]
Description=This script makes sure that app.py is started via systemd. This file is located under /etc/systemd/system
After=network.target

[Service]
Type=simple
EnvironmentFile=/etc/profile.local.systemd
WorkingDirectory=/opt/obl-db-sql/
ExecStart=/opt/obl-db-sql/venv/bin/uwsgi --ini /opt/obl-db-sql/configuration/uwsgi.ini
Restart=on-failure

[Install]
WantedBy=multi-user.target

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.

**Comment by rubenhartenstein** [comment]
Sorry, for that.
