### ISSUE TITLE
`release_classifiers` table contains duplicates

### ISSUE THREAD

**Issue by miketheman** [pypi/warehouse#14264]
Interesting behavior observed when looking at converting the current table to a Declarative ORM style.

We allow for duplicate `release_classifier` entries, since the table is a joiner between `trove_classifiers` and `releases` and has no primary key / unique constraint. Table defined here:
https://github.com/pypi/warehouse/blob/881782a62b96323ce97528c75508056e27d2cea2/warehouse/packaging/models.py#L715-L726

This query returns a list of duplicates:
```sql
SELECT trove_id, release_id, COUNT(*)
FROM release_classifiers
GROUP BY trove_id, release_id
HAVING COUNT(*) > 1 ORDER BY 3 DESC;
```
We have some 4k duplicate entries in a table of 30,175,758 rows - so it's not endemic, but is definitely odd.

One such entry is: https://pypi.org/project/django-supertools/0.1/
Which has 3 records linking to `Programming Language :: Python` (trove_id: 241)

This was released back in 2013, so it seems like there might have been tooling/data constraints then?

I don't yet know how this could be a runtime problem - but if nothing else it's table bloat.

We also cannot convert the table to declarative without either a real primary key or [a mapper candidate key](https://docs.sqlalchemy.org/en/20/faq/ormconfiguration.html#how-do-i-map-a-table-that-has-no-primary-key) - so instead of choosing a candidate I figured let's discuss if we should remove the duplicates and enforce database-level uniqueness across the pairings.

**Comment by di** [comment]
Seems like this is an artifact of "PyPI legacy" as it hasn't happened since 2017:

```
warehouse=> SELECT rc.trove_id, rc.release_id, r.created, COUNT(*) as count
FROM release_classifiers rc
JOIN releases r ON rc.release_id = r.id
GROUP BY rc.trove_id, rc.release_id, r.created
HAVING COUNT(*) > 1
ORDER BY created DESC limit 10;
 trove_id |              release_id              |          created           | count
----------+--------------------------------------+----------------------------+-------
      156 | f533bf17-fc32-4ed8-8e35-884816959b4d | 2017-07-03 12:54:25.017221 |     2
      423 | 4f8e58b9-2e4e-416b-aef4-448db0e8642b | 2017-07-02 05:10:16.030547 |     2
      423 | 1742ac12-0ba1-4abd-8192-d99ad85b4a3f | 2017-07-02 04:59:52.272168 |     2
      156 | 7c6e6c95-4610-4652-b40a-c48fbe7d38d7 | 2017-07-01 16:30:16.53149  |     2
      214 | cfe7fc21-b34f-4783-aead-02e6def7d0dc | 2017-06-28 11:49:28.414461 |     2
      214 | 75cef419-ed5c-4610-907e-55643faea853 | 2017-06-28 03:28:44.923277 |     2
      423 | e804ef0a-a927-4558-ad48-4d2c7898432b | 2017-06-27 04:13:46.303117 |     2
      523 | 582bf7d0-e766-40e5-b6b0-7fcb4c0f7fc6 | 2017-06-26 13:43:40.22499  |     3
      533 | 88dbb8d2-c682-4324-b975-bdf069765a38 | 2017-06-26 12:46:15.112753 |     2
      214 | bb7ca756-c7b7-49ec-bae1-251f37036a76 | 2017-06-26 10:16:13.801903 |     2
(10 rows)
```

I don't see any reason to retain the duplicates.

**Comment by ewdurbin** [comment]
Quick scan adding a join to `releases` for `created` shows that this occurred between 2004 and 2017 with the latest instance occurring 2017-07-03.

I'm +1 to the later "remove the duplicates and enforce database-level uniqueness across the pairings."
