### ISSUE TITLE
unable to change / remove / add new 2FA device

### ISSUE THREAD

**Issue by bjornarfjelldal** [pypi/warehouse#14274]
I am trying to change my 2FA app, however when trying to add a new one, the error is
"Error Account cannot be linked to more than one authentication application at a time". The "remove" option on 2FA app is also greyed.

I removed the creds from my current app, but it didn't impact anything (I didn't think it would either).

Can currently only log in using recovery codes. Tried using one of them as TOTP security key, but it didn't work.

Looks like manual help is needed..?

**Comment by ewdurbin** [comment]
cc @di @ristomcgehee  May be related to recent changes regarding handling of last 2FA method?

**Comment by di** [comment]
I think this is a duplicate of #14257 and will be resolved by #14260.
