### ISSUE TITLE
Resolve requirements without downloading wheels

### ISSUE THREAD

**Issue by fabioz** [pypi/warehouse#14290]
**What's the problem this feature will solve?**

The problem is that I'd like to know whether an environment is valid and which versions would be installed without actually having to download the wheels related to it.

So, I guess I'd like to resolve whether an environment is valid without downloading all the packages. From reading I understood that sometimes this may not be possible because the metadata is not available, but this shouldn't be an impediment (in this cases it can fallback to do the download), but when the metadata is present/available it shouldn't download anything.

**Describe the solution you'd like**

I'd like the following command line:

> python -m pip install --dry-run --ignore-installed --python-version 3.7 --platform win-amd64 --report out.json <requirements>

to work without downloading packages into the cache (and querying the python version/platform expected) -- it could potentially be a different command too instead of pip install with dry-run and report...

**Additional context**

As a context, what I'd like is a way to verify whether the environment is resolvable for a given python version (but without actually downloading such python packages) and that such environment would also be valid in other platforms.

**Comment by di** [comment]
Hi, it seems like what you're describing is https://peps.python.org/pep-0658/, which is partially implemented (see #8254 for updates) and which pip already uses if the metadata is available on PyPI.

Is there something else you're requesting besides what's already planned in that PEP?

**Comment by di** [comment]
If this is a feature request for `pip`, the right place to request that would be at https://github.com/pypa/pip, but it's my understanding that `pip` already supports PEP 658: https://github.com/pypa/pip/pull/11111.

**Comment by di** [comment]
Note that this is only partially implemented for PyPI (see #8254) and so the metadata file is likely not present for all the projects you're attempting to install. You can follow #8254 for progress on that.

**Comment by ddelange** [comment]
On pip side, there is an open PR to fix wheels still being downloaded despite metadata being available on warehouse: https://github.com/pypa/pip/pull/12186#issuecomment-1671050968
