### ISSUE TITLE
Invalid name for valid entry

### ISSUE THREAD

**Issue by hastiin-manuelito** [pypi/warehouse#14341]
**Describe the bug**

I am getting a login failure for invalid username despite my username abiding by the restrictions on the register page.

- My actual full name
- My first name: no trailing space
- My first initial and last name with an underscore and numbers

**Expected behavior**

The site accept my name that follows the restrictions

**To Reproduce**

Fill out the register information and click "create account".

**My Platform**

Android Galaxy Tab A10, newest version

**Additional context**

**Comment by miketheman** [comment]
Please supply what username you have tried and screenshots of the error message.

**Comment by hastiin-manuelito** [comment]
Names: "Derrick Etsitty" "Derrick" "d_etsitty44"

![Screenshot_20230812-150556_Brave](https://github.com/pypi/warehouse/assets/78440845/a43d4393-6c89-4063-a5a6-726b1f2bd866)

**Comment by di** [comment]
Hi @hastiin-manuelito, looks like you're typing your email into the "username" field. Usernames can't contain the `@` symbol.

**Comment by hastiin-manuelito** [comment]
😵
