### ISSUE TITLE
How to obtain a complete dump of the PyPI index, including all associated metadata?

### ISSUE THREAD

**Issue by code2graph** [pypi/warehouse#14359]
**What's the problem this feature will solve?**
We require a metadata dump of all packages consolidated into a single file

**Describe the solution you'd like**
A single file (probably a compressed JSON) dump of metadata for all PyPI packages. Probably in the same format as [JSON API](https://warehouse.readthedocs.io/api-reference/json.html#project) returns, just an aggregation of data for all packages into a single array.

We require a comprehensive metadata dump for all packages available on PyPI. Our ideal format is a JSON file. The structure of this metadata dump should align with the data representation provided by the [JSON API](https://warehouse.readthedocs.io/api-reference/json.html#project). It will be good to have all the metadata included into this json array.

Any alternative is welcome.

**Comment by ewdurbin** [comment]
Please see https://warehouse.pypa.io/api-reference/bigquery-datasets.html#project-metadata-table

**Comment by code2graph** [comment]
Thank you, @ewdurbin. I greatly appreciate your assistance. I'm trying to determine when the package first appeared in the PyPI index. I assume the `upload_time` field indicates when this package was initially uploaded to the PyPI index.

**Comment by nashid** [comment]
@code2graph I had a look into the `distribution_metadata` table. It does not look like

**Comment by di** [comment]
@nashid Not sure what query you used, but the `upload_time` field captures the upload time for each individual artifact. For the `dependency-injector` package:

```sql
SELECT
  version, upload_time
FROM
  `bigquery-public-data.pypi.distribution_metadata`
WHERE
  name = 'dependency-injector'
ORDER BY
  upload_time
```

The table shows results starting in 2015, when the first versions of this package were uploaded:

Row | version | upload_time |  
-- | -- | -- | --
1 | 0.8.1 | 2015-08-31 13:36:47.685350 UTC |  
2 | 0.9.1 | 2015-09-02 21:28:26.450431 UTC |  
3 | 0.9.2 | 2015-09-03 13:01:12.673643 UTC |  
4 | 0.9.3 | 2015-09-03 23:35:01.168325 UTC |  
5 | 0.9.4 | 2015-09-04 07:18:10.956846 UTC |  
6 | 0.9.5 | 2015-09-14 07:53:50.008484 UTC |  
7 | 0.10.0 | 2015-10-23 13:50:17.648398 UTC |  
8 | 0.10.1 | 2015-10-23 14:10:43.720232 UTC |  
9 | 0.10.2 | 2015-10-23 15:08:14.332140 UTC |

I'm going to close this as the BigQuery dataset should have everything you need here.
