### ISSUE TITLE
Bigquery table data.pypi.distribution_metadata  does not contain source url

### ISSUE THREAD

**Issue by code2graph** [pypi/warehouse#14362]
**What's the problem this feature will solve?**
In the json output, it has:
```
        "project_urls": {
            "Bug Reports": "https://github.com/pypa/sampleproject/issues",
            "Funding": "https://donate.pypi.org",
            "Homepage": "https://github.com/pypa/sampleproject",
            "Say Thanks!": "http://saythanks.io/to/example",
            "Source": "https://github.com/pypa/sampleproject/"
        },
```
But source field is missing in the `data.pypi.distribution_metadata` table. It only has homepage.

**Describe the solution you'd like**
It will be good to have the `Source` field in the metadata table dump.

**Comment by di** [comment]
These are available via the [`Project-Url`](https://packaging.python.org/en/latest/specifications/core-metadata/#project-url-multiple-use) metadata field:

```sql
SELECT
  version,
  project_urls
FROM
  `bigquery-public-data.pypi.distribution_metadata`
WHERE
  name = 'sampleproject'
ORDER BY
  version DESC
LIMIT
  1
```

produces:

Row | version | project_urls |  
-- | -- | -- | --
1 | 3.0.0 | Homepage, https://github.com/pypa/sampleproject |  
  |   | Bug Reports, https://github.com/pypa/sampleproject/issues |  
  |   | Funding, https://donate.pypi.org |  
  |   | Say Thanks!, http://saythanks.io/to/example |  
  |   | Source, https://github.com/pypa/sampleproject/ |
