### ISSUE TITLE
`invalid-pending-publisher` when using OIDC to upload 2nd version of package

### ISSUE THREAD

**Issue by NickCrews** [pypi/warehouse#14389]
**Describe the bug**
Not sure if this is a bug, but at least it was unexpected, and the [OIDC Troubleshooting guide](https://docs.pypi.org/trusted-publishers/troubleshooting/) wasn't very helpful.

In [this CI run](https://github.com/NickCrews/feco3/actions/runs/5899323313), I got `Token request failed: the server refused the request for the following reasons: invalid-pending-publisher: valid token, but project already exists`

So, I went ahead and downloaded the .whl files generated from that CI run, and manually uploaded them from my laptop using twine. That worked. I haven't tried again using OIDC to see if it will work again now that I did a fresh upload.

**Expected behavior**
Upload to PyPI should work: The project exists, and I have the OIDC configured correctly.

**To Reproduce**
You can see the workflow file used at https://github.com/NickCrews/feco3/actions/runs/5899323313/workflow.

Screenshot of OIDC config:
<img width="480" alt="image" src="https://github.com/pypi/warehouse/assets/10820686/b915ab55-d4ab-424f-a5b3-350aed944f76">

Here is the complete security audit log for my project (screenshot taken Aug 17, 2023)
<img width="477" alt="image" src="https://github.com/pypi/warehouse/assets/10820686/1617cdf5-7e5a-433d-b844-d89bf5d0bdbd">

Was this something to do with enabling 2FA?

Also, this doesn't show up in the security log, but I thought I remember back in June adding GitHub as a "pending trusted publisher", and then a very similar thing happening, and I think that is why I uploaded v0.3.0 of the project using Twine back in June. Perhaps this was bugging out because of some stale state where PyPI thought that my OIDC registration was pending, when now I don't even see an option int the PyPI webUI to to add pending publishers?

**Comment by di** [comment]
Thanks for the issue! Seems like we have an edge case here where we're not properly converting "pending" publishers if the project gets created via a regular upload instead.

I think this is the timeline of what happened, does this look right to you? 

| Time | Action |
| - | - |
| 2023-06-06 17:45:27 UTC | You created a "pending" publisher for `feco3` |
| 2023-06-06 18:26:53 UTC | You did a manual upload of https://pypi.org/project/feco3/0.3.0/ with `maturin` |
| 2023-06-09 23:38:14 UTC | [This workflow run](https://github.com/NickCrews/feco3/actions/runs/5226857761/job/14150207710) failed with `invalid-publisher: valid token, but no corresponding publisher`
| 2023-08-16 06:12:36 UTC | [This workflow run](https://github.com/NickCrews/feco3/actions/runs/5899323313/job/16001928847) found the pending publisher, [deleted it](https://github.com/pypi/warehouse/blob/99b4b0ff8cbf99ad851216abcc747f8fb01c432e/warehouse/oidc/views.py#L118-L127), and returned the error `invalid-pending-publisher: valid token, but project already exists` |
| 2023-08-17 23:04:35 UTC | [This workflow run](https://github.com/NickCrews/feco3/actions/runs/5896677892/job/15995272066) found no publishers, and returned the error `invalid-publisher: valid token, but no corresponding publisher (All lookup strategies exhausted)`
| 2023-08-18 05:36:35 UTC | You created a regular publisher for `feco3` 
| 2023-08-18 06:38:57 UTC |  You did a manual upload of https://pypi.org/project/feco3/0.5.0/ with `twine` |

I think in the current state future runs of your `CI.yml` workflow should successfully publish without the need to change anything.

> Was this something to do with enabling 2FA?

No, this is unrelated.

> Also, this doesn't show up in the security log, but I thought I remember back in June adding GitHub as a "pending trusted publisher", and then a very similar thing happening, and I think that is why I uploaded v0.3.0 of the project using Twine back in June. Perhaps this was bugging out because of some stale state where PyPI thought that my OIDC registration was pending, when now I don't even see an option int the PyPI webUI to to add pending publishers?

As far as I can tell it appears that you uploaded [v0.3.0](https://pypi.org/project/feco3/0.3.0/) first, and then had a failing workflow run. I couldn't find any runs before that, do you have the CI run which would have corresponded to that prior failure?

I am curious why the first workflow run failed, is it possible something changed with the repository/workflow name?

**Comment by NickCrews** [comment]
That timeline looks right, except it is missing [CI run 29](https://github.com/NickCrews/feco3/actions/runs/5191885069), which ran sometime on 2023-06-06, and failed with `502: Bad Gateway`. Due to run 29 failing, I did the `You did a manual upload of https://pypi.org/project/feco3/0.3.0/ with maturin`, and that worked.

I don't see a precise enough timestamp on that CI run to know if me creating the pending publisher was before or after CI run 29. Maybe I didn't do that first, or maybe I didn't give PyPI enough time for that change to propagate. If I failed to set up the pending publisher beforehand, then run 29 failing was expected. If I set up the pending publisher correctly, then the 502 error might be a symptom of something not working on your end. But I think I set up pending publisher beforehand.

One thing I'm still confused about with your timeline:
Why would [run 52](https://github.com/NickCrews/feco3/actions/runs/5226857761/job/14150207710) fail with one error, and [run 66](https://github.com/NickCrews/feco3/actions/runs/5899323313/job/16001928847) fail with a different error. 52 didn't delete the pending publisher or make any state changes (did it?), so what was the difference between these two runs?

> we're not properly converting "pending" publishers if the project gets created via a regular upload instead.

That sounds like a very probable explanation. Have you looked at the code to see if this is possible, or just a hunch? This explanation still doesn't explain my above confusion.

Anyway, I would say the action is to explore the above possible bug, and then if we don't have any other explanation, close this. If it works for me in the future, I'm happy :)

**Comment by woodruffw** [comment]
If I'm understanding the flow of actions correctly here, I _think_ it makes sense that the pending publisher wasn't converted here: a user (A) who manually uploads a project might not be aware of another user (B) who's registered a pending publisher for that project name, so converting it could either result in a surprise publisher for A or unintended publishing access for B.

We could probably carve out a subset of cases here: if the package is manually uploaded by the same user who has the pending publisher registered, then it's probably safe to reify that pending publisher into a normal one. 

(I don't have a good explanation for the order in which you saw these errors yet, either 😅)

**Comment by di** [comment]
Ah, that makes sense if you got a 502 the first time (that could have been due to an error on our end that since got fixed). I'm still curious why "run 52" failed as well, that's what I was asking about here:

> I am curious why the first workflow run failed, is it possible something changed with the repository/workflow name?

If you renamed the repo or the workflow file, that might explain it, otherwise I'm not sure why. The rest of the progression of errors makes sense, though.

**Comment by di** [comment]
> We could probably carve out a subset of cases here: if the package is manually uploaded by the same user who has the pending publisher registered, then it's probably safe to reify that pending publisher into a normal one.

Yes, I think that's the fix that we should implement here.

**Comment by NickCrews** [comment]
> is it possible something changed with the repository/workflow name?

The repo never changed name. The workflow file was called `CI.yml` since [the first commit](https://github.com/NickCrews/feco3/commit/0f7e3452dbc9e9c70b91cacfed8b97b94abc1283), which is what PyPI expected as the pending publisher (see my screenshot of the security log). I only [recently added the `environment: release` to the workflow](https://github.com/NickCrews/feco3/commit/16f0f3350156a21f535bba1f786311bdfa9b4f26), but I can't see from the security log whether or not PyPI was expecting a release environment or if I never configured that. Maybe you can see that from your more detailed logs? That could explain why run 52 failed.

**Comment by di** [comment]
Hi @robertdj, it's still unfixed. Can you tell us what project you tried to publish so we can verify this is the same issue you're having? What error messages did you get?

**Comment by di** [comment]
Thanks, looks to be the same. Just curious, why did you try and do a manual upload after configuring trusted publishing?

**Comment by robertdj** [comment]
It's the first time I'm publishing a package so I followed a guide that showed how to do this with twine. I went for TestPyPI first. When that succeeded I looked into automate publishing with GitHub Actions.
 
I have only uploaded manually that first time.

**Comment by woodruffw** [comment]
Thinking about the fix here: we want to reify the pending publisher if (1) the project exists and (2) it's already owned by the person with the pending publisher.

There are at least two places we could do this: we could do it in the `mint_token_from_oidc` view handler itself, or in `legacy.file_upload`. Doing it in `mint_token_from_oidc` keeps all of the pending publisher state close together, but will complicate the logic slightly (since the pending case will no longer unconditionally create an empty project). Doing it in `file_upload` makes the logic slightly simpler, but spreads it out.

Thoughts @di @miketheman?

**Comment by robertdj** [comment]
Hi @woodruffw 

I searched for "publish on pypi" and found the page <https://packaging.python.org/en/latest/tutorials/packaging-projects/>

**Comment by ChemGuy88** [comment]
Hi, I think I have the same problem as others here. This was also my first time publishing a package, and I did so manually, since I was following [this Real Python guide](https://realpython.com/pypi-publish-python-package/#upload-your-package). You can see my GitHub Action log [here](https://github.com/ChemGuy88/DRAPI-Lemur/actions/runs/7821107635/job/21337365275).

I'm currently stuck, now quite sure what to do. Thanks!

**Comment by di** [comment]
This particular bug has been resolved -- if you've arrived here and think you're experiencing something similar, [please open a new issue](https://github.com/pypi/warehouse/issues/new/choose).
