### ISSUE TITLE
The download number of Python-EasyGraph library is not consistent with the information from https://www.pepy.tech/projects/Python-easyGraph

### ISSUE THREAD

**Issue by mgao97** [pypi/warehouse#14418]
Please correct the download number of Python-EasyGraph library https://pypi.org/project/Python-EasyGraph/
![image](https://github.com/pypi/warehouse/assets/90015105/f077a632-21f5-4bc2-8c0a-82822d970cb8)

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.

**Comment by mgao97** [comment]
So you mean the Python-EasyGraph library itself?
