### ISSUE TITLE
PyPi can't find my library

### ISSUE THREAD

**Issue by wkillus** [pypi/warehouse#14433]
![IMG_20230826_025004](https://github.com/pypi/warehouse/assets/139456748/5bd84f7f-f0b7-4b52-8d76-972682773da4)
Hello! In PyPi Can't find my library, posted 9 hours ago.  Even after that it doesn't find my library.  If you know the solution - please help me!

**Comment by miketheman** [comment]
The search index might not recognize that the aa is not a typo.

The project is located at https://pypi.org/project/AaioAPI/ directly.

**Comment by wkillus** [comment]
> The search index might not recognize that the aa is not a typo.
> 
> The project is located at https://pypi.org/project/AaioAPI/ directly.

So do I need to rename my library?

**Comment by miketheman** [comment]
Nope, looks like it was an index latency issue, the library can now be found via search: https://pypi.org/search/?q=aaioapi
