### ISSUE TITLE
Recaptcha error if I register an account.

### ISSUE THREAD

**Issue by s0rmayz** [pypi/warehouse#14519]
### Are there somebody can help me with this?

**Comment by s0rmayz** [comment]
**I just want to upload my package**

**Comment by s0rmayz** [comment]
Just, can you cancel it or use another method? I think its not friendly to chinese.

**Comment by s0rmayz** [comment]
@di can you repair it?

**Comment by di** [comment]
Hi @s0rmayz, sorry you're having trouble here. We've tried a few workarounds on our end for this over the years (#13350, #3174), but looks like this has stopped working again.

If you can provide us with your email address and desired username, we can set up an account for you.

**Comment by s0rmayz** [comment]
@di RRRRRRRRRRRReally?
