### ISSUE TITLE
Can't register a nitrokey 3 security key as 2FA

### ISSUE THREAD

**Issue by fabien-michel** [pypi/warehouse#14520]
**Describe the bug**

Trying to add a nitrokey 3 for 2 factors auth from account configuration raise a `Unsupported credential public key type "OKP"` error.

Tried with both nitrokey 3A and nitrokey 3 mini.

The same keys works with Github, Google and Microsoft for 2FA auth.

**My Platform**
* Os: Arch
* Browser: Firefox 117

**Comment by di** [comment]
This error comes from our dependency on `py_webauthn`: https://github.com/duo-labs/py_webauthn/blob/56acd35480b7fc355499e9458931dc31476ec08f/webauthn/helpers/decode_credential_public_key.py#L116

The key types that library supports are listed [here](https://github.com/duo-labs/py_webauthn/blob/56acd35480b7fc355499e9458931dc31476ec08f/webauthn/helpers/cose.py#L35-L45), and there is some existing discussion about this issue [here](https://github.com/duo-labs/py_webauthn/issues/160#issuecomment-1679113276). 

I've submitted a new issue about this here: https://github.com/duo-labs/py_webauthn/issues/175

**Comment by fabien-michel** [comment]
I've tried from Chromium and I  am able to add the security keys.
Fun fact: after that, I am able to connect to pypi account using the keys from Firefox !

**Comment by di** [comment]
As far as I can tell this is a bug or issue in Firefox, here's where Chrome expects the `kty` field of the JWK to be `OKP`:

https://github.com/chromium/chromium/blob/638018f724c52a7b8bf1aca4fe76b6a18fffc542/components/webcrypto/algorithms/x25519.cc#L315-L326

I'm not sure if there's anything we can do here besides recommend using a different browser to register the security key in question.

**Comment by fabien-michel** [comment]
[Problem seems resolved in firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1852812). I can't reproduce with latest nightly.

**Comment by APN-Pucky** [comment]
I get the same error on test.pypi.org with NK3 + Firefox 115.10.0. Chrome 124.0.6367.118 worked however.
