### ISSUE TITLE
Author text is overflowing on some PyPI project pages

### ISSUE THREAD

**Issue by samlader** [pypi/warehouse#14548]
**Describe the bug**
The author text on **some** PyPI project pages is overflowing and not displaying correctly.

**Expected behavior**
The author text should be displayed without overflowing and should be fully visible on the project page.

**To Reproduce**

- Go to the following PyPI project page: https://pypi.org/project/transformers/.
- Scroll down to the "Author" section of the page.

My Platform

Browser: Google Chrome version 116.0.5845.187
Operating System: macOS Ventura (13.4.1)

I have also reproduced  this bug when visiting the page in Safari.

**Additional context**
It would be helpful to have this issue resolved to improve the readability of the PyPI website.

I'm happy to submit a PR to fix this, once this issue has been triaged.

![Screenshot 2023-09-12 at 23 57 08](https://github.com/pypi/warehouse/assets/6299632/604ffb52-803d-4210-9fee-10866411fda0)

**Comment by di** [comment]
Thanks for the report, this is now fixed: https://pypi.org/project/transformers/
