### ISSUE TITLE
No files into test.pypi.org/simple

### ISSUE THREAD

**Issue by Ribeiro-Breno** [pypi/warehouse#14569]
**Describe the bug**
I'm trying to create a package using testPyPI. Until version 0.0.4 the files were succesfully uploaded and installed into my machine. From version 0.0.5 when I try to install this version a error message returns "No matching distribution found for example-package-ribeiro-breno==version", even using the presented link for testPyPI. Looking for the files at `https://test.pypi.org/simple/example-package-ribeiro-breno/` I only find files for versions until 0.0.4. The files for versions 0.0.5+ can be download from test.pypi.org, but they can't be installed.

**Expected behavior**
Expect to be able to install the latest version of my package

**To Reproduce**
link for my last version: https://test.pypi.org/project/example-package-ribeiro-breno/0.0.10/
link for test.pypi.org/simple: https://test.pypi.org/simple/example-package-ribeiro-breno/

**My Platform**
Windows 10
Chrome
VSCode

**Additional context**
No additional context

**Comment by miketheman** [comment]
Hi @Ribeiro-Breno ! Looks like you're hitting up against some caching slowness in TestPyPI. I've kicked a few containers to restart the processing.

The project should be displaying correctly now.

**Comment by ewdurbin** [comment]
Seems relate to #14572. It seems dd-trace is once again interfering with worker health.

We run fewer workers in test-pypi which probably led to them all being dropped sooner.

**Comment by Ribeiro-Breno** [comment]
Thank you, guys, it worked now!
