### ISSUE TITLE
Package types-setuptools are missing from pypi.org/simple

### ISSUE THREAD

**Issue by vhaldemar** [pypi/warehouse#14561]
**Describe the bug**
Package `types-setuptools` are missing from `pypi.org/simple` and returns 404:
https://pypi.org/simple/types-setuptool/ while it preset at pypi itself: https://pypi.org/project/types-setuptools

**Expected behavior**
https://pypi.org/simple/types-setuptool shouldn't return 404.

**Comment by di** [comment]
You have a typo, it's https://pypi.org/simple/types-setuptools/ not https://pypi.org/simple/types-setuptool/

**Comment by vhaldemar** [comment]
> You have a typo, it's https://pypi.org/simple/types-setuptools/ not https://pypi.org/simple/types-setuptool/

Sorry, thanks!
