### ISSUE TITLE
Recently updated packages install with a new folder packagename.libs instead of .libs being a subfolder

### ISSUE THREAD

**Issue by Rob-Hulley** [pypi/warehouse#14573]
I am not sure if this is a PyPI issues or all the package owners are doing the same error.
Packages I have updated with this problem are: numpy, pandas, pyzmq, scipy, tables
ls *.libs
numpy.libs:
libopenblas64__v0.3.23-293-gc2f4bdbb-gcc_10_3_0-65e29aac85b9409a6008e2dc84b1cc09.dll

pandas.libs:
msvcp140-59fdf63e48138046aebeb6ddb5b4e960.dll

pyzmq.libs:
concrt140.dll                      libsodium-ac42d648.dll             libzmq-v141-mt-4_3_4-0a6f51ca.dll  msvcp140.dll

scipy.libs:
libopenblas_v0.3.20-571-g3dec11c6-gcc_10_3_0-c2315440d6b6cef5037bad648efc8c59.dll

tables.libs:
blosc-52e1ff56f1a5ae0531ae8326d175da77.dll      libblosc2-171ab9f2f622b856eb94dddf2a28406a.dll  zlib-d55e36628eb318a855472f2ea826ce0a.dll
hdf5-88ac2abe3f783f62fe1ac08e0d2d7861.dll       libbz2-d45ea5379d1c948c2f52ea3a157cbb9c.dll     zstd-98dcac8fb8d1da204d03ddce5283b502.dll

When I check the RECORD file there is a difference between the old and new version.
The slash "/" before .libs is missing.

eg:
1.25.2
numpy-1.25.2.dist-info/top_level.txt,sha256=4J9lbBMLnAiyxatxh8iRKV5Entd_6-oqbO7pzJjMsPw,6
numpy/.libs/libopenblas64__v0.3.23-246-g3d31191b-gcc_10_3_0.dll,sha256=h1zxwNoqsy37O71f1cIatss1Z55NPAqfX8vnDtvL6Wk,38166567

1.26.0
numpy-1.26.0.dist-info/entry_points.txt,sha256=zddyYJuUw9Uud7LeLfynXk62_ry0lGihDwCIgugBdZM,144
numpy.libs/libopenblas64__v0.3.23-293-gc2f4bdbb-gcc_10_3_0-65e29aac85b9409a6008e2dc84b1cc09.dll,sha256=7A4P0sKw5BzY-9HJHVGFxvAMPRhJyscxBvLVoxoB56k,38168576

pandas is the same.
pandas-2.1.0.dist-info/entry_points.txt,sha256=OVLKNEPs-Q7IWypWBL6fxv56_zt4sRnEI7zawo6y_0w,69
pandas.libs/msvcp140-59fdf63e48138046aebeb6ddb5b4e960.dll,sha256=7FK3VWFW3K6unFY4IOM-PV5H1NFinMeJpX1YtxDYoPw,621960
[numpy-1.26.0.dist-info.zip](https://github.com/pypi/warehouse/files/12644599/numpy-1.26.0.dist-info.zip)
[numpy-1.25.2.dist-info.zip](https://github.com/pypi/warehouse/files/12644600/numpy-1.25.2.dist-info.zip)

Every think works OK except I use pynsist to create packages to give to others and the folder structure causes errors.

Hope you can help

Thanks
Rob

**Comment by miketheman** [comment]
Hi Rob,

Thanks for reporting - this is better reported to the project trackers directly, as this is a build-time issue, not a PyPI one. PyPI is serving the archived packages they generate.

**Comment by Rob-Hulley** [comment]
Thanks Mike,

To complete the solution.
To fix the pynsist errors you need to include these packages as wheels.
e.g.
[Include]
# Packages from PyPI that your application requires, one per line
# These must have wheels on PyPI:
pypi_wheels:
 pywin32==306
 numpy==1.26.0
 pandas==2.1.0
 tables==3.8.0

Regards

Rob
