### ISSUE TITLE
Adding PyPI Trusted Publisher note about repository entry case-sensitivity

### ISSUE THREAD

**Issue by d33bs** [pypi/warehouse#14622]
**What's the problem this feature will solve?**
I recently noticed that adding a GitHub-based Trusted Publisher for PyPI was case sensitive for the repository name. The same might be for the owner field, but I have not tested this.

I wondered if other people might run into the same without some kind of notice within the documentation [here](https://github.com/pypi/warehouse/blob/main/docs/user/trusted-publishers/adding-a-publisher.md) and [here](https://docs.pypi.org/trusted-publishers/creating-a-project-through-oidc/). It also might be that adding a note to PyPI itself for these fields could be helpful in avoiding this challenge (perhaps something like `(case-sensitive)` added to the text field default suggestion or the labeling nearby).

**Describe the solution you'd like**
I'd like to see a note and/or a somehow highlighted indication that the `repository` field for Trusted Publisher additions within PyPI are case-sensitive. The same might be included for the `owner` field if this holds true there as well.

**Additional context**
GitHub appears to automatically re-route or have some way to transcribing relationships to organizations and repository names which use capitalizations. For example, https://github.com/PyCQA/bandit links to the same place as https://github.com/pycqa/bandit. One can also use capitalizations (or not) where they wish and still be routed to the same location, for example https://github.com/python/cpython links to the same place as https://github.com/Python/CPython . Despite GitHub not being authoritative for PyPI's standards, this might be cause for confusion when it comes to PyPI integration with GitHub.

**Comment by di** [comment]
Thanks, it should be case-insensitive, https://github.com/pypi/warehouse/pull/14623 will fix this.

**Comment by d33bs** [comment]
Thank you @di !
