### ISSUE TITLE
Update documentation for PEP 691

### ISSUE THREAD

**Issue by gsnedders** [pypi/warehouse#14644]
**Describe the bug**
The documentation claims the simple API is legacy (c.f. https://warehouse.pypa.io/api-reference/legacy.html)

**Expected behavior**
The documentation matches the implementation, which no longer considers the simple API as legacy (c.f. https://github.com/pypi/warehouse/pull/11676). Additionally, it should document the PEP 691 implementation, rather than pushing people to use the (non-standard?) legacy JSON API.

**To Reproduce**
Load the documentation.

**My Platform**
N/A

**Additional context**

**Comment by woodruffw** [comment]
#16541 should address this: we now consistently refer to the 503/691 APIs as the "Index APIs" or "simple APIs."
