### ISSUE TITLE
Latest `types-requests` breaks deps build, surfaces urllib3 chain issue

### ISSUE THREAD

**Issue by miketheman** [pypi/warehouse#14671]
The latest `types-requests` package removes a dependency on `types-urllib3`, and the typeshed has completely removed `urllib3` types from the shed, since they are available in 2.0.x series.
https://github.com/python/typeshed/pull/10812

We are unable to upgrade to urllib3 yet, as some other tools pin to lower than 2.x

- [x] botocore https://github.com/boto/botocore/blob/fcad88429eebfb3024be80e2700648c4a357ca16/setup.py#L28 - see https://github.com/pypi/warehouse/pull/14747
- [x] elasticsearch (we're pinned to 7.10.1 that requires `<2`, and even up to 7.17.9 https://github.com/elastic/elasticsearch-py/blob/deccbb732f17eee0937b7ec5980792849a2393d4/setup.py#L55 )

I'll pin urllib3 to <2 to resolve a lot of these chains until we can resolve the above.

**Comment by di** [comment]
Looks like `elasticsearch==8.x.x` supports `urllib3<3`: https://github.com/elastic/elasticsearch-py/issues/2216

But we're pinned back: https://github.com/pypi/warehouse/blob/56f0f6c719809564de44dbca18dff967d69930ac/requirements/main.in#L16
