### ISSUE TITLE
2FA with USB key always fails with "This field is required."

### ISSUE THREAD

**Issue by kennknowles** [pypi/warehouse#14690]
**Describe the bug**

I registered a USB Titan security key to my pypi account. It seemed to go smoothly. When I attempt to use it to log in, I get the following:

![image](https://github.com/pypi/warehouse/assets/575353/9f1cd353-f917-4352-a1e0-ba82fa9966fe)

I have tried this with another Titan key with the same result.

**Expected behavior**

I expect to log in via USB titan key.

**To Reproduce**

I cannot determine if there are steps to reproduce or if it is isolated to my account.

**My Platform**

Browser is Chrome `Version 117.0.5938.132 (Official Build) (x86_64)`

**Additional context**

Recovery codes work, and I did get an authenticator app to work as well, FWIW. I've removed and re-added the security key(s) a few times just to be sure.

**Comment by woodruffw** [comment]
Thanks for the report @kennknowles, and sorry for the regression. 

Possible regression point: https://github.com/pypi/warehouse/pull/14674

**Comment by woodruffw** [comment]
Fixpoint: #14691.

**Comment by miketheman** [comment]
@kennknowles fix is live, please confirm when you get a chance!

**Comment by kennknowles** [comment]
Awesome! It worked.
