### ISSUE TITLE
Invalid TOTP code. Try again?

### ISSUE THREAD

**Issue by dreamcode1994** [pypi/warehouse#14697]
**Describe the bug**
 Invalid TOTP code. Try again?

**Expected behavior**
2 FA Should Work on Entering Correct Code 

**To Reproduce**
* Create New Account
* Try To Enable 2FA 
*  Every time i am getting  "Invalid TOTP code. Try again?"
*  

**System Details**
    * Browser : Chrome
    * OS: Ventura 13.4
    *  Platform: MAC M1 pro

**Additional context**

* My Mobile Timing is also in sync.
* Happening For    both test account(test.pypi.org) as well as main account(* pypi.org)
*Tried Below Apps for Generating Authentication Codes
1. Google Authenticator
2. Microsoft Authenticator
3. Duo 

Attachments:
<img width="1728" alt="Screenshot 2023-10-05 at 2 19 10 PM" src="https://github.com/pypi/warehouse/assets/118388087/8bdf162f-0dd8-4a35-bcea-3c56747f376c">

**Comment by di** [comment]
Closing this in favor of https://github.com/pypi/warehouse/issues/14710, which is a newer issue but where most of the discussion about this has been happening.
