### ISSUE TITLE
Name transfer for apparently abandoned project "mm"

### ISSUE THREAD

**Issue by aivazis** [pypi/warehouse#14711]
The existing `mm` project on `pypi` appears abandoned. I have attempted to contact the project maintainer without success and the project homepage is non-existent.

I have been developing a python-based build system by this name since 1994. The project moved to Github in 2018 (see GitHub.com/aivazis/mm). It is used as the build system for a handful of projects, most notably `pyre` (GitHub.com/pyre/pyre), a project that is already available on `pypi`. Historically, users were comfortable accessing the build system from whichever source control system was hosting, but the class of user is about to change as `pyre`, and a number of projects that use it, are about to become available on a cloud based on-demand system for a NASA mission. The de facto installation tool for python packages is `pip`, so it would be important to provide access to `mm` through `pypi`.

Looking forward to your comments.

**Comment by di** [comment]
Please see https://pypi.org/help/#project-name-claim.
