### ISSUE TITLE
Project Details Sidebar Statistics behavior

### ISSUE THREAD

**Issue by miketheman** [pypi/warehouse#14727]
Eventually replace it with a new statistics sidebar that does the following:

* if trusted publishing from GitHub has been used for the release:
  * include the URL of the upstream repository (https://github.com/pypi/warehouse/issues/10917)
  * fetch statistics for the repository that trusted publishing is configured for
  * mark the statistics as "verified via Trusted Publishing", with a link
* if trusted publishing was not used, and a GitHub URL was provided in the metadata (e.g., we would currently show statistics):
  * don't fetch the statistics
  * instead, include a message + provide a link that indicates that trusted publishing should be used to enable GitHub statistics

_Originally posted by @di in https://github.com/pypi/warehouse/pull/14657#discussion_r1349338677_

**Comment by lukehinds** [comment]
Please also expose this information via the API, something like `trusted_published: true` will do.

**Comment by VigneshVSV** [comment]
I dont use trusted publishing from Github (at least as far as I know) to publish my package. There's just a Github action now that uploads using my account's API key. Is this the reason why I dont see Github statistics on my package? (https://pypi.org/project/hololinked/) 

When I uploaded the first version of my package using python command line tools, there was not a problem in showing the Github statistics. It has only recently disappeared, although visible for other repositories (i.e. seems to be an issue with my repository only and not the webpage itself).
