### ISSUE TITLE
Since you force the 2 factor Authentification, I cannot upload anymore into PYPI

### ISSUE THREAD

**Issue by Laurent-Tupin** [pypi/warehouse#14762]
**I cannot upload into PYPI anymore
When I type: 
twine upload dist/*

I put the username:
__token__

And the password as your tutorial told me to:
pypi-{token_code}

this is the answer I got:
WARNING  Your password contains control characters. Did you enter it correctly?
WARNING  See https://twine.readthedocs.io/#entering-credentials for more information.
Uploading py2nut-4.2.1-py3-none-any.whl
100% ---------------------------------------- 125.0/125.0 kB • 00:00 • ?
WARNING  Error during upload. Retry with the --verbose option for more details.
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
         Invalid or non-existent authentication information. See https://pypi.org/help/#invalid-auth for more
         information.

I already arrives at this point after too much time to adapt to this new process. 
All of this to not even work.**

**Please go back to a normal system that actually works and that is profitable to everyone. Dont force change on work that would takes many hours of solving **

**Comment by di** [comment]
Did you see this warning?

> WARNING Your password contains control characters. Did you enter it correctly?
> WARNING See https://twine.readthedocs.io/#entering-credentials for more information.

Your PyPI API token should definitely not contain control characters, so it's likely you're entering it incorrectly.

**Comment by Laurent-Tupin** [comment]
Hello, I have the solution.
CMD window is not authorizing Password PASTE
On the CMD window, you click on the top left icon and clic on 
  - Properties
  - Check 'Use Ctl+Shift+C/V as Copy/Paste'
And you will be able to PASTE your very long TOKEN password into a CMD window.
The upload worked fine after that.

**Comment by Laurent-Tupin** [comment]
close
