### ISSUE TITLE
testpypi Upload Fails With Error "Service Unavailable"

### ISSUE THREAD

**Issue by eehlers** [pypi/warehouse#14780]
**Describe the bug**
When I attempt to upload a wheel to test pypi, the operation fails with the error message "Service Unavailable".

**Expected behavior**
I would expect the operation to succeed.

**To Reproduce**
This is the command that I am using:

    python -m twine upload --verbose --repository test open_source_risk_engine-1.8.11.1-cp39-cp39-win_amd64.whl

I append the output to the bottom of this bug report.

**My Platform**
I attempted this on Windows 11 and Ubuntu 20.04.

**Additional context**

Again, here is the command that I am running:

    python -m twine upload --verbose --repository test open_source_risk_engine-1.8.11.1-cp39-cp39-win_amd64.whl

Below is the output.  It gives me a link to twitter.com but that web site does not exist.  It also refers me to https://status.python.org but that page indicates that all services are running.  Any idea what I'm doing wrong?

    INFO     Using configuration from C:\Users\username\.pypirc
    Uploading distributions to https://test.pypi.org/legacy/
    INFO     open_source_risk_engine-1.8.11.1-cp39-cp39-win_amd64.whl (20.8 MB)
    INFO     username set from config file
    INFO     password set from config file
    INFO     username: __token__
    INFO     password: <hidden>
    Uploading open_source_risk_engine-1.8.11.1-cp39-cp39-win_amd64.whl
    100% ---------------------------------------- 21.8/21.8 MB • 00:17 • 1.4 MB/s
    WARNING  Received "503: Service Unavailable"
             Package upload appears to have failed. Retry 1 of 5.
    Uploading open_source_risk_engine-1.8.11.1-cp39-cp39-win_amd64.whl
    100% ---------------------------------------- 21.8/21.8 MB • 00:17 • 1.4 MB/s
    WARNING  Received "503: Service Unavailable"
             Package upload appears to have failed. Retry 2 of 5.
    Uploading open_source_risk_engine-1.8.11.1-cp39-cp39-win_amd64.whl
    100% ---------------------------------------- 21.8/21.8 MB • 00:17 • 1.4 MB/s
    WARNING  Received "503: Service Unavailable"
             Package upload appears to have failed. Retry 3 of 5.
    Uploading open_source_risk_engine-1.8.11.1-cp39-cp39-win_amd64.whl
    100% ---------------------------------------- 21.8/21.8 MB • 00:17 • 1.4 MB/s
    WARNING  Received "503: Service Unavailable"
             Package upload appears to have failed. Retry 4 of 5.
    Uploading open_source_risk_engine-1.8.11.1-cp39-cp39-win_amd64.whl
    100% ---------------------------------------- 21.8/21.8 MB • 00:17 • 1.4 MB/s
    WARNING  Received "503: Service Unavailable"
             Package upload appears to have failed. Retry 5 of 5.
    INFO     Response from https://test.pypi.org/legacy/:
             503 Service Unavailable
    INFO     <!DOCTYPE html>
             <html lang="en">
               <head>
                 <meta charset="utf-8">
                 <meta http-equiv="X-UA-Compatible" content="IE=edge">
                 <meta name="viewport" content="width=device-width, initial-scale=1">
    
                 <meta name="defaultLanguage" content="en">
                 <meta name="availableLanguages" content="en">
    
                 <title>Service Unavailable (503)</title>
    
                 <meta name="description" content="The Python Package Index (PyPI) is a repository of software for the
             Python programming language.">
    
                 
                 <link rel="stylesheet"
             href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400italic,600,600italic,700,700italic|Source
             +Code+Pro:500">
    
                 <style>
                   html,
                   body {
                     box-sizing: border-box;
                     font-family: 'Source Sans Pro', 'Helvetica', Arial, sans-serif;
                     font-size: 17px;
                     line-height: 1.4;
                     font-weight: 300;
                     color: #fff;
                     -webkit-text-size-adjust: 100%;
                     font-size: 100%;
                     padding: 0;
                     margin: 0;
                   }
    
                   h1, strong {
                     font-weight: 600;
                   }
    
                   ul {
                     list-style-type: none;
                     padding-left: 0;
                   }
    
                   hr {
                     margin: 50px auto;
                     width: 300px;
                     max-width: 100%;
                     border: 0;
                     height: 2px;
                     background: rgba(255, 255, 255, 0.5);
                   }
    
                   .viewport-section {
                     height: 100vh;
                     display: flex;
                     align-items: center;
                     justify-content: center;
                     background-color: #006dad;
                     color: #fff;
                   }
    
                   .viewport-section a {
                     color: #fff;
                   }
    
                   .viewport-section__content {
                     text-align: center;
                     padding: 30px;
                     min-width: 0;
                   }
    
                   .viewport-section__heading {
                     font-size: 2.4em;
                     padding: 20px 15px 0;
                     margin: 0;
                   }
    
                   @media screen and (max-width: 600px) {
                     .viewport-section__content {
                       padding: 15px;
                     }
    
                     .viewport-section__heading {
                       font-size: 1.5em;
                     }
                   }
                 </style>
    
               </head>
    
               <body>
                 <div class="viewport-section">
                   <div class="viewport-section__content">
                     <img alt="PyPI logo"
             src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NS44MTIiIGhlaWd
             odD0iNTgiIHZpZXdCb3g9IjAgMCA2NS44MTIwMzUgNTguMDAwMDAxIj48ZyBmaWxsPSIjYTI5ZDg2IiBzdHJva2U9IiNjY2MiIHN0cm9rZS13a
             WR0aD0iLjIxNCIgc3Ryb2tlLWxpbmVqb2luPSJiZXZlbCI+PHBhdGggZD0iTTE4LjkzIDE4LjgyNmw5LjMyMyAzLjM5NHYxMC45NTdsLTkuMzI
             wNC01LjIwNnoiIGZpbGw9IiMyZjY0OTEiLz48cGF0aCBkPSJNMjY0MC43NzIgODAzLjM3NHYxNi44MTFsMTQuNTE1LTUuMjgzdi0xNi44MTF6I
             iBmaWxsPSIjMzc3NWE5Ii8+PHBhdGggZD0iTTI2MjYuNDY4IDc5OC4xNjhsMTQuMzA0IDUuMjA2djE2LjgxMWwtMTQuMzA0LTUuMjA2eiIgZml
             sbD0iIzJmNjQ5MSIvPjwvZz48Y2lyY2xlIHRyYW5zZm9ybT0ic2tld1koLTIwKSBzY2FsZSguOTM5NyAxKSIgY3k9IjE3NzIuOTIyIiBjeD0iM
             jgxNi4wMTciIHI9IjIuOTY3IiBmaWxsPSIjZmZmIi8+PC9nPjwvc3ZnPg==">
                     <h1 class="viewport-section__heading">Sorry, something went wrong</h1>
    
                     <div class="viewport-section__text">
                       <p>PyPI is down for maintenance or is having an outage.</p>
                       <p>
                         This is affecting several of our services, including our web interface.</br>
                         If you are trying to install a package, you should be able to <strong>pip install</strong>
             packages without problem.
                       </p>
    
                       <ul class="unstyled">
                         <li><a href="https://status.python.org/">Check our status page</a>, or</li>
                         <li><a href="https://twitter.com/PythonStatus">View Python Status on Twitter</a></li>
                       </ul>
    
                       <hr>
    
                       <p>
                         <strong>
                           Rely on PyPI to get your job done?</br>
                           Consider <a href="https://github.com/pypa/warehouse">contributing</a> or <a
             href="https://psfmember.org/civicrm/contribute/transact?reset=1&id=13">donating</a> to help us build a more
             stable and secure platform.
                         </strong>
                       </p>
                     </div>
                   </div>
                 </div>
               </body>
             </html>
    
    ERROR    HTTPError: 503 Service Unavailable from https://test.pypi.org/legacy/
             Service Unavailable

**Comment by di** [comment]
Hi, looks like you experienced a brief outage we had, this should be resolved now. Feel free to comment if it is still not working for you.
