### ISSUE TITLE
Can't create new account on (test) pypi.org, username invalid

### ISSUE THREAD

**Issue by MaximilianHauser** [pypi/warehouse#14790]
![AccountCreation](https://github.com/pypi/warehouse/assets/113019206/d805ed85-4162-4ebe-8cf6-4fdd8d63cfee)

I'm trying to create an account on https://test.pypi.org/ , to familiarize myself with the process of uploading a package.

No matter what I enter as username, mail or password, it is never successfully created, and I get the error message shown above, that my username is invalid and it may only contain letters, numbers, dots, hyphen, underscores and it has to begin and end with either a letter or a number. I may please choose a different username.

My username is within the described constraints. (same result for only letters, for example)

**Comment by di** [comment]
Hi @MaximilianHauser, sorry you're having trouble. It doesn't look like you've put anything in the "Username" field, just the "Name" field, which should be your name, like `Maximilian Hauser`.

**Comment by MaximilianHauser** [comment]
I didn't look at the thing properly, as autocomplete filled out the form, putting my email in the username field, my brain registered the field as the repeat your email address field. Fields are empty, because I removed the email in paint.
My brain was mushy. Sorry for taking up your time.
