### ISSUE TITLE
403 Invalid or non-existent authentication information error when uploading package using twine

### ISSUE THREAD

**Issue by MilesMilesFrissons** [pypi/warehouse#14826]
I am attempting to upload my Python package to PyPI using twine, but consistently receive the error: 403 Invalid or non-existent authentication information. I've checked the following:

Verified the correctness of my PyPI username and password.
Checked for any trailing or leading characters in my credentials.
If using API token:
Ensured the token is valid and has not been revoked.
Made sure it's correctly formatted without extraneous characters.
Used __token__ as the username in the .pypirc file.
Double-checked that I'm targeting the right PyPI instance (https://pypi.org).
Made sure I'm pasting credentials correctly in the Windows Command Prompt.
Despite these checks, the error persists. I am using Python 3.11 and the latest version of twine.

Please advise on how I can resolve this issue. I've attached relevant (and non-sensitive) logs and the structure of my .pypirc file (with sensitive info redacted) for reference.

```shellsession
PS C:\Users\mairu\OneDrive\Desktop\Projects\FractalFrissons\Python Package Project> twine upload --verbose dist/*
INFO     Using configuration from C:\Users\mairu\.pypirc
Uploading distributions to https://upload.pypi.org/legacy/
INFO     dist\fractalpackage-1.0.0-py3-none-any.whl (1.5 KB)
INFO     dist\fractalpackage-1.0.0.tar.gz (1.1 KB)
INFO     username set from config file
INFO     password set from config file
INFO     username: __Token__
INFO     password: <hidden>
Uploading fractalpackage-1.0.0-py3-none-any.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 kB • 00:00 • ?
INFO     Response from https://upload.pypi.org/legacy/:
         403 Invalid or non-existent authentication information. See
         https://pypi.org/help/#invalid-auth for more information.
INFO     <html>
          <head>
           <title>403 Invalid or non-existent authentication information. See
         https://pypi.org/help/#invalid-auth for more information.</title>
          </head>
          <body>
           <h1>403 Invalid or non-existent authentication information. See
         https://pypi.org/help/#invalid-auth for more information.</h1>
           Access was denied to this resource.<br/><br/>
         Invalid or non-existent authentication information. See
         https://pypi.org/help/#invalid-auth for more information.


          </body>
         </html>
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
         Invalid or non-existent authentication information. See
         https://pypi.org/help/#invalid-auth for more information.
```

## Structure of .pypirc file
```
[pypi]
username = __Token__
password = pypi-api-token
```

**Comment by di** [comment]
Is your configured username `__token__` or `__Token__`?

**Comment by FastFingertips** [comment]
Use right click when pasting the token

**Comment by yashksaini-coder** [comment]
Similarly for me and after searching around the net for 2 days and trying every means and method also using another packages. Still ended up no good results
