### ISSUE TITLE
PyPi Marked a newer `0.0.4` release as a older, previous was `0.0.39`

### ISSUE THREAD

**Issue by 0x96e63** [pypi/warehouse#14851]
**Describe the bug**
When attempting to release version 0.0.4 of my library, following version 0.0.39, PyPI erroneously marked it as an old release, even though the version number clearly succeeded the previous one.

**Expected behavior**
I expected PyPI to accept and register the new release version, 0.0.4, acknowledging its sequence after version 0.0.39.

**To Reproduce**
The issue occurred during the release process of version 0.0.4 on PyPI. No specific steps led to this problem.

**My Platform**
- The issue is related to PyPI and the release process.
- No specific platform-related details. Using standard release mechanisms and Python packaging tools.

**Additional context**
The problem surfaced when I attempted to publish my library's new version, 0.0.4, on PyPI. Despite the version number being sequentially ordered after the last release, PyPI marked it as an older version. This situation is unexpected and problematic for maintaining version consistency and updates for the library.

You can navigate this bug through the 'JokerSDK' library on PyPi, find 0.0.4 on release history, and it was released after 0.0.39.

pypi.org / project /JokerSDK/

![image](https://github.com/pypi/warehouse/assets/71209712/c1794be3-b6ee-48ac-9ed4-bdbbc75b00ac)
![image](https://github.com/pypi/warehouse/assets/71209712/7667c488-27b3-495e-9a01-674423c62875)

**Comment by miketheman** [comment]
Hi there @0x96e63 !

Sorry you're hitting a condition that you're not expecting, but this is explicitly how the version numbers work.

If we split the parts of the version as described in [PEP 440](https://peps.python.org/pep-0440/), we can see that the last part  `4` is smaller than `39`, and is sorted as such.

**Comment by 0x96e63** [comment]
Thanks.
