### ISSUE TITLE
Broken layout on docs/user/trusted-publishers/security-model.md

### ISSUE THREAD

**Issue by soxofaan** [pypi/warehouse#14865]
Maybe this is more general, but I noticed some broken `<li>` layout issues on https://docs.pypi.org/trusted-publishers/security-model/

- under "Considerations", there is a two-level list (e.g see https://github.com/pypi/warehouse/blob/main/docs/user/trusted-publishers/security-model.md#considerations) , but it is rendered as flat list on https://docs.pypi.org/trusted-publishers/security-model/#considerations
- under "do the following to "ratchet down" the scope " there is another list with problems:
   - the second item "Use a dedicated environment" has three paragraphs, but on https://docs.pypi.org/trusted-publishers/security-model/ the second paragraph is rendered at document top-level, broken out of the listing
   - the last item has "Limit the scope of your publishing job" has a sub-list, but this is again rendered as a single flat list

**Comment by woodruffw** [comment]
Thanks for the report @soxofaan! I can confirm that I see the same incorrect rendering.

I'll look into a fix this afternoon.

**Comment by woodruffw** [comment]
Fixed in #14866, thanks again!
