### ISSUE TITLE
Can't verify secondary email if primary email is not verified.

### ISSUE THREAD

**Issue by di** [pypi/warehouse#14890]
In https://github.com/pypi/support/issues/3352, a user typo'd their first email, tried to add/verify a secondary email to replace it, but was met with "You must verify your primary email address before you can perform this action.", which leaves their account in a stuck state.

We should exclude email verification from the requirement to have a primary verified email.

**Comment by di** [comment]
This can be resolved by changing the second email to primary (per https://github.com/pypi/support/issues/3352#issuecomment-1804250115) but is still not very clear.

**Comment by afonso-pereira** [comment]
I faced a similar situation, but there was no problem in activating the second email. Only after activating it, I was able to set it as the primary email (and a pop up appeared saying so).

**Comment by hechth** [comment]
Actually I'm having the same issue right now and I can't even make the secondary verified email the primary email address.

**Comment by di** [comment]
We've changed how this works since the issue was created. If you cannot verify a primary email address, please see https://pypi.org/help#account-recovery.
