### ISSUE TITLE
RFE: new classifier, `Programming Language :: Go`

### ISSUE THREAD

**Issue by scop** [pypi/warehouse#14895]
**What's the problem this feature will solve?**

Being able to use a classifier to mark something as written in Go.

**Describe the solution you'd like**

`Programming Language :: Go` included in the list of classifiers at https://pypi.org/classifiers/

**Additional context**

Would have filed a PR but don't know where, `grep` produces no hits in this repo for the existing classifiers.

**Comment by miketheman** [comment]
The source for the classifiers is over https://github.com/pypa/trove-classifiers/ 

Feel free to submit your PR to that repo.

**Comment by scop** [comment]
Cheers, https://github.com/pypa/trove-classifiers/pull/159
