### ISSUE TITLE
Can upload new package to test.pypi.org, but not to PyPI

### ISSUE THREAD

**Issue by lzchen** [pypi/warehouse#14891]
**Describe the bug**

I have two packages `opentelemetry-instrumentation-aiohttp-server` and `opentelemetry-resource-detector-container`, both of which have been successfully uploaded to TestPypy [here](https://test.pypi.org/project/opentelemetry-instrumentation-aiohttp-server/) and [here](https://test.pypi.org/project/opentelemetry-resource-detector-container/). However when I try to upload to Pypi I get 

```
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
         The user 'opentelemetry' isn't allowed to upload to project 'opentelemetry-instrumentation-aiohttp-server'. See
         https://pypi.org/help/#project-name for more information.
```
and
```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
         The name 'opentelemetry-resource-detector-container' isn't allowed. See https://pypi.org/help/#project-name for
         more information.
```
respectively.

Any idea what is happening here? I get 404s when trying to hit `https://pypi.org/project/opentelemetry-instrumentation-aiohttp-server/` and `https://pypi.org/project/opentelemetry-resource-detector-container`. Do the projects somehow exist already and if so, how do I submit a request to remove them?

**Expected behavior**

**To Reproduce**

**My Platform**

**Additional context**

**Comment by di** [comment]
Please see https://pypi.org/help/#project-name-claim.
