### ISSUE TITLE
"503: Service Unavailable" on test.pypi.org when uploading release assets using trusted publishing

### ISSUE THREAD

**Issue by bastimeyer** [pypi/warehouse#14927]
I'm the maintainer of the [`streamlink`](https://github.com/streamlink/streamlink) project, and I've been trying to switch from user+pass based PyPI uploads to trusted publishing using the [`pypa/gh-action-pypi-publish`](https://github.com/pypa/gh-action-pypi-publish) GH action. In order to test the project's deployment changes, I tried uploading to the `test.pypi.org` index first, but ran into **503 HTTP status** issues while uploading the release assets.

Full reference here: https://github.com/streamlink/streamlink/pull/5670

----

I've been using my own GH test account (`bastimeyer-test`) and test repo (`streamlink-test`) to test these changes:
https://github.com/bastimeyer-test/streamlink-test/compare/b680d3819b77c2f45e683dc614e311fc49f2c8bf...60a4cb5da905b0f8e7146bdc25cdc39fa61d2663
As you can see, this simply uses the `pypa/gh-action-pypi-publish` action, with the `id-token: write` permission and `repository-url: https://test.pypi.org/legacy/` option, according to the action's documentation.

In order to make this test work though, I had to rename the project (in `pyproject.toml`) from `streamlink` to `streamlink-test`, as `streamlink` was already claimed on `test.pypi.org` by an ex-maintainer in 2018 who hasn't responsed to my ownership transfer yet. I also didn't want to open a `PEP 541` request just for the test index.

On the side of my newly created `streamlink-test` account on `test.pypi.org`, I correctly set up trusted publishing using my GH test account+repo, namely:
`streamlink-test` project, uploaded from `bastimeyer-test/streamlink-test` and the `release.yml` workflow.

The `pypa/gh-action-pypi-publish` action successfully obtained the token and registered the `streamlink-test` project, so I assume that trusted publishing worked correctly.
![image](https://github.com/pypi/warehouse/assets/467294/7da0f4ca-8575-4182-bbf0-792c356b87f7)
![image](https://github.com/pypi/warehouse/assets/467294/b7beffe3-39ab-40dc-bc21-81c3e6dba2c7)

However, uploading release assets resulted in a **"503: Service Unavailable" HTTP status**. This is also why the project is not visible yet on the test index, as no release was created.

Please see the log output of the GH workflow here:
https://github.com/bastimeyer-test/streamlink-test/actions/runs/6896127688/job/18766716430#step:4:1

> ```
> Notice: Attempting to perform trusted publishing exchange to retrieve a temporary short-lived API token for authentication against https://test.pypi.org/legacy/ due to __token__ username with no supplied password field
> Checking dist/streamlink_test-999.0.0-py3-none-any.whl: PASSED
> Checking dist/streamlink_test-999.0.0-py3-none-win32.whl: PASSED
> Checking dist/streamlink_test-999.0.0-py3-none-win_amd64.whl: PASSED
> Checking dist/streamlink-test-999.0.0.tar.gz: PASSED
>
> Uploading distributions to https://test.pypi.org/legacy/
> INFO     dist/streamlink_test-999.0.0-py3-none-any.whl (496.5 KB)               
> INFO     Signed with dist/streamlink_test-999.0.0-py3-none-any.whl.asc          
> INFO     dist/streamlink_test-999.0.0-py3-none-win32.whl (496.5 KB)             
> INFO     Signed with dist/streamlink_test-999.0.0-py3-none-win32.whl.asc        
> INFO     dist/streamlink_test-999.0.0-py3-none-win_amd64.whl (496.5 KB)         
> INFO     Signed with dist/streamlink_test-999.0.0-py3-none-win_amd64.whl.asc    
> INFO     dist/streamlink-test-999.0.0.tar.gz (697.6 KB)                         
> INFO     Signed with dist/streamlink-test-999.0.0.tar.gz.asc                    
> INFO     username set by command options                                        
> INFO     password set by command options                                        
> INFO     username: __token__                                                    
> INFO     password: <hidden>                                                     
>
> Uploading streamlink_test-999.0.0-py3-none-any.whl
> ...
> Received "503: Service Unavailable"
> Package upload appears to have failed. Retry 1 of 5.
> ...
> Response from https://test.pypi.org/legacy/:
> 503 Service Unavailable  
> ```

I checked this multiple times yesterday and today, to see if this was a temporary issue, but it resulted in 503 every time. 5xx is a server error response, hence why I'm opening this issue here. Similar issues have been reported before:
https://github.com/pypi/warehouse/issues?q=%22Service+Unavailable%22

I'm also not sure if this is caused by me having to rename the project (so I could register a new project on the test index) which made PyPI fail for some reason. The sdist and built wheels however should be fine according to the metadata. And as said, the trusted publishing was set up correctly, and the project was added on the first upload attempt.

Please have a look. Thank you!

**Comment by di** [comment]
Looks like this is a bug, the workaround for now is to not upload GPG signatures (they are no longer supported anyways, see https://blog.pypi.org/posts/2023-05-23-removing-pgp/)

Closing in favor of https://github.com/pypi/warehouse/issues/14928.

**Comment by bastimeyer** [comment]
Thanks for the hint. That did indeed work.

We're still signing our release files because we upload release signatures to GH-releases, so `pypa/gh-action-pypi-publish` picked up everything in the `dist/` directory, which then caused the failure.
