### ISSUE TITLE
Organisation requests: queued indefinitely

### ISSUE THREAD

**Issue by ModeSevenIndustrialSolutions** [pypi/warehouse#14972]
### Affected: pypi.org, test.pypi.org

Organisation join requests are **apparently queued indefinitely**! After a few days or weeks, I would expect these to be processed or rejected. Instead, they appear to be sat untouched. Can we get some movement on these? Do you need help processing them?

**I work for the Linux Foundation in the Release Engineering Team.**

A lot of our projects use/leverage PyPi!

Our account names on both the production and test site: "lf-releng-pypi"

We have requested to join the "os-climate" organisation under both the production and test sites/accounts.

![image](https://github.com/pypi/warehouse/assets/93649628/ef82520a-97f4-4e01-94f3-8ecc675c310c)

**Comment by dannysauer** [comment]
Just since October?  Ameteur. :p

![image](https://github.com/pypi/warehouse/assets/3950223/4545131c-dd28-427f-b92a-0386a83f8d5d)

I was just onboarding three new maintainers today, and it'd be *great* if I could do that by simply adding them to an org instead of individually adding them to every single project. :)

**Comment by ModeSevenIndustrialSolutions** [comment]
@dannysauer Most amusing...
I think the documentation is out of date; I was led to believe this launched earlier in the year...
[https://blog.pypi.org/posts/2023-04-23-introducing-pypi-organizations/](https://blog.pypi.org/posts/2023-04-23-introducing-pypi-organizations/)

**Comment by webknjaz** [comment]
There's a huge backlog, I heard. I got a few orgs in the very beginning, but then couldn't. One of the requests had to be resubmitted by another person and is stuck since early summer or late sprint too.

**Comment by ModeSevenIndustrialSolutions** [comment]
Indeed, two months on and still no apparent progress on this... I'm guessing the project is somewhat under-resourced and needs help (volunteers).

**Comment by ModeSevenIndustrialSolutions** [comment]
I'm guessing this should be moved or replicated to:
https://github.com/pypi/support/
I'll take a look their for existing comments/issues on this topic.

**Comment by ModeSevenIndustrialSolutions** [comment]
Lots of comments there, many without responses. The issue for corporate entities seems to be that they are on temporary pause, pending some supporting infrastructure related to payments. Can't see why community requests are not being processed, though, other than project/staffing issues. Closing this for now...

**Comment by webknjaz** [comment]
@ModeSevenIndustrialSolutions yes, the volunteers aren't paid. And the number of people with accesses is restricted. AFAIK it's just that it's physically impossible to move faster unless someone sponsors a role so somebody could do such support full time.

**Comment by webknjaz** [comment]
That said, orgs provide RBAC and visual grouping, but not scoping / isolation. You could use a bot account for uploads or OIDC if the project is published from GHA. And then, move to the org whenever it's there. The name will remain regardless.

**Comment by Andrew-S-Rosen** [comment]
Probably should be kept open for easier visibility. I've also been waiting since May 2023.

**Comment by dannysauer** [comment]
I'm not sure I agree with "completed." 😉 

It would've been nice to link to one of those other issues when closing. Perhaps pypi/support#2858 or pypi/support#3123, even though one says "read the blog" (which has said nothing about this issue) and the other has no response.

The delay would be a lot more palatable if there was some kind of transparency. Perhaps a request for funding or display a count of how many people are ahead of you / total in the queue on the status page. 🤷‍♂️ I'd make a donation to get this implemented.
