### ISSUE TITLE
URGENT: Enable Migration Capabilities for Spatial Data Types

### ISSUE THREAD

**Issue by spatial-moi** [pypi/warehouse#15096]
**What's the problem this feature will solve?**

**Describe the solution you'd like**

**Additional context**

This is the code I have: 

from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.orm import Mapped
from uuid import uuid4
from geoalchemy2 import Geometry

db = SQLAlchemy()

def get_uuid():
    return uuid4().hex

class Profile(db.Model):
    __tablename__ = "profiles"
    id = db.Column(db.String(11), primary_key=True, unique=True, default=get_uuid)
    #    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    first_name = db.Column(db.String(50), unique=True)
    last_name = db.Column(db.String(50), unique=True)
    username = db.Column(db.String(50), unique=True)
    password = db.Column(db.Text, nullable=False)
    location = db.Column(db.Geometry('POINT'), nullable=True)

I am using Flask. This is quite simple as its a very small app that has not been built yet. In a seperate server.py file I create the data and connect to the postgresql database. I used postgresql for its spatial data type extension, PostGIS. 

from datetime import datetime, timedelta, timezone
from flask_jwt_extended import create_access_token, get_jwt, get_jwt_identity, unset_jwt_cookies, jwt_required, JWTManager
from flask_cors import CORS
import json
from app.models import db, Profile
from psycopg2 import __libpq_version__

app = Flask(__name__)

app.config['JWT_SECRET_KEY'] = 'XXXXXXX'
app.config['SQLALCHEMY_DATABASE_URI'] = "postgresql://postgres:postgres@localhost/moisesherrera"
app.config["JWT_ACCESS_TOKEN_EXPIRES"] = timedelta(hours=24)
jwt = JWTManager(app)

SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ECHO = True

CORS(app)

db.init_app(app)

with app.app_context():
    db.create_all()

All the above is working.
The error I get when I run the app is this:

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) type "geometry" does not exist
LINE 8:  location GEOMETRY, 
                  ^

[SQL: 
CREATE TABLE profiles (
	id VARCHAR(11) NOT NULL, 
	first_name VARCHAR(50), 
	last_name VARCHAR(50), 
	username VARCHAR(50), 
	password TEXT NOT NULL, 
	location GEOMETRY, 
	PRIMARY KEY (id), 
	UNIQUE (id), 
	UNIQUE (first_name), 
	UNIQUE (last_name), 
	UNIQUE (username)
)

This Change would really Amp up Psycopg2 for all users oreinted towards spatial databases and capabilities.

Thank you!!

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
