### ISSUE TITLE
Checksum for packages againts github releases for security

### ISSUE THREAD

**Issue by TheFern2** [pypi/warehouse#15103]
**What's the problem this feature will solve?**

Developers can upload different version of a release, different from github. This can introduce a loophole to let anyone upload malware to pypi when the github release and source look clean.

**Describe the solution you'd like**

Match github release with pypi via a checksum or signature check, better yet let pypi pull the release straight from a github release if possible.

**Additional context**

**Comment by di** [comment]
Hi, PyPI does provide SHA256, MD5 and BLAKE2b-256 hashes for every artifact, which you can see via the "View hashes" link on the "Download Files" page:

<img width="837" alt="image" src="https://github.com/pypi/warehouse/assets/294415/b986bdbe-210d-4b71-9b62-b9a9f3ac40cf">

<img width="832" alt="image" src="https://github.com/pypi/warehouse/assets/294415/06fb766c-6553-49a8-9372-84d27441cb3a">

These can be compared to artifacts in GitHub releases to confirm integrity.

Additionally, we support direct publishing from a trusted publisher via https://docs.pypi.org/trusted-publishers/, and this supports GitHub Actions.
