### ISSUE TITLE
Can I add Korean Translation

### ISSUE THREAD

**Issue by cpprhtn** [pypi/warehouse#15117]
Pypi Korean Translate progress has also achieved 50%. 

Can I add a Korean page added to the footer?

And also will trying to contribute regularly to reach 100%.

**Comment by di** [comment]
Hi, please see https://warehouse.pypa.io/translations.html#adding-a-newly-completed-translation, we usually only add new translations when they reach 100%

**Comment by cpprhtn** [comment]
I checked the Aha document.
I will comment again when I reach 100%.
Thank :)
