### ISSUE TITLE
Link Broken on https://pypi.org/project/python-Levenshtein/

### ISSUE THREAD

**Issue by AlanApter** [pypi/warehouse#15150]
**Describe the bug**
On the page https://pypi.org/project/python-Levenshtein/ there is a section that says:

The documentation for the current version can be found at https://maxbachmann.github.io/Levenshtein/

The link provided returns a 404 not found.

**Expected behavior**
I believe the correct link to the documentation is now maintained at https://rapidfuzz.github.io/Levenshtein as that is where Max Bachmann is now contributing to the Levenshtein module (see https://github.com/rapidfuzz/Levenshtein for proof of commits by Max)

**To Reproduce**
1) Navigate to https://pypi.org/project/python-Levenshtein/
2) Observe incorrect link on that page to https://maxbachmann.github.io/Levenshtein/ instead of https://rapidfuzz.github.io/Levenshtein
3) Click on incorrect link and get a 404

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
