### ISSUE TITLE
Not able to use aibuilder to register model in powerapps. Can you please provide details steps on how to user AIbuilder sdk.

### ISSUE THREAD

**Issue by akshatakalp** [pypi/warehouse#15172]
**Describe the bug**

**Expected behavior**

**To Reproduce**

**My Platform**

**Additional context**

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
