### ISSUE TITLE
The link to Python Packaging User Guide is currently broken

### ISSUE THREAD

**Issue by willmcgugan** [pypi/warehouse#15224]
The link to Python Packaging User Guide is currently 404ing.

https://pypi.org/manage/project/PROJECT/releases/

<img width="1158" alt="Screenshot 2024-01-16 at 11 03 07" src="https://github.com/pypi/warehouse/assets/554369/fb159697-2266-4950-b24e-cff4e88db6b4">

**Comment by woodruffw** [comment]
Confirmed that this is broken (this only appears when a project has no releases, which is pretty rare).

Bugpoint: 

https://github.com/pypi/warehouse/blob/30c8720951db492dbd800bb5433edbdf1fc6085f/warehouse/templates/manage/project/releases.html#L179

The correct link is probably this one: <https://packaging.python.org/en/latest/guides/section-build-and-publish/>

**Comment by woodruffw** [comment]
@willmcgugan would you be willing to do a quick PR for this? Otherwise, I'll try and file one later today 🙂

**Comment by woodruffw** [comment]
Doing this now.

**Comment by JohannesEbke** [comment]
> Confirmed that this is broken (this only appears when a project has no releases, which is pretty rare).

Maybe this is unnecessary, but I came here to report the same issue; and I got the link in a project with three releases: [https://pypi.org/manage/project/aws-close-account/releases/](https://pypi.org/manage/project/aws-close-account/releases/)

I do appreciate the link being there, though!
