### ISSUE TITLE
"Add API token" takes me to the wrong page

### ISSUE THREAD

**Issue by ocket8888** [pypi/warehouse#15237]
## Describe the bug
When I click on the "Add API Token" button in my [account settings](https://pypi.org/manage/account/#api-tokens)
![image](https://github.com/pypi/warehouse/assets/6013378/ab186daa-9d03-4fb5-b318-f56666b908d6)
instead of taking me to any API token-related page, I am redirected to https://pypi.org/manage/account/two-factor/?next=%2Fmanage%2Faccount%2Ftoken%2F - note that the 'next' path there simply takes me back to the API Tokens section of my account settings, so it seems like an infinite loop.

## Expected behavior
It should take me to an API token generation page. As you can see in the screenshot, I've done this before, so surely there's nothing wrong with my account? Am I not allowed to have more than one API token? I can't find anything about that anywhere in any documentation. If so, then perhaps the expected behavior is that a button that can't work doesn't appear.

## To Reproduce
Go to account settings, click on "Add API Token".

## My Platform
Firefox 121.0.1 (64-bit) on Pop!_OS 22.04

**Comment by miketheman** [comment]
Hi there! I'm a little confused - the page you end up on should be the 2FA enrollment page per the URL - https://pypi.org/manage/account/two-factor/ - as your account has yet to enroll in 2FA, which is now required. I guess our notification banner expired a little early? But you should see other notices prompting you to active 2FA in some fashion.

Read more about it here: https://blog.pypi.org/posts/2024-01-01-2fa-enforced/

**Comment by ocket8888** [comment]
Oh god, it's really required now? The world seems absolutely hell-bent on making sure losing my phone every day is as crippling as possible.
