### ISSUE TITLE
please add classifier "License :: OSI Approved :: NASA Open Source Agreement (NOSA)"

### ISSUE THREAD

**Issue by ebo** [pypi/warehouse#15244]
It is my understanding that NASA's  Open Source Agreement (NOSA) is OSI approved, but it does not appear in any of the standard lists.

Here are the official links for NOSA:
    https://opensource.gsfc.nasa.gov/nosa.php

which include PDF, TRF, and ASCII text versions of the license.

Adding NOSA will help facilitate using pypi and other tools in NASA's open source projects.

Please let me know if you prefer to have me make the modifications and make a pull request.

**Comment by miketheman** [comment]
Hi there! The warehouse classifiers are inherited from the `trove-classifiers` project. https://github.com/pypa/trove-classifiers
I'd recommend you open a pull request at that repository instead.
