### ISSUE TITLE
Interested for this Volunteer work

### ISSUE THREAD

**Issue by madhuammulu8** [pypi/warehouse#15245]
Looking for maintainers! Please open an issue with a method of contacting you if you're interested.

I am interested 

Contact: mtung007@ucr.edu

**Comment by miketheman** [comment]
I'm not certain what this is, but I don't think we have a call for maintainers that looks like this.

**Comment by madhuammulu8** [comment]
https://pypi.org/project/pytrends/#pytrends

This is where I found the above

**Comment by miketheman** [comment]
This issue tracker is for issues with the codebase behind pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
