### ISSUE TITLE
Trim leading and trailing whitespace from username in forms

### ISSUE THREAD

**Issue by miketheman** [pypi/warehouse#15356]
**Describe the bug**
When using a mobile keyboard for input, auto complete may add a trailing space to a username field in a form, making the submission fail due to mismatch.

**Expected behavior**

Any trailing or leading whitespace is removed either from the form, the view, or the database query, allowing the user to log in

**To Reproduce**

Try logging in with your username and add a space to the end.

**Comment by HimanshuSinghGH** [comment]
Hi @miketheman, I would like to work on this. I reproduced the problem on the login page and understand how to solve this. However, when I try to configure the development environment on my system it fails after the `make initdb` step with an error saying **"warehouse-db-1 is unhealthy"**

Is this a common issue and is there a known fix available ?

![db_1](https://github.com/pypi/warehouse/assets/20122511/ea80fff4-f162-49bc-84de-0f1ef7519a6d)

**Comment by miketheman** [comment]
Hi @HimanshuSinghGH ! Thanks for taking a pass at this.

Can you share some more of your computer environment? It's hard to diagnose from a screenshot.

Did you do these steps in order?
- stop everything with `make stop`
- start the stack with `make serve` and wait a few minutes until you see something like: 
    > static-1         |   admin (webpack 5.88.2) compiled successfully in 5226 ms
- in another terminal session, execute `make initdb`
