### ISSUE TITLE
Periodically purge OIDC-exchanged API tokens from the DB

### ISSUE THREAD

**Issue by woodruffw** [pypi/warehouse#15432]
From https://github.com/pypi/warehouse/pull/15240#discussion_r1496243886: PyPI is currently accumulating "orphaned" API tokens in the macaroons table, since Trusted Publishing's OIDC exchange produces (by design) a new self-expiring API token each time. 

These don't cause any real issues on their own, but they might contribute to unnecessarily long/contentious locks during data migrations. So a periodic job to purge them would probably be ideal 🙂 

In terms of how best to do that: `Macaroon.created` reflects the Macaroon's *database* creation time, which should be nearly identical to the interior `Expiration` caveat on the user-held Macaroon. OIDC-minted Macaroons expire 15 minutes after their creation, so it'd be more than safe to have a once-daily job that deletes every DB macaroon that satisfies `Macaroon.oidc_publisher_id is not None and Macaroon.created > 15 minutes ago`.

**Comment by woodruffw** [comment]
(Triaging: this falls into the scope of the OIDC maintenance that @facutuesca and I are doing, so we'll work on this as well.)

**Comment by facutuesca** [comment]
PR created here: https://github.com/pypi/warehouse/pull/15463
