### ISSUE TITLE
Admin UI is missing new Metadata 2.2/2.3 fields

### ISSUE THREAD

**Issue by di** [pypi/warehouse#15492]
The template at https://github.com/pypi/warehouse/blob/main/warehouse/admin/templates/admin/projects/release_detail.html is missing the new `Dynamic` field.

Additionally, `Provides-Extra` is commented out for some reason, and should be uncommented: https://github.com/pypi/warehouse/blob/f87e97d9274ed40a1c2526c68eb2b30d8739da07/warehouse/admin/templates/admin/projects/release_detail.html#L311-L320

~Ideally, this template would use the enum from #13606 instead of manually enumerating all these fields.~ This is probably to complicated for a "Good First Issue" because it requires knowing which fields are lists.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypi/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/).

If you are working on this issue and have questions, feel free to ask them here, in the [`#pypa-dev` chat channel on Libera](https://web.libera.chat/#pypa-dev), the [PyPA Discord](https://discord.gg/pypa) or on the [Discourse](https://discuss.python.org/c/packaging/14).

**Screenshot Required**: *If your pull request makes a visual change*, include a screenshot of your update. This helps our team give you feedback faster.

**Comment by javanlacerda** [comment]
Working on it
