### ISSUE TITLE
recurring 500 error on upload.pypi

### ISSUE THREAD

**Issue by dan1hc** [pypi/warehouse#15491]
**Describe the bug**
Job log: https://github.com/dan1hc/r/actions/runs/8058449660/job/22011275445

```
Run pypa/gh-action-pypi-publish@release/v1
  with:
    verbose: true
    user: __token__
    repository_url: https://upload.pypi.org/legacy/
    packages_dir: dist
    verify_metadata: true
    skip_existing: false
    print_hash: false
  env:
    [...]
  
[...]
Notice: Attempting to perform trusted publishing exchange to retrieve a temporary short-lived API token for authentication against https://upload.pypi.org/legacy/ due to __token__ username with no supplied password field
Error: Trusted publishing exchange failure: 
Token request failed: the index produced an unexpected
500 response.

This strongly suggests a server configuration or downtime issue; wait
a few minutes and try again.

```

**Expected behavior**
`200 Response that tells me how awesome I am when it is deserialized.`

**To Reproduce**
The package is called `r`, guessing there is an undocumented reason it can't be published even though I seem to have reserved the spot on the index?

**My Platform**
https://github.com/dan1hc/r

**Comment by di** [comment]
I think you're probably experiencing the bug that #15490 will fix.

What's your PyPI username?

**Comment by dan1hc** [comment]
Ah perfect, thank you! I am: `dan_dube`

**Comment by dan1hc** [comment]
@di Sorry, realizing I should have asked: when #15490 is merged, will I then receive a 400 Error telling me I should email admin@pypi.org to express my belief my pending publisher was invalidated erroneously... or will I receive a 200 / 201 confirming publication lol

**Comment by di** [comment]
@dan1hc Unfortunately neither: the name `r` is not available, and there was an additional bug here where it was possible to configure trusted publishers for projects with invalid names. You'll have to choose a new project name, sorry for the confusion.
