### ISSUE TITLE
Get Direct URL Download of Package

### ISSUE THREAD

**Issue by ZribeDev** [pypi/warehouse#15523]
**What's the problem this feature will solve?**
Not problems but just a cool feature

**Describe the solution you'd like**
I want a api endpoint that allows me to get the download for the package. for example requests is:
https://files.pythonhosted.org/packages/9d/be/10918a2eac4ae9f02f6cfe6414b7a155ccd8f7f9d4380d62fd5b955065c3/requests-2.31.0.tar.gz

**Comment by di** [comment]
Hi @ZribeDev. This is what the [Simple API](https://peps.python.org/pep-0503/) is for, which is the API that installers like `pip` use to determine the URLs for packages that users request to install.

For example, for `requests`, you would request https://pypi.org/simple/requests/, which would give you a list of files and their links.
