### ISSUE TITLE
speak.save_to_file() function not appending data but overwriting it

### ISSUE THREAD

**Issue by jonfon96** [pypi/warehouse#15522]
Hello 
I am trying to use the pyttsx3 and pyttsx4 to save a pdf to an mp3 file.  what I have encountered is the function works in creating the mp3 but if you have say 20 page pdf your mp3 file will not append the data to the mp3 but will over write it.  As a result the mp3 will only have the last block of data saved to it.  

I run windows 10 with all the updates installed.  I have installed Pyttsx3 and Pyttsx4 along with PyPDF2. 
-->

**Describe the bug**
<the Mp3 or wav file are not including all the data sent to them but just the last block of data. it no appending the data but over writing it. 

**Expected behavior**
<I should have an mp3 that grows to include the first page of converted data to the last but its not doing that at all. 

**To Reproduce**
< I was able to reproduce the issue on my Centos 9 stream pc with the same results. I also got the same behavior with a windows 10 pc both events did the same thing. 

**My Platform**

**Additional context**
<I do not think this is a new issue but I would like to have someone tell me if this is a bug or bad code.

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
