### ISSUE TITLE
New packages not being available for installation

### ISSUE THREAD

**Issue by mullenkamp** [pypi/warehouse#15543]
**Describe the bug**
I just uploaded a [new version](https://pypi.org/project/s3tethys/0.1.1/) to a package to pypi, but it doesn't show up on the [main page](https://pypi.org/project/s3tethys/) of the package on pypi. It also doesn't seem to be registered as a package version that can be downloaded and installed via pip. 

**Expected behavior**
This should work, but doesn't:
`pip install s3tethys==0.1.1`

**To Reproduce**
`pip install s3tethys==0.1.1`

**My Platform**
Ubuntu using hatch and pip

**Comment by miketheman** [comment]
Hi there,

This is due to a cache purge sitting in a queue for longer than we expect.

**Comment by ewdurbin** [comment]
We're seeing recovery in the incident that caused this, but are shipping a PR to limit impact if this happens again in #15545
