### ISSUE TITLE
constants bug

### ISSUE THREAD

**Issue by shuai-bin8** [pypi/warehouse#15638]
The following content is missing：
datetime.date(year=2024, month=6, day=8): Holiday.dragon_boat_festival.value,
datetime.date(year=2024, month=6, day=9): Holiday.dragon_boat_festival.value,

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
