### ISSUE TITLE
I am getting a LangChain MsWordParser Error when trying to parse DOCX files

### ISSUE THREAD

**Issue by CyberBearSec** [pypi/warehouse#15639]
I am using the code below to load various documents into a Chroma vector store. PDF and TXT work fine but MsWordParser keeps failing with the follow error:

A Document Loading error occurred: Could not import unstructured, please install with `pip install unstructured`.
I pip installed unstructured, added it to my requirements.txt file, and verified it was in the Project Interpreter. I tried different Word documents but nothing makes a difference. Does anybody have any ideas on what is wrong?

from langchain_community.document_loaders.parsers.pdf import PyPDFParser
from langchain_community.document_loaders.parsers.txt import TextParser
from langchain_community.document_loaders.parsers.msword import MsWordParser

try:
    loaders = {
        '.pdf': GenericLoader.from_filesystem(
            path="./UserData",
            glob="**/*.pdf",
            parser=PyPDFParser(),
            show_progress=True
        ),
        '.txt': GenericLoader.from_filesystem(
            path="./UserData",
            glob="**/*.txt",
            parser=TextParser(),
            show_progress=True
        ),
        '.docx': GenericLoader.from_filesystem(
            path="./UserData",
            glob="**/*.docx",
            parser=MsWordParser(),
            show_progress=True
        ),
        # Add other file types and their respective loaders here
    }
    documents = []
    for loader in loaders.values():
        documents.extend(loader.load())

**Comment by woodruffw** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org/ itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
