### ISSUE TITLE
Low number of changelog events

### ISSUE THREAD

**Issue by chriseldredge** [pypi/warehouse#15673]
I see on https://status.python.org/incidents/dc9zsqzrs0bv that pypi.org is undergoing maintenance but the message indicates that it should only affect new projects or accounts.

However, in the last hour or so I've seen the xml-rpc API returning very few changelog items, almost all of which seem to be `yank release`, `remove release`. I'm wondering if there is any additional information available on whether normal publishing activity for existing projects has been temporarily suspended?

**Comment by miketheman** [comment]
@chriseldredge I believe this was largely due to the restrictions put into place at the time of the event.

I think this may have also prevented all package publishing.

**Comment by di** [comment]
Closing, this should be resolved.
