### ISSUE TITLE
[Project specific] Cannot find my package (singletCode) uploaded on 25-Mar-2024. 

### ISSUE THREAD

**Issue by Keerthana910234** [pypi/warehouse#15681]
I uploaded my package singletCode on 25th March. I can install and use it via pip. I can also it on my projects list. It is not visible when searching for it on pypi or google search. Is there anything I can do to resolve this? Thank you!

![image](https://github.com/pypi/warehouse/assets/70164426/5d9e25f6-0cf3-43c8-962b-bdee3e1a5a6e)

![image](https://github.com/pypi/warehouse/assets/70164426/e7cf763c-48d8-4d03-8750-f66bfc7124df)

**Comment by fxcoudert** [comment]
I am not sure it its package-specific. I have a new package named `CoRE-MOF`, uploaded 5 days ago: https://pypi.org/project/CoRE-MOF/ 

The project page is fine, the release is there, the project can be installed through pip. But it won't appear in the search results, even when the query if very specific (like search for its name, or its entire description). It's simply never visible in the search results.

**Comment by Keerthana910234** [comment]
It is now visble. Both singletCode and CoRE-MOF. I am not sure what exactly was the issue, but it is resolved. So closing the issue.

**Comment by Keerthana910234** [comment]
It is now visble. Both singletCode and CoRE-MOF. I am not sure what exactly was the issue, but it is resolved. So closing the issue.
