### ISSUE TITLE
Update docs/dev/development/frontend to relate to docker builds

### ISSUE THREAD

**Issue by jzohrab** [pypi/warehouse#15691]
(this isn't a feature, but I couldn't open a blank request)

Per [this comment](https://github.com/pypi/warehouse/pull/15689#discussion_r1545513966) from @miketheman in https://github.com/pypi/warehouse/pull/15689, the FE dev docs should be updated:

> I tend to use something like `docker compose run --rm static npm ...` for commands to run inside the static container.  This also helps avoid any platform-specific dependencies that might be installed as a result - keeping it consistent.

The current docs at https://github.com/pypi/warehouse/blob/main/docs/dev/development/frontend.rst seem to all imply that dev, updates, deploys, etc can be run outside of docker, but the makefiles and root dev docs in getting started imply otherwise.  Should everything in that file be updated?

**Comment by miketheman** [comment]
> can be run outside of docker, but the makefiles and root dev docs in getting started imply otherwise. Should everything in that file be updated?

Yes, we've moved to a docker-first development methodology, to maintain consistency for a complex stack.

We have `make` targets for most of the common actions, and some places in "Getting Started" show `docker compose ...` examples when something is out of the normal workflows.
