### ISSUE TITLE
Unable to login two accounts

### ISSUE THREAD

**Issue by marcantonio** [pypi/warehouse#15711]
**Describe the bug**
_Sorry in advance if this the wrong forum._

I've been unable to login with two new accounts since yesterday (4/1). On Saturday (3/30) I created two new accounts: `marcantonio` and `jdeweeselab`. Both seemed fine, I was able to upload and remove a test package.

**Expected behavior**
I expect to be able to login and use the site for both accounts.

**To Reproduce**
I try to login (from https://pypi.org/account/login/) I get redirected back to https://pypi.org/. The Login link is still in the upper right hand corner. If I click Login again, I am taken to https://pypi.org/account/login/ again, but this time there is a big red banner at the top of the page that says "Session invalidated".

**My Platform**
macOS 14.2 with both Firefox 124 and Safari 17.2. 

**Additional context**

**Comment by jqiuyin** [comment]
+1
same problem

**Comment by evangelionlion** [comment]
I encounter the same problem

**Comment by Yeying-Xingchen** [comment]
Indeed, so do I. However, I once saw a workaround in [this issue](https://github.com/pypi/warehouse/issues/14881), but I found that it didn't work after I had already sent the email.

**Comment by di** [comment]
Hi, you all should have recently received an email from PyPI about your accounts, please follow the directions in that email.

**Comment by marcantonio** [comment]
Thank you!
