### ISSUE TITLE
Removing a project with OIDC configured fails

### ISSUE THREAD

**Issue by miketheman** [pypi/warehouse#15729]
When removing a project via admin (such as malware), currently the removal fails, presumably due to not having an on delete cascade for the foreign key relationship.

```python
(psycopg.errors.ForeignKeyViolation) update or delete on table "projects" violates foreign key constraint "oidc_publisher_project_association_project_id_fkey" on table "oidc_publisher_project_association"
DETAIL:  Key (id)=(REDACTED) is still referenced from table "oidc_publisher_project_association".
[SQL: DELETE FROM projects WHERE projects.id = %(id)s::UUID]
[parameters: {'id': UUID('REDACTED')}]
```

We probably want to delete a publisher on project removal, since it's a one-to-one relationship, is that correct @woodruffw ?

We probably also want Admin UI functionality to remove an OIDC publisher from a project.

**Comment by miketheman** [comment]
Manual workaround for now:
```pycon
>>> from warehouse.oidc.models import GitHubPublisher
>>> pub = db.query(GitHubPublisher).filter_by(repository_owner='redacted', repository_name='redacted').one()
>>> db.delete(pub)
>>> db.commit()
```

**Comment by woodruffw** [comment]
> We probably want to delete a publisher on project removal, since it's a one-to-one relationship, is that correct @woodruffw ?

Unfortunately not -- it's a many-many relationship, since other PyPI projects could have the same publisher registered. So I think we want to persist the publisher unless it's the last project associated with it, in which case it can be deleted 🙂

**Comment by miketheman** [comment]
Oh, I see - I must have misread the relationships. Instead of removing the publisher itself, then maybe the related [`OIDCPublisherProjectAssociation`](https://github.com/pypi/warehouse/blob/4b73a1ed889b9ae65a9ba7693278814373ae3a29/warehouse/oidc/models/_core.py#L67-L78) should be removed on project delete?

It works for publisher-side delete - when I ran the code above to remove the publisher, it removed the association as well.

**Comment by woodruffw** [comment]
Yeah, that makes sense to me!
