### ISSUE TITLE
hCaptcha broke pypi-cleanup automation

### ISSUE THREAD

**Issue by arcivanov** [pypi/warehouse#15736]
**What's the problem this feature will solve?**
I'm the maintainer of the https://github.com/arcivanov/pypi-cleanup project that is used to clean out project releases automatically from CLI using regex patterns.
A user just reported the added CAPTCHA breaking the functionality: https://github.com/arcivanov/pypi-cleanup/issues/27

**Describe the solution you'd like**
The lack of API providing for project maintenance capability (e.g. delete/yank releases) for the PyPI is a real bummer. By introducing hCaptcha you've basically killed the last hope for automating these maintenance procedures (hundreds of .dev releases can be generated by the CI for a project).

Please either provide an option for automation tools to function without hCaptcha or provide the maintenance API that allows such functionality to exist natively.

**Comment by miketheman** [comment]
I encourage all folks with a 👍 on this to also check out #13409 and make sure that your use cases are reflected on that issue.

**Comment by arcivanov** [comment]
Thank you!
