### ISSUE TITLE
Failed to establish a new connection: [Errno 101]

### ISSUE THREAD

**Issue by jokkovitch** [pypi/warehouse#15741]
Dear All,
The infamous NewConnectionError is back, I have network issue again
=> [3/6] RUN pip install -r requirements.txt                                                                                           264.0s
 => => # WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError => => # r('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f4ac51f2090>: Failed to establish a new connection: [Errno 101] Netwo
 => => # rk is unreachable')': /simple/certifi/                                                                                                 => => # WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionErro
 => => # r('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f4ac51f2890>: Failed to establish a new connection: [Errno 101] Netwo
 => => # rk is unreachable')': /simple/certifi/
Is anyone else having issues ?

**Comment by miketheman** [comment]
Please open a network issue in the support repository, with necessary details.
https://github.com/pypi/support/issues/new/choose
