### ISSUE TITLE
Uploading a correctly formatted README.rst fails

### ISSUE THREAD

**Issue by Gouvernathor** [pypi/warehouse#15771]
**Describe the bug**
I'm trying to publish my package but it gets rejected with error 400 saying that "the description failed to render".
Previous to that, the runner falsely claimed that [my readme file](https://github.com/Gouvernathor/parliamentarch/blob/f2cbb622e1b42c4a5eac6c233f2209d7da1f99f9/README.rst) had wrong syntax with wrong indentation at line 25 : it is not true because github displays it correctly and no other indentation at that line yields the same result.
On a sidenote, providing no readme at all also fails, though that block may not be at the upload level.

**Expected behavior**
The package publication should work.

**To Reproduce**
Try to upload a package with my readme, or any recursive bullet list with line wrapping.

**My Platform**
I think that's called GitHub Actions

**Comment by miketheman** [comment]
Hello!

> it is not true because github displays it correctly and no other indentation at that line yields the same result.

First off, PyPI and GitHub may not share same RST parsers, so there's no expectation of equivalent behavior.

Your example is actually called out in the RST specification as an incorrect example of nested lists.
See https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#bullet-lists

So if you believe this is an issue with the specification and/or the `docutils` library that handles the parsing, I'd advise you to raise it with those maintainers.

You might also want to test your description with `twine check` - see https://twine.readthedocs.io/en/stable/#twine-check
