### ISSUE TITLE
`opencv-python-headless` PyPI page has broken CSS

### ISSUE THREAD

**Issue by johnthagen** [pypi/warehouse#15797]
**Describe the bug**

Navigate to: https://pypi.org/project/opencv-python-headless/

The page's HTML/CSS does not loaded correctly:

<img width="434" alt="Screenshot 2024-04-16 at 12 23 56 PM" src="https://github.com/pypi/warehouse/assets/10340167/6d2af911-9fc8-4ba9-9501-9d471f43aaff">

But navigating to a specific release renders correctly:

- https://pypi.org/project/opencv-python-headless/4.9.0.80/

<img width="1159" alt="Screenshot 2024-04-16 at 12 24 59 PM" src="https://github.com/pypi/warehouse/assets/10340167/9cb027ae-5ee3-4fb3-9ccc-8796fa125ed9">

**Expected behavior**

https://pypi.org/project/opencv-python-headless/ should render a correct-looking HTML page.

**To Reproduce**

Visit https://pypi.org/project/opencv-python-headless/  as of the writing of this issue.

**My Platform**

- macOS 14
- Chrome 123.0.6312.124
- Also Firefox 124.0.2

**Comment by miketheman** [comment]
@johnthagen Thanks - but I cannot reproduce this issue in either Firefox nor Chrome.

Can you check to see if there's specific error messages in your browser's Console and supply those here?

**Comment by johnthagen** [comment]
@miketheman 

Sure thing. One error that looks relevant

```
opencv-python-headless/:1 Refused to apply style from 'https://pypi.org/static/css/warehouse-ltr.4d531b4e.css/' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

Some other warnings

```
Error with Permissions-Policy header: Unrecognized feature: 'ambient-light-sensor'.
Error with Permissions-Policy header: Unrecognized feature: 'battery'.
Error with Permissions-Policy header: Unrecognized feature: 'document-domain'.
Error with Permissions-Policy header: Unrecognized feature: 'execution-while-not-rendered'.
Error with Permissions-Policy header: Unrecognized feature: 'execution-while-out-of-viewport'.
Error with Permissions-Policy header: Unrecognized feature: 'speaker-selection'.
Error with Permissions-Policy header: Unrecognized feature: 'web-share'.
```

**Comment by johnthagen** [comment]
An error message in Firefox

```
The resource from “https://pypi.org/static/css/warehouse-ltr.4d531b4e.css/” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```

**Comment by johnthagen** [comment]
The page also renders broken on Safari 17.4.1 and Microsoft Edge 123.0.2420.97 on the same machine.

**Comment by miketheman** [comment]
Thanks @johnthagen !

This is indeed odd - since there's no document at `https://pypi.org/static/css/warehouse-ltr.4d531b4e.css/` - that's an appropriate 404 html response.

Note the trailing slash - the correct resource is at https:://pypi.org/static/css/warehouse-ltr.4d531b4e.css - which is the path we set in the HTML content

Do you have an extension or something adding a slash to the URL?

**Comment by johnthagen** [comment]
@miketheman Interesting. I tested with no extensions active, but it's possible there is something on the company managed system causing the issue. If everything looks fine on the PyPI side, happy to close this issue if it's client-side issue. Just strange it only happened on this page and others seem okay.

Either way, wanted to report it and thanks for the triage.

**Comment by johnthagen** [comment]
@miketheman Not sure if you intentionally changed anything, but the page is loading correctly now.

**Comment by miketheman** [comment]
Nope, nothing changed on my end, as far as I know!
