### ISSUE TITLE
Trusted Publisher support for GitLab subgroups

### ISSUE THREAD

**Issue by mwoodbri** [pypi/warehouse#15836]
**What's the problem this feature will solve?**
I'm adding a trusted publisher to an existing PyPI project. The project is in a subgroup i.e. following [the GitLab documentation](https://docs.gitlab.com/ee/user/namespace/#determine-which-type-of-namespace-youre-viewing) it would be in the `alex-team/marketing` namespace.

If I try to use this I see the following error (though obviously I'm using our own namespace and project name - it's a private project):

![Screenshot 2024-04-23 at 10 43 05](https://github.com/pypi/warehouse/assets/1724545/a20f3198-5af1-4a41-9126-8fbd1c25033a)

I've also tried specifying namespace as the equivalent of `alex-team`, with project name as `marketing/myproject`.

**Describe the solution you'd like**
I could well be misinterpreting the instructions and doing it wrong, in which case any guidance would be gratefully received. The help label says "group/subgroup" which suggests it's supported but I'm not sure.

**Comment by facutuesca** [comment]
@mwoodbri Thanks for the report! This is definitely a bug on our side, your first attempt using `alex-team/marketing` as the namespace should have worked. I'm creating a fix for it now.
