### ISSUE TITLE
not able to install hampel with pyhton 3.12.3

### ISSUE THREAD

**Issue by hbiergans** [pypi/warehouse#15842]
I was able to install hampel with

 **pip install hampel**

with an **earlier version** of Python.

Now with the update to **Python 3.12.3** i get the error

 note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hampel
ERROR: Could not build wheels for hampel, which is required to install pyproject.toml-based projects

Thank you for your help.

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
