### ISSUE TITLE
Page formatting incorrect

### ISSUE THREAD

**Issue by itakimasu** [pypi/warehouse#15853]
**Describe the bug**

The project description portion of the [anchore project](https://pypi.org/project/anchore/) is improperly formatted. The back tick aren't translating into code snippets and some of the text is in a strange font and exceeding the boundaries of the page.

**Expected behavior**

Page should be formatted properly

**To Reproduce**

Visit the following URL: https://pypi.org/project/anchore/

**My Platform**

Browser: Chrome Version 123.0.6312.107
OS: macOS Sonoma Version 14.2.1

**Additional context**

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
