### ISSUE TITLE
Trouble after uploading two sdist tarballs in the same twine invocation

### ISSUE THREAD

**Issue by dalcinl** [pypi/warehouse#15873]
**Describe the bug**

I'm not sure where the root cause of my issue originated in `twine` or was a server-side issue in PyPI. 
In any case, I will probably need manual intervention of a PyPI server admin to fix the publishing of my package.

I used twine 4.0.1
```
$ twine --version
twine version 4.0.1 (importlib-metadata: 6.8.0, keyring: 23.11.0, pkginfo: 1.9.6, requests: 2.31.0, requests-toolbelt: 1.0.0,
urllib3: 2.2.1)
```

I tried to upload two distributions in one twine invocation, but got a failure
```
$ twine upload petsc-3.21.1.tar.gz petsc4py-3.21.1.tar.gz
Uploading distributions to https://upload.pypi.org/legacy/
Uploading petsc-3.21.1.tar.gz
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB • 00:03 • 11.0 MB/s
WARNING  Error during upload. Retry with the --verbose option for more details.                                                
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/                                                       
Start filename for 'petsc4py' with 'petsc4py'.
```

Then I tried to upload again the second tarball, and it succeeded.
```
$ twine upload petsc4py-3.21.1.tar.gz
Uploading distributions to https://upload.pypi.org/legacy/
Uploading petsc4py-3.21.1.tar.gz
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 426.1/426.1 kB • 00:01 • 605.5 kB/s
```

However, I went to https://pypi.org/project/petsc/ to double check, and the looked like the first tarball (corresponding to a new version 3.20.1) was not uploaded, as the project in PyPI is still at version 3.20.0.
Therefore, I attempted to upload the first taball again. It failed with:
```
$ twine upload petsc-3.21.1.tar.gz 
Uploading distributions to https://upload.pypi.org/legacy/
Uploading petsc-3.21.1.tar.gz
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB • 00:02 • 10.0 MB/s
WARNING  Error during upload. Retry with the --verbose option for more details.                                                
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/                                                       
Only one sdist may be uploaded per release.
```

**Expected behavior**

The following two projects should be both at version 3.21.1
https://pypi.org/project/petsc/
https://pypi.org/project/petsc4py/

**To Reproduce**

* The link https://pypi.org/project/petsc/ is still at version 3.20.0.
* `twine upload petsc-3.21.1.tar.gz` fails with *Only one sdist may be uploaded per release*.

**My Platform**

Linux Fedora 39 with twine installed via pip in user `~/.local/` directory.

**Additional context**

The original tarball I'm trying to upload to PyPI is the one from the following link:
https://web.cels.anl.gov/projects/petsc/download/release-snapshots/petsc-3.21.1.tar.gz

**Comment by di** [comment]
I'll take a guess that you just renamed the file rather than rebuild it, and that it's actually the same file, correct? 

If so, you'll need to rebuild it with the other name, because the metadata inside the release is not consistent with the project name.

I agree that the error message is a little confusing here so feel free to leave this open so we can improve it.

**Comment by dalcinl** [comment]
> I'll take a guess that you just renamed the file rather than rebuild it, and that it's actually the same file, correct?

No, not at all... What I a did was to `wget` the following two tarballs:
* https://web.cels.anl.gov/projects/petsc/download/release-snapshots/petsc-3.21.1.tar.gz
* https://web.cels.anl.gov/projects/petsc/download/release-snapshots/petsc4py-3.21.1.tar.gz

The second one is a "proper" Python sdist that was generated the usual way. The first one, however, was not obtained by usual mechanisms, but it contains a `setup.py` and and `pyproject.toml` (with only the `[build-system]` table). Maybe that's the problem, I mean, the lack of a proper `PKG-INFO` info file at the top level? 

Also, I just noticed that the tarball has deep inside another `PKG-INFO` file corresponding to the other project. So it may very well bee that this is a mess up on my side. Let me take a closer look.

**Comment by dalcinl** [comment]
The problem was indeed a bad tarball, with a missing PKG-INFO file at the top level, and a bogus PKG-INFO file deep inside the tree corresponding to a separate distribution.

Sorry for the noise. Clossing.
