### ISSUE TITLE
Unable to register at test.pypi.org

### ISSUE THREAD

**Issue by Drhansom** [pypi/warehouse#15959]
When trying to register at test.pypi.org, I always get the message

_The username is invalid. Usernames must be composed of letters, numbers, dots, hyphens and underscores. And must also start and finish with a letter or number. Choose a different username._

I tried different usernames and made sure the information is given in the right input fields.
Am I missing something? Is there a required pattern for Usernames?

**Comment by di** [comment]
Hi @Drhansom, are you maybe putting your email address in the username field? Could you share a screenshot of the username you're trying and the resulting error message?

**Comment by Drhansom** [comment]
I tried again and it worked. Thanks!
