### ISSUE TITLE
Source package download locations.

### ISSUE THREAD

**Issue by bdubbs** [pypi/warehouse#15990]
At linuxfromscratch.org we publish build instructions for over 1000 open source packages including many Python modules.  We are starting to see module source code being placed in relatively obscure locations.  For example, for the gi-docgen module the location for the previous version is available at 

https://files.pythonhosted.org/packages/source/g/gi-docgen/gi-docgen-2023.3.tar.gz.  

However the current version appears to only be available at 

https://files.pythonhosted.org/packages/d1/86/d17f162d174b6340031fc96474405f13d50ceda4b6bf6588593cf31eb84b/gi_docgen-2024.1.tar.gz

We are seeing the same issue for several other modules (.e.g. requests).  Can you please help putting all modules in the appropriate location under the https://files.pythonhosted.org/packages/source/ directory tree.

**Comment by di** [comment]
Hi, please see https://warehouse.pypa.io/api-reference/integration-guide.html#predictable-urls.

For example, you can find the `2024.1` version at https://files.pythonhosted.org/packages/source/g/gi_docgen/gi_docgen-2024.1.tar.gz
