### ISSUE TITLE
Flask-Mail docs weren't fully deleted from pythonhosted.org

### ISSUE THREAD

**Issue by davidism** [pypi/warehouse#16002]
We recently moved the Flask-Mail docs to Read the Docs. I used the UI in PyPI to delete the docs for the project from pythonhosted.org. That successfully deleted the docs from https://pythonhosted.org/Flask-Mail/, but there appears to be another copy at https://pythonhosted.org/flask-mail/ (note the lower case name) that remains up. First, can you please remove this copy as well?

It seems like there wasn't a check for other forms of the same name during the deleting. All names that normalize to the project name should probably be considered as part of the deletion.

**Comment by ewdurbin** [comment]
cleanup for flask-mail is done. i think this can be left open as needing addressed though.
