### ISSUE TITLE
Possible O(n) query on the upload view

### ISSUE THREAD

**Issue by dstufft** [pypi/warehouse#16026]
When investigating https://github.com/pypi/warehouse/pull/16025 I noticed that the upload view was executing several queries like this:

```
SELECT releases.description_id AS releases_description_id 
FROM releases 
WHERE releases.id = %(pk_1)s::UUID
```

and 

```
SELECT release_descriptions.content_type AS release_descriptions_content_type, release_descriptions.raw AS release_descriptions_raw, release_descriptions.html AS release_descriptions_html, release_descriptions.rendered_by AS release_descriptions_rendered_by, release_descriptions.id AS release_descriptions_id 
FROM release_descriptions 
WHERE release_descriptions.id = %(pk_1)s::UUID
```

It appeared to be one set of two queries for every release that existed on the project I was uploading, and the very next query was

```
UPDATE releases SET _pypi_ordering=%(_pypi_ordering)s::INTEGER WHERE releases.id = %(releases_id)s::UUID
```

So I suspect this bit of code:

https://github.com/pypi/warehouse/blob/eabc81dd0cd18145a44de4f116f65031a73c345e/warehouse/forklift/legacy.py#L801-L815

**Comment by di** [comment]
Fixed in #16448.
