### ISSUE TITLE
Unable to register at Pypi.org

### ISSUE THREAD

**Issue by algotrader-br** [pypi/warehouse#16080]
When I try to register my account at Pypi I get the following error:

"The username is invalid. Usernames must be composed of letters, numbers, dots, hyphens and underscores. And must also start and finish with a letter or number. Choose a different username."

I think this problem is very similar to this issue:
https://github.com/pypi/warehouse/issues/15959

**Comment by di** [comment]
Hi @algotrader-br, are you maybe putting your email address in the username field? Could you share a screenshot of the username you're trying and the resulting error message?

**Comment by algotrader-br** [comment]
Hi @di , this is what I tried (it is in portuguese):

![print_error_pypi](https://github.com/pypi/warehouse/assets/133046782/9bc9920f-ab08-4b34-ac8f-ed8df694da1e)

**Comment by di** [comment]
Hi @algotrader-br,  you are putting your email address in the username field. Try putting your username instead!

**Comment by algotrader-br** [comment]
It worked! Thank you @di!

My mistake, sorry.
