### ISSUE TITLE
twine upload triggers SSL: SSLV3_ALERT_BAD_RECORD_MAC error and fails

### ISSUE THREAD

**Issue by yihming** [pypi/warehouse#16092]
**Describe the bug**

When I tried to release a new version by

```
python -m twine upload dist/* --repository <my-package>
```
I encountered the following SSL error:
```
Retrying (Retry(total=9, connect=5, read=None, redirect=None, status=None)) after connection broken by 'SSLError(1, '[SSL: SSLV3_ALERT_BAD_RECORD_MAC] ssl/tls alert bad record mac (_ssl.c:2578)')': /legacy/
```
And the upload finally failed.

**Expected behavior**

**To Reproduce**

**My Platform**

I tried on both macOS and Ubuntu Linux

Python 3.9
OpenSSL 3.3.1

**Additional context**

**Comment by yihming** [comment]
It seems the issue was at the server side. I can now upload without issues.

**Comment by 811414114** [comment]
https://github.com/orgs/community/discussions/126737

**Comment by 811414114** [comment]
https://github.com/orgs/community/discussions/126737
