### ISSUE TITLE
Latex rendering issue for project's README on PyPI website

### ISSUE THREAD

**Issue by tlunet** [pypi/warehouse#16134]
**Describe the bug**

### Problem description

Hi, I've recently uploaded a small package on PyPI for computational mathematics : [qmat](https://pypi.org/project/qmat/)

The main [README.md file](https://github.com/Parallel-in-Time/qmat/blob/main/README.md) contains some base formula using the latex `array` environment, that are rendered correctly on GitHub :

![image](https://github.com/pypa/packaging-problems/assets/12183839/a9e371e7-5124-414f-9e59-197281561c6b)

 but not on the PyPi website :

![image](https://github.com/pypa/packaging-problems/assets/12183839/04c6ea62-38fd-44fb-b9a8-24f6d09c1962)

Since PyPI markdown format is supposed to follow the format used by Github, I don't know if this is a bug with the current PyPI interface, or a formatting problem during packaging ?

**Expected behavior**

See above ...

**To Reproduce**

None ...

**My Platform**

Currently on Ubuntu 22.04, tried with Firefox, Chrome, Brave (latest versions)

**Additional context**

[pyproject.toml of the package](https://github.com/Parallel-in-Time/qmat/blob/main/pyproject.toml)

**Comment by di** [comment]
Hi @tlunet, thanks for the report. Descriptions on PyPI are rendered by https://github.com/pypa/readme_renderer, which in turn uses https://github.com/theacodes/cmarkgfm to render GitHub-flavored markdown specifically. If this is a bug, it may be in that library or it may be in one of its subdependencies. I would recommend opening this issue there with a minimal reproducing example instead, as this isn't an issue with PyPI itself.

**Comment by tlunet** [comment]
Thanks for the references ! Seems to be a small issue with `cmarkgfm` indeed, cf https://github.com/theacodes/cmarkgfm/issues/67
