### ISSUE TITLE
Add Prohibited Domains list to Admin UI

### ISSUE THREAD

**Issue by miketheman** [pypi/warehouse#16135]
Now that we not only rely on the disposable-email-domains, and have our own domain blocklist (see #15672) we should be able to display these and manage them in the Admin UI.

We likely need:

- new routes to display paginated entries, update/remove entries
- html templates
- a search function - or at least a DataTables setting

**Comment by samjove** [comment]
Would this be similar to what exists for prohibited project names?

**Comment by miketheman** [comment]
> Would this be similar to what exists for prohibited project names?

Yes, that's the general idea.

**Comment by samjove** [comment]
Great I'll work on this

**Comment by miketheman** [comment]
@samjove any progress? If not, that's okay! I'll be looking to start on this tomorrow, since I'm finding the need to get this done sooner.
