### ISSUE TITLE
Make it clear that a "pending" publisher does not reserve a name

### ISSUE THREAD

**Issue by woodruffw** [pypi/warehouse#16157]
Writing this up for myself.

@miketheman pointed out that users can be confused by the behavior/language of "pending" publishers:  we should make both the docs and the form (more) explicit about the fact that a "pending" publisher does not reserve the to-be-created name, and that another user may invalidate the "pending" publisher by creating the project first.

(This is already made clear by the emails we send on pending publisher invalidation, but we can further clarify it.)

**Comment by woodruffw** [comment]
#16158 has the changes!

**Comment by miketheman** [comment]
Thanks!!
