### ISSUE TITLE
Documentation issues (typos and diagrams)

### ISSUE THREAD

**Issue by warsaw** [pypi/warehouse#16159]
**Describe the bug**
There doesn't seem to be a documentation specific template, so this appears to be the best match.  I'm reading through the various (excellent!) documentation on warehouse and have noticed a few issues:

* Some minor spelling and grammar issues in `frontend.rst`
* Difficult to read diagrams on several pages, such as `architecture.md`.  These diagrams are especially difficult to read on dark themed web pages.

**Expected behavior**

Fixed typos and better diagrams.

**To Reproduce**

An [example](https://warehouse.pypa.io/architecture.html) of poorly readable diagrams.  Select light theme for slightly better readability, dark theme for poorer readability.

**My Platform**

Brave browser FWIW.

**Additional context**

I'll put up a PR soon and follow up here for the typo fixes.  I'm just going through a few other pages first.  I don't know how to make the diagrams more readable.

**Comment by warsaw** [comment]
![Screenshot 2024-06-24 at 16 28 55](https://github.com/pypi/warehouse/assets/210184/c942e993-69d6-469d-aeb0-19d7f58120d9)
![Screenshot 2024-06-24 at 16 28 37](https://github.com/pypi/warehouse/assets/210184/06802d82-b838-4cfd-8a65-79581eee5429)

Dark and light theme screen caps for illustration.

**Comment by miketheman** [comment]
> An [example](https://warehouse.pypa.io/architecture.html) of poorly readable diagrams. Select light theme for slightly better readability, dark theme for poorer readability.

Track for resolution https://github.com/mermaid-js/mermaid/issues/4906

In the meantime, it'd be great to add an admonition above the diagram of "best viewed in light mode" or something like that.

**Comment by warsaw** [comment]
Fixed
