### ISSUE TITLE
Parallelize the test suite

### ISSUE THREAD

**Issue by woodruffw** [pypi/warehouse#16178]
From conversation wit @miketheman: the tests *do* currently parallelize cleanly, but coverage is broken in the process. My SWAG explanation is that coverage's intermediate files may be generated with the same seed in each process, resulting in clobbered outputs.

WIP branch from above: https://github.com/pypi/warehouse/compare/main...miketheman:miketheman/pytest-xdist?expand=1

I've asked @DarkaMaul to take a look at this once his queue is empty 🙂

**Comment by DarkaMaul** [comment]
Hi all - I've spent some time analyzing this issue.

I managed to find a solution to improve the coverage report using `sitecustomize.py`. 

The idea is borrowed from [coverage documentation](https://coverage.readthedocs.io/en/latest/subprocess.html) and is also used by `pytest-cov` plugin : [here](https://github.com/pytest-dev/pytest-cov/blob/master/src/pytest-cov.pth)

My work-in-progress is available [here](https://github.com/miketheman/warehouse/pull/2057)

I get about 99% coverage, with the following report

```
+ python -m coverage report -m --fail-under 100
Name                                    Stmts   Miss Branch BrPart  Cover   Missing
-----------------------------------------------------------------------------------
warehouse/admin/views/ip_addresses.py      29      1      6      1    94%   26
warehouse/api/config.py                    17      1      4      1    90%   28
warehouse/api/echo.py                      28      2     10      1    92%   24-26
warehouse/events/models.py                117      1     62      1    99%   29
warehouse/observations/models.py           73      2     16      1    97%   32-34
warehouse/observations/tasks.py            38      4     14      1    90%   25-30
warehouse/oidc/interfaces.py               14      3      0      0    79%   37, 47, 58
warehouse/organizations/models.py         209      3     37      1    98%   49-52
warehouse/packaging/models.py             368      1     95      1    99%   84
warehouse/utils/db/windowed_query.py       25      1     10      1    94%   27
-----------------------------------------------------------------------------------
TOTAL                                   14622     19   4590      9    99%
```

A progress, but still not complete.
