### ISSUE TITLE
Links underlined rather aggressively on Chromium on Android

### ISSUE THREAD

**Issue by leoheitmannruiz** [pypi/warehouse#16191]
**Describe the bug**
Links are underlined rather aggressively and different from Firefox on Android or Firefox/Chromium on desktop.

**Expected behavior**
I expect links to be underlined in the same way as on other browsers/platforms.

**To Reproduce**
Visit pypi.org on Chromium on Android

**My Platform**
Vanadium 126.0.6478.122 on GrapheneOS

![vanadium](https://github.com/pypi/warehouse/assets/148111793/099a4d80-b305-4452-97ec-46047bafb287)

**Comment by di** [comment]
Hi @leoheitmannruiz thanks for reporting. I think this will be fixed by #16267 once that's deployed in a few minutes but I actually couldn't reproduce in any browsers I have access to. If you could verify, would appreciate it, thanks!
