### ISSUE TITLE
JSON API Reference is missing information on metadata 2.2 and 2.3 fields

### ISSUE THREAD

**Issue by dralley** [pypi/warehouse#16190]
**Describe the bug**

This JSON API reference: https://github.com/pypi/warehouse/blob/main/docs/dev/api-reference/json.rst

Is missing documentation on the "dynamic" and "provides_extra" fields, added in versions 2.2 and 2.3 of the core metadata specification (https://packaging.python.org/en/latest/specifications/core-metadata/).

The example output shown in the reference is missing them entirely, yet they can currently be seen if you query the JSON API.

**Expected behavior**
API reference should include these fields

**Comment by dralley** [comment]
@konstin re: https://github.com/pypi/warehouse/pull/13606

**Comment by di** [comment]
Thanks! I've added the "Good First Issue" label to this issue.

**Comment by dralley** [comment]
Perchance could you comment here w/ what those fields look like when populated (or point to a package where they are not null, I had trouble finding one)

**Comment by dralley** [comment]
Thanks!

**Comment by samjove** [comment]
Working on this
