### ISSUE TITLE
Trusted publishing: pending publisher should warn about ultranormalized name collision

### ISSUE THREAD

**Issue by twm** [pypi/warehouse#16226]
**What's the problem this feature will solve?**

I created a pending publisher when I named my package:

![image](https://github.com/pypi/warehouse/assets/43662/d4000458-44b5-4aad-bcb9-a07c6181f4ed)

But when I tried to use it I [got an error](https://github.com/twm/coveragepth/actions/runs/9824421246/job/27123375336#step:4:12):

> Error: Trusted publishing exchange failure: 
> Token request failed: the server refused the request for the following reasons:
> 
> * `invalid-payload`: The name 'coveragepth' is too similar to an existing project. See https://pypi.org/help/#project-name for more information.

It's probably colliding with [coverage_pth](https://pypi.org/project/coverage_pth/), the abandoned package I'm trying to replace.

**Describe the solution you'd like**

The PyPI UI should warn that the pending publisher will fail to create the package due to a name conflict. I'd expect this check to happen on page load, since the UI warns that races are possible:

![image](https://github.com/pypi/warehouse/assets/43662/938d1506-953d-403f-bbe2-f0f03488e4cc)

Alternatively, it could be treated as a form validation error like a closer match does:

![image](https://github.com/pypi/warehouse/assets/43662/55aa6dbd-b111-44b5-83c2-4792206af688)

**Additional context**

Related issues:

- #11139
- #2082

**Comment by woodruffw** [comment]
Thanks for the report @twm!

I agree this should be a form error, like the second screenshot you posted.

(A variant of this error will still be possible when a project with a too-similar name is created between the pending publisher's creation and use. But that should be much less common.)

**Comment by twm** [comment]
Thanks @woodruffw! I would also be happy to give it a go myself if that'd be helpful.

**Comment by woodruffw** [comment]
No problem with me!
