### ISSUE TITLE
Missing most recent versions of package PySimpleGUI27. Possible data loss on the server?

### ISSUE THREAD

**Issue by liam-baker-sm** [pypi/warehouse#16345]
**Describe the bug**

Current version of package pySimpleGUI27 missing between versions 1.38.0 to last released version 2.4.1
We have some in house software which depended on the version 2.4.1 of package PySimpleGUI27 from pip. About a month ago, pip starts to tell us that version 2.4.1 no longer exists and the latest version is 1.3.7. 

**Expected behavior**

Latest version is 2.4.1 published Sep 7, 2019
![image](https://github.com/user-attachments/assets/ab3da6ec-d2ce-4fa0-be34-2501dc615a64)

**Actual behavior**
Latest version is 1.3.7, published Jun 2, 2019
![image](https://github.com/user-attachments/assets/f60592ab-d812-47ca-ab01-8712b92adbac)

**To Reproduce**

- Visit https://pypi.org/project/PySimpleGUI27/#history in any browser
- Attempt to download pinned version 2.4.1 of PySimpleGUI27 with pip.

**My Platform**

**Additional context**

The web archive shows 2.4.1 was available for download until at least April of 2024
http://web.archive.org/web/20240414141947/https://pypi.org/project/PySimpleGUI27/#history

**Comment by miketheman** [comment]
@liam-baker-sm The owner of PySimpleGUI27 has removed these releases themselves, I recommend you reach out to them directly to inquire they they may have removed these releases.
