### ISSUE TITLE
Pressing slash in Organization Description jumps to search

### ISSUE THREAD

**Issue by jaraco** [pypi/warehouse#16371]
**Describe the bug**

When attempting to create a new organization, I'm filling out the form and I want to add a URL to the description. When I press the slash key, the UI jumps to the search box in the header, making it impossible to enter a slash without some sort of workaround like copy/paste.

**Expected behavior**

Slash character should be allowed, or if it's disallowed, it should be validated out and not jump to the search box. Jumping to the search box should only happen when there's no focus on an input control.

**To Reproduce**

1. Create a new organization.
2. In the Description, type a slash.

**My Platform**

* Firefox 128.0.3
* macOS 14.5

**Additional context**

Here's a screen recording of the issue:

https://github.com/user-attachments/assets/dbc22a87-9a99-48ae-bcad-3aa0f4a71616

**Comment by miketheman** [comment]
Related code is here: https://github.com/pypi/warehouse/blob/b28d08f5b375c9537aa880019aff8db624233619/warehouse/static/js/warehouse/controllers/search_focus_controller.js#L20

**Comment by jaraco** [comment]
That's lightning fast. Thanks!
