### ISSUE TITLE
PyPi incorrectly renders RST definition lists

### ISSUE THREAD

**Issue by divenex** [pypi/warehouse#16387]
When the `README.rst` file contains RST [definition lists](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#definition-lists), which requires a space **before** the colon, like

    term : classifier
        Definition

They are rendered by PyPi without the colon and spaces, like `termclassifier`.

![image](https://github.com/user-attachments/assets/efef00a2-45b9-4d4e-8aed-2067c1a19567)

**Comment by di** [comment]
Hi @divenex, thanks for the report. Descriptions on PyPI are rendered by https://github.com/pypa/readme_renderer, which in turn uses hhttps://pypi.org/project/docutils/ to render reStructuredText specifically. If this is a bug, it may be in that library or it may be in one of its subdependencies. I would recommend opening this issue there with a minimal reproducing example instead, as this isn't an issue with PyPI itself.
