### ISSUE TITLE
outlook.com is blocked from registering new accounts

### ISSUE THREAD

**Issue by leukipp** [pypi/warehouse#16386]
**Describe the bug**
It seems that @outlook.com is blocked from registering new accounts.

The following message appears when trying to register a new account on https://pypi.org/account/register:
`You can't use an email address from this domain.`
![image](https://github.com/user-attachments/assets/67a89cfe-d257-4792-84cf-a1416686530e)

**Expected behavior**
@outlook.com is a widely used and legit domain. Please consider making it available.

**Additional context**
Registering an account on https://test.pypi.org with an @outlook.com address works without any problems.

**Comment by cofiem** [comment]
This blog post is relevant: https://blog.pypi.org/posts/2024-06-16-prohibiting-msn-emails/

**Comment by leukipp** [comment]
Thanks for the blog post, I totally missed that!

I honestly understand that this is out of your hands and the move was necessary to prevent bots, mass signups, malware and abuse.
But I also want to avoid creating a random, redirected or throwaway email address for account registration, because that would just make the whole thing even more absurd.

Is there any other way to create an account with my primary e-Mail Address? Maybe by creating a ticket or you contacting me personally on social media?

Thanks

**Comment by di** [comment]
Hi @leukipp, sorry you're having trouble registering. Like @cofiem mentioned, we're currently unable to deal with the additional spam/bots that come from outlook and hotmail email addresses. For the time being, we're planning to keep this ban in place and recommend creating an additional email address elsewhere and redirecting to your primary inbox.

**Comment by nicolgit** [comment]
on https://blog.pypi.org/posts/2024-06-16-prohibiting-msn-emails/ I read "We hope that this change does not need to be permanent" as today I still not able to use my 20 years old @outlook.com addess :-( is this action still relevant and required?

**Comment by xgboosted** [comment]
@di I am on the same boat as @nicolgit, unable to register using my trusty old outlook email.

**Comment by AyOhEe** [comment]
This is unfortunate, but perhaps too harsh. I feel that there's likely little harm in allowing secondary email addresses under MSN domains - the user has already registered using a non-MSN email.
