### ISSUE TITLE
Test PyPi not working

### ISSUE THREAD

**Issue by byungchan0725** [pypi/warehouse#16402]
**Describe the bug**
After uploading a package to Test PyPI, the latest version is not being downloaded. The pip install command retrieves an older version instead.

**Expected behavior**
When running the command pip install -i https://test.pypi.org/simple/ vridge-tensorflow, the latest version of the package (0.0.4) should be downloaded. However, version 0.0.1 is being downloaded instead. Additionally, an error occurs stating that version 0.0.4 cannot be found.

**To Reproduce**
1. Upload the package vridge-tensorflow to Test PyPI.
2. Execute the following command
`pip install -i https://test.pypi.org/simple/ vridge-tensorflow`
3. Verify that version 0.0.1 is downloaded.
4. Attempt to install version 0.0.4 and receive an error saying "version not found."

**My Platform**
- Operating System: Windows
- Browser: Chrome
- IDE: PyCharm

**Additional context**
- Package Name: vridge-tensorflow
- Latest package version on Test PyPI: 0.0.4
- The issue persists even after several hours.

**Comment by di** [comment]
I see the package listed at `/simple`:

```
$ curl -s https://test.pypi.org/simple/  | grep vridge-tensorflow
<a href="/simple/vridge-tensorflow/">vridge-tensorflow</a>
```

And version 0.0.4 listed at `/simple/vridge-tensorflow`:

```
$ curl -s https://test.pypi.org/simple/vridge-tensorflow/ | grep 0.0.4
<a href="https://test-files.pythonhosted.org/packages/9c/1e/2a1944917d79653e0ef58772ffe1b312ed32163d34d1f641266004e0deb6/vridge_tensorflow-0.0.4-py3-none-any.whl#sha256=94b4867a9b4e07749c69c49610901242054ca01f45d3e350b5df6f835eb125ac" data-requires-python="==3.7" data-dist-info-metadata="sha256=b544befd8faca50a0b643304f11802d35029a5aeeda304b924859713d3b163c4" data-core-metadata="sha256=b544befd8faca50a0b643304f11802d35029a5aeeda304b924859713d3b163c4">vridge_tensorflow-0.0.4-py3-none-any.whl</a><br />
<a href="https://test-files.pythonhosted.org/packages/9e/62/a57adbbd3a1a3cfdb4e0c03f28f51e2cd506cb97f744c9bb1810dd291675/vridge_tensorflow-0.0.4.tar.gz#sha256=6a4d5340cd84ea1fc03f45e9a9594b59cb8f8388f20fb5e54d489a3811dc3c87" data-requires-python="==3.7" >vridge_tensorflow-0.0.4.tar.gz</a><br />
```

Is it possible that you're installing with the wrong Python version? Looks like the package has a strict requirement on Python 3.7 for versions 0.0.2, 0.0.3 and 0.0.4.

```
$ pip install -i https://test.pypi.org/simple/ vridge-tensorflow
Looking in indexes: https://test.pypi.org/simple/
ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python <3.10,>=3.7; 0.0.2 Requires-Python ==3.7; 0.0.3 Requires-Python ==3.7; 0.0.4 Requires-Python ==3.7
ERROR: Could not find a version that satisfies the requirement vridge-tensorflow (from versions: none)
ERROR: No matching distribution found for vridge-tensorflow
```

**Comment by byungchan0725** [comment]
> 잘못된 Python 버전으로 설치하고 있는 게 가능할까요? 패키지에 Python 3.7 버전 0.0.2, 0.0.3, 0.0.4에 대한 엄격한 요구 사항이 있는 것 같습니다.
> 
> ```
> $ pip install -i https://test.pypi.org/simple/ vridge-tensorflow
> Looking in indexes: https://test.pypi.org/simple/
> ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python <3.10,>=3.7; 0.0.2 Requires-Python ==3.7; 0.0.3 Requires-Python ==3.7; 0.0.4 Requires-Python ==3.7
> ERROR: Could not find a version that satisfies the requirement vridge-tensorflow (from versions: none)
> ERROR: No matching distribution found for vridge-tensorflow
> ```


After modifying setup.py to python_requires='>=3.6, <3.9' and creating a new package called vridge-test-tf, the package was found correctly.

However, I encountered an issue where install_requires does not work during the package download. For example, when install_requires specifies numpy>=1.19.2, the following error occurs:

```
ERROR: No matching distribution found for numpy>=1.19.2
```
However, if I activate the virtual environment and first run pip install numpy==1.19.2, then running `pip install -i https://test.pypi.org/simple/ vridge-test-tf` afterwards succeeds without issues.

**Comment by di** [comment]
Yes, this is because TestPyPI does not have all versions of all libraries, e.g. there is only one version available for numpy: https://test.pypi.org/project/numpy/

You might want to use `--extra-index-url` instead to install your package from TestPyPI.

**Comment by byungchan0725** [comment]
Additionally, the vridge-tf package uploaded to PyPI works as expected.

`pip install vridge-tf`

**Comment by byungchan0725** [comment]
I got the problem. Thank you :)
