### ISSUE TITLE
Recovery Code Loop

### ISSUE THREAD

**Issue by WiktorProj** [pypi/warehouse#16453]
**Describe the bug**

The recovery codes password confirm keeps looping to itself

https://github.com/user-attachments/assets/f0eecdfb-a90f-4dcf-b4fc-653fd323dd33

**Expected behavior**

Should generate recovery codes

**To Reproduce**

https://pypi.org/manage/account/recovery-codes/generate

**Additional context**

I have the same name on PyPI and TestPyPI

**Comment by di** [comment]
I can't reproduce this. Are you sure you're using the correct password? It looks like we don't output a warning when the password is incorrect (#16460).

I also don't see any user named `WiktorProj` on PyPI or TestPyPI, what is your username?

**Comment by WiktorProj** [comment]
my name on PyPI is Wikithr

**Comment by di** [comment]
It looks like you were able to successfully generate recovery codes on 2024-08-11 at 17:18 UTC, are you still experiencing this issue?
