### ISSUE TITLE
500 Error on upload after enabling 2FA

### ISSUE THREAD

**Issue by xavdid** [pypi/warehouse#16451]
**Describe the bug**

After enabling 2FA on a PyPI account, a Github Actions publish step with a pre-existing token got 500 errors when uploading files (the package and script had not changed)

```
 INFO     Response from https://upload.pypi.org/legacy/:                         
         500 Internal Server Error                                              
INFO     <html>                                                                 
           <head>                                                               
             <title>Internal Server Error</title>                               
           </head>                                                              
           <body>                                                               
             <h1><p>Internal Server Error</p></h1>                              
                                                                                
           </body>                                                              
         </html>   
```

**Expected behavior**

Either:

- existing (pre-2FA) tokens still work for uploads, or
- the server returns an error instructing the user to generate a new token

**To Reproduce**

1. Have an account without 2FA
2. Create an API token
3. publishing works normally now (or server returns a 400 about requiring 2FA)
4. Add 2FA to account
5. Attempt to publish again using token from step 2

**My Platform**

Github actions. You can see the logs [in this CI run](https://github.com/stripe/stripe-python/actions/runs/10311218331/job/28584033857)

Image: ubuntu-22.04
Version: 20240804.1.0

**Additional context**

After creating a new token and adding it to GHA, the upload completed as normal (same publishing script, same artifacts)

**Comment by di** [comment]
This is likely due to this outage: https://status.python.org/incidents/3rs39x4wyc94

Can you retry?

**Comment by xavdid** [comment]
After changing the token, the upload was successful. But, it's also possible the bug was fixed exactly when I replaced the token; I had a failure at 12:12pm PDT and a success at 12:44pm PDT (with the new token).

I don't think I can make a PyPI account without 2FA at this point so I can't verify, but I'm good to close if you don't think this is an underlying issue.

**Comment by di** [comment]
The bug that caused that outage was introduced at 10:47 AM PDT and fixed at 12:31 PM PDT. We don't have any other known issues related to 2FA, so I think it's likely due to that outage. Closing!
