### ISSUE TITLE
Gitlab's repository URL didn't marked as verified after trusted publishing

### ISSUE THREAD

**Issue by nE0sIghT** [pypi/warehouse#16475]
**Describe the bug**
I just tested URL verify (merged in the https://github.com/pypi/warehouse/pull/16205) for Gitlab and found that repository git URL didn't became verified: https://pypi.org/project/apt-mirror/9a1/

**Expected behavior**
Gitlab URLs like `https://gitlab.com/apt-mirror2/apt-mirror2.git` are verified after trusted publishing.

**Comment by woodruffw** [comment]
What happens if you change your GitLab URL to remove the `.git` prefix? As-is, I suspect it's not being marked as verified because it's failing this check:

https://github.com/pypi/warehouse/blob/293a2304379326abf2bdc90073f944ff9d8119b2/warehouse/forklift/legacy.py#L485-L488

(Tweaking this check is tricky, but not necessarily impossible -- we'd need to special case suffixes like `.git` when checking subpaths. But I think the majority of people use "bare" URLs for GitHub and GitLab, in practice.)

**Comment by di** [comment]
We should be safe to strip `.git` from the end of GitHub URLs if present:

<img width="708" alt="image" src="https://github.com/user-attachments/assets/873ad71d-adf8-4bd7-9453-6a8f70e10f6c">

Add I'm assuming the same is true with GitLab as well.

**Comment by nE0sIghT** [comment]
> What happens if you change your GitLab URL to remove the .git suffix?

Didn't tested it yet, but I believe it will be fine

> I think the majority of people use "bare" URLs for GitHub and GitLab, in practice

Just a note here that the repository URL example in the ["Writing your pyproject.toml"](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/) PyPA article have `.git` suffix:

![image](https://github.com/user-attachments/assets/60f0c4b6-47cf-4ccb-8035-d63f0bc31b5a)
 
(it's a place where I referenced while writing pyproject.toml for my initial pypi publishing)

**Comment by woodruffw** [comment]
Gotcha! TIL that's recommended in the PyPA guide 🙂 

(I was off in my estimation too -- it should be relatively easy for us to specialize the suffix check for GitHub and GitLab.)

**Comment by facutuesca** [comment]
> We should be safe to strip `.git` from the end of GitHub URLs if present:
> 
> <img alt="image" width="708" src="https://private-user-images.githubusercontent.com/294415/357563336-873ad71d-adf8-4bd7-9453-6a8f70e10f6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2Mzg5NjIsIm5iZiI6MTcyMzYzODY2MiwicGF0aCI6Ii8yOTQ0MTUvMzU3NTYzMzM2LTg3M2FkNzFkLWFkZjgtNGJkNy05NDUzLTZhOGY3MGUxMGY2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxMjMxMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZmU2OGJiNzE1MzMwZTQ4MGU3NDNkZmYwODE5ZWI2NGJhYjJlZDBlYzM1YjE0NDJmNTU2YTY1YjE1NjIyMTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4AvLu8e5zYGXVAS41qmdu-3-TuF9R9HXseSqSvw9Ao8">
> Add I'm assuming the same is true with GitLab as well.

----

Documenting here that it's true for GitLab as well:


<img width="922" alt="image" src="https://github.com/user-attachments/assets/541a44cd-20d0-4de9-a4c9-23bfd33c0eee">
