### ISSUE TITLE
After I entered the wrong email address the first time, I was unable to change it

### ISSUE THREAD

**Issue by SongTong98** [pypi/warehouse#16579]
<img width="620" alt="123" src="https://github.com/user-attachments/assets/c0259fb1-4846-4f68-ae5a-8031d93be68e">
After I entered the wrong email address the first time, I was unable to change it，It seems that I can't change my email before verification

**Comment by di** [comment]
Note the help message: "If you cannot verify a primary email address, please see https://pypi.org/help/#account-recovery".
