### ISSUE TITLE
could not login in pypi.org - session invalidate

### ISSUE THREAD

**Issue by mazzalab** [pypi/warehouse#16600]
Hi,
I'm experiencing the same issue #14881 
I've sent an email to support@pypi.org, no answer.
How to resolve?

thanks

![image](https://github.com/user-attachments/assets/99465bcb-ac56-4f65-9a86-73f0dcb044ed)

**Comment by di** [comment]
Hi, I see a response from our support staff on Aug 21, please see that email.

**Comment by mazzalab** [comment]
I do not get that email. Can you reply here?
