### ISSUE TITLE
Word wrap plain text project descriptions

### ISSUE THREAD

**Issue by wyattscarpenter** [pypi/warehouse#16606]
**What's the problem this feature will solve?**

Since https://github.com/pypi/warehouse/commit/2116945657693114231d22697d7ec7f6cfe08578 (I suppose), plain text project descriptions (eg, "readme.txt") are displayed on pypi as html pre-formatted text (`<pre>`). This is good. However, this means they don't word wrap, which makes them far more annoying to read; if the line is significantly long, the user must horizontally scroll a lot. Here's a screenshot from my project, https://pypi.org/project/golgotha/

![image](https://github.com/user-attachments/assets/ba417f30-5506-4c90-b321-313969597c84)

**Describe the solution you'd like**

The pre-formatted text should word-wrap.

This is (should be?) absolutely trivial in modern HTML&CSS. You just have to add `white-space: pre-wrap;` to the style of the element.

**Additional context**

I would open up a pull request to make this change myself, but I'm not sure what this project considers the "right" way to add CSS (which file does it go in, or does it just get attached to the element, does it go in a `pre {}` rule or some more specific class rule, etc).

**Comment by di** [comment]
Hi, thanks for the issue. One of the reasons why we haven't applied word-wrapping to plaintext project descriptions is because sometimes this may have the effect of wrapping descriptions that users don't want to wrap, for example if a description has an ASCII table, ASCII art, etc, without any way to prevent it from happening.

For users that do want word wrapping, we would recommend using Markdown for your description instead, but I'm curious if there there is any reason why this won't work for you in this case?

**Comment by wyattscarpenter** [comment]
Good considerations. I think anyone making ASCII art/tables that are quite wide must suspect that systems won't display them properly, but I can see the argument for supporting them anyway, even at the expense of The presentation of normal text. If the design decision here has been resolved definitively, feel free to close this issue. 

There's no particular reason I can't use markdown for my readme — except, of course, the inconvenience of making sure everything in the markdown file is properly escaped if it needs to be.

**Comment by di** [comment]
> Good considerations. I think anyone making ASCII art/tables that are quite wide must suspect that systems won't display them properly, but I can see the argument for supporting them anyway, even at the expense of The presentation of normal text.

Consider also that PyPI is also frequently browsed on mobile devices, so a plaintext description would not have to be very wide to trigger horizontal scrolling or word wrapping.

> There's no particular reason I can't use markdown for my readme — except, of course, the inconvenience of making sure everything in the markdown file is properly escaped if it needs to be.

I suspect that you would be able to change the extension of your readme to `.md` and it will just work, Markdown only requires additional syntax if you are trying to move beyond plaintext to formatted text.

> If the design decision here has been resolved definitively, feel free to close this issue.

I don't think we have any plans to change this for now, so I will close, but thanks for raising it!
