### ISSUE TITLE
Sponsoring PyPI support staff 

### ISSUE THREAD

**Issue by MadcowD** [pypi/warehouse#16656]
**What's the problem this feature will solve?**
Hi there! I've been using PyPI for a long time now. Recently, we [posted an issue on the PyPI support page](https://github.com/pypi/support/issues/4721). While looking through other issues, I noticed that there's a few week backlog of support tickets.

**Describe the solution you'd like**

Over the years, PyPI support has been great at helping me fix [problems](https://pypi.org/project/minerl/) quickly during my time at Carnegie Mellon and after at OpenAI. I'm really thankful for that and think that the PyPI team does a fantastic job. However, given the increasing user base of PyPI I wonder if it'd be possible to directly sponsor this aspect of PyPI.

We'd like to look into possibly sponsoring some extra support staff or helping out with resources to reduce the workload. We want to give back to the community that's helped us so much. It'd be great if other developers could keep getting the same great support we've had.

I'm not sure where the right channels are or who is directly in charge of managing the support repo, but would love to know more.

**Comment by ewdurbin** [comment]
Hi @MadcowD, thanks for reaching out. The best contact for this would be sponsors@python.org.

**Comment by MadcowD** [comment]
@ewdurbin Do you know anyone on the PyPI mod team I can speak to directly about this issue as well so I can calibrate the level of contribution needed when I go to the sponsors@python.org committee? I specifically have noticed that no PEP 541 requests have been addressed in the past 3 months, with tickets going back to [April 18, 2023](https://github.com/pypi/support/issues/2771)? I want to get a sense of how best to help here!
