### ISSUE TITLE
UTF-8 Encoding Issue on Module Page

### ISSUE THREAD

**Issue by azuk4r** [pypi/warehouse#16654]
On the /project/module page, emojis are not displaying correctly, likely due to a lack of UTF-8 support. Instead of emojis, there are incorrect symbols. I've attached screenshots showing the issue:

![Captura de pantalla 2024-09-07 204443](https://github.com/user-attachments/assets/145c02ed-1c11-4dce-963f-854cb3f6a70e)
![Captura de pantalla 2024-09-07 204451](https://github.com/user-attachments/assets/ac911254-c44a-4f4d-8dda-0e43ed7db6fc)

**Comment by miketheman** [comment]
Can you provide a link to an actual page with the problem?

**Comment by azuk4r** [comment]
https://pypi.org/project/torsel 

I have the issue in the README that reads the front

**Comment by miketheman** [comment]
Thanks. This appears to be a duplicate of https://github.com/pypi/warehouse/issues/1663 
Closing.
