### ISSUE TITLE
Verified GitHub links should probably ignore case for orgs

### ISSUE THREAD

**Issue by edgarrmondragon** [pypi/warehouse#16666]
**Describe the bug**

For project, [meltanolabs-tap-postgres](https://pypi.org/project/meltanolabs-tap-postgres/), the homepage link points to https://github.com/meltanolabs/tap-postgres (org in lower case), but the trusted publisher was created with `MeltanoLabs/tap-postgres` (org in upper case).

The result is that the links to the GitHub repo are not "verified".

**Expected behavior**

Links to the GitHub repo are verified when using trusted publishers even when the GitHub org doesn't match the case.

**To Reproduce**

NA, see description of the problem above.

**My Platform**

**Additional context**

The easy workaround on our end is simply to use consistent casing throughout, but I though I'd still log in case y'all think this is a bug.

**Comment by woodruffw** [comment]
Thanks @edgarrmondragon! If I understand correctly, this is indeed a bug in the verification handling -- GitHub slugs are case insensitive, so we should always be similarly insensitive when verifying them. I'll look at a fix today.

**Comment by woodruffw** [comment]
I looked into this a bit, and it's indeed a bug: GitHub and GitLab (at minimum) have case-insensitive `owner/repo` slugs, meaning we should compare them case insensitively.

Doing this with the current abstraction is a little painful, though (since we currently centralize URL verification across all publisher types, and not all publishers are necessarily insensitive).

**Comment by edgarrmondragon** [comment]
Gotcha, granted this is easy to fix on the user's end. Thanks for acknowledging it!

**Comment by woodruffw** [comment]
No problem! It's also pretty easy to fix on the Warehouse side, but not "20 minutes between bigger tasks" easy 😅 -- I'll try and get to it this weekend.
