### ISSUE TITLE
Error messages show non-PEP 625 filenames for PEP 625 compliant source dists

### ISSUE THREAD

**Issue by konstin** [pypi/warehouse#16687]
**Describe the bug**

I have upload a source dist called `upload_test_1-0.2.1.tar.gz`. When i attempt a re-upload, i get the following error:

```
400 File already exists ('upload-test-1-0.2.1.tar.gz', with blake2_256 hash 'ef4b7d1074c2d14f70a5c0763b49db9616901d72fb044db962ef242db888c2bd'). See https://test.pypi.org/help/#file-name-reuse for more information.
```

In the error, the filename uses package name normalization, not dist name normalization.

**Expected behavior**

Warehouse uses either the original name or PEP 625 (https://peps.python.org/pep-0625/#specification) normalized name in all user visible strings.

**To Reproduce**

Upload an sdist to testpypi. Reupload a different source dist with the same name to trigger an error message.

**My Platform**
n/a

**Additional context**
n/a

**Comment by di** [comment]
Could you provide some more context? The specific commands and filenames you're using for each upload attempt would be helpful.

I'm guessing that you originally uploaded a file that would normalize to `upload_test_1-0.2.1.tar.gz`, renamed the file to `upload-test-1-0.2.1.tar.gz`, and then tried to upload it again, is that correct? I think that would produce the error message you're seeing.

In this case, the error message is attempting to provide details about the file the user is trying to upload, not the file that already exists, so it will contain whatever filename the user is trying to upload.

**Comment by konstin** [comment]
This was indeed an error in the client (renaming the file in the upload form) and not about the warehouse output, sorry for the noise!
