### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by qiufengcute** [pypi/warehouse#16712]
![屏幕截图 2024-09-15 073339](https://github.com/user-attachments/assets/31011b3b-f34c-4ef3-b3e0-eb528edcf780)

Why???

**Comment by ewdurbin** [comment]
Unfortunately we have seen repeated automated malware and abuse campaigns from users using these email addresses, read more at https://blog.pypi.org/posts/2024-06-16-prohibiting-msn-emails/
