### ISSUE TITLE
High latency / timeouts accessing cryptography's simple index page

### ISSUE THREAD

**Issue by alex** [pypi/warehouse#16725]
Accessing the simple index page for cryptography is currently experiencing high latency, leading to timeouts with `pip`:

```
$ time curl 'https://pypi.org/simple/cryptography/'
```

can be used to reproduce the high latency. This appears to be somewhat intermittent, but reproducing regularly for me.

Currently seeing this from both my residential internet in the US east coast, as well as from Github Actions (Azure?).

**Comment by alex** [comment]
This problem appears to have begun between approximately 6:18PM and 6:24PM (all times Eastern).

**Comment by di** [comment]
We're having some issues rolling out #16562 which is causing latency issues with `/simple`. We're in the process of reverting to a prior deployment.

**Comment by di** [comment]
This should now be resolved.

**Comment by alex** [comment]
Thanks for the prompt response.
