### ISSUE TITLE
2FA and password reset emails are still sent to user's old email address even after primary email address is updated

### ISSUE THREAD

**Issue by Thespi-Brain** [pypi/warehouse#16761]
**Describe the bug**
After the account recovery process is completed through the "Start Account Recovery" tool, even after the primary email address is updated, both users and user logs indicate receiving the 2FA and password reset emails in their old email addresses. Note: subsequent emails do get sent to the newly updated primary email address, it seems that emails being sent to the old email address occurs right during the recovery process.

**Expected behavior**
The 2FA/password reset emails should go to users' newly updated primary email addresses, not their previous email addresses.

**To Reproduce**
-  Use "Start Account Recovery" process with an alternate email/new primary email for user
- Upon completion of the process, 2FA/recovery codes/password should be reset and the primary email checkbox will show the updated email address
- But logs will indicate the notification sent to the old email address even if the checkbox for this email under "Primary" will be unchecked

**Additional context**
Related to this [issue ](https://github.com/pypi/warehouse/issues/16401) and this [issue](https://github.com/pypi/warehouse/pull/16516).

**Comment by ewdurbin** [comment]
I _think_ that's because https://github.com/pypi/warehouse/blob/main/warehouse/admin/views/users.py#L575 happens before we update the users email address.

**Comment by miketheman** [comment]
> I _think_ that's because [`main`/warehouse/admin/views/users.py#L575](https://github.com/pypi/warehouse/blob/main/warehouse/admin/views/users.py?rgh-link-date=2024-09-24T14%3A20%3A00Z#L575) happens before we update the users email address.

Thanks - that was the issue. I placed it later and tested manually, and the emitted email has the new address.
