### ISSUE TITLE
Some download links are broken

### ISSUE THREAD

**Issue by maxbachmann** [pypi/warehouse#16766]
**Describe the bug**
I uploaded a new version (v0.26.0) for https://pypi.org/project/python-Levenshtein/ and https://pypi.org/project/Levenshtein/ two days ago. When creating the conda forge releases for this new version I noticed that the following download links appear to be broken:
- https://pypi.io/packages/source/p/python-Levenshtein/python-Levenshtein-0.26.0.tar.gz
- https://pypi.io/packages/source/L/Levenshtein/Levenshtein-0.26.0.tar.gz

Both of them fail with a 404 file not found. For older versions this works as expected:
- https://pypi.io/packages/source/p/python-Levenshtein/python-Levenshtein-0.25.1.tar.gz
- https://pypi.io/packages/source/L/Levenshtein/Levenshtein-0.25.1.tar.gz

**Expected behavior**
I would expect to be redirected to the correct download url.

**Comment by di** [comment]
Looks like you've changed the filename:

* For `0.25.1`, it's `Levenshtein-0.25.1.tar.gz`: https://pypi.org/project/Levenshtein/0.25.1/#files
* For `0.26.0`, it's `levenshtein-0.26.0.tar.gz`: https://pypi.org/project/Levenshtein/0.26.0/#files

**Comment by maxbachmann** [comment]
Good catch. Looks like the changed build backend normalizes the wheel name.
