### ISSUE TITLE
SSL Error: Unable to Connect to HTTPS URL for PyPy-3.10-nightly version on Windows

### ISSUE THREAD

**Issue by aparnajyothi-y** [pypi/warehouse#16802]
Windows github hosted runner and [failure links](https://github.com/actions/setup-python/actions/runs/11098960252/job/30832442213) for reference.

We need to fix this as soon as possible as it is breaking the setup-python workflows.

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  setup-pypy:
    name: Setup PyPy ${{ matrix.pypy }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        pypy:
          - 'pypy-3.10-nightly'
          

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup-python ${{ matrix.pypy }}
        id: setup-python
        uses: ./
        with:
          python-version: ${{ matrix.pypy }}
Error we are getting is mentioned below
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
  Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
  ERROR: Could not find a version that satisfies the requirement pip (from versions: none)
  ERROR: No matching distribution found for pip
  WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
  Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
  The process 'D:\a\_temp\5871[35](https://github.com/actions/setup-python/actions/runs/10957214111/job/30424936558?pr=947#step:3:36)78-6f7f-47f8-a4ec-62dcdc704c0d\pypy-c-jit-185389-9ca9d9be1715-win64\python.exe' failed with exit code 1
  Error: The process 'D:\a\_temp\58713578-6f7f-47f8-a4ec-62dcdc704c0d\pypy-c-jit-185389-9ca9d9be1715-win64\python.exe' failed with exit code 1

**Comment by ewdurbin** [comment]
Hi @aparnajyothi-y. Based on the error `(Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))` it appears that this is an issue with the pypy distribution or underlying OS causing the ssl module to fail to load, and thus not PyPI.

You'll need to work with the `setup-python` maintainers, GHA support, or PyPy team to resolve this issue.
