### ISSUE TITLE
Reuploaded package tarball filename includes '-reupload'

### ISSUE THREAD

**Issue by sveetch** [pypi/warehouse#16869]
**Describe the bug**
I'm pretty sure this is not a bug but i didn't found any information on warehouse documentation about this behavior.

So i'm parsing the package releases files from the Legacy API (`/simple/<project>/`) and in results for `html5lib` package i found that its `1.0` release tarball is named `html5lib-1.0-reupload.tar.gz`. I assume this is the correct behavior but i didn't found any explicit documentation about it.

**Expected behavior**

I was not expecting reuploaded package filename to be marked with `-reupload` although it seems accurate.

I'm just wondering if there is any explicit documentation about it and if there was other similar behavior for other specific cases ?

**To Reproduce**

- Make a request to the Legacy API for the endpoint [/simple/html5lib/](https://pypi.org/simple/html5lib/)
- In the 'files' search for the 1.0 release item
- Look at the tarball filename 

**My Platform**

- Python 3.10
- I'm doing this parsing from a tool which check about requirements informations
- The tool is using `requests` package to make a request to the Legacy API in JSON format

**Comment by di** [comment]
This is generally not expected behavior, at least anymore. The release in question is almost 7 years old ("Released: Dec 7, 2017") and there's a fair amount of cruft from times when we did less validation of file ames, metadata, etc. This seems to be one example.

**Comment by sveetch** [comment]
Ah ok thanks, but i suppose these package release filename won't never change so i need to still supporting it, no ?

**Comment by di** [comment]
Yes, this is what was originally uploaded, and we don't (usually) make corrections.

**Comment by sveetch** [comment]
Thanks for the informations
