### ISSUE TITLE
Connection Resets from Specific Source

### ISSUE THREAD

**Issue by nshobe** [pypi/warehouse#16905]
**Describe the bug**

When installing packages from pypi we're seeing intermittent connection resets/failures to download or even query for packages. This seems to be happening across all our internal org when coming out of a specific location. We've done what we can to inspect the drops with our networking team but there's no indication of blocking happening at our firewalls, or issues with our provider. We do see tcp resets, seemingly initiated by the endpoint.

The specific endpoints we see lots of resets from:
 - 104.17.254.182
 - 104.17.255.182
 - 151.101.192.223
 - 151.101.0.233
 - 162.247.243.20

And our public facing IP is:
 - 192.149.76.131

The behavior is erratic enough that simply retrying several times can lead to _eventual_ success, but for anything 
**Expected behavior**

`pip install` functions without networking failures
**To Reproduce**

This will be very difficult to reproduce outside our networks I fear. But it's easily reproduced on our end every time we install a python package with a large list of dependencies.

**My Platform**

We're pretty much exclusively Linux as a source. Source python versions are 3.7 and 3.11 though we've reproduced in other versions as well. Pip versions on clients seeing this issue range from 18 to latest.
**Additional context**

**Comment by di** [comment]
Closing this as we haven't had any similar reports, and so this is likely an issue with your source rather than with Warehouse itself.

If you're still experiencing this, filing a [network access issue](https://github.com/pypi/support/issues/new?template=access-issues.yml) with the relevant information is preferred and would help us determine what might be happening here.

**Comment by di** [comment]
Also, note that some of these IPs don't appear to be PyPI IP addresses (https://pypi.org/help/#ips) so there might be something else going on here as well.
