### ISSUE TITLE
Error to create account

### ISSUE THREAD

**Issue by Julieteandrade** [pypi/warehouse#16955]
I can't create my account on pypi, it doesn't accept any emails. I've already tried using 3 different emails and I get the error message.

**Comment by ewdurbin** [comment]
Hello @Julieteandrade, what email domain(s) are you trying to use to register?

**Comment by Julieteandrade** [comment]
Hello !
I tried to use three diferent e-mails:
***@***.***
***@***.***
***@***.***


but none were accepted.

________________________________
De: Ee Durbin ***@***.***>
Enviado: quarta-feira, 23 de outubro de 2024 11:16
Para: pypi/warehouse ***@***.***>
Cc: Julieteandrade ***@***.***>; Mention ***@***.***>
Assunto: Re: [pypi/warehouse] Error to create account (Issue #16955)


Hello @Julieteandrade<https://github.com/Julieteandrade>, what email domain(s) are you trying to use to register?

**Comment by ewdurbin** [comment]
Hi @Julieteandrade, unfortunately GitHub masks email addresses when responses are sent via e-mail.

Can you share just the domain portions of the addresses you tried to use?

**Comment by Julieteandrade** [comment]
gmail , hotmail and outlook.

________________________________
De: Ee Durbin ***@***.***>
Enviado: quarta-feira, 23 de outubro de 2024 15:43
Para: pypi/warehouse ***@***.***>
Cc: Julieteandrade ***@***.***>; Mention ***@***.***>
Assunto: Re: [pypi/warehouse] Error to create account (Issue #16955)


Hi @Julieteandrade<https://github.com/Julieteandrade>, unfortunately GitHub masks email addresses when responses are sent via e-mail.

Can you share just the domain portions of the addresses you tried to use?

**Comment by ewdurbin** [comment]
hotmail and outlook are blocked from registration, please see https://blog.pypi.org/posts/2024-06-16-prohibiting-msn-emails/

I'm unsure why an @gmail.com address would be blocked unless the email was already in use. can you share the error message you receive when registering with that address?

**Comment by di** [comment]
Closing due to lack of response.
