### ISSUE TITLE
Entered incorrect email and now can't fix it

### ISSUE THREAD

**Issue by travisgk** [pypi/warehouse#17020]
**Describe the bug**
I entered my email incorrectly and now my newly-created account can't be verified and I can't add a new email either.

**Expected behavior**
The website says I can add a new address but no option is to be seen.

**To Reproduce**
Create an account with an invalid email address and try to add a functional email.

**My Platform**
Chrome, Windows 11

**Additional context**
Using a @users.noreply.github.com email address.

**Comment by di** [comment]
Please see https://pypi.org/help/#account-recovery.
