### ISSUE TITLE
Cannot upload whl to testpypi - 400 Invalid distribution file

### ISSUE THREAD

**Issue by msquaredds** [pypi/warehouse#17111]
**Describe the bug**
I cannot upload my whl file to test PyPI. I have a project that I've been uploading to regularly and today, when trying to upload my whl file, I get the following error:

```
INFO     Response from https://test.pypi.org/legacy/:
         400 Bad Request
INFO     <html>
          <head>
           <title>400 Invalid distribution file. WHEEL not found at streamlitauth-0.7.18.dist-info/WHEEL</title>
          </head>
          <body>
           <h1>400 Invalid distribution file. WHEEL not found at streamlitauth-0.7.18.dist-info/WHEEL</h1>
           The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>
         Invalid distribution file. WHEEL not found at streamlitauth-0.7.18.dist-info/WHEEL
          </body>
         </html>
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/
         Bad Request
```

When I look in the whl file, I see the WHEEL file and it looks the same as it has in the past
This is the top level whl:
![Image](https://github.com/user-attachments/assets/75f63b34-b4d6-4af3-ae9d-9d600a275783)
Then the is the StreamlitAuth-0.7.18.dist-info folder:
![Image](https://github.com/user-attachments/assets/edb45855-8177-41fc-bf69-d02f1cdd65d4)
And finally the WHEEL file:
![Image](https://github.com/user-attachments/assets/9878ee67-5b13-4ad0-b3aa-c814511ed9b8)

**Expected behavior**
I would expect the upload to succeed.

**To Reproduce**
I run this in cmd:
`python -m twine upload --repository testpypi dist/StreamlitAuth-0.7.18-py3-none-any.whl --verbose`
Followed by __token__ and my password

**My Platform**
I'm using cmd in Windows 10 Home

**Additional context**
I can attach the actual files if necessary

**Comment by mrmundt** [comment]
+1 - we are having the same issue on Pyomo. We are trying to upload our wheels using `twine upload *.whl` and we get the error:
```
Uploading distributions to https://upload.pypi.org/legacy/
Enter your API token: 
Uploading Pyomo-6.8.2-cp310-cp310-macosx_10_9_x86_64.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB • 00:05 • 1.1 MB/s
WARNING  Error during upload. Retry with the --verbose option for more details.                                         
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/                                                
         Invalid distribution file. WHEEL not found at pyomo-6.8.2.dist-info/WHEEL 
```

**Comment by jinjingforever** [comment]
+1. Same happened for us when trying to upload a package to pypi

**Comment by rjw57** [comment]
Looking at the blame for the [relevant file](https://github.com/pypi/warehouse/blame/main/warehouse/forklift/legacy.py#L329), it looks like this change was only added an hour or so ago in https://github.com/pypi/warehouse/commit/f40fa5ee51f1e9996466dca4759a5e249dc54750.

I'm also seeing this in my CI publish jobs for wheel which were uploading just fine an hour or so ago. Example: https://github.com/rjw57/verify-oidc-identity/actions/runs/11902914356/job/33169114508 with wheels which can be downloaded from https://github.com/rjw57/verify-oidc-identity/releases/tag/0.3.4.

<details><summary>Relevant twine logs</summary>

```
Uploading distributions to https://test.pypi.org/legacy/
INFO     dist/verify_oidc_identity-0.3.4-py3-none-any.whl (10.1 KB)             
INFO     dist/verify_oidc_identity-0.3.4.tar.gz (9.1 KB)                        
INFO     password set by command options                                        
INFO     username: __token__                                                    
INFO     password: <hidden>                                                     
Uploading verify_oidc_identity-0.3.4-py3-none-any.whl
INFO     Response from https://test.pypi.org/legacy/:                           
         400 Bad Request                                                        
INFO     <html>                                                                 
          <head>                                                                
           <title>400 Invalid distribution file. WHEEL not found at             
         verify-oidc-identity-0.3.4.dist-info/WHEEL</title>                     
          </head>                                                               
          <body>                                                                
           <h1>400 Invalid distribution file. WHEEL not found at                
         verify-oidc-identity-0.3.4.dist-info/WHEEL</h1>                        
           The server could not comply with the request since it is either      
         malformed or otherwise incorrect.<br/><br/>                            
         Invalid distribution file. WHEEL not found at                          
         verify-oidc-identity-0.3.4.dist-info/WHEEL                             
                                                                                
                                                                                
          </body>                                                               
         </html>                                                                
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/          
         Bad Request                                                            
```
</details>

Note that the wheel has `verify-oidc-identity-0.3.4.dist-info/WHEEL` present but PyPI is looking for `verify-oidc-identity-0.3.4.dist-info/WHEEL`. Looks like the stricter verification code may need to `s/-/_/` in package names?

**Comment by kratsg** [comment]
I'm having this issue as well. Fundamentally, I think the problem relates to https://github.com/pypa/packaging-problems/issues/230 (and maybe https://github.com/pypa/build/issues/770 related too). Specifically, the [sdist spec](https://packaging.python.org/en/latest/specifications/source-distribution-format/#source-distribution-file-name) indicates that the package names need to be normalized.

In my case, I have a `project = "atlas-schema"` and it's built as `atlas_schema-{tag}.tar.gz` however pypi upload complains about this:

```
Uploading distributions to https://upload.pypi.org/legacy/
Uploading atlas_schema-0.1.0-py3-none-any.whl
WARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         Invalid distribution file. WHEEL not found at                          
         atlas-schema-0.1.0.dist-info/WHEEL          
```

because it's looking for `atlas-schema-{tag}` and not `atlas_schema-{tag}` which is why it cannot find the `WHEEL` file that does exist.

```
$ unzip -l dist/atlas_schema-0.1.0-py3-none-any.whl
Archive:  dist/atlas_schema-0.1.0-py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
      354  02-02-2020 00:00   atlas_schema/__init__.py
      411  02-02-2020 00:00   atlas_schema/_version.py
      118  02-02-2020 00:00   atlas_schema/_version.pyi
     5522  02-02-2020 00:00   atlas_schema/enums.py
     4111  02-02-2020 00:00   atlas_schema/methods.py
        0  02-02-2020 00:00   atlas_schema/py.typed
     7668  02-02-2020 00:00   atlas_schema/schema.py
      555  02-02-2020 00:00   atlas_schema/typing_compat.py
    16445  02-02-2020 00:00   atlas_schema-0.1.0.dist-info/METADATA
       87  02-02-2020 00:00   atlas_schema-0.1.0.dist-info/WHEEL
    11344  02-02-2020 00:00   atlas_schema-0.1.0.dist-info/licenses/LICENSE
      963  02-02-2020 00:00   atlas_schema-0.1.0.dist-info/RECORD
---------                     -------
    47578                     12 files
```

See failing workflow here: https://github.com/scipp-atlas/atlas-schema/actions/runs/11902924940/job/33168916369

**Comment by ewdurbin** [comment]
Yeah, the changes in #17107 weren't intended to be quite so restrictive on wheel filenames. I used the wrong parsing logic that normalized project names/versions. https://github.com/pypi/warehouse/pull/17112 will relax the unintended impact on wheels.

**Comment by jepler** [comment]
We were able to complete the upload of an [affected package](https://github.com/adafruit/Adafruit_CircuitPython_BME680) after #17112. However, I'm unclear whether this did indicate an actual bug in our packaging. Is action required to ensure our packages continue uploading in the future?
