### ISSUE TITLE
Not reciving the verification mail in test pypi

### ISSUE THREAD

**Issue by julianhill28416** [pypi/warehouse#17132]
**Describe the bug**
I have created a user in Test pypi and was asked to verify via a verification email.
When I checked my inbox (also the spam folder and all mail folder) I could not find the verification email.
I tried the resend button but still haven't received the verification.

**Expected behavior**
Receiving a verification email  

**To Reproduce**
Create an test pypi account and try to receive a verification email. 

**My Platform**
test.pypi.org

What could be the reason for this problem? any help would be highly appreciated.
Thank you.

**Comment by di** [comment]
Hi, please contact support@pypi.org and include your username and email.
