### ISSUE TITLE
"no token supplied" when following an invite to join a project at test.pypi.org

### ISSUE THREAD

**Issue by dimaqq** [pypi/warehouse#17157]
- I was logged into test.pypi.org
- I received an email from a colleague with a link to join a project on test.pypi.org
- I clicked the link
- landed on test.pypi.org list of my project with:
  - a red notice "not token supplied"
  - that project listed as waiting, and I can join it manually

**Comment by dimaqq** [comment]
token was about 7 hours old by the time I clicked the link.

**Comment by di** [comment]
Duplicate of #9510.
