### ISSUE TITLE
PyPI caching packages too long (updated release still not showing up after 12 hours after upload)

### ISSUE THREAD

**Issue by zopyx** [pypi/warehouse#17179]
I have upload my package `pp.server` in version 3.4.0 on 2024-11-26 at around 18:00 UTC and uploaded version 3.4.1 on 2024-11-27 at around  06:00 UTC.

When I look and search at PyPI, the old version 3.3.0.2 is still shown as most current version.

![Image](https://github.com/user-attachments/assets/81c9b372-16b6-49c8-b917-31e45246112b)
![Image](https://github.com/user-attachments/assets/9e379a34-b9e7-45e0-bf94-2441d5f6c640)

Is this an issue of over-caching or missing cache invalidation?

**Comment by miketheman** [comment]
The search index is often on a delay, but the package is immediately available for download.
