### ISSUE TITLE
How to login my account when my auth and recovery code are lost

### ISSUE THREAD

**Issue by user-11150** [pypi/warehouse#17195]
**Describe the bug**

I am just know token, username and password, auth apps and recovery codes is lost. How to login my account in webpage?

**Expected behavior**

Let me login my account

**To Reproduce**

**My Platform**

**Additional context**

**Comment by woodruffw** [comment]
> I am just know token, username and password, auth apps and recovery codes is lost. How to login my account in webpage?

You'll need to go through the account recovery process. 

Please fill out the account recovery issue here: <https://github.com/pypi/support/issues/new?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen&template=account-recovery.yml>
