### ISSUE TITLE
Undesirable formatting on recovery code generation page

### ISSUE THREAD

**Issue by ofek** [pypi/warehouse#17233]
https://pypi.org/manage/account/recovery-codes/generate

![Image](https://github.com/user-attachments/assets/51516f7f-ba86-4596-8d17-bd820a316784)

-----

https://pypi.org/manage/account/recovery-codes/burn

![Image](https://github.com/user-attachments/assets/e0835c0e-a0ac-4662-81bf-90a0b29c10b3)

**Comment by di** [comment]
Ooof, yes, confirmed that this looks quite bad.

This page [hasn't changed in a while](https://github.com/pypi/warehouse/blob/b156290a4d7a9fc60a9dbd9ff7ccadd8944ba991/warehouse/templates/manage/account/recovery_codes-provision.html#L42).

Perhaps this is due to #17160? cc @miketheman
