### ISSUE TITLE
Not receiving TestPyPI verification emails

### ISSUE THREAD

**Issue by gboeing** [pypi/warehouse#17249]
Similar to #4704 and #5957, I signed up for a test pypi account and have not received the verification emails I've tried to send a few times over the past two days. Email address is correct and it's not ending up in the spam folder. Test pypi username is gboeing.

**Comment by msfrisbie** [comment]
Also experiencing this, test username is mattfriz. Tried gmail and custom domain, neither delivered and it is not ending up in spam.

**Comment by skeletorXVI** [comment]
I'm experiencing the same issue. Test username is `skeletorXVI` and email address is with a custom domain.
