### ISSUE TITLE
The user '[My name]' isn't allowed to upload to project 'lbw'

### ISSUE THREAD

**Issue by Saltsmart** [pypi/warehouse#17254]
**Describe the bug**

Hello, I'm `saltsmart` on pypi.org.
I want to upload my package called `lbw` using `twine upload dist/*`, but get this:
```
WARNING  Error during upload. Retry with the --verbose option for more details.
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
         The user 'saltsmart' isn't allowed to upload to project 'lbw'. See
         https://pypi.org/help/#project-name for more information.
```

**Expected behavior**

The files are successfully upload.

**To Reproduce**

1. Create a void project called `lbw`, or use the file below:
[lbw.zip](https://github.com/user-attachments/files/18059956/lbw.zip)
2. Build and upload the project with the commands:
```
python -m build
twine upload dist/*
```

**My Platform**

twine version 6.0.1 (keyring: 25.5.0, pkginfo: 1.12.0, requests: 2.31.0, requests-toolbelt: 1.0.0, urllib3: 2.0.4)

**Additional context**

I have seen the website https://pypi.org/help/#project-name, which lists four reasons:
The project name conflicts with a [Python Standard Library](https://docs.python.org/3/library/index.html) module from any major version from 2.5 to present.
The project name is too similar to an existing project and may be confusable.
The project name has been explicitly prohibited by the PyPI administrators. For example, pip install requirements.txt is a common typo for pip install -r requirements.txt, and should not surprise the user with a malicious package.
The project name has been registered by another user, but no releases have been created.See [How do I claim an abandoned or previously registered project name?](https://pypi.org/help/#project-name-claim)

However, there is no `lbw` in Python Standard Library.
The website https://pypi.org/project/lbw/ returns `Page Not Found (404)`.
I wonder why `lbw` is not available.

**Comment by di** [comment]
It's not available because:

> The project name has been registered by another user, but no releases have been created

Please follow the steps in https://pypi.org/help/#project-name-claim if you'd like to claim this project name.
