### ISSUE TITLE
Remove `pycurl` dep?

### ISSUE THREAD

**Issue by woodruffw** [pypi/warehouse#17279]
I was perusing `main.in`, and I noticed that `pycurl` is a dep:

https://github.com/pypi/warehouse/blob/04cf4df20c50da9a4ca71fb85c82618db8427e99/requirements/main.in#L45

AFAICT, `pycurl` isn't used anywhere in the codebase, so this may be a dangling dep from a previous iteration/feature. Removing it should't cause any problems, and should reduce build times slightly.

Opening first as an issue to confirm that there's no hidden `pycurl` dep that keeps this from being deletable 🙂

**Comment by ewdurbin** [comment]
Was added in https://github.com/pypi/warehouse/commit/9aabda76624d26832a32ddc140f1de82d5b7a9a0, which added celery[sqs]. so it is just there for that.

we should let dependency resolution do its own thing indeed. thanks.
