### ISSUE TITLE
Getting 403 Error after transferring a project to a different org

### ISSUE THREAD

**Issue by Mariatta** [pypi/warehouse#17311]
**Describe the bug**
I transferred the project `python-docs-theme` from individual accounts to the `python` PyPI org.
After I transferred the project, I got redirected to https://pypi.org/manage/project/python-docs-theme/settings/ with 403 error code.

![Image](https://github.com/user-attachments/assets/79ebb563-d487-41a7-b33f-da0c40b9a685)

However the project was transferred correctly to the new org. When I load the project page, I saw a notification saying that the project was transferred.

![Image](https://github.com/user-attachments/assets/6e1e421a-2f9c-4544-9273-aae616d18ec4)

Somehow after the transfer, on the pypi page for python-docs-theme, it does not include myself as the maintainer, however the other maintainer's information are still listed there. It seems like my own access to the org was removed. 
Screenshot of the new maintainers list after the transfer.

![Image](https://github.com/user-attachments/assets/dd61f732-62a4-4f9b-b5c6-d26c7167ec96)

**Expected behavior**
- There shouldn't be a 403 error after transferring the project to the new org
- My access and permission should be retained after transferring

**To Reproduce**
- Not sure if there is a way to reproduce unless we try again transferring back the project?

**My Platform**
- On the browser

**Additional context**

**Comment by miketheman** [comment]
Appears to be https://github.com/pypi/warehouse/issues/13558

**Comment by Mariatta** [comment]
Screenshot of the original list of maintainers can be seen on this comment which was posted before the org transfer: https://github.com/python/python-docs-theme/issues/205#issuecomment-2490361297

**Comment by miketheman** [comment]
Added 'Mariatta' as 'Owner' on 'python-docs-theme'

Closing as duplicate, follow #13558 for resolution.

**Comment by Mariatta** [comment]
Thank you @miketheman
