### ISSUE TITLE
Support Groups/Organizations

### ISSUE THREAD

**Issue by dstufft** [pypi/warehouse#201]
Packages should be able to be owned/maintained by a group or organization which has it's own members. This will allow projects that have multiple PyPI projects to manage their permissions in one central location.

**Comment by brainwane** [comment]
@ncoghlan mentioned "orgs, teams, and role-based access control" [on distutils-sig](https://mail.python.org/pipermail/distutils-sig/2018-January/031860.html) as a future feature to explore, and noted this depends on PyPI serving as its own identity provider.

**Comment by kpfleming** [comment]
Dreaming of an amazing future, as an organization owner/manager, I'd absolutely love the ability to delegate authentication for my organization's users to our own identity/auth provider via SAML. In fact if Warehouse supported "scoped users" (so I can have a standalone user account 'kpfleming' and also an org-managed user account 'kpfleming@org'), that would be phenomenal.

**Comment by brainwane** [comment]
Speaking for [the Econ-Ark folks](http://econ-ark.org/) -- we'd like this too.

**Comment by stephenfin** [comment]
I'm interested in this from the perspective of @sphinx-contrib. What relationship, if any, does this have to #994? I assume that, for the simple case, this would merely mapping a user to a group and including the permissions of that group alongside the user's own?

**Comment by ashmastaflash** [comment]
Being able to have group ownership of repos would make user access much easier to manage.

**Comment by potiuk** [comment]
We have 59 packages to manage in Apache Airflow when we release 2.0. Individual management will be a total overkill if we do not have it.

**Comment by hsluoyz** [comment]
Hi guys, I'm from the Casbin team (https://casbin.org/) and we maintain a lot of Python-related packages on pypi (15 pkgs for now: https://pypi.org/search/?q=casbin), including our popular Python authorization library, PyCasbin: https://github.com/casbin/pycasbin (https://pypi.org/project/casbin/) . We have multiple pypi package maintainers and we definitely would like to see pypi has the support for organizations.

Besides, Casbin supports a lot of access control models including RBAC, RBAC with domains (aka organization): https://casbin.org/docs/en/supported-models . So I think we could also use Casbin in warehouse to implement the organization permisisons. It will save dev efforts from warehouse developers. We'd like to help if this idea sounds reasonable. Thanks!

**Comment by uranusjr** [comment]
Chiming in here. I’m looking into the possibility to allocate some paid time working on this feature, but it’s a bit diffuclut to evaluate the resource needed since this has not yet gone to the design phase. Is there some process I should go through before taking a shot on this?

**Comment by potiuk** [comment]
Happy to be involved at minimum to beta-test it and take part in design discussions. We have complex-ish setup in Apache Airflow and we are currently solving our needs by custom pearl scripts scraping the PyPI website and sending post requests :scream: .

**Comment by di** [comment]
@uranusjr I think this feature should probably be designed in tandem with https://github.com/pypa/warehouse/issues/2589 (namespaces) -- for example, it would make sense for the `apache` organization to own the `apache` namespace.

For both, I think the first step would be a PEP describing how namespaces/groups/organizations will work on PyPI, how existing tools are expected to be updated, how existing APIs will change, how namespace ownership is conferred, etc. Happy to collaborate on this.

**Comment by potiuk** [comment]
Never worked on PEP but happy to collaborate too :)

**Comment by njsmith** [comment]
@di IIRC namespaces had a lot of uncertainty around them? Like, are they even a good idea given python's flat global import namespace? I'm worried that linking them to this feature will make neither happen anytime soon.

On the other hand, I think a pretty minimal group permissions system like https://github.com/pypa/warehouse/issues/201#issuecomment-381026997 could reduce a lot of pain pretty quickly.  And it wouldn't need a PEP, I don't think, because it's just a new table or two in warehouse, not a fundamental change to how packages are organized.

**Comment by uranusjr** [comment]
I am under a similar impression. It seems to me the original request here is not permission-via-prefix (which namespaces would solve), but that projects can be owned/maintained by a multi-user kind of account (“flexible ACL model”). PyPI alreaduy has a user account system that’s not related to project names (I don’t need an account `pip` to manage the project `pip`), so I don’t see why group permissions need to be tied to project name prefixes (namespaces). While the group permission system does somewhat overlap with what namespaces can offer, it can also achieve different things and is desired no matter namespace happens or not. Neither should block the other, as long as we correctly consider things and leave enough room in the design and implementation.

**Comment by stephenfin** [comment]
For what it's worth, it appears this effort is well underway https://discuss.python.org/t/pypi-organization-account-roadmaps/14699. I spotted a couple of closed PRs (#11184, #11271, #11208, #11311, #11261, #11342, #11379, #11473) and one that is still in flight (#11665). There are also corresponding issues. It would be nice if those issues all linked back to this so we could see the progress but I'm just happy to see work on this feature finally happening :smile:

**Comment by dhalbert** [comment]
Are Organizations expected to be at least minimally functional by the time the 2FA requirement for critical projects comes into effect? Thanks.

**Comment by ewdurbin** [comment]
Yes, Organization support is here and is slowly rolling out.
