### ISSUE TITLE
Admin: Spam cleanup and prevention tooling

### ISSUE THREAD

**Issue by ewdurbin** [pypi/warehouse#2976]
Historically spammers have been rather naive by registering tons of packages from a single user account or IP address.

Our latest wave of spam has been coming from a multitude of users and IP addresses :(

I propose a couple parts in the Warehouse Admin UI for:

# ~~Complete delete of a user~~ (done)

  - Must display a list of all projects/releases to be deleted before execution
  - Must require explicit confirmation in some manner before execution
  - Should remove all projects and releases they have "contributed"
  - Should disable and trash the account

# Bulk delete from supplied package name list

  - Must display a list of all projects/releases to be deleted before execution
  - Must require explicit confirmation in some manner before execution
  - Should remove all projects and releases associated

**Comment by brainwane** [comment]
I discussed this with Ernest & Dustin and we decided that it's not in Milestone 1; if there are bits of this that we need to do by any particular milestone, such as Launch, then we'll break out issues and prioritize and do them separately.

**Comment by di** [comment]
This has been sufficiently resolved.
