### ISSUE TITLE
Move package claim issues

### ISSUE THREAD

**Issue by brainwane** [pypi/warehouse#3369]
Package claim issues will wait until PEP 541 process is in place, but once that is finished, migrate package claim issues from:

* https://github.com/pypa/pypi-legacy/issues
* https://sourceforge.net/p/pypi/support-requests/

**Comment by di** [comment]
We are down to a single page of pypi-legacy issues: https://github.com/pypa/pypi-legacy/issues

We should probably figure out #1506 and move all the PEP 541 issues into whatever system that will use.

**Comment by brainwane** [comment]
All props to @di for doing that work! A great mitzvah.

@di yeah, agreed, we should move the PEP 541 issues to that new system, but in the meanwhile, I am fine with moving this out of the launch milestone. :tada:

**Comment by anarcat** [comment]
How about the [old issue queue on Sourceforge](https://sourceforge.net/p/pypi/support-requests/)? Old discussions (like [this one](http://code.activestate.com/lists/python-distutils-sig/24089/)) refer people there and new request are still being filed there.

I know I [filed one over a year ago](https://sourceforge.net/p/pypi/support-requests/709/), right before PEP-0541 was created (!), until I found the "legacy" issue queue and filed https://github.com/pypa/pypi-legacy/issues/725 now six months ago.

So it will certainly be great to see this fixed!  :)

**Comment by di** [comment]
@anarcat Yes, we will migrate those issues as well, I've updated this issue's title and description accordingly.

Thanks for your patience!

**Comment by anarcat** [comment]
hmm... the repository was archived and issues not migrated - should we reopen issues here instead? where should claims be filed now? PEP541 doesn't say, nor do the [PyPI docs](https://pypi.org/help/#project-name-claim)...

**Comment by di** [comment]
WIth the creation of `pypa/pypi-support`, I'm calling this "done" unless anyone wants to take on the task of transferring issues from the old Sourceforge tracker. We haven't had a new one there in nearly a year, but it'd be nice to shut it down or provide a notice or something.

**Comment by brainwane** [comment]
@di I see ~17 [relevant open issues in the pypi-legacy GitHub tracker](https://github.com/pypa/pypi-legacy/issues); I do not think those got migrated to https://github.com/pypa/pypi-support/issues . Did they?

I'm beginning to transfer issues now from Sourceforge to https://github.com/pypa/pypi-support/issues .

**Comment by di** [comment]
@brainwane I'm struggling to recall what happened there. I think rather than migrating these potentially stale issues to pypi-support, we should ping the original authors of those issues and ask them to migrate their issue to pypi-support if it's still relevant.

If that sounds like a good plan of action to you, I can temporarily un-archive that repo so we can make the necessary comments and close those issues.

**Comment by brainwane** [comment]
@di Sure, your plan sounds fine! Please do un-archive the pypi-legacy repo. I'm happy to make those comments, close all 18 issues, and let you know so you can archive it again.

**Comment by brainwane** [comment]
And, similarly, instead of auto-migrating the potentially stale SourceForge issues using the data export and https://github.com/cmungall/gosf2github , I'll reply and close them and ask authors to please migrate them to https://github.com/pypa/pypi-support/issues .

**Comment by di** [comment]
Can't believe I just did that, but https://github.com/pypa/pypi-legacy is now un-archived.

**Comment by brainwane** [comment]
It'll be quick! I'm working now.

**Comment by brainwane** [comment]
@di I have now closed all but one PyPI-Legacy support ticket. I suggest you migrate https://github.com/pypa/pypi-legacy/issues/789 directly over to the support ticket queue, based on the linked issues. Then you can go ahead and archive it.

**Comment by di** [comment]
Done. I'll leave this open until you resolve the SourceForge issues.

**Comment by di** [comment]
@brainwane What's the status here?

**Comment by brainwane** [comment]
Hi Dustin. Still working on the backlog here.

**Comment by miketheman** [comment]
Closing, as all support issues are now handled via https://github.com/pypi/support/issues
