### ISSUE TITLE
add "search by new release" and "trending" sort orders, link to them from homepage

### ISSUE THREAD

**Issue by jfkw** [pypi/warehouse#3447]
Testing the new warehouse today at https://test.pypi.org, the list for "New Releases Hot off the press: the newest project releases" is only 5 items long. I can not find a link to view a longer list.

The older PyPI listing of 40 most recent packages was more usable given the rate of package uploads. A few projects upload many packages with each release.

A paged history of package uploads going back a day or two would be a welcome addition.

**Comment by brainwane** [comment]
@jfkw Thanks for testing and suggesting this! Would #3424 solve your issue?

**Comment by jfkw** [comment]
I do think the 'show more' buttons are a nice addition to the current home page. I'd still prefer to bookmark a list of 40+ recent packages, preferably with a paged history going back a day or so.

**Comment by brainwane** [comment]
@jfkw Thanks for the response. In the very short term, in case you haven't already looked at what libraries.io provides, here's their "recent PyPI releases" page:

https://libraries.io/search?order=desc&platforms=PyPI&sort=latest_release_published_at

But I get that this is something where it may well make sense to have more recent releases on the front page of pypi.org. I'll defer to our designer on this.

**Comment by nlhkabu** [comment]
Thanks for your feedback @jfkw 

Maybe we could introduce a new sort order 'by new releases' on the search results page?  We could then link through to this page, where you could *also* filter the latest releases?

@ewdurbin @di how much work might it be to add this sort order to the search results?

**Comment by di** [comment]
@nlhkabu I agree, I don't think it would be a ton of work, and the the user would be able to add classifiers/filters to the search as well.

**Comment by brainwane** [comment]
Potentially related: #3463.

**Comment by brainwane** [comment]
We just got some advice on #701 so maybe we could do that soon and then address @jfkw's request with a combination of #3424, #3463, and a "sort by new releases" sort order in search results.
