### ISSUE TITLE
ie11: Logo gets squished on small resolutions

### ISSUE THREAD

**Issue by nlhkabu** [pypi/warehouse#3504]
### How to reproduce

- Use IE11
- Make the browser window small

### What happens

The logo is "squished" and the menu items are not vertically centered

![screenshot from 2018-04-02 16-16-26](https://user-images.githubusercontent.com/3323703/38201750-38bcc3cc-3691-11e8-8c9e-bd2a94fef20e.png)

### What should happen

The logo should retain its aspect ratio, and the menu links should be centered vertically.

---

**Screenshot Required**: This issue will require an update to the visual design of the site. To help our team give you faster feedback, please include a screenshot in your Pull Request.

**Comment by dstufft** [comment]
Closing as IE11 is no longer supported.
