### ISSUE TITLE
ie11: badges not rendering correctly

### ISSUE THREAD

**Issue by nlhkabu** [pypi/warehouse#3505]
### How to reproduce

- Use IE11
- Go to https://pypi.org/project/pipsy/0.1.2/
- Go to https://pypi.org/project/pipsy/0.1.1/

### What happens

The version badges are broken.  This is even more obvious if you make the resolution smaller:

![screenshot from 2018-04-02 16-17-17](https://user-images.githubusercontent.com/3323703/38201784-556f84dc-3691-11e8-84ae-a2df75021956.png)

![screenshot from 2018-04-02 16-17-04](https://user-images.githubusercontent.com/3323703/38201785-558e58b2-3691-11e8-88c5-e721dd8bab7e.png)

### What should happen

They should look like this:

![screenshot from 2018-04-02 17-46-42](https://user-images.githubusercontent.com/3323703/38205259-da3c1cb4-369d-11e8-879a-05b0279de4de.png)

![screenshot from 2018-04-02 17-46-50](https://user-images.githubusercontent.com/3323703/38205258-da1e60f2-369d-11e8-9a7c-0cb75c482b71.png)

---

**Screenshot Required**: This issue will require an update to the visual design of the site. To help our team give you faster feedback, please include a screenshot in your Pull Request.

**Comment by dstufft** [comment]
Closing as IE11 is no longer supported.
