### ISSUE TITLE
ie11: description and button not centered vertically

### ISSUE THREAD

**Issue by nlhkabu** [pypi/warehouse#3506]
### How to reproduce

- Use ie11
- Log into an account with projects
- View one of the projects you manage

### What happens

The project description and 'manage' button are not centered vertically:

![screenshot from 2018-04-02 16-23-07](https://user-images.githubusercontent.com/3323703/38202016-30cc0442-3692-11e8-84af-10c6dcaca03f.png)

### What should happen

They should be centered vertically

---

**Screenshot Required**: This issue will require an update to the visual design of the site. To help our team give you faster feedback, please include a screenshot in your Pull Request.

**Comment by dstufft** [comment]
Closing as IE11 is no longer supported.
