### ISSUE TITLE
ie11: history timeline "lines" not connected on project history tab

### ISSUE THREAD

**Issue by nlhkabu** [pypi/warehouse#3507]
### How to reproduce

- Use IE11
- Go to https://pypi.org/project/pipsy/0.1.1/#history

### What happens

![screenshot from 2018-04-02 17-40-11](https://user-images.githubusercontent.com/3323703/38205028-f9e4a7c6-369c-11e8-9547-833b83646068.png)

### What should happen

![screenshot from 2018-04-02 17-40-32](https://user-images.githubusercontent.com/3323703/38205027-f9c5c748-369c-11e8-8ca3-f9ac7f902fce.png)

---

**Screenshot Required**: This issue will require an update to the visual design of the site. To help our team give you faster feedback, please include a screenshot in your Pull Request.

**Comment by nlhkabu** [comment]
Note - this seems to be even worse when there are more releases.  See https://pypi.org/project/Flask/#history as an example:

![screenshot from 2018-04-02 17-42-11](https://user-images.githubusercontent.com/3323703/38205098-392b43a4-369d-11e8-9fa9-2dc6a6b751de.png)

**Comment by dstufft** [comment]
Closing as IE11 is no longer supported.
