### ISSUE TITLE
Ordering of releases in JSON API

### ISSUE THREAD

**Issue by di** [pypi/warehouse#3650]
From https://github.com/pypa/pypi-legacy/issues/171

> Originally reported by: **Aaron Meurer (Bitbucket: [asmeurer](https://bitbucket.org/asmeurer), GitHub: [asmeurer](https://github.com/asmeurer))**
>
> ---
>
> One thing that the json API lacks compared to the xmlrpc API is the ordering of releases. In the json API, the releases are keys in a dictionary, and hence unordered. 
>
> The tarballs have upload times, but a release can have multiple tarballs, and also if I'm not mistaken you can upload a tarball to an old release. 
>
> The xmlrpc API has package_releases(package_name, show_hidden=False). The json API could have a package_releases key with a list of releases. I don't know how to handle hidden releases. 
>
> ---

**Comment by di** [comment]
More or less blocked on #284.

**Comment by miketheman** [comment]
Related: https://github.com/pypi/warehouse/pull/6570#issuecomment-1194963679

Recommending closing both, since JSON is explicitly unordered, and Python's behavior provides the desired end result.
