### ISSUE TITLE
Allow users to report that a package's description is rendered incorrectly

### ISSUE THREAD

**Issue by ishirav** [pypi/warehouse#4002]
**What's the problem this feature will solve?**
Looks like a significant percentage of packages provide a `long_description` in Markdown format, without providing the `long_description_content_type` necessary for it to be rendered correctly. This can happen for a variety of reasons:

- The package was released before `long_description_content_type` was available.
- The developer is unaware of `long_description_content_type`.
- The developer didn't use Twine, so the `long_description_content_type` was not transmitted to Warehouse.
- The developer doesn't care what the package looks like in Warehouse, as long as it looks fine in Github.

This is a problem that will exist for a very long time - even if all Python developers get the necessary "education" to provide the `long_description_content_type` properly, there will always be existing packages that are not being maintained and will never get fixed. Failing to render their descriptions properly is a disservice to Warehouse users, so I think it would be a good idea to improve rendering where possible.

**Describe the solution you'd like**
Issue #3896 talks about flagging problematic packages. Once such a mechanism is in place, it should be relatively easy to add a way for users to flag wrongly-rendered package descriptions. Basically a user interface on the package page to say "this should be Markdown". When used, a report should be added to some kind of moderation queue where it can be checked and accepted. Or, the whole process could be automated - once at least N users report it, the rendering should switch to Markdown without further human intervention.

**Additional context**
Some random examples of packages with Markdown descriptions that are rendered as plain text (they are very easy to come across):

- https://pypi.org/project/safety-django/#description
- https://pypi.org/project/number_to_string/#description
- https://pypi.org/project/bj-phone-number/#description
- https://pypi.org/project/z-format/#description
- https://pypi.org/project/tree-format/#description

**Comment by dstufft** [comment]
I'm going to close this. I don't think we would ever want to override the choices made by authors as to how their description should be rendered, and I'm very suspect of our ability to crowdsource this metadata even if we wanted to override those choices.
