### ISSUE TITLE
Create recommendation engine

### ISSUE THREAD

**Issue by nlhkabu** [pypi/warehouse#4407]
Feature request from user research:

It would be good to be able to expose similar packages in the UI based on based on trove, tags, etc.

I spoke to @pierresp at EuroPython about this - he said he would be interested in looking into what might be involved.

@pierresp let us know your thoughts!

**Comment by miketheman** [comment]
We never heard from the original requestor on this issue, and it's tough to conceive what related packages might be.
Other aggregators like libraries.io or libhunt.com are more suited to this work, so I'll close this issue. If more context or design is surfaced, please open a new issue.
