### ISSUE TITLE
Document project URLs icons

### ISSUE THREAD

**Issue by gbdlin** [pypi/warehouse#5682]
**What's the problem this feature will solve?**
Right now there is no way to know how project URLs will be handled. There is some logic that automatically assigns an icon to URLS, but no easy way to find out what icons are available and what to expect. 

**Describe the solution you'd like**
Basically, document [this](https://github.com/pypa/warehouse/blob/5cd92a3ecff5db2d04ba4c951830deceb34ed235/warehouse/templates/packaging/detail.html#L20-L54) logic somewhere.

**Comment by di** [comment]
Thanks for the request! I agree we should document this.

Can you give us a bit more information about _why_ you'd like to see this documented? E.g., have you seen different icons, and wasn't sure how to get them for your project?

**Comment by gbdlin** [comment]
I've managed to dig up that part of the code, so this is not an issue for me, but it most probably is for people that are not that familiar with warehouse code. Documenting this part (as it works in some way, so it can be used in projects) will help everyone in creating better project pages.

**Comment by di** [comment]
This is now resolved: https://docs.pypi.org/project_metadata/
