### ISSUE TITLE
HTML tables in Markdown readme files are rendered without honoring "colspan" and "rowspan"

### ISSUE THREAD

**Issue by s-m-e** [pypi/warehouse#5878]
**Describe the bug**

As the title says: HTML tables in Markdown readme files are rendered without honoring "colspan" and "rowspan".

**Expected behavior**

On GitHub for instance, my table is rendered like this:

![Screenshot_20190518_171137](https://user-images.githubusercontent.com/16851110/57971668-3c46c300-7991-11e9-86e5-bb8574749eae.png)

See [original](https://github.com/pleiszenburg/refuse/blob/v0.0.3/README.md#installation).

**To Reproduce**

On PyPI.org it is rendered like this:

![Screenshot_20190518_171123](https://user-images.githubusercontent.com/16851110/57971661-2d601080-7991-11e9-9e3f-2d9d58c68c2b.png)

See [original](https://pypi.org/project/refuse/0.0.3/).

**Comment by di** [comment]
Interestingly the raw description does contain the `colspan` and `rowspan` attributes:

```html
<table>
  <tr>
    <th>OS</th>
    <th colspan="2">API</th>
    <th colspan="6">arch</th>
  </tr>
  <tr>
    <th></th>
    <th>level</th>
    <th>version</th>
    <th>i386</th>
    <th>x86_64</th>
    <th>PPC</th>
    <th>PPC64</th>
    <th>arm64</th>
    <th>MIPS</th>
  </tr>
  <tr>
    <td rowspan="4">Linux</td>
    <td rowspan="2">high</td>
    <td>2</td>
    <td>yes</td>
    <td>yes</td>
    <td>yes</td>
    <td>yes</td>
    <td>yes</td>
    <td>yes</td>
  </tr>
  <tr>
    <td>3</td>
    <td>no</td>
    <td>no</td>
    <td>no</td>
    <td>no</td>
    <td>no</td>
    <td>no</td>
  </tr>
...
```
So it seems like this isn't a bug with `readme_renderer`, but I'm not sure how or why they'd be disappearing between the rendered readme and our UI.

**Comment by roniemartinez** [comment]
I also get this issue.

It is working fine on Github: https://github.com/roniemartinez/dude#supported-parsers

<img width="788" alt="image" src="https://user-images.githubusercontent.com/2573537/157854266-0c6130d6-9945-4653-88d1-59b1a4afa545.png">

But not on PyPI: https://pypi.org/project/pydude/

<img width="788" alt="image" src="https://user-images.githubusercontent.com/2573537/157854322-248de2c5-8443-4705-90f4-0b691b1276d2.png">

**Comment by miketheman** [comment]
Resolved via https://github.com/pypa/readme_renderer/pull/245
