### ISSUE TITLE
Document the package size limit

### ISSUE THREAD

**Issue by brunobord** [pypi/warehouse#6192]
**What's the problem this feature will solve?**

The [PyPI help page](https://pypi.org/help/#file-size-limit) describes what to do in case you hit the package upload size limit. But there's apparently no public document or page that says: *"File upload limit is X"*.
There are issues talking about 60MB, which is probably a good guess, because it's the MAX_FILESIZE set by default in the code. But the file in which it is set is called ``legacy.py`` so there's still doubt.
Also, an issue that says that the file upload limit is X in 2017 doesn't mean that the file size limit hasn't been changed since.

**Describe the solution you'd like**

I think that under the *"How do I get a file size limit exemption or increase for my project?"*, there could be a mention of what's the current file size limit, in order to make it clear for project maintainers.

**Additional context**

* [MAX_FILESIZE defined in legacy.py](https://github.com/pypa/warehouse/blob/master/warehouse/forklift/legacy.py#L60)
* [A year 2017 issue stating that the upload limit is 60MB](https://github.com/pypa/warehouse/issues/2017) *(and ironically, it has the number 2017)*

**Comment by miketheman** [comment]
FAQ source: https://github.com/pypi/warehouse/blob/fc5a2e4e6fafdfefef70b0b56f10274eb2ecb9b5/warehouse/templates/pages/help.html#L594-L630

The variables controlling the limits can be found here: https://github.com/pypi/warehouse/blob/532091757513f1ecda747708861a834c47d09257/warehouse/forklift/legacy.py#L72-L74

I'd prefer using the variables to control the output so as to prevent drift between the values and the docs. The "hard part" is translating the bytes values into more human-friendly MB/GB strings.
