### ISSUE TITLE
Switch from backrefs to explicit references

### ISSUE THREAD

**Issue by di** [pypi/warehouse#6320]
We currently use SQLAlchemy's `backref` property in a number of places, e.g. this line enables the `User.projects` attribute.

https://github.com/pypa/warehouse/blob/5dfcbf0a77861a5d3b30eaa6bca2e307c8b26d88/warehouse/packaging/models.py#L128

Backrefs are confusing to new contributors, however, since an attribute like `user.projects` is not listed on the `User` model where it would be expected.

We should explicitly define these relationships on both sides instead using backrefs. In addition, if possible, we should find a way to disable the use of the `backrefs` parameter to prevent this from being used in the future.

**Comment by miketheman** [comment]
Also noted that since SQLAlchemy 2.0, `backref` is considered legacy, in favor of `back_populates`
https://docs.sqlalchemy.org/en/20/orm/backref.html
