### ISSUE TITLE
Warehouse logo usage guidelines page with links to SVGs

### ISSUE THREAD

**Issue by webknjaz** [pypi/warehouse#6640]
**What's the problem this feature will solve?**

People will know how to properly use the Warehouse logos.

**Describe the solution you'd like**

A separate web-page under pypi.org having a style guide and usage conditions wrt the Warehouse logo.
Something like https://www.redhat.com/en/about/brand/standards/logo or https://www.python.org/community/logos/.

**Additional context**

* I want to have some graphics to use for https://github.com/pypa/gh-action-pypi-publish
* https://twitter.com/nlhkabu/status/1173467743112355840
* FWIW I've used it for the preview at this page https://github.com/topics/github-action, I hope that's fine for now

**Comment by nlhkabu** [comment]
@ewdurbin I believe the PSF was in the process, or have already, placed a trademark on the PyPI logo.  Could you please look into this and let me know the best next steps?

Thanks

**Comment by webknjaz** [comment]
@nlhkabu @ewdurbin did this ever actually happen? I don't think I've seen anything published to date.

**Comment by ewdurbin** [comment]
My understanding is that "PyPI" has been issued trademark but the logo itself has not been. @VanL do you know the status of the logo mark registration for PyPI?

**Comment by VanL** [comment]
The registration on the logo for PyPI has been granted.
Building blocks alone: Reg. 5752245
Building blocks plus "Python Package Index": Reg. 5764496

Thanks,
Van

**Comment by ewdurbin** [comment]
Thanks Van! I guess the next steps here would be to determine what a usage policy would look like, who would moderate it, and have someone build such a page.

**Comment by VanL** [comment]
I would suggest that for these marks, that there is no allowed use outside
of what we do.

Thanks,
Van

**Comment by webknjaz** [comment]
Can we define who's "we"? The PSF? The PyPA? The PyPI/Warehouse project?

**Comment by ewdurbin** [comment]
I suppose on further consideration, unlike all of the other PSF held trademarks...

- "Python" a widely used and adaptable programming language
- "PyCon" an idea / core name for an event
- "PyLadies" a chaptered organization

"PyPI" and associated logo represent a single entity/service, so usage outside of our presence on the web doesn't make sense in the same ways.

For all intents and purposes "PyPI" is the service hosted at pypi.org, so I think "we" in this case is limited to that service and its associated web presence.

**Comment by webknjaz** [comment]
@ewdurbin it's currently present in a “social preview” (that thing displayed when you paste a link on Twitter or Facebook, and lists like https://github.com/topics/github-actions-python) of this page https://github.com/marketplace/actions/pypi-publish. It is technically quite coupled with the PyPI service, but is under PyPA currently.
Should I rework it, then?

**Comment by di** [comment]
IMO, that's fine. What we're mostly concerned about is people using the logo for things that aren't "PyPI" -- e.g., some other index or private repo.

**Comment by webknjaz** [comment]
Right, that's what I wanted to clarify. What's fair use and what's absolutely forbidden.

**Comment by VanL** [comment]
Our messaging around the name and logo marks for PyPI should be that they
always exclusively need to refer to the service hosted at pypi.org. Yes,
nominative fair use exists, but we don't need to call it out (and even
nominative fair use is fair use because it still refers to our single
source for the PyPI service - pypi.org).

Our statement should be:

"PyPI", the "Python Package Index", and the PyPI blocks logo are registered
trademarks of the Python Software Foundation referring to the products and
services associated with pypi.org. Any other use by any other party is
prohibited.

Thanks,
Van

**Comment by di** [comment]
That makes sense to me!

**Comment by ewdurbin** [comment]
Opened #12405 to document this on pypi.org.
