### ISSUE TITLE
Autodetect the locale based on the preferred browser language

### ISSUE THREAD

**Issue by webknjaz** [pypi/warehouse#6864]
The browser communicates such intent using `Accept-Language` header that lists a number of locales in the order of priority.

For example, if HTTP request contains `Accept-Language: uk,en`, this means that the browser is asking the server to provide the content in Ukrainian, if possible, and fall back to English if Ukrainian is not available.

Currently, PyPI ignores this header completely.
<details>
<summary>curl log</summary>

```console
$ curl -svH 'Accept-Language: uk,en' https://pypi.org | head -c 500
*   Trying 2a04:4e42:200::223:443...
* TCP_NODELAY set
* connect to 2a04:4e42:200::223 port 443 failed: No route to host
*   Trying 2a04:4e42::223:443...
* TCP_NODELAY set
* connect to 2a04:4e42::223 port 443 failed: No route to host
*   Trying 2a04:4e42:400::223:443...
* TCP_NODELAY set
* connect to 2a04:4e42:400::223 port 443 failed: No route to host
*   Trying 2a04:4e42:600::223:443...
* TCP_NODELAY set
* connect to 2a04:4e42:600::223 port 443 failed: No route to host
*   Trying 151.101.64.223:443...
* TCP_NODELAY set
* Connected to pypi.org (151.101.64.223) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: none
  CApath: none
* loaded libnssckbi.so
* ALPN, server accepted to use http/1.1
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=www.python.org,O=Python Software Foundation,L=Wolfeboro,ST=New Hampshire,C=US,serialNumber=3359300,incorporationState=Delaware,incorporationCountry=US,businessCategory=Private Organization
*       start date: Sep 18 00:00:00 2018 GMT
*       expire date: Oct 14 12:00:00 2020 GMT
*       common name: www.python.org
*       issuer: CN=DigiCert SHA2 Extended Validation Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
> GET / HTTP/1.1
> Host: pypi.org
> User-Agent: curl/7.65.1
> Accept: */*
> Accept-Language: uk,en
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Security-Policy: base-uri 'self'; block-all-mixed-content; connect-src 'self' https://api.github.com/repos/ *.fastly-insights.com sentry.io https://2p66nmmycsj3.statuspage.io; default-src 'none'; font-src 'self' fonts.gstatic.com; form-action 'self'; frame-ancestors 'none'; frame-src 'none'; img-src 'self' https://warehouse-camo.cmh1.psfhosted.org/ www.google-analytics.com *.fastly-insights.com; script-src 'self' www.googletagmanager.com www.google-analytics.com *.fastly-insights.com https://cdn.ravenjs.com; style-src 'self' fonts.googleapis.com; worker-src *.fastly-insights.com
< Content-Type: text/html; charset=UTF-8
< ETag: "/r3JSqvtLeoGObDXqvsphw"
< Referrer-Policy: origin-when-cross-origin
< Server: nginx/1.13.9
< Content-Length: 21373
< Accept-Ranges: bytes
< Date: Thu, 17 Oct 2019 15:38:48 GMT
< Connection: keep-alive
< X-Served-By: cache-iad2148-IAD, cache-hhn4058-HHN
< X-Cache: MISS, HIT
< X-Cache-Hits: 0, 1
< X-Timer: S1571326729.506037,VS0,VE1
< Vary: Accept-Encoding, PyPI-Locale, Accept-Encoding
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< X-Frame-Options: deny
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Permitted-Cross-Domain-Policies: none
< 
{ [1518 bytes data]






<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="defaultLanguage" content="en">
    <meta name="availableLanguages" content="en">

    

    <title>PyPI · The Python Package Index</title>
    <meta name="description" content="The Python Package Index (PyPI) is a repository of software for the Python programming language.">
* Failed writing body (1241 != 2759)
* Closing connection 0
```
</details>

Additionally, HTTP server should reply with the correct `Content-Language` header as per https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Language / https://tools.ietf.org/html/rfc7231#section-3.1.3.2.

What to do
==========

PyPI should learn to detect this header and set a language accordingly.
If the `_LOCALE_` cookie is present, `Content-Language` should probably be ignored as it indicates that the user selected the language explicitly.

I'm not sure whether PyPI should save the locale from `Content-Language` into a cookie if it's not present. I think, no.

There may also be a way for the registered user to save their preferred language in their profile. This should also influence the locale selection logic but is out of the scope of this issue.

**Comment by ewdurbin** [comment]
If we work to support `Accept-Language`, the VCL will need to be updated to undo https://github.com/python/pypi-infra/pull/52 and replace it with something using Fastly's support for this header: https://docs.fastly.com/en/guides/accept-language-header-vcl-features

**Comment by NathanBnm** [comment]
You could use a cookie too in order to store the user language preference. (For example when the browser is in english but the user choose French as default language for PyPI).

**Comment by webknjaz** [comment]
Well, that's what I described. But the initial language should be taken from the browser preferences.

**Comment by kilrogg** [comment]
I've created a [pull request](https://github.com/python/pypi-infra/pull/53) on python/pypi-infra with a change for the Fastly config.
Looks like warehouse already supports Accept-Language if the header is passed through. Hope caching by language works fine, too.

**Comment by di** [comment]
Seems ok to me!

**Comment by ewdurbin** [comment]
https://github.com/pypi/infra/pull/109/ is live on https://test.pypi.org for validation and all looks OK from my end. We'll roll this out to https://pypi.org/ later today.

**Comment by ewdurbin** [comment]
This is live on https://pypi.org/
