### ISSUE TITLE
Visibly flag projects that provide type details

### ISSUE THREAD

**Issue by brettcannon** [pypi/warehouse#6919]
**What's the problem this feature will solve?**
Making it easier to identify projects that providing type details (if that's your jam and it would make a difference in which project you choose to go with).

**Describe the solution you'd like**
Some way to signal that a project either has a `py.typed` file declaring that it's typed or an appropriate `-stubs` project is available on PyPI. IOW whether the project has declared type support as specified by [PEP 561](https://www.python.org/dev/peps/pep-0561/).

**Additional context**
I'm not sure if a new trove classifier that can be automatically provided is best or some visible notation along with some metadata exposed through the data endpoints so that something like py3readiness.org could exist for type support.

**Comment by ewdurbin** [comment]
related: #4967 and #4164

**Comment by dstufft** [comment]
I don't think Warehouse can or should add classifiers that aren't present in the package metadata itself.

So that leaves either something completely different, or we push this down to asking for packages to add a classifier or having setuptools, flit, etc automatically apply the classifier when it's typed.

**Comment by miketheman** [comment]
Type-oriented Trove Classifiers were added starting in 2020: https://github.com/pypa/trove-classifiers/blob/d4ad70c1b4c79ef2e0649c4a3b3184432f19a108/src/trove_classifiers/__init__.py#L807-L808
and can also be seen at the bottom of the supported classifiers on pypi: https://pypi.org/pypi?%3Aaction=list_classifiers

Over 4000 projects use the classifier today: https://pypi.org/search/?q=&o=&c=Typing+%3A%3A+Typed

The Typed classifier status is displayed in the Classifiers section of a given project's release ([random example](https://pypi.org/project/click-extra/#:~:text=Typing,Typed))

Based on these pieces in place, I recommend closing out this issue as the feature has been implemented
