### ISSUE TITLE
Stop bundling JS, use ECMAScript modules and HTTP 2 for it.

### ISSUE THREAD

**Issue by KOLANICH** [pypi/warehouse#7330]
**What's the problem this feature will solve?**
* The modules are combined into few files that are hard to audit and that cannot be blocked selectively.
* bundler is used which is software with own dependencies and can contain backdoors

**Describe the solution you'd like**
* Use HTTP 2 to deliver multiple files efficiently.
* Use ECMAScript modules to get rid of linking sources with a bundler. Instead this work is done by a browser.

**Comment by webknjaz** [comment]
Not sure how H2 helps here: JS will still be blocking on deps resolution. If not, you'll need to do H2 push which requires knowing what to push on the backend and it's the bundler that knows all the deps there...

**Comment by miketheman** [comment]
We refactored how we bundle JavaScript. If there’s specific modules of concern you’d like to block on clients, please surface what those are, and consider contributing a change to the webpack configuration to extract those as specific bundles.
