### ISSUE TITLE
Make Malware Verdicts auditable

### ISSUE THREAD

**Issue by xmunoz** [pypi/warehouse#7421]
**What's the problem this feature will solve?**
Because of https://github.com/pypa/warehouse/commit/ac9c649ecb6904696699d92e3254c919b25d7738, Malware Verdicts are completely removed once the associated object is deleted (`CASCADE` on delete). This eliminates the ability of to perform audits of verdicts or evaluate the efficacy of checks. 

**Describe the solution you'd like**
Once #4440 is addressed, the schema of `malware_verdicts` should be modified such that verdicts are never removed from the database.

**Comment by dstufft** [comment]
This is gone now https://github.com/pypi/warehouse/pull/13647
