### ISSUE TITLE
Help section for common TOTP issues

### ISSUE THREAD

**Issue by di** [pypi/warehouse#7588]
One of the reasons TOTP might fail is due to time being out of sync between devices. From https://github.com/pypa/warehouse/issues/7584#issuecomment-603463969:

> Indeed my mobile device was 2 minutes ahead of current time in Google. After putting automatic time on my Android settings and trying again I got `Success Authentication application successfully set up!`. Maybe the error message should hint that or the [Help Section](https://pypi.org/help/#totp).

This has happened enough times that we should have a "troubleshooting TOTP failure" section in our help guide, which describes this issue, and link to that section when TOTP fails.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by stefpiatek** [comment]
I'd be happy to give this a go if it's still up for grabs?

**Comment by boringow** [comment]
Hello! I am quite new to github, I did some stuff but not really into detail. I would like to perform the first issue on PyPI. What is the task I have to do?

**Comment by webknjaz** [comment]
@boringow essentially, this task is about adding a section with an explanation about the clock on a TOTP device being out of sync to https://github.com/pypa/warehouse/blob/main/warehouse/templates/pages/help.html.

**Comment by Arthavruksha** [comment]
Hey I would love to work on this Issue , plz assign it to me !

**Comment by andrwcnln** [comment]
I am working on this

**Comment by AroshaJ** [comment]
This still seems to be an issue. I've ensured that time is sync'd across my devices but it still isn't working. I've tried both google authenticator and the Microsoft app as well.

**Comment by emersonfelipesp** [comment]
I also have the same problem. Tried different webbrowsers, tried FreeOTP and Google Authenticator e nothing works. Time is synced between both devices.

**Comment by di** [comment]
Anyone experiencing issues with TOTP, please [open a new issue](https://github.com/pypi/warehouse/issues).
