### ISSUE TITLE
Should "Python Package Index" be translated or used as-is?

### ISSUE THREAD

**Issue by scop** [pypi/warehouse#7883]
Would you prefer "Python Package Index" being translated to each target language, or kept as-is (in English) in translations? It seems currently translated in some languages, as-is in others.

**Comment by fitojb** [comment]
Unless the whole sequence of words in “Python Package Index” is a trade/service mark (like the unitary “Python” is), I don’t see why it shouldn’t be translated. It’s a descriptive name.

**Comment by di** [comment]
"Python Package Index" is trademarked: https://trademarks.justia.com/876/57/python-package-87657448.html

**Comment by di** [comment]
Closing this: it should _**not**_ be translated due to the wordmark, any translations that do translate it should be updated (and we should probably update our strings to make this easier on the translators).
