### ISSUE TITLE
Search by package name returns no matches

### ISSUE THREAD

**Issue by andy-z** [pypi/warehouse#8321]
**Describe the bug**
Searching package on pypi.org by its full name returns zero results for package `pyemf`:

    0 projects for "pyemf" Did you mean 'pyamf'?

Searching for `pyemf` in Google returns PyPI link as first result: https://pypi.org/project/pyemf/

**Expected behavior**

PyPI should be able to find a package.

**To Reproduce**

Click https://pypi.org/search/?q=pyemf

**My Platform**

Web browser.

**Comment by eamanu** [comment]
Hi! I would like to work on this if there any objection :)

**Comment by di** [comment]
It seems like the package is not in the search index for some reason. One thing we could do to help here would be to provide a way for PyPI administrators to trigger the `reindex_project` task from the Admin UI: 
https://github.com/pypa/warehouse/blob/12c2b81b190c6bff5c1664d44879e6eca1135a68/warehouse/search/tasks.py#L229-L250

**Comment by di** [comment]
Taking a second look at this, it's likely that the age of the package in question (last published Jan 1 2006) has something to do with this.

**Comment by DavidDoran-Hub** [comment]
I am getting the same issue with my brand new package, “oligoss”. It does not appear on any searches. However, direct link to the project works.

To reproduce: https://pypi.org/search/?q=oligoss&o=

Link to project: https://pypi.org/project/oligoss/

**Comment by enkidulan** [comment]
I've just observed this issue. Searching by `networkx` returns 0 results, however searching by `"networkx"` returns some results with the https://pypi.org/project/networkx/ package on top.

**Comment by FOUREX** [comment]
My library is not searchable, what should I do?

Library: https://pypi.org/project/alerts-in-ua.py/

**Comment by mscisdk** [comment]
I am encountering a similar issue with my new package, "msci.sdk". 
It does not show up in any searches, but the direct link to the project works fine.

https://pypi.org/search/?q=msci.sdk&o=
https://pypi.org/project/msci.sdk/

If you're interested, I wanted to let you know that the search functionality is working perfectly fine on testpypi for the same package.

**Comment by miketheman** [comment]
@mscisdk search finds your project now. Sometimes our search index lags behind.
![Search results · PyPI](https://github.com/pypi/warehouse/assets/529516/8f3863db-ec80-4792-83eb-440dc1f88625)

**Comment by mscisdk** [comment]
Thanks for checking @miketheman . the search functionality is working fine now.

**Comment by miketheman** [comment]
I think it's time to close this issue for a few reasons.

1. The original issue of not finding `pyemf` - I have discovered the real reason it wasn't found in the search index, and it's that this project has no files associated with it. If you try to `pip install pyemf`, you get an error. If there's nothing to install, we don't add it to the index. See https://github.com/pypi/warehouse/pull/8111 for the history on that.
2. The feature request of adding an Admin utility to trigger a reindex has been added in https://github.com/pypi/warehouse/pull/8822
3. Other reports of not being able to search for projects (networkx, alerts-in-ua.py, msci.sdk) all work proerly.

All existing mysteries have been answered!

**Comment by Keerthana910234** [comment]
To reopen this issue, I uploaded a package singletCode. I can install it via pip. However, I cannot find it on search and Google search. This was uploaded on 25th March. Is it just a matter of waiting for it to get indexed? Thank you for the help. 

![image](https://github.com/pypi/warehouse/assets/70164426/3ca9a0cc-7389-4e2d-b185-37e5c6f016f7)
![image](https://github.com/pypi/warehouse/assets/70164426/220f7e4b-df00-42f5-875e-3cb0426319f1)
