### ISSUE TITLE
Migrate Warehouse to PostgreSQL v12

### ISSUE THREAD

**Issue by callmecampos** [pypi/warehouse#8436]
**What's the problem this feature will solve?**

Currently, our CI Python testing jobs are run using the `postgres:10.1` container (both on [Travis](https://github.com/pypa/warehouse/blob/master/docker-compose.yml) and on [GitHub Actions](https://github.com/pypa/warehouse/pull/8255)) corresponding to PostgreSQL v10. In talking with @di, there was discussion of upgrading Warehouse (and our CI jobs) to run with the most recent PostgreSQL version, specifically PostgreSQL v12 (https://www.postgresql.org/support/versioning/).

When running Warehouse inside a [Postgres Service Container](https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-postgresql-service-containers) when testing out a new CI pipeline, I found that some migrations that were running were failing when using the `postgres:latest` container. Specifically, running alembic.command.upgrade when configuring the Python tests (https://github.com/pypa/warehouse/blob/master/tests/conftest.py#L196) yielded the following logs:

```
context = <sqlalchemy.dialects.postgresql.psycopg2.PGExecutionContext_psycopg2 object at 0x7fbf97cecf40>

    def do_execute(self, cursor, statement, parameters, context=None):
>       cursor.execute(statement, parameters)
E       sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) constraint "description_urls_name_fkey" of relation "description_urls" does not exist
E       
E       [SQL: ALTER TABLE description_urls DROP CONSTRAINT description_urls_name_fkey]
E       (Background on this error at: http://sqlalche.me/e/f405)
```

See the GitHub Actions job showing the failing migration here (see the "Connect to PostgreSQL and Run Tests" step): https://github.com/callmecampos/warehouse/runs/856387716?check_suite_focus=true

Additionally, I found that running inside the `postgres:latest` container required using a password to authenticate and connect with the Postgres service, which required some changes to [`DatabaseJanitor`](https://github.com/ClearcodeHQ/pytest-postgresql/blob/master/src/pytest_postgresql/janitor.py#L23) in tests/conftest.py: https://github.com/pypa/warehouse/commit/d07c37c6329ae91ee343d7532e2073319a801e6b#diff-484462fced51d1a06b1d93b4a44dd535R134. I removed these changes once I reverted to using `postgres:10.1`, but figured it would be good to note those changes in case somebody needs them in the future.

**Describe the solution you'd like**

Upgrade Warehouse to run with Postgres v12, handling the default password requirement when running in our CI pipeline as well as handling the failing migrations.

**Comment by miketheman** [comment]
Resolved in https://github.com/pypi/warehouse/pull/11573
Recommend closure.
