### ISSUE TITLE
Only show GitHub stars, if it is the same project

### ISSUE THREAD

**Issue by MartinThoma** [pypi/warehouse#8462]
**What's the problem this feature will solve?**

I've recently written an article about pytest plugins. I manually checked a lot of them and had to judge quickly which ones are worth a shot. So the Github stars displayed on PyPI help a bit by filtering. There was one plugin I only mentioned because it had many stars: https://pypi.org/project/pytest-xdist-debug-for-graingert/ 

Having a second look at it, I noticed that it simply linked to a different project.

This is misleading at the very least, but can support typosquatting at worst.

**Describe the solution you'd like**

There are multiple solutions:

1. Don't show github stars at all.
2. Only show them, if the linked page has a back-link to the package.
3. Check if other packages link to the same repository already

I would prefer (2). We could also provide a badge like https://badge.fury.io/for/py

**Comment by miketheman** [comment]
Now that Trusted Publishing exists, we might consider this for only repos that have published with GitHub Actions, since then we have something to compare against.

**Comment by miketheman** [comment]
Also, today I learned of https://capec.mitre.org/data/definitions/693.html

**Comment by miketheman** [comment]
Before we try to tackle this, we need to understand the flow of how trusted publishing treats multiple packages from a single github repo (a la monorepo)

**Comment by MartinThoma** [comment]
I'd rather completely remove the feature than having such easy starjacking. The only value this gives to the user is to know if the package is trustworthy. As the current mechanism of retrieving the number of stars is so easy to fake, it gives a false sense of trustworthiness.

**Comment by MartinThoma** [comment]
@yeraydiazdiaz I think you missed the point. The point is that the Github stars belong to another project. It doesn't matter that it is a copy/fork. The copy might introduce bugs or even be malicious.

As it is, the "Github stars" feature of PyPI warehouse makes the live of attackers easier and provides no value to end users.

**Comment by di** [comment]
Fixed by #16532.
