### ISSUE TITLE
It takes two hits for `pip` to find a newly-published version of a package

### ISSUE THREAD

**Issue by TimoMorris** [pypi/warehouse#9572]
**Describe the bug**
Having just published a new version of a package, trying to install that version using `pip` using the `==` version specifier, `pip` reports that it couldn't find a matching package. But retrying immediately afterwards succeeds.

**Expected behavior**
Attempting to install a specific version of a package, which has been published, should find and install that version.

I initially assumed it was just taking some time for the new publication to percolate through and the right indexes/mirrors/etc to be updated (or however it works - I'm a novice when it comes to stuff like that 😅). But I discovered that if you wait only a couple of seconds or a full minute, it fails either way on the first attempt, but _reliably succeeds_ on the second attempt immediately after.

**To Reproduce**
Easiest to do in a command line script of some sort:
1. Publish a new version of a package
2. Attempt to install that specific version, e.g. `python -m pip install my-package==<version>`
3. It returns an error: `ERROR: Could not find a version that satisfies the requirement my-package==<version>`
4. Attempt to install that specific version again immediately after, using the same command
5. Successfully finds and installs this time

This was using **TestPyPI** - which may or may not be significant. I haven't tried to reproduce on the main PyPI as I didn't want to clog up my release history there 😕

If the package version is a pre-release, adding the `--pre` argument (while keeping the version specifier) doesn't make a difference. But just using `--pre` (without the version specifier) means it picks up the latest previously-published pre-release version (and not the one just uploaded).

**My Platform**
* Using `pip` v21.1.1
* Python v3.6.8
* Windows 10

**Additional context**
I discovered this when trying to write a batch script to automate my release process, including checking the release by installing it after publication and running the test suite against it. The relevant part(s) of the script are:
```
poetry build
poetry run twine check dist/my-package-%VERSION%*
poetry publish -r test-pypi -u my-user -p %TESTPYPIPASSWORD%

mkdir %TESTDIR%
cd %TESTDIR%
python -m venv venv
call venv\Scripts\activate
python -m pip install --upgrade pip

call python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ my-package==%VERSION%
call python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ my-package==%VERSION%
```

**Comment by Coronon** [comment]
Can confirm. It can also cause an old version to be installed when not using `==` for version locking. This happened to me while testing on test.pypa too. I thought it was probably some error on my side, but this issue fits perfectly.

**Comment by miketheman** [comment]
#Triage

Hi there! This was from an era where we may have had delays between new uploads and index cache availability, which have since improved significantly.

If this is still an issue for you, please open a support issue with this template, where you can also provide significant debugging information:

https://github.com/pypi/support/issues/new?assignees=&labels=network&projects=&template=access-issues.yml
