### ISSUE TITLE
"BLAKE2-256" is misleading

### ISSUE THREAD

**Issue by nolta** [pypi/warehouse#9628]
**What's the problem this feature will solve?**

For example, the wheel `mkl_devel-2021.2.0-py2.py3-none-manylinux1_x86_64.whl` is [reported](https://pypi.org/project/mkl-devel/#copy-hash-modal-180430cd-3ba1-40d4-9e93-94f7c0d62c71) to have a `BLAKE2-256` hash of `382508b4c5a5f2e7c9d8aa1c812546ef02c9557758a23e8a1d1a8c12b3b3cc84`.

Naively, i thought `BLAKE2-256` meant `BLAKE2s`, but that's not the case:

```
$ openssl dgst -r -blake2s256 mkl_devel-2021.2.0-py2.py3-none-manylinux1_x86_64.whl 
b4aaf53b34aec76e5951eb8cb32c6c932e843d2a0222e5d2c66ae3bb0f148b96 *mkl_devel-2021.2.0-py2.py3-none-manylinux1_x86_64.whl
```

The algorithm instead appears to be `BLAKE2b` with a digest size of 32:

```python
>>> import hashlib
>>> b = open('mkl_devel-2021.2.0-py2.py3-none-manylinux1_x86_64.whl', 'rb').read()
>>> hashlib.blake2s(b).hexdigest()
'b4aaf53b34aec76e5951eb8cb32c6c932e843d2a0222e5d2c66ae3bb0f148b96'
>>> hashlib.blake2b(b, digest_size=32).hexdigest()
'382508b4c5a5f2e7c9d8aa1c812546ef02c9557758a23e8a1d1a8c12b3b3cc84'
```

**Describe the solution you'd like**

Clarify that `BLAKE2-256` is not `BLAKE2s`.

**Comment by di** [comment]
Correct: https://github.com/pypa/warehouse/blob/7fc3ce5bd7ecc93ef54c1652787fb5e7757fe6f2/warehouse/forklift/legacy.py#L1222

I agree we could be more clear here, I've added the "good first issue" label to this PR.

**Comment by abitrolly** [comment]
@di renaming `blake2_256` to `blake2b256` over the codebase won't be enough, right?

**Comment by di** [comment]
Not on that line (that's just our internal representation) but here, on the page where these hashes are displayed:

https://github.com/pypa/warehouse/blob/c1055c57b70b7a827829ba36ba9efdf245ddf9e4/warehouse/templates/includes/hash-modal.html#L56

We probably need to be more clear there about what this hash is.

**Comment by dstufft** [comment]
This is also in the JSON API, but deleting the old name is probably a non starter for backwards incompatible changes that aren't worth it, but we could add the new name as an additional hash.

**Comment by di** [comment]
I think a section at https://pypi.org/help/ on what these hashes are and how to calculate them might be appropriate.

**Comment by abitrolly** [comment]
If the change to API is required, I would actually look into adding `blake2s128` instead of `blake2b256`. It is shorter, and 2**64 collision security is more than enough for PyPI purposes https://datatracker.ietf.org/doc/html/rfc7693#section-4

```
            Algorithm     | Target | Collision | Hash | Hash ASN.1 |
               Identifier |  Arch  |  Security |  nn  | OID Suffix |
           ---------------+--------+-----------+------+------------+
            id-blake2b160 | 64-bit |   2**80   |  20  |   x.1.5    |
            id-blake2b256 | 64-bit |   2**128  |  32  |   x.1.8    |
            id-blake2b384 | 64-bit |   2**192  |  48  |   x.1.12   |
            id-blake2b512 | 64-bit |   2**256  |  64  |   x.1.16   |
           ---------------+--------+-----------+------+------------+
            id-blake2s128 | 32-bit |   2**64   |  16  |   x.2.4    |
            id-blake2s160 | 32-bit |   2**80   |  20  |   x.2.5    |
            id-blake2s224 | 32-bit |   2**112  |  28  |   x.2.7    |
            id-blake2s256 | 32-bit |   2**128  |  32  |   x.2.8    |
           ---------------+--------+-----------+------+------------+
```

**Comment by dstufft** [comment]
Isn't 2s slower than 2b on 64bit systems?

**Comment by abitrolly** [comment]
Not sure. https://www.blake2.net/ benchmarks don't list the hash sizes. There is some theory https://crypto.stackexchange.com/questions/83241/why-blake2b-is-the-fastest-despite-it-being-512-bits-hashing-algorithm but I would be interested to see how 256 b compares to 128 s. And also the same benchmark on some popular 32bit platforms.

**Comment by dstufft** [comment]
It's probably a moot point, I suspect they're both fast enough, but when I picked 2b that's why I picked it since I had no other reason to pick one over the other. The [blake2 website](https://www.blake2.net/) makes the claim about speed. I also think that length is kind of a moot point TBH, the JSON api includes the full text of the long-description, which can be very large.

**Comment by abitrolly** [comment]
I would use 2s for `.metadata` checksums, because it is more friendly to low powered devices and shorter to embed into simple API urls (#8254). The size of hash also matters for content addressing - a way to securely decentralize package distribution without complicated schemes like TUF.

**Comment by chrismcgehee** [comment]
Hi, I would like to take this issue. For this change, I will do the following:
* Change the webpage to say "BLAKE2b-256", which would look like:
![image](https://user-images.githubusercontent.com/8961650/209450525-2a91c3ea-0e33-4356-8e4a-2c7b528960a4.png)
* Update code references from `blake2_256_digest` to `blake2b_256_digest`.
* I will NOT make any change to the JSON API.

**Comment by di** [comment]
Sounds good! I think adding a help section (as mentioned in https://github.com/pypi/warehouse/issues/9628#issuecomment-908450246) and adding the new hash as a field to the JSON API (as mentioned in https://github.com/pypi/warehouse/issues/9628#issuecomment-908446405) should be included as well.

**Comment by chrismcgehee** [comment]
Sure thing, I'll add to the JSON API and add a section to the help page. I have a couple follow up questions:

1. If we were to change the internal code names from `blake2_256` to `blake2b_256`, I think we would want to also change the database column to `blake2b_256` in the `release_files` table to keep the naming consistent. I see that it is difficult to rename an existing column, so would it be okay if I leave the internal code names as `blake2_256` and just update the web UI and JSON API? 
1. Currently, the BLAKE2 field is not present in the JSON API at all; it just contains the MD5 and SHA256 hashes. For my change, I'll simply add `"blake2b_256"` to the `"digests"` field. Does that sound good?

**Comment by di** [comment]
> so would it be okay if I leave the internal code names as blake2_256 and just update the web UI and JSON API?

I think this is fine.

> Currently, the BLAKE2 field is not present in the JSON API at all; it just contains the MD5 and SHA256 hashes. For my change, I'll simply add "blake2b_256" to the "digests" field. Does that sound good?

Looks like you're right! 🙂 Sounds good.
