### ISSUE TITLE
Support Metadata Version 2.2

### ISSUE THREAD

**Issue by uranusjr** [pypi/warehouse#9660]
**What's the problem this feature will solve?**
Since PEP 643 is accepted, PyPI should start accepting Metadata 2.2 distributions. See  PyO3/maturin#564.

**Describe the solution you'd like**
Allow `Metadata-Version: 2.2` to pass the legacy upload endpoint’s form validation, and validate the corresponding `Dynamic` field.

The latter part could be a bit tricky since `Dynamic` is not allowed for wheels. Not sure how it could be best handled (I don’t have much experience with WTForm).

**Additional context**
https://www.python.org/dev/peps/pep-0643/

**Comment by di** [comment]
There's a couple levels of 'validation' that could happen for the `Dynamic` field here:

1. Validate that `Name` and `Version` are not marked as `Dynamic` (feasible)
2. Validate that wheels do not set `Dynamic` (probably feasible)
3. Validation across multiple artifacts (probably infeasible):
    - If a field is not marked as `Dynamic`, then the value of the field in any wheel built from the sdist MUST match the value in the sdist. If the field is not in the sdist, and not marked as `Dynamic`, then it MUST NOT be present in the wheel.
    - If a field is marked as `Dynamic`, it may contain any valid value in a wheel built from the sdist (including not being present at all).
    - Backends MUST NOT mark a field as `Dynamic` if they can determine that it was generated from data that will not change at build time.

Are we OK with only doing 1 & 2? (cc @pfmoore)

**Comment by konstin** [comment]
From my perspective just allowing 2.2 when no `Dynamic` is used would already be great and solve https://github.com/PyO3/maturin/pull/564

**Comment by pfmoore** [comment]
I think (1) is reasonable. The PEP allows wheels to set `Dynamic`, so I think (2) is wrong, and should be omitted. I'm happy that Warehouse shouldn't try to do (3).

**Comment by domdfcoding** [comment]
What's the next step for this? Is it just waiting on a PR?

**Comment by di** [comment]
Yes.
