### ISSUE TITLE
Public release history and release page do not show yanked reason

### ISSUE THREAD

**Issue by Jackenmen** [pypi/warehouse#9837]
**What's the problem this feature will solve?**
For yanked versions with a reason provided, PyPI shows this reason on neither the public release history nor the public release page.

**Describe the solution you'd like**
I don't know where exactly it should be shown but I think it should be shown somewhere *at least* on the release page.

**Additional context**
See version 3.4.8 that *has* a yanked reason but it is not shown on the page:
https://pypi.org/project/Red-DiscordBot/#history
https://pypi.org/project/Red-DiscordBot/3.4.8/

**Comment by di** [comment]
I think we could probably add this as a tooltip on the "yanked" badge. I've added the "good first issue" label to this issue.

**Comment by oOhyeahh** [comment]
Hi there, I would like to work on this issue as a new bee 😃

**Comment by webknjaz** [comment]
@oOhyeahh feel free to make an attempt. It doesn't seem like anybody else is working on this.

**Comment by mgorny** [comment]
Does anyone happen to know if there's a way to get the yank reason right now?

**Comment by di** [comment]
It's available as the `data-yanked` attribute on the Simple API. For example, https://pypi.org/simple/pip-audit/ has:

```html
<a href="https://files.pythonhosted.org/packages/a6/29/3397239feb6371ad819cbc599683065c476ced251130f438cbe28287112c/pip_audit-2.4.15-py3-none-any.whl#sha256=0434d0700fc10be6758c49abf35e8154447dd2bb9a799a780741030acbb5ef62" data-requires-python="&gt;=3.7" data-yanked="Severe behavioral regressions" >pip_audit-2.4.15-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/43/40/48a9082815a2963380f7a8b00a9f2a25f354d89cb22489f1df65fba83de5/pip_audit-2.4.15.tar.gz#sha256=aeb55541c897802d0a25510d723630d1155d91579bb8dba9b0d5e5e8a01595dd" data-requires-python="&gt;=3.7" data-yanked="Severe behavioral regressions" >pip_audit-2.4.15.tar.gz</a><br />


```

**Comment by di** [comment]
I think this isn't quite fixed by https://github.com/pypi/warehouse/pull/15078/, because that didn't add the yank reason to the "release history", only on the "release page".

**Comment by miketheman** [comment]
cc @cofiem

**Comment by cofiem** [comment]
Oh, I followed the original comment: "I think it should be shown somewhere at least on the release page.".

I didn't initially understand the distinction between the "yanked badge" and the "release page".

Is the "yanked badge" and "release history" referring to the "Release History" section? And the red YANKED badge?

Is the idea to add a tooltip on hover to the red YANKED badge?

https://pypi.org/project/pip/21.2/#history

![image](https://github.com/pypi/warehouse/assets/441771/d28f3bb7-54ae-4e2b-aa32-33879117010d)

**Comment by Jackenmen** [comment]
> Is the idea to add a tooltip on hover to the red YANKED badge?

Something that also works on mobile would be great.

**Comment by cofiem** [comment]
Is this a reasonable approach?

I agree that it would be good to make this work on mobile (so not involve a hover).

![image](https://github.com/pypi/warehouse/assets/441771/78f8e715-d4fa-4160-b54a-727ef0f4db79)

**Comment by Jackenmen** [comment]
It looks great on your screenshot. I'm not sure if people will like it when there are more yanked releases, with longer yank reasons. Based on my own quick test (just an approximation of what you've shown done through DevTools), it looks fine but the longest yank reason I wrote is 150 characters so it may not be representative of how much text some maintainers put in the yank reason? Presumably one could cut the text with ellipsis after a bit though, people can always go to release page to read the full reason if the shortened one doesn't suffice (and perhaps people will start putting the important information at the beginning).
![image](https://github.com/pypi/warehouse/assets/6032823/8cfa633f-43f4-4762-a5dd-a8ee3fdce420)

**Comment by webknjaz** [comment]
Also, keep in mind that at some point, the yank reason might end up being a multi-line string: https://github.com/pypi/warehouse/issues/12243.
